### ISSUE TITLE
node canvas jpegstream as input

### ISSUE THREAD

**Issue by gh0sTedBuddy** [fluent-ffmpeg/node-fluent-ffmpeg#1008]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.2.2
* OS: MacOS

### Code to reproduce

```js
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(config.width, config.height)
const ctx = canvas.getContext('2d')
const video = ffmpeg()
	.input(canvas.createJPEGStream())
	.audioFilters('lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100')
	.on('start', () => {
		console.log('FFMPEG: STARTED')
	})
	.on('error', err => {
		console.log('FFMPEG: ERROR', err)
	})
	.on('end', () => {
		console.log('FFMPEG: FINISHED')
	})
	.save('output.mp4')

// drawing routine.
```

### Expected results
ffmpeg waiting for further "frames" to be rendered, maybe i'm just stupid :-)

### Observed results
after first frame the FFMPEG: FINISHED output appears on screen...

**Comment by chiboubys** [comment]
for input data (FFmpeg) why you don't use a blob data coming from canvas.captureStream()
it gives you a blob data
