### ISSUE TITLE
Fluent-ffmpeg Canvas streaming (blob -> RTMP streaming)

### ISSUE THREAD

**Issue by chiboubys** [fluent-ffmpeg/node-fluent-ffmpeg#1014]
### Version information

* fluent-ffmpeg version:Latest
* ffmpeg version:4.x.x
* OS:UBUNTU SERVER 18.04 LTS
@muaz-khan
### Code to reproduce

```js
const inputStreamBuffer = new ReadableStreamBuffer()
     var cmd =  FFMpeg(inputStreamBuffer)
            .inputOption('-re')
            .addOptions(opt.split(' '))
            .on('start', function (commandLine) {
              console.log('commandLine: ' + commandLine);
            })
            .on('error', function(err) {
              console.log('An error occurred: ' + err.message);
            })
            .on('progress', function(progress) {
              console.log('FPS : ' + progress.currentFps);
            })
            .on('end', ()=>{
              console.log('end data in ffmpeg')
            })
            .save(rtmp)   //rtmp url

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
-> I have set my Socket.io :
  socket.on('data', function(data) {  
    inputStreamBuffer.put(data) // the data is a blob sended from canvas.captureStream()
  });
I wan't to stream the canvas to youtube live using fluent ffmpeg
### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by inselmensch** [comment]
#1008 i think we've the same issue here.... don't you think?

**Comment by chiboubys** [comment]
Yes i think is the same, i have a solution  but the fpsis too low, maybe i need to change my FFmpeg settings :
* Note that the rtmp var is : youtube URL + RTMP key
var args = '-re -i - -movflags +faststart -vf scale=1280x720 -aspect 16:9 -vcodec libx264 -pix_fmt yuv420p -q:v 0 -r 30 -crf 13 -profile:v main -preset:v ultrafast -b:v 2500k -maxrate 2500k -bufsize 2500k -r 30 -c:a aac -b:a 128k -ar 44100 -threads 10 -f flv ' + rtmp

cmdFFmpeg = child_process.spawn(ffmpegPath, args.split(' '));
    cmdFFmpeg.stderr.on('data', (data) => {
      console.log('Data coming through STDERR:', data.toString());
    });

    // onWrite
    cmdFFmpeg.stdin.on('write', (e)=>{
      console.log('something new was written', e);
    })

//receiving data (blob) from canva.captureStream()
  socket.on('data', function(data) {
    if(cmdFFmpeg !== undefined){
      cmdFFmpeg.stdin.write(data)
    }
    
    //cmdFFmpeg.ffmpegProc.stdin.write(data);
    //cmd.stdin.write(data)
  });

I don't know if my FFmpeg settings is correct.
