### ISSUE TITLE
How would I merge a video and audio link into a file?

### ISSUE THREAD

**Issue by Bonyoze** [fluent-ffmpeg/node-fluent-ffmpeg#1016]
* fluent-ffmpeg version: 2.1.2

How would I take a link to a video file and a link to an audio file and merge them into an mp4 and the fastest method? I’ve tried downloading both files and then inputting them but I always receive the error: ffmpeg exited with code 1.

```
ffmpeg()
    .addInput("./files/media.mp4")
    .addInput("./files/media.mp3")
    .saveToFile("./files/output.mp4")
```

**Comment by TheKinrar** [comment]
Could you provide ffmpeg's stdout and stderr outputs? You get them as second and third arguments of the error event.

**Comment by ThePubDoc** [comment]
I have written a script to do the same thing and its working fine.

```
ffmpeg("video.mp4")
    .inputOption('-stream_loop -1')
    .mergeAdd("audi.mp3")
    .setStartTime(startTime)
    .duration(duration)
    .on("start", function(commandLine) {
        console.log("Spawned FFmpeg with command: " + commandLine);
    })
    .on('error', function(err, stdout, stderr) {
        console.log('Cannot process video: ' + err.message);
    })
    .on('end', function(stdout, stderr) {
        console.log('Transcoding succeeded !');
    })
    .saveToFile("merged.mp4")
```
I have used an additional option "-stream_loop -1" to loop the video according to the duration of the audio.
