### ISSUE TITLE
convert m3u8 to mp4 and use http protocol for downloading converted mp4 file

### ISSUE THREAD

**Issue by akshaybhuradia2020** [fluent-ffmpeg/node-fluent-ffmpeg#1021]
* ffmpeg version:4.2
* OS:RHEL 8.1

I want to convert m3u8 to mp4 and i would like to do conversion as well as download on same time.

I am running this command

ffmpeg -i ultra.m3u8  -c copy -listen 1 -seekable 1 -content_type video/mp4 -f mp4 http://0.0.0.0:8080/test.mp4

when user trigger this url("http://0.0.0.0:8080/test.mp4"), then file start's download, but i am not able to play video.

and i get error when all chunks are read:
[hls @ 0x55da053b4100] Opening 'ultra177.ts' for reading
[tcp @ 0x55da0540f940] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da05520480] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da053ca780] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da05485f80] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da053ced40] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da054255c0] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da0540f940] Connection to tcp://0.0.0.0:8080 failed: Connection refused
[tcp @ 0x55da05435380] Connection to tcp://0.0.0.0:8080 failed: Connection refused
frame=53236 fps=7939 q=-1.0 Lsize= 476447kB time=00:29:36.30 bitrate=2197.3kbits/s speed= 265x
video:446847kB audio:28278kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.278083%

**Comment by asio1337** [comment]
That's not a issue by fluent-ffmpeg.
