### ISSUE TITLE
Electron build can not use ffmpeg

### ISSUE THREAD

**Issue by wangfpp** [fluent-ffmpeg/node-fluent-ffmpeg#1033]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: /@ffmpeg-installer/ffmpeg" : 4.1.0
* OS:  Ubuntu 20.04

### Code to reproduce

```js
onst ffmpeg = require('fluent-ffmpeg');
const { path: pathToFfprobe } = require('ffprobe-static');
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;
ffmpeg.setFfmpegPath(ffmpegPath);
ffmpeg.setFfprobePath(pathToFfprobe)

ffmpeg(analyse_data_path)
           .screenshots({
            timestamps: ['00:00:02'],
            filename: `${type}_cover_img.png`,
            folder: cover_path,
             size: '320x240'
 });

```
## error image
![Screenshot_20200706_140523](https://user-images.githubusercontent.com/35289556/86561131-896d6600-bf92-11ea-8216-637d39874a66.png)

**Comment by wangfpp** [comment]
## error message
Uncaught Exception 
Error: spawn ENOTDIR 
fluent-ffmpeg/lib/precessor.js 152:24
fluent-ffmpeg/lib/capabilities.js 90:14
fluent-ffmpeg/lib/capabilities.js 517:10
fluent-ffmpeg/lib/capabilities.js 568:14
fluent-ffmpeg/lib/capabilities.js 565:11

**Comment by xinlei3166** [comment]
How did you solve this problem?
