### ISSUE TITLE
Merge 2 mp4 files in a row (concat) (urgent)

### ISSUE THREAD

**Issue by ahmetozalp** [fluent-ffmpeg/node-fluent-ffmpeg#1034]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: ffmpeg version 4.3
* OS: MacBook Pro

### Code to reproduce

```js
ffmpeg()
          .input(`${VIDEO_PATH}/${room}/videos/07eb096c7353011952b9fcd69b29d37c_1594019508753.mp4`)
          .input(`${VIDEO_PATH}/${room}/videos/bc9a7bca8ff414967196d114956a5a57_1594019508767.mp4`)
          // .inputOptions(['-f concat', '-safe 0'])
          // .outputOptions('-c copy')
          //.addInputOptions(['-f concat', '-safe 0'])
          // filesFilter.forEach((file: any, index: number) => {
          //   if(index > 2) return false
          //   merge.input(`${VIDEO_PATH}/${room}/videos/${file}`)
          // })
          .complexFilter(['"[0:a][1:a]amerge=inputs=2[aout]"'])
          .outputOptions([
            '-c:v copy',
            '-c:a aac',
            '-strict experimental',
            '-map 0:v:0',
           // '-filter_complex "[0:a][1:a]amerge=inputs=2[aout]"',
            '-map "[aout]"',
            '-ac 2'
          ])
          .output(`${VIDEO_PATH}/${room}/result_${new Date().getTime()}.mp4`)
          .on('start', (cmd: any) => {
            console.log("basladiiii: ", cmd)
          })
          .on('error', (err: any) => {
            console.log("hata!", err.message)
          })
          .on('end', ()=>{
            console.log("bigttiti")
          })
          .run()
```

error line
`ffmpeg -i ./res/records/b60cf79d85c4e23fca401d1d6832035e/videos/07eb096c7353011952b9fcd69b29d37c_1594019508753.mp4 -i ./res/records/b60cf79d85c4e23fca401d1d6832035e/videos/bc9a7bca8ff414967196d114956a5a57_1594019508767.mp4 -y -filter_complex "[0:a][1:a]amerge=inputs=2[aout]" -c:v copy -c:a aac -strict experimental -map 0:v:0 -map "[aout]" -ac 2 ./res/records/b60cf79d85c4e23fca401d1d6832035e/result_1594059963335.mp4`

where am i making a mistake?

**Comment by ahmetozalp** [comment]
example working code but  erasing the other voice, I want it to be deleted

ffmpeg -i ./res/records/b60cf79d85c4e23fca401d1d6832035e/videos/07eb096c7353011952b9fcd69b29d37c_1594019508753.mp4 -i ./res/records/b60cf79d85c4e23fca401d1d6832035e/videos/bc9a7bca8ff414967196d114956a5a57_1594019508767.mp4 -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0    -y output2.mp4

**Comment by ahmetozalp** [comment]
-y how do i get to an end?

**Comment by flenoir** [comment]
you error line is not an error line , it just the command line version of your fluent-ffmpeg command. Can you post the error  ?
