### ISSUE TITLE
Lazy import fluent ffmpeg

### ISSUE THREAD

**Issue by skhaz** [fluent-ffmpeg/node-fluent-ffmpeg#1038]
How can I use this lazy import with fluent ffmpeg?

### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: ffmpeg-static 4.2.5
* OS: linux

### Code to reproduce

```js
const ffmpeg = await import('fluent-ffmpeg')

const takeScreenShot = ffmpeg(tempFilePath).takeScreenshots(
  { count: 1, timemarks: ['00:00:01.000'], size: '200x200' },
  'video/'
)
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

Import fluent ffmpeg.

### Observed results

TypeError: ffmpeg is not a function

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [X] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [X] I have included full stderr/stdout output from ffmpeg

**Comment by schizobulia** [comment]
If you need to confirm the results, you can use Promise.

example:
```
function main() {
    return new Promise((resolve, reject) => {
        ffmpeg(inputFilePath)
            .on('filenames', function (filenames) {
            })
            .on('end', function () {
                resolve('end');
            })
            .on('error', function (err) {
                reject(err);
            })
            .takeScreenshots({ count: 2, timemarks: ['00:00:02.000', '6'], size: '150x100' }, outFilePath);
    }).catch(err => {
        console.error(err);
    });
}
```
