### ISSUE TITLE
Check if ffmpeg rtsp connection was succesful?

### ISSUE THREAD

**Issue by mhiaxo** [fluent-ffmpeg/node-fluent-ffmpeg#1076]
I'm updating an image every 5 seconds from an RTSP stream, and trying to figure out the best way to send a response to the client that says rtsp connection was successful.

```
      ffmpeg(streamUrl, { timeout: 432000 })
        .output(`./public/posters/${streamId}.jpg`)
        .inputOptions(["-rtsp_transport tcp"])
        .addOptions([
          "-flags +global_header",
          "-c:v",
          "libwebp",
          "-update",
          "1",
          "-s",
          "960x540",
          "-r",
          "1/5",
          "-f",
          "image2",
          "-y",
        ])
        .size("1280x720")
        .on("error", function (err) {
          console.log(err.message);
        })
        .run()
```

I've tried all of the event listeners and only "progress" really outputs anything useful, though not sure how I can really use that as a way to tell if it was successful. 

Also, error listener is unreliable as "Invalid data" can still mean it could reconnect. 

One codebase polls  hls files to see if they exist, but I can't really do that here so any other ideas I would appreciate!

**Comment by FedericoCarboni** [comment]
You could check if the RTSP connection was successful by setting FFmpeg's log level to `debug` and checking its logs. Otherwise, I don't think there's any way to do it.
