### ISSUE TITLE
[Question] Is it possible to download a file while its getting converted with ffmpeg?

### ISSUE THREAD

**Issue by deniscerri** [fluent-ffmpeg/node-fluent-ffmpeg#1092]
Right now, i have to wait for the file to get converted with ffmpeg then after its done, i pipe it for download.
But this can get really long if im trying to convert a big video.

Is there a way to convert and download the file at the same time?
Thanks!

**Comment by FedericoCarboni** [comment]
@deniscerri Yes, you can do it, but not with all video formats, you have to make sure that the output is streamable. For example, MP4 won't work, the best options would be WebM or MKV (MKV is a little bit more flexible). You can pipe the file directly to a writable stream (which could be a response object in express for example). Keep in mind that you won't be able to seek backwards or forwards in the video while streaming the download like this.

**Comment by deniscerri** [comment]
> @deniscerri Yes, you can do it, but not with all video formats, you have to make sure that the output is streamable. For example, MP4 won't work, the best options would be WebM or MKV (MKV is a little bit more flexible). You can pipe the file directly to a writable stream (which could be a response object in express for example). Keep in mind that you won't be able to seek backwards or forwards in the video while streaming the download like this.

Thanks. I dont really need to stream the video so seeking wont be an issue. I just want to download it and that is sufficient. Really appreciate the reply

**Comment by deniscerri** [comment]
@FedericoCarboni Mind if i ask, why doesnt mp4 work in this case scenario but mkv does?

**Comment by FedericoCarboni** [comment]
@deniscerri Due to limitations in FFmpeg's MP4 demuxer, it can't stream the file because it has to seek back and forth to write bytes in different parts of the file. So it requires the output destination to be seekable. This limitation also applies to other formats btw.
