### ISSUE TITLE
on('progress') returns NaN for some properties... 

### ISSUE THREAD

**Issue by Sten435** [fluent-ffmpeg/node-fluent-ffmpeg#1093]
I get frames: (NaN, currentFps: NaN,) when i used the .on progress with ffmpeg.

I want to become a percentage like "40% Done"

The format of video Im inputting is -> 'webm'
And the output is -> 'mp3'

When i do:
```js
on('progress', function (data) {
     console.log(data);
})
```
The result I get is ...

```js
{
  frames: NaN,
  currentFps: NaN,
  currentKbps: 105,
  targetSize: 768,
  timemark: '00:00:59.92'
}
{
  frames: NaN,
  currentFps: NaN,
  currentKbps: 122,
  targetSize: 1024,
  timemark: '00:01:08.78'
}
{
  frames: NaN,
  currentFps: NaN,
  currentKbps: 108.5,
  targetSize: 1024,
  timemark: '00:01:17.32'
}
{
  frames: NaN,
  currentFps: NaN,
  currentKbps: 121.1,
  targetSize: 1280,
  timemark: '00:01:26.57'
}
```

dependencies ->

```json
"dependencies": {
    "ffmpeg-static": "^4.2.7",
    "fluent-ffmpeg": "^2.1.2",
    "node-fetch": "^2.6.1",
    "seconds-converter": "^1.3.0",
    "ytdl-core": "^4.2.1"
  },
```

full code ->
```js
          let ffmpeg = require('fluent-ffmpeg');
          let convert = ffmpeg()
          convert.input(`${__dirname}/temp/${title}.${filetype}`)
          convert.output(`${filePath}/${title}.mp3`)

          convert.on('start', function(commandLine) {
            console.log('Spawned Ffmpeg with command: ' + commandLine);
          });

          convert.on('error', function(err) {
                console.log('Cannot process video: ' + err.message);
                win.webContents.send('convert-error', err.message)
          })

          convert.on('progress', function (data) {
            console.log(data);
          })

          convert.on('end', function() {
                console.log('ended');
                win.webContents.send('download-info', 'Processing Complete')
                fs.unlink(`${__dirname}/temp/${title}.${filetype}`, function (err) {
                  if (err){
                    win.webContents.send('delete-error', err)
                  }
                }); 
          })
          convert.run();
```

**Comment by Sten435** [comment]
> I get frames: (NaN, currentFps: NaN,) when i used the .on process with ffmpeg.
> 
> I want to become a percentage like "40% Done"
> 
> The format of video Im inputting is -> 'webm'
> And the output is -> 'mp3'
> 
> When i do:
> 
> ```
> on('progress', function (data) {
>      console.log(data);
> })
> ```
> 
> The result I get is ...
> 
> ```
> {
>   frames: NaN,
>   currentFps: NaN,
>   currentKbps: 105,
>   targetSize: 768,
>   timemark: '00:00:59.92'
> }
> {
>   frames: NaN,
>   currentFps: NaN,
>   currentKbps: 122,
>   targetSize: 1024,
>   timemark: '00:01:08.78'
> }
> {
>   frames: NaN,
>   currentFps: NaN,
>   currentKbps: 108.5,
>   targetSize: 1024,
>   timemark: '00:01:17.32'
> }
> {
>   frames: NaN,
>   currentFps: NaN,
>   currentKbps: 121.1,
>   targetSize: 1280,
>   timemark: '00:01:26.57'
> }
> ```
> 
> dependencies ->
> 
> ```
> "dependencies": {
>     "ffmpeg-static": "^4.2.7",
>     "fluent-ffmpeg": "^2.1.2",
>     "node-fetch": "^2.6.1",
>     "seconds-converter": "^1.3.0",
>     "ytdl-core": "^4.2.1"
>   },
> ```
> 
> full code ->
> **```
>       let convert = ffmpeg()
>       convert.input(`${__dirname}/temp/${title}.${filetype}`)
>       convert.output(`${filePath}/${title}.mp3`)
> 
>
>       convert.on('start', function(commandLine) {
>         console.log('Spawned Ffmpeg with command: ' + commandLine);
>       });
> 
>       convert.on('error', function(err) {
>             console.log('Cannot process video: ' + err.message);
>             win.webContents.send('convert-error', err.message)
>       })
> 
>       convert.on('progress', function (data) {
>         console.log(data);
>       })
> 
>       convert.on('end', function() {
>             console.log('ended');
>             win.webContents.send('download-info', 'Processing Complete')
>             fs.unlink(`${__dirname}/temp/${title}.${filetype}`, function (err) {
>               if (err){
>                 win.webContents.send('delete-error', err)
>               }
>             }); 
>       })
>       convert.run();
> ```

**Comment by FedericoCarboni** [comment]
@Sten435 Since you are not encoding audio frames and fps will not be printed by FFmpeg. `NaN` will be used instead.
