### ISSUE TITLE
BUG: Duration is longer than excepted

### ISSUE THREAD

**Issue by dalisoft** [fluent-ffmpeg/node-fluent-ffmpeg#1094]
### Version information

* fluent-ffmpeg version: `fluent-ffmpeg/node-fluent-ffmpeg#master`
* ffmpeg version: `4.3.1`
* OS: macOS Catalina 10.15.7

### Code to reproduce

```js
async function convertJpgToVideo(jpegFilePath, duration = 5) {
  const instance = ffmpeg();
  const [width, height] = [600, 600]

  return instance
    .addInput(jpegFilePath)
    .inputFPS(1)
    .outputFPS(1)
    .loop()
    .duration(duration)
    .outputOptions('-movflags frag_keyframe+empty_moov')
    .toFormat('mp4')
    .size(`${width}x${height}`)
    .noAudio();
}
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
Output video with `duration === 5 seconds`

### Observed results

Output video with `duration 6 seconds`

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by xedsvg** [comment]
This is the expected output. Ffmpeg will cut to the nearest GOP which in
your case will be at second nr 6. Try the same command in ffmpeg and post
your result.

**Comment by dalisoft** [comment]
After a lot of tries i found fix.
If anyone gets same issue, set fps to `25`
