### ISSUE TITLE
Cannot define first parameter before input file

### ISSUE THREAD

**Issue by IL55** [fluent-ffmpeg/node-fluent-ffmpeg#1102]
Hi, according to this recommendation
https://superuser.com/questions/1406566/how-to-specify-input-audo-decoder-for-ffmpeg
we need to add some option (-c:a mp3) **before** input file:

`ffmpeg -c:a mp3 -i "file.mp3" -c:a libopus "file.opus"`

That option is "codec for input file", without that option ffmpeg fails.
it seems there is no way for fluent-ffmpeg to define that use case, i.e. input is mandatory and add as first parameter ?

I tried to define it via addOption, addOptions and without success.
ffmpeg()
      .addOptions([
        "-c:a mp3",
        '-i "file.mp3"',       
        "-c:a libopus",
        "file.opus"
      ])

**Comment by IL55** [comment]
the answer is that for input we should use inputOption i.e.
ffmpeg("file.mp3"')
.inputOption("-c:a mp3")
...

**Comment by sashazxtt** [comment]
I have an opposite problem: the input file is specified *after* the '-c copy' and that causes ffmpeg to fail with the 'unknown codec copy' error.
This command line works, but I can't construct it with fluent-ffmpeg:
ffmpeg.exe -i input.webm  -strict experimental -c copy output.mp4

Is there a way to force the input file to be the first parameter to ffmpeg?

**Comment by dimdenGD** [comment]
> I have an opposite problem: the input file is specified _after_ the '-c copy' and that causes ffmpeg to fail with the 'unknown codec copy' error. This command line works, but I can't construct it with fluent-ffmpeg: ffmpeg.exe -i input.webm -strict experimental -c copy output.mp4
> 
> Is there a way to force the input file to be the first parameter to ffmpeg?
I could fix this by using `.outputOptions('-c copy');`
