### ISSUE TITLE
Ffmpeg Filter: Amplify 🌟

### ISSUE THREAD

**Issue by phaticusthiccy** [fluent-ffmpeg/node-fluent-ffmpeg#1107]
**I could not see this filter among the supported filters. A must-have filter that can do great things, in my opinion.**

**Soo i'll wait for this 😉**

**Comment by FedericoCarboni** [comment]
@phaticusthiccy You can change the volume using the `volume` filter. Also, this library is just a wrapper around FFmpeg, so any feature like a new filter will never be implemented here, but in FFmpeg directly.

**Comment by phaticusthiccy** [comment]
Oh, ı dont mean audio. There is an Amplify filter for the video.

**Comment by FedericoCarboni** [comment]
What do you mean exactly with amplify?
