### ISSUE TITLE
start event on secondary call never comes

### ISSUE THREAD

**Issue by micahg** [fluent-ffmpeg/node-fluent-ffmpeg#1110]
### Version information

* fluent-ffmpeg version: 2.1.16
* ffmpeg version:n4.3.1-221-gd08bcbffff
* OS: windows 10

### Code to reproduce

Sorry, the following is typescript (can be run with ```mocha -r ts-node/register --timeout 60000 --full-trace --allow-uncaught --bail --exit filename.ts``` or I can rewrite in javascript)
```
import * as ffmpeg from "fluent-ffmpeg";

function spawn(url: string): ffmpeg.FfmpegCommand {
  return ffmpeg(url)
    .audioBitrate("192k")
    .videoCodec("libx264")
      .addOption("preset", "ultrafast")
      .addOption("tune", "zerolatency")
    .audioCodec("aac")
    .addOption("hls_time", "4")
    .addOption("hls_list_size", "4")
    .addOption("hls_flags", "delete_segments+temp_file")
    .save("c:\\tmp\\stream.hls")
    .on("stderr", line => console.log(line))
    .on("error", (err) => {
      console.log(`"ERRORED OUT ${err.message}"`);
    })
    .on("end", () => {
      console.log("ENDED");
    })
    .on("start", cmd => {
      console.log(`STARTED ${cmd}`)
    });
}

describe("stuff", () => {

  it("Is getting wierd", function(done) {
    let proc1: ffmpeg.FfmpegCommand = spawn(`udp://localhost:5000`);
    let proc2: ffmpeg.FfmpegCommand = spawn(`udp://localhost:5001`);
    setTimeout(() => {
      proc1.kill("SIGKILL");
      proc2.kill("SIGKILL");
      setTimeout(() => {
        done();
      }, 500)
    }, 500);
  });

  it("Is getting wierder", function(done) {
    let proc1: ffmpeg.FfmpegCommand = spawn(`udp://localhost:5000`);
    setTimeout(() => {
      proc1.kill("SIGKILL");
      setTimeout(() => {
        let proc2: ffmpeg.FfmpegCommand = spawn(`udp://localhost:5000`);
        setTimeout(() => {
          proc2.kill("SIGKILL");
          setTimeout(() => {
            done();
          }, 500);
        }, 500);
      }, 500);
    }, 500);
  })
})

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

```
  stuff
STARTED ffmpeg -i udp://localhost:5001 -y -b:a 192k -acodec aac -vcodec libx264 preset ultrafast tune zerolatency hls_time 4 hls_list_size 4 hls_flags delete_segments+temp_file c:\tmp\stream.hls
STARTED ffmpeg -i udp://localhost:5000 -y -b:a 192k -acodec aac -vcodec libx264 preset ultrafast tune zerolatency hls_time 4 hls_list_size 4 hls_flags delete_segments+temp_file c:\tmp\stream.hls
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
    √ Is getting wierd (1035ms)
STARTED ffmpeg -i udp://localhost:5001 -y -b:a 192k -acodec aac -vcodec libx264 preset ultrafast tune zerolatency hls_time 4 hls_list_size 4 hls_flags delete_segments+temp_file c:\tmp\stream.hls
STARTED ffmpeg -i udp://localhost:5001 -y -b:a 192k -acodec aac -vcodec libx264 preset ultrafast tune zerolatency hls_time 4 hls_list_size 4 hls_flags delete_segments+temp_file c:\tmp\stream.hls
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
    √ Is getting wierder (2093ms)


  2 passing (3s)
```

### Observed results

This test does two things:

* start two udp listeners asynchronously at the same time on different ports, then kill them both
* start two udp listeners synchronously on the _same_ port (killing one then starting the next)

After the first two processes spawn and behave as expected in the first test case, the _started_ event is not happening on the second set of processes. If you uncomment ```.on("stderr", line => console.log(line))```, those calls no longer seem to happen either. I get:

```
  stuff
STARTED ffmpeg -i udp://localhost:5001 -y -b:a 192k -acodec aac -vcodec libx264 preset ultrafast tune zerolatency hls_time 4 hls_list_size 4 hls_flags delete_segments+temp_file c:\tmp\stream.hls
STARTED ffmpeg -i udp://localhost:5000 -y -b:a 192k -acodec aac -vcodec libx264 preset ultrafast tune zerolatency hls_time 4 hls_list_size 4 hls_flags delete_segments+temp_file c:\tmp\stream.hls
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
    √ Is getting wierd (1035ms)
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
"ERRORED OUT ffmpeg was killed with signal SIGKILL"
    √ Is getting wierder (2093ms)


  2 passing (3s)
```

The process seems to be created an killed (according to the output) but I never get any actual events after the first two process live and die. Is this expected? I did read through the readme but didn't see anything about ffmpeg only being able to run once.

If the first case is removed (leaving only the synchronous case) the results are similar -- everything works as expected for the first process, but the second has no started or stderr...

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by micahg** [comment]
I believe this is actually a duplicate of 1095

**Comment by totzcc** [comment]
You should register event handlers before calling save(), because the processing methods check for registered event handlers at the beginning. That would probably explain unpredictible results when registering events after having called save().

#674
