### ISSUE TITLE
Cannot compose a video from multiple images using input and loop.

### ISSUE THREAD

**Issue by TrofinSorin** [fluent-ffmpeg/node-fluent-ffmpeg#1113]
![image](https://user-images.githubusercontent.com/43543139/111514939-e690fc80-875a-11eb-9db0-012bccbce1ff.png)

Can composing a video from multiple images with certain durations and transitions and merging with other videos be done in this library? I mean.. there is an example in this repository with creating a video by looping one image but not multiple.

In the example above both images are looping super fast, how can i set the duration of each one to 3 seconds each? I tried with loop(3) also, and it doesn't work.
I'm trying to create a functionality where i can merge images that can be looped for a number of seconds and videos with tranzitions at the same time. Can this be done with this library? 

I'm not so experienced in this so some questions might be odd.

Can all of this be done with chaining functions? Or i need to use spawn and command lines from ffmpeg.
Also i saw that i can use ./images/image%01d.png' to get the images that have a certain format. Is there a pattern for the extension also? Some images are jpg not all are png.

**Comment by aanishacharyaa** [comment]
Have you find solution to this? I am encountering the same problem.

**Comment by TrofinSorin** [comment]
Yes, i've used ffmpeg directly. 
And it's better because it gets updated more often.

ffmpeg -y -i 1.jpeg -i 2.jpeg -t 4 -i 3.jpg -filter_complex "[0:v]tpad=stop=-1:stop_mode=clone,trim=0:5,scale=878x494,setsar=1[0v];[1:v]tpad=stop=-1:stop_mode=clone,trim=0:5,scale=878x494,setsar=1[1v];[2:v]tpad=stop=-1:stop_mode=clone,trim=0:5,scale=878:494,setsar=1[2v];[0v][1v][2v]concat=n=3:v=1[v]" -map "[v]"  video.mp4
