### ISSUE TITLE
`pipe:0: Input/output error` when input is a `Buffer` and resizing gif

### ISSUE THREAD

**Issue by DetachHead** [fluent-ffmpeg/node-fluent-ffmpeg#1157]
the gif: https://i.stack.imgur.com/kNTGR.gif
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.1.6-1~deb10u1
* OS: ubuntu

### Code to reproduce

```ts
import ffmpeg from 'fluent-ffmpeg'
import fs from 'fs'
import { Readable } from 'stream'

const inputBuffer = fs.readFileSync('test/input.gif')
const outputPath = 'test/output.gif'

//pipe:0: Input/output error:
ffmpeg(Readable.from(inputBuffer))
//no error (uncomment this line):
// ffmpeg(outputPath)
    .output(outputPath)
    .addInputOptions('-hide_banner', '-v', 'warning')
    //https://superuser.com/a/1362406
    .complexFilter([
        '[0:v] scale=320:-1:flags=lanczos,split [a][b]',
        '[a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]',
        '[b][p] paletteuse',
    ])
    .on('error', console.error)
    .on('start', console.log)
    .on('stderr', console.error)
    .on('end', console.log)
    .run()
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
no error and gif is resized successfully

### Observed results
the following error in stderr
```
pipe:0: Input/output error
```
the gif is resized but no longer animated

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [X] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [X] I have included full stderr/stdout output from ffmpeg
```
ffmpeg -hide_banner -v warning -i pipe:0 -y -filter_complex [0:v] scale=320:-1:flags=lanczos,split [a][b];[a] palettegen=reserve_transparent=on:transparency_color=ffffff [p];[b][p] paletteuse test/output.gif
pipe:0: Input/output error
[Parsed_palettegen_2 @ 0x55a170564f00] Dupped color: FF000000
[Parsed_palettegen_2 @ 0x55a170564f00] Dupped color: FF010101

 pipe:0: Input/output error
[Parsed_palettegen_2 @ 0x55a170564f00] Dupped color: FF000000
[Parsed_palettegen_2 @ 0x55a170564f00] Dupped color: FF010101
```

**Comment by FedericoCarboni** [comment]
When streaming images to ffmpeg you must specify the format: try to add `-f gif_pipe` to input arguments.
