### ISSUE TITLE
Overlay Image with Video

### ISSUE THREAD

**Issue by imclean** [fluent-ffmpeg/node-fluent-ffmpeg#1170]
### Version information

* fluent-ffmpeg version: latest
* ffmpeg version: latest
* OS: MacOS M1 Apple Latest

I am looking to overlay a video onto an image and output the new video in H264, I can do this with ffmpeg in the terminal with:

ffmpeg -loop 1 -i './image.jpg' -vf "movie=video.mp4,scale=1080:1080[inner];[in][inner]overlay=0:0:shortest=1[out]"  -vcodec libx264 -y output.mp4

### Code to reproduce
I am trying to do the exact same with fluent:

ffmpeg().addInput('./image.jpg').loop().addInput('./video.mp4').videoCodec('libx264').save('/Path/To/File/On/myMac/file.mp4')

### Expected results

As per ffmpeg terminal

### Observed results

Just the video with no image, no error

### Checklist

* [ x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x ] I have included full stderr/stdout output from ffmpeg

**Comment by imclean** [comment]
it's ok, I sorted it.

ffmpeg()
        .input(`./image.jpg`)
        .inputOptions(['-loop 1'])
        .input(`./image.jpg`)
        .videoFilter(`movie=Video.mp4,scale=1080:1080[inner];[in][inner]overlay=0:0:shortest=1[out]`)
        .videoCodec('libx264')
        .noAudio()
        .save(`./output.mp4`)

**Comment by PrincePRS** [comment]
@imclean , I'm going to overlay 4 videos on background image.
4 videos will be shown as a grid(2 X 2).
How can I do this using flutent-ffmpeg
