### ISSUE TITLE
FfmpegCommand is not a constructor

### ISSUE THREAD

**Issue by Matix-Media** [fluent-ffmpeg/node-fluent-ffmpeg#1193]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 2022-10-13-git-9e8a327e68-full_build-www.gyan.dev
* OS: Windows 11
* TypeScript version: 4.8.4
* JavaScript version: ESNext (ES2022)

### Code to reproduce

```js
const command = new FfmpegCommand(filePath);
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
no error creating the command

### Observed results
Error that `FfmpegCommand` is not a constructor.
```
TypeError: fluent_ffmpeg_1.FfmpegCommand is not a constructor
    at D:\Development\JS\media-server\src\entities\preview.ts:53:29
```

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by Matix-Media** [comment]
Turns out this a type definitions issue. (@types/fluent-ffmpeg)

**Comment by NorthGuard** [comment]
I have the same problem.
How did you get rid of it? :)
Can you not use @types/fluent-ffmpeg?

**Comment by hshqwq** [comment]
I have same problem.

This is my solution:

Replace `import Ffmpeg from 'fluent-ffmpeg';` with `import Ffmpeg = require('fluent-ffmpeg');`

(If you don't need type, just use `const Ffmpeg = require('fluent-ffmpeg');`)

Because it's not a ES module, so we need to import like a CommonJs module.

**Comment by stoplion** [comment]
Is there a way in 2023 to use `import` and not `require`? 🙄
