### ISSUE TITLE
Invalid argument when using fluent-ffmpeg to concatenate two video files

### ISSUE THREAD

**Issue by DGLcsGaming** [fluent-ffmpeg/node-fluent-ffmpeg#1197]
### Version information

* fluent-ffmpeg version:  2.1.2
* ffmpeg version:  git-2022-10-25-9bed814-ffmpeg-windows-build-helpers
* OS: Windows 10 (21H2) 
* Nodejs: v14.18.3

So I'm trying to use fluent-ffmpeg to concatenate (using concat demuxer) two .mp4 videos files (identical video/audio formats) but I'm getting this error:

```js
Error: ffmpeg exited with code 1: ":../../input.txt": Invalid argument
```

### Code to reproduce

```js
const ffmpeg = require('fluent-ffmpeg');
.
.
const mergeVideoImageWithOriginalVideo = (imageVideo) => {
  return new Promise((resolve, reject) => {
    const command = new ffmpeg();
    command
      .input(`"../../${imageVideo.replace('./', '')}"`)
      .inputFormat('concat')
      .inputOptions(['-safe 0'])
      .outputOptions(['-c copy'])
      .on('start', function (ffmpegCommand) {
        console.log(ffmpegCommand);
      })
      .on('progress', function (data) {
        /// do stuff with progress data if you want
      })
      .on('end', function () {
        resolve();
      })
      .on('error', function (error) {
        return reject(new Error(error));
      })
      .save(`"../../${imageVideo.replace('txt', 'final.mp4').replace('./', '')}"`)
      .run();
  });
};
```
### The contents of input.txt:
```js
file 'video.image.mp4'
file 'video.mp4'
```
### The output of console.log(ffmpegCommand) is:
```js
ffmpeg -f concat -safe 0 -i "../../input.txt" -y -c copy "../../video.final.mp4"
```

### Expected results
Concatinate both video files into a video.fina.mp4

### Observed results
The weird thing is when I run that exact command (using CMD) in the same directory that I'm running this nodejs script it works.

**Comment by klesun** [comment]
Hi. Did you find out why it did not work in the end?

**Comment by klesun** [comment]
I managed to make concat work using the [`mergeToFile()`](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg?tab=readme-ov-file#mergetofilefilename-tmpdir-concatenate-multiple-inputs)

```js
const command = new ffmpeg();
for (const inputFilePath of inputFilePaths) {
    command.input(inputFilePath);
}
command
    .input(`"../../${imageVideo.replace('./', '')}"`)
    .on('end', resolve)
    .on('error', reject)
    .mergeToFile(`"../../${imageVideo.replace('txt', 'final.mp4').replace('./', '')}"`, "tmp");
```

**Comment by klesun** [comment]
Upd.: hm, though somehow it ended up changing the codec =/

**Comment by klesun** [comment]
Related: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1012
Guess it can only be done with command line...
