### ISSUE TITLE
Fix to Output format [***] is not available

### ISSUE THREAD

**Issue by MarianoFacundoArch** [fluent-ffmpeg/node-fluent-ffmpeg#1266]
I have created a fix for this, but I see that the NPM package has not been updated for a long time.
I don't know if someone has permission to push into the official NPM after a fix.
I created a pull request here:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/1265

It basically fixes the regex expr to be compatible with ffmpeg 7 too

You can also install package from: https://www.npmjs.com/package/fluent-ffmpeg-7 and just change the import to from 'fluent-ffmpeg-7' I did a quick version there till official version gets fixed.

**Comment by romain130492** [comment]
Thanks......!
I second this, any way to push that update to the official package?

**Comment by DGXeon** [comment]
It doesnt work for webp

**Comment by MarianoFacundoArch** [comment]
Can you provide a replication case to further investigate ?
Are you sure you installed from fluent-ffmpeg-7 and you are importing from that package ?

**Comment by DGXeon** [comment]
> Can you provide a replication case to further investigate ? Are you sure you installed from fluent-ffmpeg-7 and you are importing from that package ?

Yes imported from package

**Comment by MarianoFacundoArch** [comment]
Can you provide me with a sample replication code to further debug/fix it?

**Comment by MarianoFacundoArch** [comment]
By the way, are you sure that you have the encoder/decoder in ffmpeg?
Try running
ffmpeg -encoders|grep webp
ffmpeg -decorders|grep webp

**Comment by klesun** [comment]
@njoyard please? fluent-ffmpeg is broken for current version of ffmpeg without this PR.

**Comment by totallytavi** [comment]
Made a patch for this in [the PR](#1265). Instructions are there

**Comment by komninoschatzipapas** [comment]
Still doesn't work with ffmpeg 7.0 & fluent-ffmpeg 2.1.3 on MacOS.
```
Output format mp3 is not available
```

**Comment by MarianoFacundoArch** [comment]
On my version it works if you have the output format available.

Execute ffmpeg -encoders | grep mp3
And paste here the output please

**Comment by ricbir** [comment]
> On my version it works if you have the output format available.
> 
> Execute ffmpeg -encoders | grep mp3 And paste here the output please

```
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
 A....D libmp3lame           libmp3lame MP3 (MPEG audio layer 3) (codec mp3)
```

**Comment by mrkos67** [comment]
I'm still getting this issue on a Mac with ffmpeg v7.1.1 + fluent-ffmpeg v2.1.3.

Running the equivalent ffmpeg command directly in terminal works.
