### ISSUE TITLE
Input format v4l2 is not available

### ISSUE THREAD

**Issue by SageKwun** [fluent-ffmpeg/node-fluent-ffmpeg#1290]
### Version information

* fluent-ffmpeg version: 2.1.3
* ffmpeg version: git-2024-07-11-092ef40 Copyright (c) 2000-2024 the FFmpeg developers
* OS: ubuntu 23.04

### Code to reproduce

```js
ffmpeg('/dev/video0')
      .inputOptions([
        '-f', 'v4l2',
        '-input_format', 'mjpeg'
      ])
      .videoFilter('scale=640:360')
      .videoCodec('h264_qsv')
      .outputOptions('-preset:v veryfast')
      .outputOptions('-maxrate 1000k')
      .outputOptions('-bufsize 1000k')
      .outputOptions('-r 30')
      .outputOptions('-g 60')
      .format('mpegts')
      .output('my url')
      .run();

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

I tried 

``` bash
ffmpeg -f v4l2 -i /dev/video0 -vf scale=640:360 -c:v h264_qsv -preset:v veryfast -maxrate 1000k -bufsize 1000k -r 30 -g 60 -f mpegts 'my url' 
```

and it succeed. I turn in to fluent-ffmpeg format, but error:

```bash
node_modules/.pnpm/async@0.2.10/node_modules/async/lib/async.js:582
                    tasks[index].apply(null, arguments);
                                 ^
Error: Input format v4l2 is not available
```

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by stepin** [comment]
It's related to https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1282
