### ISSUE TITLE
Recommended way to kill process?

### ISSUE THREAD

**Issue by dweldon** [fluent-ffmpeg/node-fluent-ffmpeg#138]
If a user wants to kill a running ffmpeg process, what is the recommend way to go about that?

**Comment by ariel-frischer** [comment]
> This is not feasible as commands are complex objects. And it is also useless (node keeps running commands in memory anyway, so no need to store them somewhere else in addition).

I'm running into Node ENOMEM issues on Node v 12.16.2, calling a bunch of normal FFMPEG commands. Perhaps ENOMEM is a result of Node management and accumulation of ffmpeg commands?? I am passing in file paths rather then readStreams as well, could that be a source of memory leak??

**Comment by dyeoman2** [comment]
The approach below allowed me kill an RTSP to RTMP live stream when a kill criteria was met. Hope it helps!

```
const ff = ffmpeg()

ff.input(rtspUri)
  .outputOptions(['-c copy', '-acodec aac', '-f flv'])
  .save('rtmp://127.0.0.1:1935/live/test')
  .on('progress', (p) => {
    if (killCriteria) {
      ff.kill()
      console.log('ffmpeg > killed')
    }
    console.log('ffmpeg > in progress')
  })
  .on('end', () => {
    console.log('ffmpeg > completed')
  })
  .on('error', (err) => {
    console.log(`ffmpeg > error: ${err.message}`)
  })
```
