### ISSUE TITLE
how do I run make

### ISSUE THREAD

**Issue by fschwiet** [fluent-ffmpeg/node-fluent-ffmpeg#143]
This is more of a question than issue, but has anyone been able to run make test on Windows.  I do not use make files typically, so I am probably making a mistake.  Anyhow, after installing make from http://chocolatey.org/packages/GnuWin, I then get complaints about NODE_ENV.

```
c:\src\node-fluent-ffmpeg>set NODE_ENV=development

c:\src\node-fluent-ffmpeg>make
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
make: *** [test] Error 1

c:\src\node-fluent-ffmpeg>make test
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
make: *** [test] Error 1
```

  I was going to try to add cropping functionality to work like applyAutopadding(), but haven't been able to run the tests.  I know some node, but not make.

**Comment by lesion** [comment]
ehi @fschwiet have you implemented cropping at the end ?
