### ISSUE TITLE
ffmpeg pipe, missing metadata

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [fluent-ffmpeg/node-fluent-ffmpeg#159]
Was trying to dump the ffmpeg into a writable via the writeToStream method but stream is missing important metadata....

Error looks isolated to ffmpeg on Windows (using windows 8, 64 bits).  Ran the following:
    ffmpeg -i "<input h264>" -codec:v libvpx -f webm "<output webm>"

and (note: -f webm has to be there otherwise ffmpeg complains about no suitable output format):
    ffmpeg -i "<input h264>" -codec:v libvpx -f webm pipe:1 > "<output webm>"

Viewing the video file via chrome shows no duration for the piped output whereas the other file (from the first command) works fine.  Confirmed with ffprobe.  No bitrate info either.

Assume ffmpeg uses file stat info but with streams there isn't any.  It affects the writeToStream methods and will give users a head-ache.  Update the Readme?

Any rate, great plugin to node!!!!

**Comment by FallingSnow** [comment]
This is a major stream joy kill :(

Do you know of any way around this? Such as opening a new stream to prepend this information to the file.

**Comment by jbromberg** [comment]
Encountering this issue and wondering if there's a known workaround to getting metadata when piping
