### ISSUE TITLE
Help encoding a video from a live sequence of canvas image data

### ISSUE THREAD

**Issue by subblue** [fluent-ffmpeg/node-fluent-ffmpeg#210]
In my app I'm encoding rendered frames from an html canvas element into a video. 
However, rather than first render out all frames to disk and then encode from a folder of images I would like to progressively add new frames to the output video as they are received from the client. 

Each frame takes a few seconds to render so I'm not trying to do anything like recording a realtime image of the canvas, just what is passed to node when each frame is ready.

I have the image data for each frame coming in like:

```
var newFrame = function (pngData, endFrame) {
    var data = pngData.replace(/^data:image\/\w+;base64,/, '');
    var buf  = new Buffer(data, 'base64');

    // it was previously just writing the image to disk and later 
    // converting the entire folder to a video, but now would like to 
    // pass just the current frame buffer into FFmpeg and progressively
    // encode until 'endFrame' is true and we are done
};
```

The app is running locally on the client machine within a nodewebkit app wrapper.
Any insight would be greatly appreciated :)

**Comment by stiller-leser** [comment]
Do you have an idea how I can implement this?

http://stackoverflow.com/questions/33190126/encode-stream-of-base64-encoded-images-with-ffmpeg-in-nodejs

It's a similar issue ;)

**Comment by njoyard** [comment]
I don't think you'd have a simpler way than saving the images as temp files and running ffmpeg on them.

Or going through the hassle of building a stream from that base64 images stream in such a way that ffmpeg has a codec to consume it.
