### ISSUE TITLE
2 pass encoding

### ISSUE THREAD

**Issue by kusmayadi** [fluent-ffmpeg/node-fluent-ffmpeg#217]
Is it possible to do 2 pass encoding using fluent-ffmpeg?

**Comment by rayfranco** [comment]
@njoyard I know this is an old thread but before opening a new one, can you confirm `save('/dev/null')` should work?

I get `[NULL @ 0x7f86cd801e00] Unable to find a suitable output format for '/dev/null'`

Same goes with forcing double quotes.

**Comment by njoyard** [comment]
You have to specify an output format.

**Comment by rayfranco** [comment]
@njoyard that is right I was missing that part on first pass. Thanks.

**Comment by ytingyeu** [comment]
I tried @njoyard 's solution in my Electron project and had something like:
```
let newJob = ffmpeg("/path/input")
    .addOptions(["-pass", "1"])
    ......
    .on('end', => {
        let secondPass = ffmpeg("/path/input")
            .addOptions(["-pass", "2"])
            ......
            .run();
})

newJob .run();
mainWindow.on('cancel', () => newJob.kill());
```
`mainWindow` listens `cancel` event and interrupt the encoding process.
But I found the way I did here cannot kill 2nd-pass process but 1st-pass only.
Any suggestion for tmy case?
