### ISSUE TITLE
Support RTMP, RTSP, RTP as output

### ISSUE THREAD

**Issue by matteos** [fluent-ffmpeg/node-fluent-ffmpeg#245]
FFmpeg can be used to push a stream towards remote servers or clients using different protocols. However, the current codebase prevents such outputs, because the normalization applied to the target string breaks protocol identifiers.

```
this.options.outputfile = path.normalize(target);
```

My suggestion is to implement a new method, "saveToStream" for example, and move the normalization check to the "saveToFile" method.

```
FfmpegCommand.prototype.saveToStream = function(targetstream, callback) {
       this._process(targetstream);
};
```

and

```
FfmpegCommand.prototype.saveToFile = function(targetfile, callback) {
 this._process(path.normalize(targetfile));
};
```

**Comment by mojibaked** [comment]
Is there an easy way of extracting the SDP information when generating a RTP-stream from fluent-ffmpeg?
The codecData event doesn't contain this information.

For example:
```
ffmpeg -re -i video.mp4 -vcodec copy -an -f rtp rtp://225.1.1.1:12345
```

Gives:
```
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 224.10.20.30
t=0 0
a=tool:libavformat 57.19.100
m=video 20000 RTP/AVP 96
b=AS:1499
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAH6zZQFAFuhAAAAMAEAAAAwPA8YMZYA==,aOvssiw=; profile-level-id=64001F
```

**Comment by azarus** [comment]
So can you please explain how?
