### ISSUE TITLE
Getting mjpeg as input

### ISSUE THREAD

**Issue by jwanhussin** [fluent-ffmpeg/node-fluent-ffmpeg#246]
Hi all,

I am trying to take an mjpeg stream as the input of the ffmpeg like this:

var request = require("request"),
ffmpeg = require('fluent-ffmpeg');

var stream = request('http://192.168.8.164:81/videostream.cgi');
var proc = new ffmpeg({ source: stream, nolog: true })
.
.
.

This is not working and I am getting the following error:

an error happened: could not determine width of source video, aborting execution 

Can someone enlighten me on this? Thank you.

**Comment by szhansen** [comment]
@jwanhussin how about the frame rate of flv video ?
i use: ffmpeg -f mjpeg  -r 25 -i "http://192.168.8.1:8090/?action=stream" -an -vcodec flv -r 25 -q 1 video.flv
but actually the video.flv frame rate is very low(fps = 1.8):
frame=  285 fps=1.8 q=1.0 Lsize=   28479kB time=00:00:11.36 bitrate=20534.8kbits/s speed=0.0724x
