### ISSUE TITLE
Volume level detection

### ISSUE THREAD

**Issue by wclr** [fluent-ffmpeg/node-fluent-ffmpeg#250]
To get volume level of the media file in command line I use:

```
ffmpeg -i audo.mp3 -af "volumedetect" -f null /dev/null
```

in the output I see something like this:

```
[Parsed_volumedetect_0 @ 0000000004087260] n_samples: 41316480
[Parsed_volumedetect_0 @ 0000000004087260] mean_volume: -22.5 dB
[Parsed_volumedetect_0 @ 0000000004087260] max_volume: -5.8 dB
[Parsed_volumedetect_0 @ 0000000004087260] histogram_5db: 3
[Parsed_volumedetect_0 @ 0000000004087260] histogram_6db: 892
[Parsed_volumedetect_0 @ 0000000004087260] histogram_7db: 8686
[Parsed_volumedetect_0 @ 0000000004087260] histogram_8db: 36098
```

How can I get volume level using fluent-ffmpeg?

I tried

``` javascript
new Ffmpeg({ source: file})
        .withAudioFilter('volumedetect')
        .addOption('-f', 'null /dev/null')
        .on('error', function(err) {
            console.log('An error occurred: ' + err.message);
        })
        .on('end', function(){      
            console.log('finished')

        })

```

But it doesn't work for me (end event doesn't occur) 

So could you advice what should I do to execute the command get the output to parse?

Maybe volume detection could be included in future releases.

**Comment by MaffooBristol** [comment]
I'm assuming the `.withAudioFilter()` option isn't available in this implementation of ffprobe? I know it should be in the actual ffprobe binary as the documentation mentions it.

**Comment by njoyard** [comment]
You're right, no options can be passed to ffprobe. I'm not sure what the effect of filters would be on ffprobe, though, even if the documentation mentions it.

**Comment by MaffooBristol** [comment]
Okay, it's no biggie :smiley: Well, the current value `metadata` that ffprobe returns could have volume data added to the object. At the moment I'm doing it in two goes and running the `ffmpeg.withAudiofilter` and `ffprobe` separately, but it'd be nice to have an optional kind of... "souped up" version of ffprobe data returned that gives loads of extra info about the audio.

This is my current method of parsing the audiofilter stdoutput and merging the two together, I'm sure it could be done better but you get the idea (apologies for coffeescript!)

```coffeescript
probe: (cb) =>
  ffmpeg.ffprobe e.file.pathName, (err, stat) =>
    if err
      cb 'Error converting file'
    else if (lo.where stat.streams, codec_type: 'audio').length < 1
      cb 'File has no audio'
    else
      ffmpeg(e.file.pathName).withAudioFilter 'volumedetect'
      .on 'end', (stdout, stderr) ->
        volumeDetect = {}
        y = stderr.split("\n").filter (x) ->
          return ~x.indexOf 'Parsed_volumedetect'
        .forEach (x) ->
          x = x.substr 2 + x.indexOf '] '
          x = x.split ': '
          volumeDetect[x[0]] = x[1]
        stat.volumeDetect = volumeDetect
        cb null, stat
      .on 'error', (err) ->
        cb err, stat
      .saveToFile '/dev/null/null.mp3'
```

**Comment by MaffooBristol** [comment]
Ps, neither `.saveToFile '/dev/null/null.mp3'` nor `.saveToFile '/dev/null'` work for me. The former says not a directory, the latter says invalid argument. Only seems to work if I write to an actual real file!

**Comment by felix-lunii** [comment]
First of all, sorry for the necrobump.
For those who find this message I had to add `.format(null)` to the code provided by njoyard in order to make it work on my mac with ffmpeg 4.2 (this response https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/250#issuecomment-42934633). It ended up looking like this:
``` 
new Ffmpeg({ source: file})
        .withAudioFilter('volumedetect')
        .addOption('-f', 'null')        
        .on('error', function(err) {
            console.log('An error occurred: ' + err.message);
        })
        .on('end', function(stdout, stderr){        
            console.log('finished', stderr)     
        })
         .format(null)
         .saveToFile('/dev/null');
```
