### ISSUE TITLE
Merging Audio and video

### ISSUE THREAD

**Issue by khurramraheel** [fluent-ffmpeg/node-fluent-ffmpeg#267]
I was about to merge an audio and video file, According to docs, there is a method name "mergedAdd" that is supposed to merge multiple media streams, But it did not work for me. Am I missing something? 

new FFmpeg({ source: '/media/myVideo.avi' })
    .mergeAdd('/media/myAudio.mp3')
    .on('error', function(err) {
        console.log('An error occurred: ' + err.message);
    })
    .on('end', function() {
        console.log('Final video created!');
    })

Thanks

**Comment by zanxiaoyu** [comment]
how to remove source video's audio track ?

**Comment by nitin-1926** [comment]
@zanxiaoyu Here is a sample code I used for removing audio from video using fluent-ffmpeg. Hope it helps.

`
const PATH_TO_VIDEO = "./sample.mp4";
const PATH_TO_ONLY_VIDEO = "./noAudio.mp4";
ffmpeg(PATH_TO_VIDEO)
        .output(PATH_TO_ONLY_VIDEO)
        .noAudio()
        .on('end', () => {
            console.log('Removed audio from video');
            .run();
        })
        .on('error', err => {
            console.log('Error while removing audio from video: ', err);
        })
        .run();
`

**Comment by handita** [comment]
how about replacing with the other audio?? I got no audio using this code

const ffmpeg = require("fluent-ffmpeg");

const inputVideo =
  "C:\\Users\\user\\AppData\\Roaming\\envidi\\Envidi\\videos\\86.mp4";
const inputAudio = "C:\\Users\\user\\Downloads\\Music\\aa.mp3";
const outputFile = "output2.mp4";

ffmpeg()
  .addInput(inputVideo)
  .addInput(inputAudio)
  .output(outputFile)
//   .videoFilters('vflip')
  .on('end', () => console.log('Finished merging video and audio'))
  .on('error', (err) => console.error('Error:', err))
  .run();
