### ISSUE TITLE
Merge is failing 

### ISSUE THREAD

**Issue by dolph1n** [fluent-ffmpeg/node-fluent-ffmpeg#302]
i'm using code from example:

```
var ffmpeg = require('./vendor/fluent-ffmpeg');

var firstFile = "part_001.mp4";
var secondFile = "part_002.mp4";
var thirdFile = "part_003.mp4";
var outPath = "out.mp4";

var proc = ffmpeg(firstFile)
    .input(secondFile)
    .input(thirdFile)
    //.input(fourthFile)
    //.input(...)
    .on('end', function() {
      console.log('files have been merged succesfully');
    })
    .on('error', function(err) {
      console.log('an error happened: ' + err.message);
    })
    .mergeToFile(outPath, "./tmp");
```

and get error:

> an error happened: ffmpeg exited with code 1: Error while opening encoder for ou
> tput stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or h
> eight

i added log for ffmpeg commands and get this:

> spawned ffmpeg with command: ffmpeg -i part_001.mp4 -i part_002.mp4 -i part_003.
> mp4 -y -filter_complex concat=n=3:v=1:a=1 out.mp4

fluent-ffmpeg version 2.0.0-rc1 (clone from git)

**Comment by ngomezleal** [comment]
Hi njoyard I need your help.
This is my code:
    var videoFile1 = path.join(__dirname, 'uploads', '1_empresaspolar.webm'),
       audioFile2 = path.join(__dirname, 'uploads', '2_empresaspolar.wav');
    var mergedFilevideo2 = path.join(__dirname, 'uploads', 'demo-merged.webm');
    var ffmpeg = require('fluent-ffmpeg');
    console.log(videoFile1);
    console.log(audioFile2);
    var proc = new ffmpeg({ source: videoFile1 })
        .mergeAdd(audioFile2)
        .mergeToFile(mergedFilevideo2);

But, I show the follow error:

C:\xampp\htdocs\MediaStreamRecorder\demos>node server
Stop-MAKING MERGE
C:\xampp\htdocs\MediaStreamRecorder\demos\uploads\1_empresaspolar.webm
C:\xampp\htdocs\MediaStreamRecorder\demos\uploads\2_empresaspolar.wav
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ffmpeg exited with code 1
    at ChildProcess.<anonymous> (C:\xampp\htdocs\MediaStreamRecorder\node_module
s\fluent-ffmpeg\lib\processor.js:735:20)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

----------------
Please helpme.
Regards, 

Nelson
Vzla

**Comment by njoyard** [comment]
See #424.
