### ISSUE TITLE
logger defined but seeing no output

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#335]
I have `new FfmpegCommand({logger: console.log})` here but am not seeing any output.

Any idea why?

**Comment by odigity** [comment]
I just ran into the same issue.  Logger was mentioned in the README, so I implemented it, then so no change.  :)

Perhaps time to remove it from the README?

**Comment by kus** [comment]
I must admit, I just got caught up on the `logger` option as well and landed here because I was wondering why it wasn't working.

```
const log = (...args) => console.log(...args);
ffmpeg({source: filePath, logger: {debug: log, info: log, warn: log, error: log}})
```

I now use this which satisfies my requirements:

```
.on('progress', function(progress) {
    console.log('Processing: ' + progress.percent + '% done @ ' + progress.currentFps + ' fps');
})
.on('end', function(err, stdout, stderr) {
    console.log('Finished processing', err, stdout, stderr);
})
```

**Comment by paulo-digital** [comment]
Some thing here, the Log is poorly documented.
