### ISSUE TITLE
ffmpeg exited with code 1: pipe:1: Invalid argument

### ISSUE THREAD

**Issue by mbuff24** [fluent-ffmpeg/node-fluent-ffmpeg#337]
Hey all,

I'm running into an issue where I want an output stream but 'pipe:1' is an invalid argument. I noticed both pipe:0 and pipe:1 in the command, which doesn't seem right.. It also works fine when I use saveToFile()

```
function makeGif(buffer, cb) {

    var outStream = fs.createWriteStream('test.gif');

    ffmpeg(new BufferStream(buffer))
        .withSize('640x360')
        .addOptions([
            '-vf scale=640:-1',
            '-t 00:00:15',
            '-r 10'
        ])
        .on('start', function(cmd) {
            console.log('Started ' + cmd);
        })
        .on('error', function(err) {
            console.log('An error occurred: ' + err.message);
            cb(err);
        })
        .on('end', function() {
            console.log('Finished encoding');
            cb();
        })
        .writeToStream(outStream, { end: true });
}
```

Produces this command:

```
ffmpeg -i pipe:0 -filter:v scale=w=640:h=360 -vf scale=640:-1 -t 00:00:15 -r 10 pipe:1
```

With this error:

```
ffmpeg exited with code 1: pipe:1: Invalid argument
```

I'm also using this version:

```
"fluent-ffmpeg": "^2.0.0-rc3",
```

Any idea where I'm going wrong?

Thanks!

**Comment by alekbarszczewski** [comment]
:+1: Thank you!

**Comment by henrych4** [comment]
Similar situation occurs to me when trying to crop image from video. I tried adding `.format('jpg')` / `.format('png')` but they all failed with error message: "Output format png is not available".

At the end, adding `.addOutputOption([..., '-f image2'])` works for me.

**Comment by intuity-hans** [comment]
> At the end, adding `.addOutputOption([..., '-f image2'])` works for me.

what exactly do you mean with those three dots? obviously they produce an error when using them, but I am not sure what else to insert

**Comment by henrych4** [comment]
Sorry for the ambiguity. Those dots refer to other output options like scale, quality.

**Comment by intuity-hans** [comment]
> Sorry for the ambiguity. Those dots refer to other output options like scale, quality.

thanks for the clarification! 👍
