### ISSUE TITLE
Get lists of input devices

### ISSUE THREAD

**Issue by citosid** [fluent-ffmpeg/node-fluent-ffmpeg#355]
Is there any way to get the list of the devices? I've been reading the code but I cannot find any way to do it.

Thanks for this awesome library! It works wonderful! 

Edit: Could this be related? https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/351

**Comment by njoyard** [comment]
I don't think this is possible with ffmpeg. You'll have to look for other libraries to do that, or inspect /sys or /proc if you target unixes.
