### ISSUE TITLE
RTMP input streams with subdirectories

### ISSUE THREAD

**Issue by turbidwater** [fluent-ffmpeg/node-fluent-ffmpeg#357]
I am having issues with using RTMP streams with subdirectories in the path through Fluent FFMPEG. To accommodate the subdirectories, I have to manually specify the app and playpath params for my input. For example, if the following works from the CLI.
ffmpeg -i "rtmp://myfmsserver.com/myApp/mp4:channel0/stream0/streams/liveMP4_1.mp4 live=1 app=myApp playpath=mp4:channel0/stream0/streams/liveMP4_1.mp4" -vcodec copy -b:v 1000 mytest.mp4

If I use the same input value in fluent FFMPEG, I am getting an error: 
Exited with code 1, "rtmp://myfmsserver.com/myApp/mp4:channel0/stream0/streams/liveMP4_1.mp4 live=1 app=myApp playpath=mp4:channel0/stream0/streams/liveMP4_1.mp4" Invalid argument

If there is a different way to hit an RTMP stream with a subdirectory in the URL, I'd love to know. I've tried using the rtmp_app and rtmp_playpath arguments but have been unable to get them to be acknowledge via CLI or fluent. Thanks!

**Comment by njoyard** [comment]
I didn't know that syntax was supposed to work. Spaces are not valid in URLs.

Could you try the following:
* Replace spaces with %20 or +
* Use a classic query string (url?key=value&key=value...)

If nothing works, and if this is a valid way to pass parameters to a RTMP streaming server, then I guess we will have to implement something that works...

**Comment by turbidwater** [comment]
Actually fluent-ffmpeg has been working with the simple live=1 param on the end, like so.
"rtmp://myfmsserver.com/myApp/mp4:liveMP4_1.mp4 live=1"

I will take a look at URL encoding the URL string and see if that makes a difference.

By the way, there are arguments such as -rtmp_app and -rtmp_playpath that go outside the input path, but I have been unable to get those to work in CLI or fluent. Those are supposedly supported according to this: http://www.ffmpeg.org/ffmpeg-protocols.html#rtmp. The above sample was the only way I could get ffmpeg to handle RTMP subdirectories.

Thanks!

**Comment by njoyard** [comment]
Have you tried passing a quoted input ? Something like ffmpeg("\"rtmp://... live=1 app=...\"") ? That may work.

**Comment by turbidwater** [comment]
I have not tried that, but will give it a go. Thanks!

**Comment by njoyard** [comment]
Closing for housekeeping, feel free to reopen if you still have problems.
