### ISSUE TITLE
input/output error - Windows Only

### ISSUE THREAD

**Issue by citosid** [fluent-ffmpeg/node-fluent-ffmpeg#358]
I'm experiencing a problem. 

When trying to execute this command:

ffmpeg -f dshow -i  video="vMix Video":audio="vMix Audio" -y -b:a 128k -ac 2 -b:v 300k -vcodec libx264 -r 24 -preset superfast -hls_time 10 -hls_list_size 0 g:\videos\testing.m3u8

It throws an error: input/output error

However, when trying to execute it directly from command line it works...

**Comment by citosid** [comment]
Error fixed... there is needed remove the "

**Comment by njoyard** [comment]
Yup, the double quotes are there to tell the shell (or cmd.exe) that the space is part of the arguments. This is not needed with fluent-ffmpeg as you already pass arguments separately.
