### ISSUE TITLE
Using codec -copy and no extra options changes the size of the stream

### ISSUE THREAD

**Issue by ecyshor** [fluent-ffmpeg/node-fluent-ffmpeg#362]
Using this command video segments are streamed to my nodejs server.
``ffmpeg -rtbufsize 1500M -f dshow -i video="UScreenCapture" -flags +global_header -vf scale=800x600  -vcodec libvpx -g 1 -deadline realtime -profile:v 0 -cpu-used 0 -vb 1000k -qmin 10 -
qmax 42  -threads 8 -bufsize 18000k -slices 4 -map 0 -f stream_segment -segment_
time 2 -segment_time_delta 0.05 -segment_format webm -dash 1 http://192.168.2.10
1:3000/
``
On the server side wanted to reduce the size of the segments by reducing quality using ffmpeg, but unfortunately somehow the segments are altered in a bad way.
After some digging I found that using the following command:
```
ffmpeg(pipingStream,{priority:20})
  .outputOptions(['-map 0', '-codec copy', '-c:a copy'])
  .format('webm')
  .on('start', function (cmd) {
    log('Spawned Ffmpeg with command ' + cmd);
 })
.pipe().on('data',function(data){
self.bufferRepresentations.downgraded.buffer.append(data);
}); 
```
produces an output with a length larger with 10 or 7

This is particular interesting because for the first segment received, the output's length is bigger with 10 units every time I tested, while for every sequential segment the length increases with 7 units.
(For example the first segment's original length is 571203 and the ffmpeg's command output length is 571213, respectively 525892/525899 for the second segment and so on).

**Comment by njoyard** [comment]
That's most likely due to the fact that you're converting webm segments to full webm videos. There may be some kind of header added. Anyway, you're better off asking for support on ffmpeg related channels, because this does not seem related to fluent-ffmpeg itself.

**Comment by AmitDJagtap** [comment]
This is happening with MP4 as well.
