### ISSUE TITLE
Unhandled exception if no logger is provided

### ISSUE THREAD

**Issue by washeck** [fluent-ffmpeg/node-fluent-ffmpeg#363]
fluent-ffmpeg 2.0.0-rc3 raises unhandled expection if no logger is provided and it tries to log warn message:

/src/node_modules/fluent-ffmpeg/lib/processor.js:631
this.options.logger.warn('No running ffmpeg process, cannot send signal'
^
TypeError: Cannot call method 'warn' of undefined
at FfmpegCommand.proto.kill (/src/node_modules/fluent-ffmpeg/lib/processor.js:631:27)
at null._onTimeout (/src/lib/index.js:94:33)
at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by njoyard** [comment]
Thanks for the report; this was fixed by pull request #347, and will be part of the 2.0.0 release (which I hope to get out sometime this week).
