### ISSUE TITLE
Stream boundaries

### ISSUE THREAD

**Issue by tunderdomb** [fluent-ffmpeg/node-fluent-ffmpeg#364]
I'm trying to stream frames using `pipe()`.
I know ffmpeg can extract frames to files (`-f image2 image-%3d.jpeg`), but when using streams, the boundary of frames are not clear, an also if the frames are the data that are being streamed. 
I'm not sure if the way I'm doing this is correct: 

```js
command = ffmpeg()
    .input(videoSrc)
    .format("image2pipe")
    .pipe(through2(function (chunk, enc, callback) {
      // chunk is a Buffer, but  not sure about the contents
      callback(null, chunk)
    }, function(  ){
      // ...
    }))
```

So I'm not sure how to achieve this, but knowing what is the data that is being stream would help.
If image2pipe streams image data, then the next question is where the file boundaries are, and how to calibrate the output stream to handle that.

Also, as a sidenote, if I can have a better understanding of this feature (stream outputs), I'd love to contribute as I see this a useful feature that isn't easy to get at first glance. 
Thanks in advance.

**Comment by njoyard** [comment]
Basically, when outputting to a stream using `.pipe()`, you get the same data that would be written to a single output file, except it never ends up being written to the filesystem. The way it is split in chunks depends mostly on the OS data buffering configuration (and possibly also both on how ffmpeg writes its output and on nodejs streams implementation), so chunk boundaries will most likely not be related to the actual data contents (ie. video frames or "valid" chunks of video).

Additionnaly, I cannot find a lot of information about the `image2pipe` format but what I found is that this is only an _input_ format, which expects to find data from multiple image files concatenated in the input stream. Maybe it also works as an output format (again, there's not much info about it and I couldn't find any example of its usage as an output format), but in that case, what's most likely is that it outputs all images concatenated in the output stream. But the way that stream is split in chunks by the OS cannot be controlled, and you'll end up having to split it into images yourself (which implies being able to decode image data to find out where each one starts and ends in the stream).

Anyway, that's not a very good use case for node streams and pipes. Streams are useful when you want to pass data around without having it written to disk and without having to handle 

If you want to create and manipulate individual frames, you're better off outputting them to actual files (see #360)

**Comment by njoyard** [comment]
Basically, when outputting to a stream using `.pipe()`, you get the same data that would be written to a single output file, except it never ends up being written to the filesystem. The way it is split in chunks depends mostly on the OS data buffering configuration (and possibly also both on how ffmpeg writes its output and on nodejs streams implementation), so chunk boundaries will most likely not be related to the actual data contents (ie. video frames or "valid" chunks of video).

Additionnaly, I cannot find a lot of information about the `image2pipe` format but what I found is that this is only an _input_ format, which expects to find data from multiple image files concatenated in the input stream. Maybe it also works as an output format (again, there's not much info about it and I couldn't find any example of its usage as an output format), but in that case, what's most likely is that it outputs all images concatenated in the output stream. But the way that stream is split in chunks by the OS cannot be controlled, and you'll end up having to split it into images yourself (which implies being able to decode image data to find out where each one starts and ends in the stream).

Anyway, that's not a very good use case for node streams and pipes. Streams are useful when you want to pass data around without having it written to disk and without having to handle a huge buffer, but you also should not care about where the data is split.

If you want to create and manipulate individual frames, you're better off outputting them to actual files (see #360). You can put them in `/tmp`, as most distributions mount a ramdisk there anyway. But in the end that depends on what you intend to do with those frames.

**Comment by tunderdomb** [comment]
I did further research too, and found a use case similar to mine on [imagemagic's boards](http://www.imagemagick.org/discourse-server/viewtopic.php?t=18320).

The basic idea is to avoid io. My use case dosn't allow me to use ramdisks. File operations is always slower than anything else, and I'd have to read the frames back again because I need them to display immediately. It's a video player, basically., using node-webkit and ffmpeg.
I'd like to process the video frame by frame in memory so it's as fast as it can get.

I understand the specifics about streams you mentioned. But that's the problem I'm facing sadly.
For individual frame processing, I should be able to tell where frames start and end. 
Then I could buffer chunks and treat them as raw image data. 

When *not* using streams/pipe, ffmpeg can output individual frames into files no problem, so I guess this is treated differently internally.

**Comment by njoyard** [comment]
In this use case you should just not use ffmpeg. ffmpeg is a CLI tool that basically gives you access to libavutils, libavcodec and libavformat from command line to process files. You should look into using libav* directly if you want to decode video in realtime for playback purposes.

**Comment by gre** [comment]
I'm having the same issue with image2pipe, it never get written to the disk. I'm not sure where the issue is, it seems that ffmpeg is perfectly able to do that, I've tried in using CLI (`cat *.jpg | ffmpeg ... > out.avi`)

Is there a way to log what does the fluent-ffmpeg generate as ffmpeg command? otherwise I might just go without fluent-ffmpeg but directly calling ffmpeg from node..

**Comment by njoyard** [comment]
I'm not sure you're having the same issue, you seem to want to do the reverse thing (turn individual frames into video). In this case can you please open a separate issue?

As for your question about the command line fluent-ffmpeg generates, you can use the 'start' event on a command. The handler for that event receives the full command fluent-ffmpeg will spawn.

**Comment by piercus** [comment]
I feel there are 2 solution for this : 

1) Switch to https://github.com/Streampunk/beamcoder
2) Check the size of the chunk and write a file wihen chunk size is different than 1024*64

NB: Why 1024*64, only thing i can tell is it works for me :-)

```js
const {Writable} = require('stream')
class WriteStream extends Writable {
	constructor(opts) {
		super(opts);
		this.currentChunks = [];
	}
	_write(chunk, encoding, cb) {
		this.currentChunks.push(chunk);
		// Here is a trick to split png between different values
		// image2pipe returns a list of concatenated images, 
		if(Buffer.byteLength(chunk, encoding) !== 1024*64){
			const date = new Date(this.startDate.getTime() + (this.nFrame / this.fps * 1000));
			this.nFrame++;
			const concatChunk = Buffer.concat(this.currentChunks)
			this.currentChunks = [];
			// here we have a concatChunk that is a png image
		}
	}
}
```

**Comment by samidalati** [comment]
Another way would be to look for JPEG file magic number FFD8FF. this involves searching the buffer which is not cheap but this approach does not care about the image size/channels/etc as long as it is a jpeg, you can also use magic number for png and other img types

here is a quick and dirty code snippet:
```
var ffmpeg = require('fluent-ffmpeg');
const { Transform } = require("stream")
 
class ExtractFrames extends Transform {
  constructor(delimiter) {
    super({ readableObjectMode: true })
    this.delimiter = Buffer.from(delimiter, "hex")
    this.buffer = Buffer.alloc(0)
  }
 
  _transform(data, enc, cb) {
    // Add new data to buffer
    this.buffer = Buffer.concat([this.buffer, data])
    while (true) {
      const start = this.buffer.indexOf(this.delimiter)
      if (start < 0) break // there's no frame data at all
      const end = this.buffer.indexOf(this.delimiter, start + this.delimiter.length)
      if (end < 0) break // we haven't got the whole frame yet
      this.push(this.buffer.slice(start, end)) // emit a frame
      this.buffer = this.buffer.slice(end) // remove frame data from buffer
      if (start > 0) console.error(`Discarded ${start} bytes of invalid data`)
    }
    cb()
  }
}

var command =  ffmpeg()
	.input('rtsp://10.10.10.190:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif')
	.outputOptions('-q:v 2')
	.outputOptions('-r 1')
        .outputOption(['-vcodec mjpeg'])
        .outputOption(['-f image2pipe'])
 
  .on('error', function(err) {
    console.log('An error occurred: ' + err.message);
  })
  .on('end', function() {
    console.log('Processing finished !');
  }).pipe(new ExtractFrames("FFD8FF"), { end: true });
```
