### ISSUE TITLE
Cannot run ffprobe on stream input

### ISSUE THREAD

**Issue by acidhax** [fluent-ffmpeg/node-fluent-ffmpeg#365]
Is it possible to pipe stream data into ffprobe? If so, where should I begin to look into this?
I have an http request feeding the _write's to a duplex stream, and giving ffprobe the readable duplex stream for input.

**Comment by njoyard** [comment]
I think it is possible but not implemented in current fluent-ffmpeg.
Keep in mind you won't be able to use the stream for anything else afterwards, because passing it to ffprobe will consume data from it.

**Comment by acidhax** [comment]
Fixed it in ffprobe.js.

Killed the statement that killed early if it's a stream and changed the spawn to this:

      // Spawn ffprobe
      var ffprobe = spawn(path, [
        '-show_streams',
        '-show_format',
        input.isStream ? 'pipe:0' : input.source
      ]);
      if (input.isStream) {
        input.source.pipe(ffprobe.stdin);
        input.source.resume();
      }
