### ISSUE TITLE
Can't rewrite my ffmpeg commands to nodejs

### ISSUE THREAD

**Issue by zajca** [fluent-ffmpeg/node-fluent-ffmpeg#368]
I'm trying to do some stuff using fluent-ffmpeg which I have working in command line just fine.
basically, I'm merging videos -> extracting audio -> mixing audio with some music -> merge it back
part when I'm stuck is after mixing audio I can't marge it back.
this is command for merge audio
```
ffmpeg -i merge.m4a -i overlay.aac -strict experimental -c:a aac -filter_complex amix=inputs=2:duration=first mergeOutput.m4a
```
and this I have in nodejs:
```
  ffmpeg('./merge.m4a')
  .input('./overlay.aac')
  .audioCodec('aac')
  .complexFilter('amix=inputs=2:duration=first')
  .saveToFile('./mergeOutput.m4a')
```
this is both working fine.
```
ffmpeg -i merge.mp4 -i mergeOutput.m4a -c:v copy -c:a copy -map 0:0 -map 1:0 -shortest final.mp4 -y
```
this merge in command line is also working.

so this shouldbe same as above: (but it's not working)
```
  ffmpeg('./merge.mp4')
  .input('./mergeOutput.m4a')
  .audioCodec('copy')
  .videoCodec('copy')
  .outputOption('-map 0:0')
  .outputOption('-map 1:0')
  .on 'error', (err, stdout, stderr)->
    console.log(err)
    console.log("ffmpeg stdout:\n" + stdout)
    console.log("ffmpeg stderr:\n" + stderr)
  .mergeToFile('./final.mp4')
```
I misunderstand how to use fluent-ffmpeg or is something else wrong.
I get this err:
```
 ffmpeg exited with code 1: Cannot find a matching stream for unlabeled input pad 2 on filter Parsed_concat_0
```
full output: http://pastebin.com/hqeeek6f

**Comment by njoyard** [comment]
I think you should not specify `-map` options when using mergeToFile. Can you please try without them ?

**Comment by zajca** [comment]
When I remove map I get exact same error.

**Comment by njoyard** [comment]
Sorry for the delay ; could you please show me the full command line generated by fluent-ffmpeg ? Just add a handler for the 'start' event, it will receive the command line as argument.

**Comment by zajca** [comment]
Sorry, I give up on that. I can't figure out how to make it work and it wasn't only command. So I just use shell.js without fluent.
