### ISSUE TITLE
Using a native FFMPEG command

### ISSUE THREAD

**Issue by samelie** [fluent-ffmpeg/node-fluent-ffmpeg#373]
Hi,

I have an existing program that generates a command line ffmpeg command. Is there a way to feed this existing command into fluent-ffmpeg?

**Comment by njoyard** [comment]
No there's not. The purpose of fluent-ffmpeg is also partly to generate command lines for you.
If you want to use already-generated command lines, you'll have to spawn them yourself using node's `child_process` module.
