### ISSUE TITLE
More detailed progress when seekInput is applied

### ISSUE THREAD

**Issue by ageblade** [fluent-ffmpeg/node-fluent-ffmpeg#375]
Hi,

I try to implement a play-pause mechanism by saving the timemark from the progress event and seeking into it when resuming the video.

However from the second run the progress is not counted from the previous timemark but it is reset to zero and all measurements are re-counted.

Is there a way to get the true timemark of the current frame ?

Thanks,
Idan

**Comment by njoyard** [comment]
No, you'll have to compute it yourself eg. `currentSeek + frameNumber*fps`. Take care though, the progress event as reported by ffmpeg is not accurate.

**Comment by ageblade** [comment]
Hi again,
I noticed in your examples the use of SIGSTOP and SIGCONT in order to pause the execution of FFMPEG, however it is not working on my windows environment (maybe its supported only on linux?), is there a proper way to pause the execution and resume it ?

**Comment by njoyard** [comment]
Signals only work on Unixes, indeed.
I don't know if you can / how to pause and resume processes on Windows, sorry.
