### ISSUE TITLE
Unable to merge multiple videos by passing file names dynamically.

### ISSUE THREAD

**Issue by shyamshyre** [fluent-ffmpeg/node-fluent-ffmpeg#379]
Hi 

I am trying to read all the files in the directory and trying to merge into single file which i couldnt able to do.

var finalresult="E:/ETV/videos/finalresult.mp4"
outputresult : It consists of all the files read in the directory.

/*Javascript*/
MergeVideo(outputresult);
function MergeVideo(outputresult){
console.log("in merge video");
var videostring = "";

for(i=1;i<5;i++)
    {
videostring = videostring+".input("+"'"+outputresult[i]+"'"+")";
}
console.log("Video String"+videostring);
    var proc = ffmpeg()+videostring
    .on('end', function() {
      console.log('files have  succesfully Merged');
        })
    .on('error', function(err) {
      console.log('an error happened: ' + err.message);
    })
    .mergeToFile(finalresult);
}

Its resulting me below error, Unable to proceed ahead Please help.

TypeError: Object .input('ETV 22-02-2015 1-02-25 AM.mp4').input('ETV 22-02-2015
9-33-15 PM.mp4').input('ETV 22-02-2015 9-32-46 AM.mp4').input('ETV 22-02-2015 8-
32-44 AM.mp4') has no method 'on'
    at MergeVideo (D:\Development\Node\node-fluent-ffmpeg-master\node-fluent-ffm
peg-master\examples\demo.js:140:6)

**Comment by njoyard** [comment]
```js
var proc = ffmpeg()+videostring
```

This code does not make sense. You cannot call methods on an object by concatenating a string. My best advice is to find online resources or books about Javascript and learn a bit more, first :)
