### ISSUE TITLE
Cannot output MP4 as stream

### ISSUE THREAD

**Issue by sirsavary** [fluent-ffmpeg/node-fluent-ffmpeg#380]
I am attempting to build a music streaming application that supports many different browsers, including mobile. To support as many devices as possible I am streaming the audio as an MP4 video. When testing with a sample MP4 video, everything works as intended. When I try to convert an audio feed (obtained from an IceCast instance in MP3 form) to an MP4 stream (and then pipe it to clients) ffmpeg seems to choke. There is no error, everything just stops after transcoding what I believe to be the MP4 header.

The code:
```coffeescript
mp3Stream = Needle.get('http://grenaderadio.com:8000/gradio-192-mp3')

cmd = FFF()
      .input(mp3Stream)
      .format('mp4')
      .videoCodec('libx264')
      .audioBitrate('192k')
      .audioChannels(2)
      .outputOptions('-movflags', 'frag_keyframe')
      .on('start', (commandLine) -> console.log("Spawned ffmpeg with command: #{commandLine}"))
      .on('error', (err) -> console.error("Error occurred during MP4 transcoding: " + err))
      .on('end', -> console.error("MP4 Stream died"))
outStream = cmd.pipe()

outStream.pipe(res)
outStream.on('data', (data) -> console.log("MP4 Data:", data))
```

This is inside an Express route. Right now an mp3 stream and an output stream are being created for each client. This is simply for testing purposes.

The output:
```
Spawned ffmpeg with command: ffmpeg -i pipe:0 -b:a 192k -ac 2 -vcodec libx264 -f mp4 -movflags frag_keyframe pipe:1
MP4 Data: <Buffer 00 00 00 1c 66 74 79 70 69 73 6f 6d 00 00 02 00 69 73 6f 6d 69 73 6f 32 6d 70 34 31>
```

No other data is transcoded, even though the mp3Stream is continuously downloading. All help is appreciated.

**Comment by sirsavary** [comment]
It's worth mentioning that I previously had this working with MP3 being converted to OGG, but browser support was not optimal. Using the commands by hand on both Windows 8.1 (my development machine) and Debian 7 (production server) both produce the expected output (an mp4 from an mp3).

**Comment by njoyard** [comment]
Are the 'error' or 'end' handlers called ? What is the output from ffmpeg (stdout and stderr are passed as arguments to both those handlers) ?

I also see that you're using pipes at both ends, this is really not a good idea. Using 2 pipes between 2 processes is prone to deadlocks. That's not a ffmpeg/fluent-ffmpeg/node issue, it's just how unix pipes work.

**Comment by sirsavary** [comment]
The error and end handlers are never called, it just locks up. I've tried the command it runs manually (without pipes) and things work just fine.

I'm aware that using a pipe at each end isn't the best solution, but the situation I'm in requires it. My client wants to re-broadcast an IceCast stream to every device possible.

**Comment by njoyard** [comment]
Then you most likely have a pipe deadlock.

To clarify: using a pipe at each end isn't just "not the best solution", it's not a viable solution at all. it *will* deadlock eventually. You'll have to use temporary files at one end.

**Comment by njoyard** [comment]
Oh and there is an other solution with pipes at both ends: using 2 nodejs apps (one to feed ffmpeg, one to read its output). This is not prone to deadlocks, but you'll most likely have to use named pipes (mkfifo) open in non-blocking mode. And it's a bit harder to code.

The idea would be to create a small node app that receives the input URL and the output file name as parameters, and that spawns the ffmpeg command and writes its output to the file name passed. Then, in your Express route, create a named fifo, then launch the secondary node app, passing it the output fifo as output filename, and pipe a stream reading from the fifo into Express response.

**Comment by darkyen** [comment]
So basically there is no way to transcode a video/audio file which you are downloading on the fly, in realtime :-/

**Comment by sirsavary** [comment]
So as it turns out this problem is caused by ffmpeg. I got around it by setting up HLS for mobile clients only. Realtime transcoding of a stream works fine, not exactly sure how it would deadlock. The stream has been running for about 3 weeks now without issue.

**Comment by njoyard** [comment]
@darkyen yes there is, but not with a single process communicating with ffmpeg. See my previous comment.

**Comment by mtrabelsi** [comment]
This bit old, but I'd like to add that this could be also an issue of **bottelneck** pipes - this happens when one of your stream flow is slower than the other, so the fast stream will kindof blocked ) then you should  take care of this with the **drain** [event](https://nodejs.org/api/stream.html#stream_event_drain)
[helpful ](http://stackoverflow.com/questions/18932488/how-to-use-drain-event-of-stream-writable-in-node-js)
