### ISSUE TITLE
custom ffprobe options

### ISSUE THREAD

**Issue by oohnoitz** [fluent-ffmpeg/node-fluent-ffmpeg#381]
Could we have `outputOptions(...)` extended to work with `ffprobe` somehow or have something similar for `ffprobe`? There are some additional options I wanted to pass so that I can retrieve some extra data from the streams with the command. Specifically the `-show_data_hash algorithm` option.

**Comment by njoyard** [comment]
That would be feasible. If you want to submit a pull request... :)
