### ISSUE TITLE
Question about arguments order 

### ISSUE THREAD

**Issue by h2non** [fluent-ffmpeg/node-fluent-ffmpeg#382]
I'm concerned about how fuent-ffmpeg is passing the arguments to `ffmpeg` binary.
For some specific ffmpeg flags you must define it before an input flag.

For example, I'm want to define something like:
```bash
ffmpeg -y -i "test.mp4" -itsoffset 00:00:05.0 -i "audio.mp3" -vcodec copy -acodec copy -map 0:0 -map 1:0 -r 25 -f avi "video.mp4"
```

But I can't use the `-itoffset` flag and I'm getting the following error:
```js
Option itsoffset (set the input ts offset) cannot be applied to output file video.mp4 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
```

I'm just calling to `inputOptions()` before the `input()` call, by I guess it's not suported to define input-specific flags for additional inputs

**Comment by njoyard** [comment]
It is indeed supported. Like all input-related methods `inputOptions` applies to the last input you added. Just call it right after adding "audio.mp3".
