### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by scaryguy** [fluent-ffmpeg/node-fluent-ffmpeg#384]
Hi,

How do I test a custom module which is simply running a `node-fluent-ffmpeg` command with Mocha&Chai?

```javascript
// segment_splicer.js
var config = require('./../config');
var utilities = require('./../utilities');
var ffmpeg = require('fluent-ffmpeg');

module.exports = {
	splice: function(raw_ad_time, crop) {
		if (!raw_ad_time || !crop) throw new Error("!!!!!!!!!! Missing argument");
		console.log("@@@@@ LAST SEGMENT IS BEING SPLITTED.");
		var segment_time = utilities.ten_seconds(raw_ad_time);
		var last_segment_path = config.akamai_user_base + 'segment' + (segment_time + 1) + "_" + config.default_bitrate + "_av-p.ts?sd=10&rebase=on";
		var command = ffmpeg(last_segment_path)
			.on('start', function(commandLine) {
				console.log('@@@@@ COMMAND: ' + commandLine);
			})
			.seekInput('0.000')
			.outputOptions(['-c copy', '-map_metadata 0:s'])
			.duration(crop)
			.on('error', function(err, stdout, stderr) {
				throw new Error('@@@@@ VIDEO COULD NOT BE PROCESSED: ' + err.message);
				console.log('@@@@@ VIDEO COULD NOT BE PROCESSED: ' + err.message);
			})
			.output('public/' + 'segment' + (segment_time + 1) + "_" + config.default_bitrate + "_av-p.ts").run();
	}
}
```

Here is what I tried:

```javascript
// test/segment_splicer.js
var expect = require('chai').expect;
var segment_splicer = require('../lib/segment_splicer');

describe('Segment Splicer', function() {
	it('should work', function(done) {
		expect(segment_splicer.splice(1111111, 20)).to.throw(Error);
		done();
	});
});
```

I get this:

>1) Segment Splicer should work: AssertionError: expected undefined to be a function

Thank you!

**Comment by njoyard** [comment]
`expect(x).to.throw(y)` expects x to be a function but you're passing `segment_splicer.splice(1111111, 20)` which actually calls your `splice()` method at the time where tests are defined, which is not what you want. Use `expect(function() { segment_splicer.splice(1111111, 20); })` instead.

**Comment by scaryguy** [comment]
Hey @njoyard , thanks for answer. But it didn't work neither :(

I updated code as you said:

```javascript
var expect = require('chai').expect;
var segment_splicer = require('../lib/segment_splicer');

describe('Segment Splicer', function() {
	this.timeout(5000);
	it('should work', function(done) {
		expect(function() {
			segment_splicer.splice(1111111, 20);
		}).to.throw(Error);
		done();
	});
});
```

But my `splice` method does not return anything so I get this:

>1) Segment Splicer should work:
>     AssertionError: expected [Function] to throw Error
>      at Context.<anonymous> (/Users/scaryguy/node/g2/test/segment_splicer.js:9:14)


But it is supposed to give an error like:

>[Error: ffmpeg exited with code 1: http://blalalalal: Invalid data found when processing input

`on('error')` is not recognized by mocha. I think it's because fluent-ffmpeg uses child_process. But I don't know how to handle it. How do you test your code?

**Comment by njoyard** [comment]
Oh, that's because the error is not thrown by slice() but by an event handler defined inside.
Use a variable to check that the error handler was called instead.

On a side note *do not throw inside event handlers*, that's very bad practice.

**Comment by scaryguy** [comment]
> Use a variable to check that the error handler was called instead.

I'm not sure if I understood this well :\ Could you give me some code tips?

**Comment by njoyard** [comment]
Try something like this (assuming mocha handles async tests with a 'done' argument to the test definition):

```js
it('should call error handler', function(done) {
  var called = 'none';
  ffmpeg(...)
  .on('error', function() {
    called = 'error';
    finish();
  })
  .on('end', function() {
    called = 'end';
    finish();
  });

  function finish() {
    expect(called).toBe('error');
    done();
  }
});
```
