### ISSUE TITLE
HLS Adaptive streaming 

### ISSUE THREAD

**Issue by fonzy2013** [fluent-ffmpeg/node-fluent-ffmpeg#385]
I have been using the following script to encode multibitrate HLS.
Does anyone know if it is possible to perform the same in node-fluent-ffmpeg?

#!/bin/bash
VIDSOURCE="$1"
RESOLUTION1="960x540"
RESOLUTION2="640x360"
RESOLUTION3="480x270"
BITRATE1="800000"
BITRATE2="600000"
BITRATE3="400000"

echo '#EXTM3U' > test.m3u8
echo '#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=500000' >> test.m3u8
echo 'stream_low.m3u8' >> test.m3u8
echo '#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=700000' >> test.m3u8
echo 'stream_med.m3u8' >> test.m3u8
echo '#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=900000' >> test.m3u8
echo 'stream_hi.m3u8' >> test.m3u8

AUDIO_OPTS="-c:a aac -strict -2 -b:a 160000 -ac 2"
VIDEO_OPTS1="-s $RESOLUTION1 -c:v libx264 -b:v $BITRATE1 -vprofile baseline -preset medium -x264opts level=41"
VIDEO_OPTS2="-s $RESOLUTION2 -c:v libx264 -b:v $BITRATE2 -vprofile baseline -preset medium -x264opts level=41"
VIDEO_OPTS3="-s $RESOLUTION3 -c:v libx264 -b:v $BITRATE3 -vprofile baseline -preset medium -x264opts level=41"

OUTPUT_HLS="-hls_time 10 -hls_list_size 10 -hls_wrap 30 -start_number 1"

ffmpeg -re -i "$VIDSOURCE" -y -threads 4 \
       $AUDIO_OPTS $VIDEO_OPTS1 $OUTPUT_HLS stream_hi.m3u8 \
       $AUDIO_OPTS $VIDEO_OPTS2 $OUTPUT_HLS stream_med.m3u8 \
       $AUDIO_OPTS $VIDEO_OPTS3 $OUTPUT_HLS stream_low.m3u8

**Comment by fonzy2013** [comment]
Anyone?

**Comment by njoyard** [comment]
It should be possible. Please read the documentation, you will want to use multiple outputs and the `run` method.

**Comment by ebuildy** [comment]
Check the example:

https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/examples/livertmp2hls.js

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
