### ISSUE TITLE
takeScreenshot error: Cannot find ffprobe

### ISSUE THREAD

**Issue by danielmeng07** [fluent-ffmpeg/node-fluent-ffmpeg#386]
I'm new to node-fluent-ffmpeg, and I'm trying to take a photo of a mp4 file at, say 50%, into the video. The console is throwing me errors and I'm not sure what I should do here. 

Version in package.json: ^2.0.0-rc3

Code:
videostream.on('close',function() {
  console.log('Downloading complete...');
  new Ffmpeg({  source: 'video.mp4' }).takeScreenshots({
    count: 1,
    timemarks: ['50%'],
    size: '650x350',
    filename: 'photo.png'
  }, './test');
});

Error below:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find ffprobe
    at /home/vagrant/local/venvy-eva/node_modules/fluent-ffmpeg/lib/ffprobe.js:110:25
    at /home/vagrant/local/venvy-eva/node_modules/fluent-ffmpeg/lib/capabilities.js:194:9
    at /home/vagrant/local/venvy-eva/node_modules/fluent-ffmpeg/lib/capabilities.js:186:13
    at /home/vagrant/local/venvy-eva/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /home/vagrant/local/venvy-eva/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/vagrant/local/venvy-eva/node_modules/fluent-ffmpeg/lib/utils.js:227:9
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

**Comment by njoyard** [comment]
Please check your ffmpeg/ffprobe installation. fluent-ffmpeg needs ffprobe to read media duration and compute what timestamp is at 50%.

**Comment by rahpuser** [comment]
Is there a solution for this ?

I'm facing the same issue, it is already checked, `ffprobe` is in the path, but still I'm getting the error.

Is there some more configuration that I should do ?

**Comment by njoyard** [comment]
Are you sure the PATH is passed correctly to node ?
What does ffmpeg()._getFfprobePath(function(err, path) { ... }) result in ?

**Comment by rahpuser** [comment]
@njoyard the result is 

`err: null, path: ''`

Is this correct ?

**Comment by njoyard** [comment]
`path` should be the full path to ffprobe, so no, that's not correct. Most likely ffprobe is not in the PATH that your nodejs app is running with.

**Comment by rahpuser** [comment]
Does it should return another error if ffmpeg is not found in the path ? this is weird, I can see 

process.env.PATH variable containing the folder with ffmpeg and ffprobe as ffserver

**Comment by gibbok** [comment]
Similar issue here: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/691
