### ISSUE TITLE
ffmpeg macos audio/video output duration is wrong

### ISSUE THREAD

**Issue by ihorml** [fluent-ffmpeg/node-fluent-ffmpeg#387]
When I trying to do any operation an output file duration 2 times greater than. Like if my video.mp4 duration is 00:19 after conversion it to mp3 file the duration is 00:38. 

Simple code example:
```
new ffmpeg('storage/test.mp4')
  .save('storage/test.mp3');
```

The fix is add `-write_xing 0` option to command (if using command line). 

Example:
```
ffmpeg -i storage/test.mp4 -write_xing 0 storage/test.mp3
```

**Comment by njoyard** [comment]
Hi,
This is an ffmpeg issue, not a fluent-ffmpeg one.

**Comment by ihorml** [comment]
Hi, this is ffmpeg issue but to fix it you can just add `-write_xing 0` to output parameters.

**Comment by njoyard** [comment]
This is not really a fix, though. It just prevents ffmpeg from writing xing frame info, thus forcing players to recompute the duration. There should be a way to get the correct frame/timing information written.
