### ISSUE TITLE
update ffmpeg binary used for testing travis

### ISSUE THREAD

**Issue by jonathanong** [fluent-ffmpeg/node-fluent-ffmpeg#388]
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/tools/test-travis.sh#L14

last update seems to be july of last year:

http://ffmpeg.gusari.org/static/64bit/

modern builds can be found here:

http://johnvansickle.com/ffmpeg/

i would make a PR but i haven't figured out how to install it on travis' old linux servers

**Comment by vogonistic** [comment]
Is this related to why all the builds fail currently? The domain `ffmpeg.gusari.org` doesn't seem to resolve anymore.

**Comment by jonathanong** [comment]
yep. it's down a lot.

here's what i use to install ffmpeg now https://github.com/mgmtio/video-thumbnail-extractor/blob/master/.travis.yml#L9

**Comment by vogonistic** [comment]
Isn't that the same gusari url?

**Comment by njoyard** [comment]
I'll have a look at that ASAP. Thanks for pointing that out.

**Comment by jonathanong** [comment]
O CRAP hold on

**Comment by jonathanong** [comment]
here you go https://github.com/mgmtio/video-phash-service/blob/master/.travis.yml#L9

**Comment by vogonistic** [comment]
:+1:
