### ISSUE TITLE
ffmpeg tee scenario (one encoder, multiple outputs(muxers))

### ISSUE THREAD

**Issue by aegor** [fluent-ffmpeg/node-fluent-ffmpeg#390]
How to release ffmpeg tee scenario (one transcoder pipeline with multiple outputs(muxers)) with fluent?
Or any "dirty" workaround?
Reference: https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs

**Comment by njoyard** [comment]
No dirty workarounds needed, just see https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#specifying-multiple-outputs

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.

**Comment by Booom3** [comment]
If you'll read the linked page it shows that adding multiple outputs creates multiple encoders. What he (and I) want is the ability to use the tee pseudo-muxer to have one encoder outputting to several different locations.

**Comment by njoyard** [comment]
Just specify the "tee" format and pass the multiple output string as an output filename, then.

**Comment by penghouho** [comment]
@njoyard May I know how to specify the tee format like what you mentioned in node-fluent-ffmpeg? Using .outputOptions()? thanks
