### ISSUE TITLE
Screenshots are created but error is thrown immediately

### ISSUE THREAD

**Issue by bendulum** [fluent-ffmpeg/node-fluent-ffmpeg#391]
I'm having a strange problem with this library. Here is my code for taking screenshots:

```
var ffmpeg = require('fluent-ffmpeg');
var snap = ffmpeg(filePath);
snap.setFfmpegPath(ffmpegPath); // (*)
snap.setFfprobePath(ffprobePath); // (*)
snap
        .on('filenames', done)
        .on('error', error)
        .on('progress', progress)
        .screenshots({
            timemarks: ['1', '2', '3'], // (**)
            filename: outputName + '_%i',
            folder: outputDir
        });
```
( * ) Apparently i need these lines otherwise I get `getFfmpegPath is not a function`. Both point to the according executables which I freshly downloaded and installed.
( ** ) Tried various cases here, some throw errors. For example when using `%` values or using `timestamps` instead of `timemarks`.

__Problem__
When executing the code above the `error` callback fires: `error [ 'file_1.png', 'file_2.png', 'file_3.png' ]`
Then I get two `progress` callbacks: 
```
{ 
  frames: 1,
  currentFps: 0,
  currentKbps: 1.5,
  targetSize: 0,
  timemark: '00:00:00.04',
  percent: 0.0004928594927610383
},
{ 
  frames: 1,
  currentFps: 0,
  currentKbps: 898.6,
  targetSize: 5,
  timemark: '00:00:00.04',
  percent: 0.0004928594927610383 
}
```
Interestingly this successfully creates screenshots as defined by the config. I can open them and they look fine! However the `filenames` callback is never called.

__OS__ 
Windows 7 x64

__FFMPEG version output in command line__
ffmpeg version N-50911-g9efcfbe built on Mar 13 2013 21:26:48 with gcc 4.7.2 (GCC)

__FFPROBE version output in command line__
ffprobe version N-71455-gfbdaebb built with gcc 4.9.2 (GCC)

__fluent-ffmpeg output from npm ls__
├─┬ fluent-ffmpeg@2.0.0-rc3
│ └── async@0.9.0

**Comment by bendulum** [comment]
__Some more information__

Using `"fluent-ffmpeg": "2.0.0-rc1"` yields the same result, without invoking the error callback.

Config `timemarks: ['1%', '2%', '3%']` throws `if(timemark.indexOf(':') === -1 && timemark.indexOf('.') >= 0)`. Same for `timemarks: [30, 300, 900]` and `timestamps: [30, 300, 900]`

Config `timestamps: ['30', '300', '900']` does not throw this error.

Config `timestamps: ['30', '300', '900']` in combination with a file path that has no empty spaces extecutes the `progress` callback about 20 times, last output being:

```
{ 
frames: 1,
  currentFps: 0,
  currentKbps: 68375.4,
  targetSize: 334,
  timemark: '00:00:00.04',
  percent: 0.0007287301876480233 
}
``` 
Hope that helps, will try further.

**Comment by njoyard** [comment]
Hi,

I'm not sure I understand clearly what happened here. Could you please, using 2.0.0-rc3, register handlers for the 'filenames', 'error' and 'end' events and dump all arguments passed to the handlers ?

FYI, the 'progress' event is completely meaningless when taking screenshots. That's something I'll have to work on.

**Comment by bendulum** [comment]
Looks like I got it all wrong with the event names! I'm using rc3 now, and everything works fine. Feel free to close this!
