### ISSUE TITLE
gridfs as output stream

### ISSUE THREAD

**Issue by caglarcem** [fluent-ffmpeg/node-fluent-ffmpeg#393]
Hi there, thanks for the great package.

Can we use gridfs as output stream? I used to do it by writing to a temp location then piping into gridfs before. I suspect now it is possible (after upgrading to v2.0.1) to pipe directly to gridfs without temp file, but the following doesn't work for me.  Is it possible, if so how, what am I doing wrong?

"ffmpeg exited with code 1: pipe:1: Invalid argument"

    var writeStream = gridFs.createWriteStream({ filename: updatedSaveLocation,
                        metadata: { actualFileName: fileName } });

    new FFmpeg({source: sourcePath, timeout:0})
        .on('error', function(err) {
            console.log('An error occurred: ' + err.message);
        })
        .on('end', function() {
            console.log('Transcoded successfully!');
        })
    .pipe(writeStream);

**Comment by njoyard** [comment]
Hi,

What ffmpeg version are you using ? On which OS ?

**Comment by phaux** [comment]
You need to specify output format with `.outputFormat('format')`

**Comment by njoyard** [comment]
@caglarcem yes, @phaux is right. You always have to specify the output format when using a stream.

**Comment by caglarcem** [comment]
Thanks guys it worked!
