### ISSUE TITLE
stream mp4 with fluent-ffmpeg and express

### ISSUE THREAD

**Issue by rchris03** [fluent-ffmpeg/node-fluent-ffmpeg#394]
I'm trying to create video stream server and client with node fluent-ffmpeg, express and ejs. And a haven't solve this for a while. What I want to do is to play video beginning by certain time. The following codes make it with Safari browser on windows but with others it makes a loop of a few seconds or it says "video format not supported".

server code :
```javascript
app.get('/video', function(req, res) {
  res.set('Content-Type', 'video/mp4');
  //define file path,time to seek the beegining and set ffmpeg binary
  var pathToMovie = '../videos/test.mp4';
  var seektime = 100; 
  proc.setFfmpegPath(__dirname + "/ffmpeg/ffmpeg");


  //encoding the video source
  var proc = new ffmpeg({source: pathToMovie})
         .seekInput(seektime)
         .withVideoBitrate(1024)
         .withVideoCodec('libx264')
         .withAspect('16:9')
         .withFps(24)
         .withAudioBitrate('128k')
         .withAudioCodec('libfaac')
         .toFormat('mp4');

  //pipe 
         .pipe(res, {end: true});
});
```
client code(index.ejs) :

```html
<html>
  <head></head>

  <body>
    <video>
      <source src="video/" type='video/mp4' />
    </video>
  </body>

</html>
```
help please and thanks.

**Comment by njoyard** [comment]
You'll have to implement multiple formats if you want all browsers to be supported.
See [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) and [the canPlayType method there](https://developer.mozilla.org/fr/docs/Web/API/HTMLMediaElement#Methods)

**Comment by rchris03** [comment]
ok, thank you very much.
