### ISSUE TITLE
example using fluent-ffmpeg and express

### ISSUE THREAD

**Issue by edwardsmarkf** [fluent-ffmpeg/node-fluent-ffmpeg#396]
hello -

i am trying to create a simple io.js that will read an opus file, convert it to mp3, and pass it to a webpage using express.   here is what i have tried so far:

    var express = require('express');
    var ffmpeg = require('fluent-ffmpeg');
    var app = express();
    var fs = require('fs');

    app.get ('/ffmpegTest', function(req,res) {
          var stream = fs.createWriteStream('tester.mp3');
          ffmpeg('./tester.opus')
               .audioCodec('libmp3lame')
               .output(stream, {end:true})
                  // tested to make sure ffmpeg worked  .saveToFile('./testerTEST.mp3')
               .on('error', function(err) {
                    console.log('Processing error! ' + err);
                })  ;
     });

      var server = app.listen(3000, function() {
      var host = server.address().address;
      var port = server.address().port;
       console.log('Example app listening at http://%s:%s', host, port);
    });

i also tried this:

     var command = ffmpeg('./tester.opus')
           .audioCodec('libmp3lame')
           .on('error', function(err) {
                console.log('Processing error! ' + err);
           })  ;
        var ffstream = command.pipe();
        ffstream.on('data', function(chunk) {
            console.log('ffmpeg just wrote ' + chunk.length + ' bytes');
        });

both of these examples give me "ffmpeg exited with code 1" 

is there a simple example of how to do this?

**Comment by njoyard** [comment]
Ffmpeg most likely complains because you're outputting to a stream without specifying the output format. You can confirm this by looking at the 2nd and 3rd arguments of the 'error' handler.

Use the `.format()` method.

**Comment by njoyard** [comment]
Closing this because it has not had any activity for months. Feel free to reopen if you still have issues.
