### ISSUE TITLE
record.kill() results in unreadable mp4

### ISSUE THREAD

**Issue by windht** [fluent-ffmpeg/node-fluent-ffmpeg#398]
Firstly, I love this repo!

I am currently using this repo in a node webkit project and tried to apply a start record and stop record function. To be clearer, this is reading input from an rtmp stream where it doesn't have a "start" or "end" point.

    var record=ffmpeg('http://192.168.2.10/hdmi')
    .duration('1:00')
    .audioBitrate(128)
    .fps(25)
    .videoBitrate('4096k')
    .videoCodec('libx264')
    .size('1920x1080')
    .aspect('16:9')
    .format('mp4')
    .on('start',function(){
      console.log('started recording!')
    })
    .on('end', function() {console.log('saved');})
    .on('error', function(err) { console.log(err);})
    .save('C:/Users/Tony/output.mp4');

After using

    record.kill();

If I let the time passed one minute, it did the record and can be opened properly. But if I want to manually stop it in between, it did save a file on the hard disk, but the mp4 file is not readable (I tried vlc and other players).
I have also tried omit the duration setting, but everything is still the same.
Can someone help? Thanks in advance.

Update:
if I remove all the video settings and use .noVideo() together with format('mp3')(which records mp3 only), it works pretty cool, the mp3 file is readable after manual kill.

**Comment by windht** [comment]
Hi,
Good news is that I found a way to handle this.
I first directly record the stream into flv file (which works well with the manual kill),
then I start the transcode to mp4 after the "end" event of record. Anyway I love this repo~

**Comment by njoyard** [comment]
Yeah, you cannot expect a valid mp4 when killing the process (notably, the default mp4 format has "headers" at the end of the file). You have to use specific options.

**Comment by hugohil** [comment]
I face the same problem.
I'll try the flv to mp4 trick, but I'd love to know what options would allow me to just `.kill()` the command and have a valid file. I've tried `.kill('SIGSTOP')`, which doesn't throw an error (when the default `SIGKILL` does), but still results in an unreadable file.
@njoyard maybe ?

**Comment by njoyard** [comment]
That's really a ffmpeg issue actually. Find a way to do that using command-line ffmpeg and the kill command, and I'll help you do it with fluent-ffmpeg.

You should ask the ffmpeg community about how to ensure having a valid output file even when interrupted, or maybe you'll have to resort to finding a way to fix the file afterwards.

**Comment by hugohil** [comment]
Ok ! Thanks for your answer, I'll check this out and come back to you when I have further informations.

**Comment by chilipote** [comment]
Hi 👋 

I'm facing the same problem here. 
Using `ffmpeg` CLI, and  using `q` when screen recording works well, and don't corrupt the fil. But I didn't find a trick w/ this package yet. 

Would you have any idea ?

I didn't try the `.flv` trick tho.

**Comment by chilipote** [comment]
Oops, nvm, regarding this issue (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/673), you can do that `command.ffmpegProc.stdin.write('q');`

Thankks
