### ISSUE TITLE
audioCodec doesn't recognize 'aac' or 'libfdk-aac'

### ISSUE THREAD

**Issue by mayurtanna** [fluent-ffmpeg/node-fluent-ffmpeg#399]
Hi,

I want to convert mp3 to aac and stream it to s3. My code is as below. Now when I try to use audioCodec as 'aac' or 'libfdk-aac'. It throws the error. Note that ffmpeg is compiled with 'libfdk-aac' and working fine from command line.

Any inputs/fixes ?

                                                            var proc = new ffmpeg({source:uploadedFiles[0].fd})
						           .audioCodec('aac')
						           .audioChannels(1);

                                                                                 proc.on('error', function(err) { 
									      		console.log('An error occurred: ' + err.message);
  										  })
  										  .on('end', function() {
    											console.log('audio uploaded successfully!');
    											
               									 })
    									  .pipe(upload(opts));

**Comment by njoyard** [comment]
What is the error ?

**Comment by mayurtanna** [comment]
Hi,

The error it sends is as below.

An error occurred: ffmpeg exited with code 1: pipe:1: Invalid argument

Thanks,
Mayur

**Comment by njoyard** [comment]
You have to specify a format when outputting to a pipe (`.format('something')`). You could have seen the full error by inspecting the second and third arguments to the `error` event handler (they contain ffmpeg stdout/stderr).

The error you get on Linux also indicates that either your ffmpeg version does not support aac or you don't have the necessary libraries installed.

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
