### ISSUE TITLE
Stream mapping

### ISSUE THREAD

**Issue by Volox** [fluent-ffmpeg/node-fluent-ffmpeg#400]
Hi,
just a quick question, is possible to map streams? Like the following?
```
ffmpeg.exe -i "$1" -map 0:0 -map 0:2 -map 0:2 -map 0:1 -map 0:4 -c:v copy -c:a:0 ac3 -c:a:1 copy -c:a:2 copy -c:s copy "$2"
```

I want my script to detect the available streams and copy as-is the video, audio and subtitle streams.
For the audio stream i want to find if a specific pair language-codec is available (EG: `ac3 for eng`), if not i want to create one from the available audio streams (EG: `convert DTS to ac3`).

**Comment by njoyard** [comment]
Yes but there are no dedicated methods for that.
You'll have to use the `outputOptions` method.

```js
ffmpeg(input)
.outputOptions([
  '-map 0:0',
  '-map 0:2',
  // ...
]);
```

**Comment by Volox** [comment]
Ok, great!
There is a way to specify codecs and other setting stream specific?
Like
 `-c:v:0 copy -c:a:0 copy -c:a:1 ac3`

**Comment by njoyard** [comment]
Not currently. You'll have to use `.outputOptions()` as well.

**Comment by Volox** [comment]
Ok, thanks

**Comment by soundflix** [comment]
Is there still no dedicated method for-map?
