### ISSUE TITLE
How to transcode input stream to another stream by use fluent-ffmpeg?

### ISSUE THREAD

**Issue by vmespace** [fluent-ffmpeg/node-fluent-ffmpeg#405]
my code is below:

```
var fs = require('fs');
var url = "rtmp://192.168.235.36/live/livestream5 live=1";
//var url = "1.mp4";
var out = "rtmp://192.168.235.60/live/livestream5432";
//var out = "11.mp4";
var ffmpeg = require('fluent-ffmpeg');
var ffmpegPath = "";
var os = require('os');
if(os.platform() === 'win32'){
    ffmpegPath = 'F:\\Downloads\\ffmpeg-20140512-git-5460ab7-win32-shared\\bin\\ffmpeg.exe';
}else{
    ffmpegPath = '/usr/local/bin/ffmpeg';
}

var proc = new ffmpeg({ source: url, nolog: false});
proc.setFfmpegPath(ffmpegPath);
proc.addOptions([
        '-vcodec copy',
        '-acodec copy',
        '-f flv',
        '-y'
    ]);

proc.on('error', function(err, stdout, stderr){
    console.log("11111111111111 -------------video: " + err);
});

proc.writeToStream(out, function(return_code, error){
    console.log('11111111111' , return_code, "222222222", error);
});
```

now,it works when the out is "11.mp4", What I expect is that out is "rtmp://192.168.235.60/live/livestream5432", now error code is "11111111111111 -------------video: Error: ffmpeg exited with code 1"

ffmpeg version is :"2.6.3" fluent-ffmpeg is : "1.7.2"

**Comment by njoyard** [comment]
You have to specify an output format. "flv" is not a valid output format AFAIK.

**Comment by vmespace** [comment]
the real order of the below is : "ffmpeg -i "rtmp://192.168.235.36/live/livestream5 live=1" -vcodec copy -acodec copy -f flv -y rtmp://192.168.235.60/live/livestream5", it works by cmd. Trouble me.

**Comment by njoyard** [comment]
Closing this because it has not had any activity for months. Feel free to reopen if you still have issues/questions :)
