### ISSUE TITLE
hard error in util.js when calling currentKbps (if progress.bitrate undefined)

### ISSUE THREAD

**Issue by jseeley78** [fluent-ffmpeg/node-fluent-ffmpeg#406]
There is no check for 'progress.bitrate' (utils.js:333) so if it's undefined there is a crashed when replace is called. 

/usr/local/v/node-app/prod-567/node_modules/fluent-ffmpeg/lib/utils.js:333
        currentKbps: parseFloat(progress.bitrate.replace('kbits/s', '')),                                         ^
TypeError: Cannot call method 'replace' of undefined

**Comment by jseeley78** [comment]
apologies; I opened another ticket for this (#426). I'd be happy to make a pull request with a fix if I had permission

**Comment by njoyard** [comment]
Anyone has permission do make a pull request. Just fork the repository, make the fix in your fork, and then create a pull request from there.

**Comment by jseeley78** [comment]
thanks for that tip, pull request created
