### ISSUE TITLE
How to run without giving output

### ISSUE THREAD

**Issue by digitaltsai** [fluent-ffmpeg/node-fluent-ffmpeg#407]
It looks like I am forced to use an output. The command I'm trying to do is this:

```
ffmpeg -i ./videos/video.mp4 \
-filter_complex "[0:v]copy[video];
  [0:a:0]anull[originalaudio]" \
-map "[video]" video-only.mp4 \
-map "[originalaudio]" audio-original.mp4
```

Is there anyway to circumvent using `.output()`?

The error I get is `'No output specified'` (from processor.js on line 392). What's interesting though, is that there looks like there are some code that supports not having an output later in the code after the error.

**Comment by njoyard** [comment]
The command you gave has outputs, it even has two. There are several ways to do this.

First, translating your command directly.
```js
ffmpeg('./videos/video.mp4')

  // Setup complex filter, see doc
  .complexFilter([
    { filter: 'copy', inputs: '0:v', outputs: 'video' },
    { filter: 'anull', inputs: '0:a:0', outputs: 'originalaudio' }
    // You can also use filter strings directly, such as '[0:v]copy[video]'
  ])

  // first output
  .output('video-only.mp4')
  // first output options (no map method is available yet so we use outputOptions)
  .outputOptions('-map [video]')

  // second output
  .output('audio-original.mp4')
  // second output options
  .outputOptions('-map [originalaudio]')

  // add event handlers here, then run the command
  .run();
```

You don't have to use a filter:
```js
ffmpeg('./videos/video.mp4')

  // first output (note that the options related to the first output
  // can also be specified BEFORE calling .output())
  .output('video-only.mp4')
  .noAudio()
  .videoCodec('copy')

  // second output
  .output('audio-original.mp4')
  .audioCodec('copy')
  .noVideo()

  // add event handlers here
  // run
  .run();
```

Finally, you can use 2 separate commands (there is nothing wrong with this AFAIK).
```js
ffmpeg('./videos/video.mp4')
  .noAudio()
  .videoCodec('copy')
  .save('video-only.mp4');

ffmpeg('./videos/video.mp4')
  .audioCodec('copy')
  .noVideo()
  .save('audio-original.mp4');
```

**Comment by njoyard** [comment]
Also note that the 2nd solution above is equivalent to:
```
ffmpeg -i ./videos/video.mp4 \
    -an -vcodec copy video-only.mp4 \
    -acodec copy -vn audio-original.mp4
```

**Comment by digitaltsai** [comment]
Ah thanks for the examples! I'm new to ffmpeg, so was getting stuck at how to piece parts together with a complex filter, especially with the optional map argument for `.complexFilter()`, but now everything is much more clear.

**Comment by njoyard** [comment]
Closing for now, feel free to reopen if you have issues.

**Comment by SyntheticTV** [comment]
write node.js code to console.log how many items are in item.content[];
