### ISSUE TITLE
Better error output for complexFilter?

### ISSUE THREAD

**Issue by joshuairl** [fluent-ffmpeg/node-fluent-ffmpeg#408]
Maybe this is a limitation of ffmpeg but for some reason it doesn't give much information about why / where it failed in my code.  Maybe child process can't function this way or something... but figured I'd post this any way...
Thanks for all you do for the community!

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ffmpeg exited with code 1: Error configuring filters.

    at ChildProcess.<anonymous> (/Users/Joshua/Projects/archiving-composer/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
```

**Comment by njoyard** [comment]
Try to add an 'error' handler and look at the arguments

```js
ffmpeg(...)
  .on('error', function(err, stdout, stderr) {...})
```

You'll find more information there. And if you don't, post the result here (especially stdout/stderr)

**Comment by joshuairl** [comment]
Yep, thank you this works perfect.
