### ISSUE TITLE
validate stream

### ISSUE THREAD

**Issue by anmerob** [fluent-ffmpeg/node-fluent-ffmpeg#411]
Hi!

I have a problem, i don't know how validate if a stream are reading, I want if not sending data or stream is end, then stop a setInterval with a clearInterval

My idea is 

if(ffmpeg(url_stream)!=validator){
     clearInterval(var);
}

But i dont know what is the response of ffmpeg() to could validate.

I'm tried put the clearInterval in the part: 
    ffmpeg(url_stream).on('end',function(clearInterval(var)));

But is not working, so i hope someone help me, please!

**Comment by njoyard** [comment]
You may want to look at the 'error' handler, too. When running a command, one of the 'end' or 'error' events is fired.

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
