### ISSUE TITLE
How to give effect in a video with filter by ffmpeg in Node JS?

### ISSUE THREAD

**Issue by bilashcse** [fluent-ffmpeg/node-fluent-ffmpeg#413]
I want to give effect in a video. I want to make this with video filter. But cant understand how to make this ? Please give me suggestion.

**Comment by njoyard** [comment]
Do you know the ffmpeg command line you want to execute?

**Comment by TheDucc** [comment]
If not he then me....

I have a command line command that works, and would like to know if this module will handle my needs.  I can use this:
     $ ffmpeg -i input.mp3 -ss 00:00:50 -t 10.5 -af afade=t=in:st=50:d=1,afade=t=out:st=59.5:d=1 output.m4a

To select a 10.5 second clip of an audio file, and give it a 1 second fade in and fade out.
I think that that something like this should work:

     .setStartTime(10)
     .setDuration(10.5)
     .withAudioFilter('afade=t=in:st=50:d=1')
     .withAudioFilter('afade=t=out:st=59.5:d=1')

Is this correct?

dmd

**Comment by TheDucc** [comment]
I think this has gotten it:
```
        command
          .toFormat('mp4')
          .setStartTime(50)
          .setDuration(10.5)
          .audioFilters([
            {
              filter: 'afade',
              options: 't=in:ss=50:d=1'
            },
            {
              filter: 'afade',
              options: 't=out:st=59.5:d=1'
            }
          ])
          .on('end', function() {
            console.log('file has been converted succesfully');
          })
          .on('error', function(err, stdout, stderr) {
            console.log('an error happened: ' + err.message, stdout, stderr);
          })
          .save('output.mp4');
```

**Comment by njoyard** [comment]
Closing this as issue seems to be solved. Feel free to reopen, though.
