### ISSUE TITLE
How to cut a video from sepcific start time to specific end time ?

### ISSUE THREAD

**Issue by bilashcse** [fluent-ffmpeg/node-fluent-ffmpeg#415]
I want to cut video form a start time to a end time & save it a new file by node JS. How can I do this in node JS ?

**Comment by njoyard** [comment]
Please [read](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#seekinputtime-set-input-start-time) [the](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#durationtime-set-output-duration) [documentation](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#savefilename-save-the-output-to-a-file) first.

**Comment by apptaminJb** [comment]
Hi @njoyard ,

I love your module, i'm currently developping a software under Node Webkit and i'm using a lot your module (it's a software to make App Previews), so thanks a lot for your work.
But i'm having trouble to cut videos here is my code: 
```
this.resizeVideo = function(capturePath, index, beginTime, endTime) {
        var defferedResize = Q.defer();
        var pathFolder = capturePath.split('capture.');
        // ffmpeg -i movie.mp4 -ss 00:00:03 -t 00:00:08 -async 1 cut.mp4
        beginTime = parseFloat(beginTime);
        endTime = parseFloat(endTime);
        var Ffmpeg = require('fluent-ffmpeg');
        var bit = 0;
        var temp = 0;
        var rate = 0;
        this.getMetadata(capturePath).then(function(metadata) {
          bit = metadata.streams[0].bit_rate;
          temp = metadata.streams[0].avg_frame_rate.split('/');
          rate = parseInt(temp[0]) / parseInt(temp[1]);
          var command = new Ffmpeg({
            source: capturePath
          });
          command.setFfmpegPath(ffmpegPath);
          console.log(pathFolder[1], bit, rate, beginTime, endTime);
          command.format(pathFolder[1]).withVideoBitrate(bit / 1000).withFpsInput(parseInt(rate)).setStartTime(parseFloat(beginTime)).setDuration(parseFloat(endTime)).on('end', function() {
            console.log('end');
            defferedResize.resolve();
          }).on('error', function(err, stdout, stderr) {
            console.log(err, stderr);
          }).save(pathFolder[0] + 'test.' + pathFolder[1]);
        });
        return defferedResize.promise;
      };
```
And here is the output:
![output](https://cloud.githubusercontent.com/assets/9529805/9041612/3e844f0a-3a09-11e5-8097-43688c893dd4.png)

I made myself sure that all the variables have the right values so the error doesn't come from there.
Sorry for my bad english (French)
Hope you answer, thanks

**Comment by apptaminJb** [comment]
Hi @njoyard,

The problem was coming from the audio codec, i don't need the audio from the video so i just added "noAudio()" it worked perfectly.

Thanks

**Comment by njoyard** [comment]
Closing as no feedback from @bilashcse was received, feel free to reopen if needed.
Also, thanks @apptaminJb but you should have opened a separate issue... :)

**Comment by njoyard** [comment]
Closing as no feedback from @bilashcse was received, feel free to reopen if needed.
Also, thanks @apptaminJb but you should have opened a separate issue... :)
