### ISSUE TITLE
Convert .dav file to mp4 

### ISSUE THREAD

**Issue by abhaygarg12493** [fluent-ffmpeg/node-fluent-ffmpeg#416]
Hello we want to convert .dav file , 

we use in this way 

 var proc = ffmpeg('/opt/safecamz/recording/558275143239337c1f3d4eed/1A01270PAA00122/2000-01-09/001/dav/11/11.54.16-11.54.51[M][0@0][0].dav')
        // use the 'flashvideo' preset (located in /lib/presets/flashvideo.js)
        .preset('flashvideo')
        .videoCodec('libx264')
        .audioCodec('aac')
        // setup event handlers
        .on('end', function() {
            console.log('file has been converted succesfully');
        })
        .on('error', function(err) {
            console.log('an error happened: ' + err.message);
        })
        // save to stream
        .pipe(stream, {end:true});

This file is converted by ffmpeg manually by this command

exec('mkdir '+directoryToLoad+';for f in '/opt/safecamz/recording/558275143239337c1f3d4eed/1A01270PAA00122/2000-01-09/001/dav/11/11.54.16-11.54.51[M][0@0][0].dav'; do ffmpeg -i "$f" -codec:v libx264 -crf 23 -preset medium \-codec:a libfdk_aac -vbr 4 -movflags faststart -vf scale=-1:720,format=yuv420p '/opt/safecamz/recording/558275143239337c1f3d4eed/1A01270PAA00122/2000-01-09/001/dav/11/11.54.16-11.54.51[M][0@0][0].mp4 ; done'

but using fluent-ffmpeg it give this error

an error happened: ffmpeg exited with code 1: /opt/safecamz/recording/558275143239337c1f3d4eed/1A01270PAA00122/2000-01-09/001/dav/11/11.54.16-11.54.51[M][0@0][0].dav: Invalid data found when processing input

**Comment by njoyard** [comment]
What does ffmpeg output ? (look at 2nd and 3rd parameters to the 'end' event handler)

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.

**Comment by Zbas01** [comment]
solved it by adding "-f h264"
ffmpeg -f h264 -i 2.dav -c:v copy -c:a copy out.mov
