### ISSUE TITLE
Pipe in and out?

### ISSUE THREAD

**Issue by NegativeIQ** [fluent-ffmpeg/node-fluent-ffmpeg#417]
Hey guys im using ytdl-core package (youtube-dl writen in pure javascript)

At the moment im downloading audioonly 256kbps mp4 like these:

var fs = require('fs');
var ytdl = require('ytdl-core');

var download = ytdl('https://www.youtube.com/watch?v=d0YNd9fPWt0', 
	{ filter: 'audioonly', quality: '141' });

download.pipe(fs.createWriteStream('shit.mp4'));

Now since i still need to convert that file to mp3 i would like to pipe it to ffmpeg. Is it possible and how could i do it? Sorry for noobish question but im still getting track with node.js and all handy features it has...

**Comment by njoyard** [comment]
Check whether ytdl can give you a ReadableStream and use it as an input for fluent-ffmpeg. Otherwise, you can use a PassThrough stream.

**Comment by nlhkh** [comment]
I am attempting the same thing. ytdl does return a ReadableStream. However, I am having an issue where the only error message I have is 

    Error: ffmpeg exited with code 1: pipe:1: Invalid argument
    at ChildProcess.<anonymous> (/Users/khanguyen/CodeProjects/lipsynsation/youtubeGrabber/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

The code that does the conversion from m4a to mp3 is

    ffmpeg(audio)
        .audioCodec('libmp3lame')
        .audioBitrate(128)
        .on('end', () => console.log('Finished!'))
        .pipe(outputStream, {
          end: true
        });

where

    var audio = ytdl('https://www.youtube.com/watch?v=d0YNd9fPWt0', { filter: 'audioonly', quality: '141' });

**Comment by nlhkh** [comment]
Finally I got it to work, from reading issue [#396](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/396). What I need to do is to specify the format for the output. The final code is

    ffmpeg(audio)
     .audioCodec('libmp3lame')
     .audioBitrate(128)
     .format('mp3')
     .on('error', (err) => console.error(err))
     .on('end', () => console.log('Finished!'))
     .pipe(outputStream, {
       end: true
    });

**Comment by njoyard** [comment]
Oh, yes, I always forget that. ffmpeg cannot guess the format when outputting to a stream.

@NegativeIQ did you work around your issue ?

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.

**Comment by oonqt** [comment]
happening for me too, but with video

**Comment by galipmedia** [comment]
This works fine for mp3 but when I try for mp4 i get...

```
Error: ffmpeg exited with code 1: Conversion failed!
```

And it is definitely working normally so its not a conversion problem. Any ideas?

**Comment by galipmedia** [comment]
-movflags empty_moov does the trick ... https://stackoverflow.com/questions/25411836/ffmpeg-doesnt-work-with-mp4-and-stdout
