### ISSUE TITLE
Video streaming of a converted file

### ISSUE THREAD

**Issue by maximeCony** [fluent-ffmpeg/node-fluent-ffmpeg#418]
I am trying to convert the audio track of an .mkv file to make it playable in Chrome.
#### index.html
```html
<video src="/video" controls></video>
```
#### server.js
```javascript
app.get('/video', function (req, res) {
  var file = path.resolve(__dirname, 'movie.mkv');
  var range = req.headers.range;
  var positions = range.replace(/bytes=/, '').split('-');
  var start = parseInt(positions[0], 10);
  fs.stat(file, function(err, stats) {
    var total = stats.size;
    var end = positions[1] ? parseInt(positions[1], 10) : total - 1;
    var contentLength = (end - start) + 1;
    res.status(206);
    res.set({
      'Content-Range': 'bytes ' + start + '-' + end + '/' + total,
      'Accept-Ranges': 'bytes',
      'Content-Length': contentLength,
      'Content-Type': 'video/mkv'
    });
    var stream = fs.createReadStream(file, { start: start, end: end });
    var tr = through(function (buffer, _, next) {
      console.log(buffer.length);
      this.push(buffer);
      next();
    });
    // stream.pipe(tr).pipe(res);
    ffmpeg(stream)
      .format('matroska')
      .videoCodec('copy')
      .audioCodec('libmp3lame')
      // .outputOptions('-bufsize 65536')
      .on('start', console.log)
      .on('error', console.error)
      .pipe(tr)
      .pipe(res);
  });
});
```
The file is successfully converted and the audio works but it's not possible to seek trough the video anymore...
Converting the file will change it's global size, I am afraid this is messing with Chrome's `Content-Range` requirements.

I also noted using [through2](https://github.com/rvagg/through2) that the buffer length is 8192 (sometimes less) instead of 65536 when I pipe `res` directly to the stream.

I tried to use `-bufsize 65536` but this was not working

Any help would be super appreciated :)

Thanks,

#### Platform
Mac OS X Yosemite
ffmpeg 2.6.3
fluent-ffmpeg 2.0.1

**Comment by njoyard** [comment]
First, you should not use both an input stream and output stream. It will deadlock eventually.

About the seeking issue, I'm not sure you can achieve it without knowing the converted file size in advance (i.e. just having the converted file already available somewhere and streaming that). Or you will want to use a fixed bitrate, which is very inefficient. The way html media seeking is implemented just makes it very difficult to work with on-the-fly conversion (there MAY be a correct way to do this that I'm not aware of, though).

What I ended up doing is just implementing seek myself. I'm using a custom seek bar and every time the user seeks, I load a different media URL with the start offset as a parameter. That's not very efficient cache-wise, but keep in mind html media playback has been mainly designed to work with systems that host already converted files.

**Comment by maximeCony** [comment]
You are right, using a ReadStream in this exemple is not a good idea but in my real app I try to convert a [torrent-stream](https://github.com/mafintosh/torrent-stream). 
Deadlocks are concerning though, I'll have to make some tests.

I also thought about implementing a custom seek but I couldn't make it work (and it didn't seemed very elegant) I'll try again tomorrow.

Merci! ;)

**Comment by maximeCony** [comment]
Sorry @njoyard I might have closed the issue too soon :cry: 

I tried to implement the "bytes offset" but I can't seem to find how to make it work.
I slightly modify the code but when I change `video.src` with a new offset the sound is working but the video is black.
Did you use a similar method?

```HTML
<video src="/video/0" controls></video>
```

```javascript
app.get('/video/:offset', function (req, res) {
  var file = path.resolve(__dirname, 'movie.mkv');
  var range = req.headers.range;
  var positions = range.replace(/bytes=/, '').split('-');
  var start = parseInt(positions[0], 10);
  var offset = parseInt(req.params.offset, 10);
  fs.stat(file, function(err, stats) {
    var total = stats.size - offset;
    var end = positions[1] ? parseInt(positions[1], 10) : total - 1;
    var contentLength = (end - start) + 1;
    res.status(206);
    res.set({
      'Content-Range': 'bytes ' + start + '-' + end + '/' + total,
      'Accept-Ranges': 'bytes',
      'Content-Length': contentLength,
      'Content-Type': 'video/mkv'
    });
    var stream = fs.createReadStream(file, { start: start + offset, end: end });
    ffmpeg(stream)
      .format('matroska')
      .videoCodec('copy')
      .audioCodec('libmp3lame')
      .on('start', console.log)
      .on('error', console.error)
      .pipe(res);
  });
});

```

then in Chrome's console

```javascript
var video = document.querySelector('video');
video.src = 'video/6000000';
```

**Comment by njoyard** [comment]
Don't use byte offsets. Use time offsets and add a `.skip()` call to your command. You should also remove content-range headers I think.

**Comment by maximeCony** [comment]
OK I'll try that, thanks again!

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.

**Comment by maximeCony** [comment]
Sorry @njoyard, I never managed to make it work.
Thanks anyway!
