### ISSUE TITLE
ffmpeg capture RTSP frame and overwrite the image output file

### ISSUE THREAD

**Issue by xianlin** [fluent-ffmpeg/node-fluent-ffmpeg#419]
How to use node-fluent-ffmpeg to implement the below ffmpeg command?
(It reads a RTSP video stream and overwrite again and again to the same jpg file on the local file system)

```
ffmpeg -i rtsp://IP_ADDRESS/live.sdp -f image2 -updatefirst 1 img.jpg
```

**Comment by njoyard** [comment]
How about

```js
fmpeg('rtsp://IP_ADDRESS/live.sdp')
  .format('image2')
  .outputOptions('-updatefirst 1')
  .saveToFile('img.jpg');
```

?

**Comment by xianlin** [comment]
Thank you and YES! IT WORKS! (Sorry for the late reply, the issue can be closed)

```
var ffmpeg = require('fluent-ffmpeg');
var command = ffmpeg();


ffmpeg('rtsp://username:password@camera_ip_address:554/live.sdp')
  .format('image2')
  .outputOptions(['-r 1/5','-updatefirst 1'])
  .saveToFile('img.jpg');

```

Notice I have added `-r 1/5` options to capture the RTSP stream every 5 seconds.

**Comment by ablankenship10** [comment]
Sorry to bump this but I'm running the same scripts here and after about 20 seconds or so the script just stops, no errors or any output. 

Node v4.4.4

Any way to get a debug log?

**Comment by antares2001** [comment]
Any news on this? I figured as well, that ffmpeg is somewhat unreliable if the stream, e.g., comes over wifi or bandwidth is bad. It is not too error-tolerant to the stream it seems. If somebody has a hint about how to deal with interrupted rasp streams I'd be glad to know.
