### ISSUE TITLE
Have a toString() to output the whole command

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#420]
Would be cool to have something like:

```js
var command = new FfmpegCommand()
...
console.log(command.toString())
```

so that I can see the whole command. Very useful for debugging / error handling.

**Comment by binarykitchen** [comment]
hello?

**Comment by njoyard** [comment]
What about using the `start` event ?

**Comment by binarykitchen** [comment]
Does the start event come with a parameter, telling the whole command?

**Comment by njoyard** [comment]
It does, as shown in the documentation.

**Comment by binarykitchen** [comment]
Right, that start event ... sorry if I wasn't precise enough before but I still think a `command.toString()` would be great. Because I only need that string in case of an error. Like this example. It helps a lot when I want to backtrace the error. The original `err` instance doesn't include the initial ffpmeg command. That's why.

```js
        command.on('error', function(err) {
            console.error('This command failed:', command.toString())
            console.error(err)
        })
```

**Comment by njoyard** [comment]
Then why not just use

```js
var cmdline = 'unknown';
command.on('start', function(c) { cmdline = c; });
command.on('error', function() { console.log('command line was ' + cmdline); });
```

?

**Comment by binarykitchen** [comment]
Good question. Yes, I was thinking of that too. Still, this isn't a good solution. In case if no error occurs, the `cmdline` variable is wasted, never used.

I only want to initialize `cmdline` in case of an error, not earlier.

**Comment by njoyard** [comment]
Not using a variable does not make it a bad solution !

Adding a `toString()` method is, on the other hand, a bad idea. It does not return a string representation of the actual command (only of the command line that it would/has/will launch), and actually some commands do not correspond to a single command line. The command line(s) that are launched are determined by the final method you call on the command object (`run`, `save`, `pipe`, `merge` etc). As a consequence the command object itself does not have a corresponding command line.

**Comment by binarykitchen** [comment]
Maybe I was a bit hars - no hard feelings. For most use cases that's fine.

It is just that I use your package for a heavily used video site where hundred of videos are beeing encoded by the hour and because the ffmpeg command is very long. Do not want to keep unnecessary strings in memory for a good reason.

**Comment by njoyard** [comment]
No offense taken, I'm just making my point here :)

Consider the following code:
```js
function doStuff() {
  var command = ffmpeg(...);
  var cmdline = 'unknown yet';
  command.on('start', function(c) { cmdline = c; });
  command.on('error', function(c) { console.log('cmdline is ' + cmdline); });
  command.run();
}
```

As soon as the command is done (finished or failed), there are no more references to `command` on the event loop so it is candidate for GC. As a consequence, the 'start' and 'error' event handlers become candidates for GC as well. `cmdline` being only referenced by these handlers, it becomes candidate for GC as well. The variable has approximately the same lifespan as the command itself.

Additionnally, the objects used to spawn processes, handle streams etc. are far bigger than a 1000-ish chars string.

If using a variable still itches you (that's your code after all) you may as well store it as a property of the command object.

**Comment by binarykitchen** [comment]
good, thanks - yes, that's a good suggestion to encourage GC to free memory. okay, i will give this one example a try and observe the memory usage closely.

again, thanks for the good debate ;)
