### ISSUE TITLE
image to video then merging with other video

### ISSUE THREAD

**Issue by apprisingapps** [fluent-ffmpeg/node-fluent-ffmpeg#421]
I am using the loop example you provide to create videos from uploaded images.  It creates the video fine.  However, when I attempt to merge with other video that was, for example, created by the same phone as the photos, the merge fails.  I get 'cannot find a matching stream for unlabled input pad 7 on filter Parsed_concat_0."  I have included the loop for creating the video and the merging function.  I suspect I am not including something needed in the loop sufficient for creating a movie that will merge with other videos, but I am unsure.  

LOOP

var  loopingPhoto1 = function(){new FfmpegCommand(photo1upload)

      
        .loop(3.53)
        // using 30 fps
        .fps(30).videoCodec('libx264')
        .audioCodec('aac').size('1920x1080').aspect('16:9')
        // setup event handlers
        .on('end', function() {
            console.log('photo1 loop created successfully');
            eventEmitter.emit('loop1Ready');
        })
        .on('error', function(err) {
            console.log('an error happened: ' + err.message);
        })
        // save to file
        .save(loop1done);}

MERGE

  var  merging2 = function (){
        setTimeout(function (){
            new FfmpegCommand(whiteStart2)

                .input(trim2)
                .input(whiteEnd2)
                .input(loop1done)
                .input(loop2done)

                .videoCodec('libx264')
                .audioCodec('aac')
                //.input(fourthFile)
                //.input(...)
                .on('end', function() {
                    console.log('files have been merged succesfully');
                    eventEmitter.emit('merge2done');
                    res.send('files merged');

                })
                .on('error', function(err, stdout, stderr) {
                    console.log(" =====Convert Video Failed======");
                    console.log(err);
                    console.log("stdout: " + stdout);
                    console.log("stderr: " + stderr);
                })
                .mergeToFile(mergedTheme2);

        },1000)

    }

**Comment by apptaminJb** [comment]
I had the same issue, i was making a video from images and then merging the created video with an other one. And it didn't work because the output file was the same that one of the videos i was merging. 
So verify that the output file isn't the same of one of your input file.

Sorry for my english,
Cheers from France

**Comment by njoyard** [comment]
@apprisingapps could you please include the full output from your 'error' handler ? And also if possible add a 'start' handler and include the output from that as well.

**Comment by apprisingapps** [comment]
Ok.

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.
