### ISSUE TITLE
utils.which problem on windows

### ISSUE THREAD

**Issue by fritx** [fluent-ffmpeg/node-fluent-ffmpeg#422]
in lib/utils.js#which, when on windows, it uses `where` to detect an exe
however, on my windows there is no `where`

```js
var cmd = 'which ' + name;
if (isWindows) {
  cmd = 'where ' + name + '.exe';
}
```

so how about using `shelljs.which`

```js
var which = require('shelljs').which
which(name)
```

i changed the code like that, and it began to work
any idea?

**Comment by njoyard** [comment]
What Windows version are you using ?
I *love* when they just get rid of standard tools like that (I'm looking at you, `telnet`).

If the shelljs version works in all cases, you should submit a pull request :)

**Comment by fritx** [comment]
yes, [shelljs](https://github.com/arturadib/shelljs) is made to work on all platforms, as well as [node-which](https://github.com/isaacs/node-which) let's trust them ;)
node-which is more lightweight, maybe we can use it?

**Comment by njoyard** [comment]
Yep, seems better to me

**Comment by fritx** [comment]
oops, wait, a mistake here

**Comment by njoyard** [comment]
I'm going to fix automated tests first. As soon as they're fixed I'll merge this.

Thanks!

**Comment by fritx** [comment]
cool, thank you!
