### ISSUE TITLE
ffmpeg pop out a command line on windows with forever

### ISSUE THREAD

**Issue by wcastand** [fluent-ffmpeg/node-fluent-ffmpeg#425]
I use FFmpeg to stream audio content with express.

It works but when I use forever to launch my server on the background. Every time a new song is launched, a command line from FFmpeg is open.

I try to put some options, but nothing works.
I tried, "-nostdin" , "< /dev/null" , "-loglevel -8", "-loglevel fatal" 
 
If someone can have an idea how to make this command line disappear, it will be nice :)

**Comment by njoyard** [comment]
What do you mean, "a command line from Ffmpeg is open" ?
Could you please show your code ?

**Comment by wcastand** [comment]
This is the part of my code where i use FFmpeg. I use an expressjs server.
```javascript
app.get('/music/', function (req, res) {
  res.contentType('arraybuffer');
  var link = req.query.link;
  var video = youtubedl(link, ['--format=18'], { cwd: __dirname });
  ffmpeg(video)
    .noVideo()
    .format('mp3')
    .pipe(res);
});
```
And this is what i mean with "a command line from FFmpeg is open": 
The command line closed when FFmpeg finished encoding the video i think
![blbl](https://cloud.githubusercontent.com/assets/2178244/9219495/90109f1c-40db-11e5-9f0b-21d8856b05b2.png)

**Comment by njoyard** [comment]
Oh, I see. I'll have a look.

**Comment by njoyard** [comment]
It seems you can't set shellexecute options from nodejs to control whether to show the console or not. You should run your program as a service to prevent being able to use the UI at all (using winser or nssm for example).

**Comment by wcastand** [comment]
It works perfectly :)
I used winser on my server and no UI appears, thank again :)
note: to use winser your main file need to be called "server.js", otherwise it won't work properly.
