### ISSUE TITLE
Outputstream size

### ISSUE THREAD

**Issue by nlhkh** [fluent-ffmpeg/node-fluent-ffmpeg#427]
I am using fluent-ffmpeg with ExpressJS to stream audio for downloading. However, the browser does not know the size of the size, and thus can only tell the bytes downloaded, and not the bytes remaining. Is there anyway I can get the size of the outputstream once it is finished so as to set the Content-Length for my response object?

**Comment by njoyard** [comment]
There is not, unless you use fixed bitrates and compute the size yourself.

**Comment by nlhkh** [comment]
I see, thanks :)
