### ISSUE TITLE
.kill() doesn't work

### ISSUE THREAD

**Issue by frog1014** [fluent-ffmpeg/node-fluent-ffmpeg#436]
Both of method kill() and event 'error' didn't really kill the process, all processes still exist after keying 
ps -ef | grep ffmpeg in Fedora

**Comment by apptaminJb** [comment]
I had the same issue, to fix it i did this:
```
var child = require("child_process");
     child.execSync("killall ffmpeg", function(error, stdout, stderr) {
     console.log(error, stdout, stderr);
});
```
Be careful it's a bit violent if you have over ffmpeg process it will also kill them.

Cheers from France

**Comment by njoyard** [comment]
That's weird, which OS are you running ?
Can you run the test suite and paste the results here ? To do so, clone the repo, run npm install and then make test.

**Comment by frog1014** [comment]
I observed the behavior of a ffmpeg instance ( var a = new ffmpeg(args) )

After the first run(), even I gave a order of `kill`, then chain to `run`, `run` works fine with a new process, but the original process hasn't be killed, it lead to 2 processes in my system.
But I can't always reproduce, it occur in certain %.

code:

a.run();
.
.
.
a.kill().run();

Is any mistake on my comprehension?
Thanks.

**Comment by njoyard** [comment]
Do not run the same command object more than once, that's not supported.

**Comment by njoyard** [comment]
Closing this as issue should be resolved.

**Comment by houzhitaohzt** [comment]
![image](https://user-images.githubusercontent.com/20673060/42609612-f61326b4-85bf-11e8-9748-cd8a121a36a5.png)
