### ISSUE TITLE
Limit ressources usage

### ISSUE THREAD

**Issue by apptaminJb** [fluent-ffmpeg/node-fluent-ffmpeg#437]
Hi,

I'm looking for a way to limit memory/cpu usage of ffmpeg. I saw that it was possible in c# by limiting the number of threads.
Why i want to do this? Because i'm developing a DIY video maker software and once a user finished his video he can export it, the export works this way:
- play the current video
- pause it
- Read all pixels (video + images + text etc..)
- Copy all pixels to a canvas
-  create a frame from those pixels via fluent ffmpeg
- set the time of the current time to 1/30s further (to have a 30fps video at the end)

This is done until the end of all videos
So once all the frames are made i'm compiling them to a mp4 video, then i'm merging it with the audio that the user uploaded before in its project.

My problem is that the users may not have a powerful computer as i do, so i would like to limit the ressources that ffmpeg use, even if the export will be slower it is still better than a crash.

If it's not possible i can work on it, it's really important for my project.

Thanks, cheers from France

**Comment by njoyard** [comment]
Please see the ffmpeg documentation on how to achieve that. If there's nothing in it, then you'll be limited to using `renice()`.

**Comment by apptaminJb** [comment]
Thanks @njoyard , 

Fmmpeg offers the -threads option, it allows to limit the number of threads, i'm going to try that out with renice as well.
