### ISSUE TITLE
How can I use `-c:a aac -strict -2`

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#439]
I know I can enable `aac` with `command.audioCodec('aac')` but how can I amend the argument `-strict -2` afterwards?

**Comment by binarykitchen** [comment]
... and will it really make a big difference for the audio quality?

**Comment by njoyard** [comment]
You can pass it with `.outputOption()`. As for your second question, I don't know. Have a look around ffmpeg communities !
