### ISSUE TITLE
Error: cannot find ffmpeg

### ISSUE THREAD

**Issue by jzellis** [fluent-ffmpeg/node-fluent-ffmpeg#442]
I am completely lost here and this is driving me nuts. I cannot deploy this properly on a remote server, no matter what I try. I'm using fluent-ffmpeg from within Meteor, streaming files to it, and every time it works perfectly on my MacBook localhost. But when I run it on any remote server -- Heroku with the ffmpeg buildpack or my EC2 instance, I get this: `[Error: Cannot find ffmpeg]`

Yes, ffmpeg is installed -- I can run it from the command line. I set FFMPEG_PATH in the environment to the proper location (/usr/bin/ffmpeg). But I get nothing. And I'm desperate at this point -- can anybody help out here? Maybe some kind of thing I can send to the console to see what's happening here?

**Comment by jzellis** [comment]
I should add that /usr/bin is also in my $PATH, of course. I installed ffmpeg in Ubuntu 14.04 using the custom repo recommended by a lot of people, and it seems to work perfectly well if I run it via the command line.

**Comment by njoyard** [comment]
Can you try running it yourself (using child_process.spawn) ? And locating it manually (`which ffmpeg`, run it both from nodejs and from the shell) ?

**Comment by jzellis** [comment]
`which ffmpeg` gives me nothing, but `whereis ffmpeg` gives me `ffmpeg: /usr/bin/ffmpeg /opt/ffmpeg/bin/ffmpeg`. I'll try doing the child_process thing from the node shell and see what that does. :-)

**Comment by jzellis** [comment]
Interesting: so I run this:

`childProcess.exec('ffmpeg', function(e,o,err){console.log("Error: " + e); console.log(o); console.log(err)})'

just to see what it does, and I get this: 

'Error: Command failed: ffmpeg version N-74748-gbaeb8f5 Copyright (c) 2000-2015 the FFmpeg developers'

But yet, ffmpeg returns the usage hints that you'll get when you don't provide any arguments, like it's working okay. I'm confused now.

**Comment by jzellis** [comment]
Full returned output is this: 

`Error: Error: Command failed: ffmpeg version N-74748-gbaeb8f5 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 59.100 / 56. 59.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.100 /  5. 40.100
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'`

**Comment by njoyard** [comment]
Is your source code available somewhere ?

**Comment by njoyard** [comment]
Closing this as no feedback was given. Feel free to reopen, though.

**Comment by theOnkar** [comment]
Im testing it on Windows 10 and Im getting the same error. `Error: Cannot find ffmpeg`. Somebody plesae help if this thread is alive.

**Comment by Darker** [comment]
I get the same issue. FFMPEG is installed, but `fluent-ffmpeg` ignores it. I can run ffmpeg directly:

```
var spawn = require("child_process").spawn;
var proc = spawn(
    "ffmpeg",
    ["-framerate","1", "-i","20170322_223734.jpg", "movie.mp4"],
    {
        env: process.env,
        cwd: process.cwd()
    }
);
proc.stdout.pipe(process.stdout);
proc.stderr.pipe(process.stderr);
```

Following example does not create a functioning video, but it definitelly does run `ffmpeg`.

I wonder if someone tested this on windows before closing the issue. It clearly happens on windows, I'm using Windows 7.

**Comment by njoyard** [comment]
This issue was not originally on windows. And it was closed for lack of info from the creator.

You can open an other issue for this windows problem, but know that I have no way of testing on any windows version.

**Comment by owen-mills** [comment]
Same issue on Ubuntu linux

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /var/www/youtube/node_modules/async/dist/async.js:473:16
    at next (/var/www/youtube/node_modules/async/dist/async.js:5315:29)
    at /var/www/youtube/node_modules/async/dist/async.js:958:16
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/var/www/youtube/node_modules/which/which.js:68:16)
    at E (/var/www/youtube/node_modules/which/which.js:80:29)
    at /var/www/youtube/node_modules/which/which.js:89:16
Emitted 'error' event at:
    at emitEnd (/var/www/youtube/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at /var/www/youtube/node_modules/async/dist/async.js:473:16
    [... lines matching original stack trace ...]
    at /var/www/youtube/node_modules/async/dist/async.js:473:16
    at next (/var/www/youtube/node_modules/async/dist/async.js:5315:29)
    at /var/www/youtube/node_modules/async/dist/async.js:958:16
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/capabilities.js:519:16
    at /var/www/youtube/node_modules/fluent-ffmpeg/lib/processor.js:136:16

```

**Comment by foufrix** [comment]
had this problems and found this post. For futur reference there is a node package to import all static files, especially useful if you work in the cloud : 
https://github.com/eugeneware/ffmpeg-static

If you need the probe as well : https://github.com/joshwnj/ffprobe-static
