### ISSUE TITLE
ffprobe throws error no results are returned

### ISSUE THREAD

**Issue by snowkeeper** [fluent-ffmpeg/node-fluent-ffmpeg#446]
I was running a set of files through ffprobe and one file was not returning data and erroring out...
```
TypeError: cannot convert undefined or null to object
```

I was able to stop this by adding format to the initial `data` object...
https://github.com/snowkeeper/node-fluent-ffmpeg/blob/b1ec497c858038b3181fe1fb2ac93e03fa6fc3bf/lib/ffprobe.js#L10-L14
```
function parseFfprobeOutput(out) {
  var lines = out.split(/\r\n|\r|\n/);
  var data = {
    streams: [],
    format: {}
  };
```
Am I doing something wrong or is this a true error?

**Comment by snowkeeper** [comment]
The root cause of this issue is using `avprobe` on Ubuntu 14.04.

The command in ffprobe is
```shell
avprobe -print_format json -show_streams -show_format 
```
and avconv changed switched `-print_formt` with `-of`
```shell
avprobe -of json -show_streams -show_format 
```

Avprobe was not sending the json data which was causing the crash.  Switching to ffprobe fixed the issue.  Invalid files do not crash with ffprobe.

**Comment by njoyard** [comment]
This annoys me a lot.
That Debian chose to ship avconv instead of ffmpeg, so be it. But they should'nt have shipped the ffmpeg compatibilty binaries, those are *not* compatible.

Anyway, end of monday morning rambling, glad you found a solution.
