### ISSUE TITLE
takeScreenshots reports an error with ffmpeg 2.3.4

### ISSUE THREAD

**Issue by Queuecumber** [fluent-ffmpeg/node-fluent-ffmpeg#448]
When I run the takeScreenshots function using ffmpeg 2.3.4, the following error is returned:

```
Error: ffmpeg exited with code 1: Filtergraph 'scale=w=160:h=120' was specified through the -vf/-af/-filter option for output stream 0:0, which is fed from a complex filtergraph.
-vf/-af/-filter and -filter_complex cannot be used together for the same stream.
```

Examining the arguments passed to ffmpeg shows that they are 

```
[ '-ss',
15,
 '-i',
 <redacted>,
'-y',
 '-filter_complex',
'split=1[screen0]',
 '-vframes',
 1,
 '-filter:v',
'scale=w=160:h=120',
 '-map',
 '[screen0]',
 <redacted>]
```

Commenting out lines 393 and 400 of lib/recipes.js fixes this issue

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
