### ISSUE TITLE
multiple output with different presets

### ISSUE THREAD

**Issue by vinodhum** [fluent-ffmpeg/node-fluent-ffmpeg#450]
how can I set different preset with different output ?
I tired using run with below command
ffmpeg('./abcd.mp4')
  .videoCodec('libx264')
  .outputOptions([
  '-minrate 2400',
  ])
  .size('1280x720')
  .output('./abcd_2400.mp4')

  .outputOptions([
  '-minrate 1200'
  ])
  .size('854x480')
  .output('./abcd_1200.mp4')
.run();

it is creating 2 file but first one have only audio and white screen where as second one looks good.

what am I dong wrong ?

Thank you

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
