### ISSUE TITLE
.thumbnails fails with ffmpeg 2.8

### ISSUE THREAD

**Issue by davibe** [fluent-ffmpeg/node-fluent-ffmpeg#452]
Since trusty media upgraded ffmpeg 2.8 i am having issues with .thumbnails()

If i use timemarks as percentages, like "20%" , i get this error

```
Could not get input duration, please specify fixed tidemarks
```

**Comment by njoyard** [comment]
What input are you using ?

**Comment by adamhcodes** [comment]
I had the same error: 
[Error: Could not get input duration, please specify fixed timemarks]

So I added the timestamps flag and it fixed it in dev mode, but still fails in production mode. 

.screenshot({
          count: 1,
          timestamps: [3.5],
          size: '960x540',
          folder: 'public/thumbnails/',
          filename: hash
})

Thoughts?

**Comment by davibe** [comment]
is was an .mkv but i don't have it before hands anymore. I ended up manually getting the duration using ffprobe codecData and then expressing the thumbnail timemarks by time, not %. It's strange because it should be the same thing .thumbnails() does internally. I think.

**Comment by njoyard** [comment]
Indeed that's strange. If you happen to stumble upon this behaviour again I'd be interested to do some tests on the input file (mostly see what ffprobe returns).

I asked what your input was because this error would be normal if you used a stream input, BTW.

**Comment by njoyard** [comment]
Closing this because it has not had any activity for months. Feel free to reopen if you still have issues/questions :)
