### ISSUE TITLE
SIGSEGV  - thrown when  heroku 'worker' calls ffmpeg

### ISSUE THREAD

**Issue by rowntreerob** [fluent-ffmpeg/node-fluent-ffmpeg#454]
--EDIT  this must be a heroku issue or a 'throng' issue...

**Comment by njoyard** [comment]
I don't think that has anything to do with fluent-ffmpeg itself. We just build a command line and run it :)

**Comment by rowntreerob** [comment]
thank you.

im still looking at it.

I dont know where the SIGSEGV was being thrown and could not get node to
provide more info.

But detailed ffmpeg logs show it running 2 passes ( due to the 'faststart'
in x264 i think )  and the SIGSEGV is being thrown before the 2nd pass
begins....

ffmpeg main() and the way the lib is unloaded and reloaded  in a multiple
pass scenario may get you into SIGSEGV territory.

since im using so many other libs in the heroku worker architecture, i
thought it was something else but now im back to ffmpeg as the culprit.
