### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by DrewDahlman** [fluent-ffmpeg/node-fluent-ffmpeg#458]
I am attempting to stitch together a video using a series of images.

<pre>
 var vid = ffmpeg();
 	for(var i = 0; i < 40; i++){
 		vid.addInput(path.join(__dirname, '../public/images/test_'+i+'.png'));
 	}
  vid.withFpsInput(10);
  vid.addOptions([
  	'-c:v', 'libx264', 
  	'-pix_fmt', 'yuv420p'
  ]);

 vid.saveToFile( path.join(__dirname, '../public/images/test.mp4')
</pre>

This works but only adds the first image as a source. upon inspecting the vid object I can see all of my sources, but the video is still just the first frame and 0 seconds...

Any thoughts?

**Comment by njoyard** [comment]
I don't think you can create a video from multiple images this way. You'll want to use a single input and use "%d" in the input filename I think (see http://trac.ffmpeg.org/wiki/Create%20a%20video%20slideshow%20from%20images)

**Comment by DrewDahlman** [comment]
Yeah - after doing some testing I found it was just easier to write an FFMPEG script and execute that - passing along my variables to the bash script.

It seemed to have issues when using `%d` in the fluent-ffmpeg.

**Comment by AaronLlanos** [comment]
So I need to listen for the callback of when ffmpeg finishes this process so I could upload to AWS. Are there any pointers of how I could I go about adding `%d` to my path? Currently I tried: 

```js
var path = '/tmp/'+userID+'-frame-%04d.png';
  ffmpeg(path)
    .inputFPS(30)
    .format('mp4')
    .size('?x700')
    .duration(10)
    .screenshots({
      timemarks: ['50%'],
      filename: name+'.png',
      folder: 'uploads',
      size: '?x700'
    })
    .on('error', function(err) {
      console.log('error', err.message);
    })
    .on('end', end)
    .save('uploads/'+name+'.mp4');
```

**Comment by Rubinhuang9239** [comment]
@AaronLlanos 
Hey Aaron, I was looking into another repo that does the thing you are trying to do.
[](https://github.com/h2non/videoshow)
somethings the loop is too short, I have to set the fps to high.

I am very interested in your solution, I think when I try to use "%03d", the function takes it as a string and tells me the file was not found. What did you do?

**Comment by AaronLlanos** [comment]
@Rubinhuang9239 I ended up encoding my video on the front end. It was less performant, but it worked for the purpose I needed. I ended up just streaming the final encoded video straight to AWS via their javascript API

**Comment by waqadArshad** [comment]
@Rubinhuang9239 I know it's been quite some time since you wrote this, But I was kinda having the same issue, so any ideas? Thanks

> @AaronLlanos Hey Aaron, I was looking into another repo that does the thing you are trying to do. https://github.com/h2non/videoshow somethings the loop is too short, I have to set the fps to high.
> 
> I am very interested in your solution, I think when I try to use "%03d", the function takes it as a string and tells me the file was not found. What did you do?
