### ISSUE TITLE
Master branch has `version` 2.0.0 in `package.json`

### ISSUE THREAD

**Issue by overlookmotel** [fluent-ffmpeg/node-fluent-ffmpeg#462]
Hi.

Judging by your responses to other issues, I gather you're very busy. However a short response to this query would be much appreciated if you have time...

I just forked the repo and noticed that `version` in `package.json` is '2.0.0' whereas latest npm release is 2.0.1. Which is the most up-to-date version?

Hope you can help...

**Comment by njoyard** [comment]
Hi,

The version token on master branch does not matter, actually it should not have been committed there in the first place.

The most recent version is indeed on the master branch. You can compare it to version tags if you want to be sure.

**Comment by overlookmotel** [comment]
OK. That's brilliant. Thanks for clarifying.

**Comment by overlookmotel** [comment]
I'm intrigued as to why you don't commit the package.json `version` tag. I've found with most repos that the code (inc the package.json) is committed to git exactly the same as the corresponding npm release. But that's just a convention I guess. I'm fairly new to this and would be interested to know if you think there's a better way.

**Comment by overlookmotel** [comment]
It seems from the commit history that there were no code changes between 2.0.0 and 2.0.1 anyway. So it's a non-issue. Please ignore me!
