### ISSUE TITLE
Parsing filter output in realtime

### ISSUE THREAD

**Issue by overlookmotel** [fluent-ffmpeg/node-fluent-ffmpeg#463]
Hi.

I have the need to capture and parse the output from filters in realtime as the file is processed. The reason is that I am looking to get ffmpeg to identify if there is black screen and silence at the start of a video file (which can then be trimmed off). Therefore I would like to get the filter output in realtime, parse it, and as soon as a frame which has sound or picture appears, kill the ffmpeg process. There's no need for it to continue processing the rest of the file (which can be very time-consuming).

At present there is no way to do this as far as I can see.

I would like to produce a PR to add support for this, and wanted to discuss what you think is the best way to implement. I can see a couple approaches:

1. Make the `start` event provide the child process instance, so then its `stderr` output can be interacted with directly by user code
2. Create an event `stderr` which is emitted every time a line of data is written to `stderr`
3. More high level, parsing `stderr` output and emitting a `filter` event for every line of filter output

Personally I think it could be good to do both (1) and (2) regardless of whether (3) is implemented too.

Doing either (2) or (3) would require a bit of tweaking to the code which currently handles `stderr` to break stderr output into lines. The data event sometimes fires with multiple lines of `stderr` output, so it's possible to lose information, if you only look at the last line of output each time. The easiest way to split the stream into lines is to use the [split](https://www.npmjs.com/package/split) module, but you may prefer not to add dependencies?

For (2), there's also the question of whether stderr lines which are already emitted by `codecData` and `progress` events should be excluded from what is emitted by `stderr` event. One approach could be:

* If a listener for `codecData` is attached, do not emit `stderr` event for lines relating to codecData
* If a listener for `progress` is attached, do not emit `stderr` event for lines relating to progress
* If listeners are not attached for one of `codecData` or `progess`, the stderr lines that would have been swallowed by that event are instead emitted by `stderr` event

Or:

* All `stderr` output is emitted by `stderr` event regardless of whether `codecData` and `progress` event listeners are attached or not.

What do you think? And would you accept a PR?

**Comment by njoyard** [comment]
Hi,
First of all, of course I'm open to PRs of any kind.

1) is unnecessary IMO as you already have a ffmpegProc property on the command object as soon as the process is started (undocumented, though).

2) is a good idea ; my opinion would be not using dependencies (splitting a text stream into lines can be done in 4 lines of code) and always emitting stderr events even if the line is something we already use for something else. The user can decide whether she wants the line or not.

3) is also a good idea but seems very specific to me : if we implement that, we should also look for other output "categories" to implement, too ; or we could just add an additional parameter to the 'stderr' event to pass that category along with the data line. And we must take additional care that the way we determine message categories is valid with older ffmpeg versions and will stay that way.
