### ISSUE TITLE
complexFilter and mutliple output

### ISSUE THREAD

**Issue by Webini** [fluent-ffmpeg/node-fluent-ffmpeg#464]
Hi, 
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/options/custom.js#L193
This line is problematic when we want to add complex filters on each output.

Nico.

**Comment by njoyard** [comment]
Hey,
ffmpeg does not support multiple complexfilters (at least it didn't when I wrote this implementation).

However you can use a single complexfilter graph for multiple outputs. You can have multiple paths (connected or not) in a graph. Just use the inputs/outputs settings.

**Comment by njoyard** [comment]
Closing for now, please reopen if you still have problems/questions on this matter.

**Comment by IvanMMM** [comment]
#754
