### ISSUE TITLE
Split and Assemble

### ISSUE THREAD

**Issue by OzGitele** [fluent-ffmpeg/node-fluent-ffmpeg#465]
Hello,
We have a scenario that calls for splitting a video to frames
(we paint on the frames, not important)
and then assemble it back to video. We are running on Windows 8.1.
There are 2 issues we ran into:
1) When splitting to screenshots, we receive an ENAMETOOLONG error above a certain number of images.

Here is the error:

child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at C:\Proj\Video\node_modules\fluent-ffmpeg\lib\processor.js:135:24
    at FfmpegCommand.proto._getFfmpegPath (C:\Proj\Video\node_modules\fluent-ffmpeg\lib\capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (C:\Proj\Video\node_modules\fluent-ffmpeg\lib\processor.js:115:10)
    at C:\Proj\Video\node_modules\fluent-ffmpeg\lib\processor.js:428:12
    at C:\Proj\Video\node_modules\fluent-ffmpeg\node_modules\async\lib\async.js:52:16
    at Immediate._onImmediate (C:\Proj\Video\node_modules\fluent-ffmpeg\node_modules\async\lib\async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

2) When splitting the video, we use the %s notation, we get images that are named like:
WF-0.2.png, WF-1.4.png, WF=1.6.png, WF-1.8.png etc.

Now, when we try to assemble to a video with the ffmpeg command: (We did not find a fluent-ffmpeg command for assembling a video):

ffmpeg -framerate 29  -i WF-%d.png -c:v libx264 -r 29 -pix_fmt yuv420p out.mp4

only the primary frames get collected, that is, only according to the seconds digit, not the digits after the decimal point, so in the example files above, only 2 files are taken 0 and 1 sec. Is there a notation for collecting all frames, also with decimal point?

**Comment by njoyard** [comment]
For 1), Windows has a pretty low limit on command line length. You should do your thumbnails in several passes or submit a PR to enable using a temporary file for parameters (i *think* ffmpeg supports that).

For 2), this is not the best place to ask, look around the ffmpeg communities. Once you have a working solution people here can help you translate it to fluent-ffmpeg.

**Comment by OzGitele** [comment]
Thank you, will follow up
