### ISSUE TITLE
ffmpeg error: Conversion failed. 

### ISSUE THREAD

**Issue by mon1020** [fluent-ffmpeg/node-fluent-ffmpeg#468]
Hi,

I am using fluent-ffmpeg to live stream to video.
But I get this error:  ffmpeg exited with code 1. Conversion failed!
Below is my command.
 ffmpeg -f v4l2 -s 320x200 -i /dev/video0 -f mpeg1video -s 320x200 -crf 2 -q 2 -preset ultrafast http://127.0.0.1:8082/crc123/320/200
When I run this command from command line I get following error:
av_interleaved_write_frame(): Broken pipe

OS: ARM Cortex 8 Linux Debian Wheezy.
Please help me with the issue.
Thanks in advance.

**Comment by njoyard** [comment]
Hi,
Please have a look with ffmpeg community to work around your command line issue first, then feel free to reopen an issue if you have problems running a working command line with fluent-ffmpeg.
