### ISSUE TITLE
Create TypeScript definitions and add to DefinitelyTyped

### ISSUE THREAD

**Issue by jaq316** [fluent-ffmpeg/node-fluent-ffmpeg#472]
See DefinitelyTyped/DefinitelyTyped#6991

**Comment by njoyard** [comment]
Sorry, but this does not belong in this repository.

I don't want to take the responsibility to freeze the interface for fluent-ffmpeg, as it is not settled yet. Feel free to contribute your own type definition to DefinitelyTyped/DefinitelyTyped, but don't forget fluent-ffmpeg is still a WIP and its API may change at any time.
