### ISSUE TITLE
multiple filter operations

### ISSUE THREAD

**Issue by chrisschaub** [fluent-ffmpeg/node-fluent-ffmpeg#474]
I'm trying to do an "afade" audio filter. I can do a fade in, but the fade out does not work.
```
command
          .toFormat('mp4')
          .setStartTime(0)
          .setDuration(12)
          .audioBitrate('128k')
          .audioFilters([
            {
              filter: 'afade',
              options: 't=in:st=0:d=2:t=out:st=9:d=3'
            }
          ])
```
Setting the start time and fade "in" works, but no fade out. What am I doing wrong?

**Comment by njoyard** [comment]
Did you try the same on command line  ? Does it work ?

**Comment by chrisschaub** [comment]
Sorry, it works. I had a bad filename.
