### ISSUE TITLE
Overlapping Playback

### ISSUE THREAD

**Issue by chrisjandrade** [fluent-ffmpeg/node-fluent-ffmpeg#475]
Not sure if fluent-ffmpeg was intended to be used this way, but its worth a shot to see if there's a way to do this.  Or I'm going about this completely wrong.

I am using fluent-ffmpeg, and node-speaker to allow the user to select some file, and then playback that file. For example
    
    this._passThru = stream.PassThrough();

    this._cmd = ffmpeg(uri).
       format('s16le').
       pipe(this._passThru);

    // some time later the user may choose to seek somewhere and start playing
    this._cmd.seek(10).run();
    this._passThru.pipe(new Speaker());

sound plays, but the previous command is still pushing data through ```this._passThru``` so you'll hear the last command you execute playing, and the most recent command.  Basically, just hear the audio playing twice overlapping each other.

Any ideas for dealing with this? I'm thinking I can just connect my PassThrough stream to some sink, that just consumes all the data.

    var sink = new Writable();
    sink._write = function (chunk, enc, next) {
      next();
    };
    sink.on('finish', function () {
      // start new command here.
    });

Or is it possible to SWITCH the stream I'm currently piping to?

**Comment by njoyard** [comment]
Did you try this._cmd.kill() before running the next one ?

**Comment by chrisjandrade** [comment]
yes, tried to kill the previous command before continuing.  But the old data is continuing through.

**Comment by njoyard** [comment]
Oh, it must have already converted the data then.

You'll need to find a way to break the passthrough stream, I think, and hope that Speaker only pops data from the passthrough when actually reading the audio (ie. does not buffer the audio too long, in which case you'll have to look at a way to break the Speaker instance...)

**Comment by njoyard** [comment]
I'm closing this issue as it is not a fluent-ffmpeg problem. Feel free to keep commenting if you need advice, though.
