### ISSUE TITLE
getting frames from a video using ffmpeg through node

### ISSUE THREAD

**Issue by vamsi0391** [fluent-ffmpeg/node-fluent-ffmpeg#480]
Using this command "ffmpeg -i inputfile.avi -f image2 image-%07d.png" i'm able to get frames for video, but how to implement the same in node.js

**Comment by njoyard** [comment]
Just use `ffmpeg('inputfile.avi').save('image-%07d.png');`. ffmpeg will guess the rest, I think, or maybe you will have to add `.toFormat('image2')`. Don't forget to add event handlers (esp. for errors).

**Comment by vamsi0391** [comment]
thankyou, i will apply this



Thanks and Regards,
Vamsi Perivilli.
