### ISSUE TITLE
xmp capabilities?

### ISSUE THREAD

**Issue by rohanrehman** [fluent-ffmpeg/node-fluent-ffmpeg#484]
anyway to retrieve and write xmp tags in the metadata?
I 've tested with few video files that have embedded XMP metadata, yet the xmp tag is not showing up.

**Comment by njoyard** [comment]
Hi,
This is an ffprobe question (fluent-ffmpeg just runs ffprobe/ffmpeg), please seek help from the ffmpeg community :)

**Comment by rohanrehman** [comment]
there is no potion to send the flag to ffprobe with your module. in ffprobe.js .
```javascript
      // Spawn ffprobe
      var ffprobe = spawn(path, [
        '-show_streams',
        '-show_format',
       '-export_xmp',
         '1',
        input.source
      ]);
```
adding "-export_xmp 1" flag is what tells ffprobe to include xmp key into the format node. but it seems that the xmp key is parsed incorrectly.
