### ISSUE TITLE
Hi I have a question

### ISSUE THREAD

**Issue by pipecivil** [fluent-ffmpeg/node-fluent-ffmpeg#500]
node-fluent-ffmpeg, can input video0 to streaming  web page no latancy?

**Comment by njoyard** [comment]
You will have latency, that's unavoidable. However the latency you get may be small enough to be acceptable. Depends on what you want to do with it.

**Comment by pipecivil** [comment]
thank you for your replay
I want to know, how about latancy  time, about 
under 100ms ?

**Comment by njoyard** [comment]
I have no idea, it depends on too many factors. Try and see !

**Comment by pipecivil** [comment]
Okay thank you I will try 
have a nice day
