### ISSUE TITLE
Missing progress.percent

### ISSUE THREAD

**Issue by positlabs** [fluent-ffmpeg/node-fluent-ffmpeg#501]
This was working before I upgraded to ffmpeg v2.8.6.

```
ffmpeg()
.input(filePath) // video
.input(palettePath) // png
.outputOptions([ filterOptions ]) // paletteuse, scale
.on('progress', progress => {
	console.log('progress', progress);
})
```

All of the other progress fields are still there. 

`progress Object {frames: 108, currentFps: 72, currentKbps: 201.5, targetSize: 221, timemark: "00:00:09.00"}`

From the docs...
> percentage is not available when using an input stream

Which I'm not doing. I'm using a local video file as the first input.

> percentage may be wrong when using multiple inputs with different durations and the first one is not the longest. 

This may be the issue, but I'm not sure. I have a video input and a png input. However, the problem is that progress.percent is completely missing, not that it's incorrect.

**Comment by njoyard** [comment]
Progress percent may be missing when fluent-ffmpeg fails to extract input duration. Can you paste what ffprobe outputs when running on your video input ?

**Comment by positlabs** [comment]
Aha! I was completely missing the ffprobe binary :)

Thanks for your help!
