### ISSUE TITLE
How to pass x264opts?

### ISSUE THREAD

**Issue by valentinmanthei** [fluent-ffmpeg/node-fluent-ffmpeg#506]
I try to add the -x264opts 'keyint=24:min-keyint=24:no-scenecut' parameter
to ffmpeg like this but it didn't work:

ffcommand.addOutputOption('-x264opts "keyint=24:min-keyint=24:no-scenecut"');

The process fails with a bitrate/size error. However, if I paste the
generated ffmpeg command on the console it works fine. I think there's some
issue with the quotation marks. Do you know how to pass these options
correctly?

Best regards,
Valentin

**Comment by njoyard** [comment]
Hey,

You're quoting arguments where there's no need to. I think the following should work:

```js
ffcommand.addOutputOption('-x264opts keyint=24:min-keyint=24:no-scenecut');
```

When copying the command line to the console you're actually quoting args *for the shell*. Ffmpeg receives what's *inside* the quotes. And if you look at ffmpeg stdout/stderr (passed as arguments to the 'error' and 'end') event handlers, you'll probably see it complain about that.

**Comment by valentinmanthei** [comment]
Indeed, that did the trick. Thanks.
