### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by bsonntag** [fluent-ffmpeg/node-fluent-ffmpeg#507]
On npm, fluent-ffmpeg's latest version (2.0.1) was published **10 months ago**.

A lot of fixes have been pushed to the `master` branch in the meanwhile, but not released to npm.
This made me add this to my project's package.json:

```
"fluent-ffmpeg": "git://github.com/fluent-ffmpeg/node-fluent-ffmpeg.git#master"
```

**Comment by njoyard** [comment]
Hi,
There is still documentation and tests missing on some changes, and I'd like to clear some pending PRs before releasing (I don't have much time to dedicate to node-fluent-ffmpeg as you probably guessed).

In the meantime the way you're referencing the package is the correct way to do it. You may even reference a specific commit if you want to stick to a specific version. There's nothing wrong doing it this way, it's just a bit more verbose.

**Comment by njoyard** [comment]
I'll probably release 2.1.0 next week.

**Comment by stephenwithav** [comment]
Will the new release support ffmpeg 3.0?

**Comment by njoyard** [comment]
@stephenwithav ffmpeg 3.0 is already supported. There's nothing breaking compatibility on a command-line level in this version. Feel free to report any bugs you should find, though.

**Comment by njoyard** [comment]
Version 2.1.0 was just released. Sorry for the delay, it's sometimes difficult to find free time for fluent-ffmpeg :)
