### ISSUE TITLE
extract SDP from RTP output?

### ISSUE THREAD

**Issue by mojibaked** [fluent-ffmpeg/node-fluent-ffmpeg#510]
Is there an easy way of getting the SDP info when generating a RTP-stream from fluent-ffmpeg?
The codecData event doesn't contain this information.
I've tried `.output('rtp://255.1.1.1:12345 > session.sdp')`, which translates to `ffmpeg -re -i video.mp4 -vcodec copy -an -f rtp rtp://225.1.1.1:12345 > session.sdp`. But no SDP file is created when used from node.

For example:
```
ffmpeg('video.mp4')
            .on('start', cmd => console.log(cmd))
            .native()
            .videoCodec('copy')
            .noAudio()
            .outputOptions(['-f rtp'])
            .output('rtp://225.1.1.1:12345')
```
Translates to `ffmpeg -re -i video.mp4 -vcodec copy -an -f rtp rtp://225.1.1.1:12345`

What i need:
```
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 225.1.1.1
t=0 0
a=tool:libavformat 57.19.100
m=video 12345 RTP/AVP 96
b=AS:1464
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAKKzZQHgCJ+XARAAAD6QAA6mAPGDGWA==,aOvssiw=; profile-level-id=640028
```

**Comment by njoyard** [comment]
Hi,

First `.output('rtp://255.1.1.1:12345 > session.sdp')` is obviously incorrect as ffmpeg expects a filename or an URL as an output and this is neither.

I see the following options :
* You may want to use #467 that emits an event when ffmpeg outputs something.
* You could hook the process stdout/stderr data events (once the 'start' event is emitted, the ffmpegProc property on the command object is a reference to the ffmpeg process object), but that may break eventually as it is not part of the official API.
* You could start a command and kill it 1 second later, that way you would get ffmpeg output in the 'error' event handler, and restart the command for real.

Or you could submit a PR that emits an 'sdp' event :)

**Comment by mojibaked** [comment]
Thanks for your reply.

I should take another shot at this soon, but your last suggestion does work in my case.
```
var sdp = undefined;
var createStream = () => {
    var command = ffmpeg()
            .on('start', cmd => sdp ? console.log(cmd) : setTimeout(() => {
                 command.kill();
                 createStream();
             }, 250))
            .on('error', (data, stdout, stderr) => sdp = stdout)
            .stuff()
}
createStream();
```
This runs the command twice, storing SDP in the sdp variable first and aborts, then executing normally.
