### ISSUE TITLE
ffmpeg exited with code 1, when trying to compress video

### ISSUE THREAD

**Issue by kmansoor** [fluent-ffmpeg/node-fluent-ffmpeg#516]
Hello All,

I'm pretty sure doing something real dumb. Any pointers will be greatly appreciated.

Essentially, I'm trying to come up with a command similar to the following:
`ffmpeg -i Django.mp4 -codec:v libx264 -profile:v high -preset slow -b:v 500k -maxrate 500k -bufsize 1000k -vf scale=-1:480 -threads 0 -codec:a libfdk_aac -b:a 128k output_file.mp4`

This is what I tried:

`
   
    var outStream = fs.createWriteStream(path.resolve(__dirname, req.user.id + '.cmp.mp4'));
    var command = ffmpeg(path.resolve(__dirname, '../../' + req.file.path), logger)
      .audioCodec('libfdk_aac')
      .audioBitrate(128)
      .videoCodec('libx264')
      .videoBitrate(500)
      .size('640x480')
      //.duration('1:30')
      .format('mp4')
      .on('start', function(commandLine) {
        console.log('Running ffmpeg with command: ' + commandLine);
      })
      .on('codecData', function(data) {
        console.log('Input is ' + data.audio + ' audio ' + 'with ' + data.video + ' video');
      })
      .on('progress', function(progress) {
        console.log('Processing: ' + progress.percent + '% done');
      })
      .on('error', function(err, stdout, stderr) {
        console.log('Error while Processing video: ' + err.message);
      })
      .on('end', function() {
        console.log('Transcoding succeeded!');
      })
      .output(outStream).run();
`

This results in the following error:

`ffmpeg exited with code 1`

**Update**
If stream is changed to file then this works fine

**Comment by njoyard** [comment]
Have a look at stdout/sterr in the 'error' handler for more info. BTW, why are you using a stream if you're writing to a file ?

**Comment by kmansoor** [comment]
Will take a look as you suggested, but to answer your question, the compressed video is supposed to be written to Amazon S3.

**Comment by kmansoor** [comment]
I found the solution [#346](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/346)

Thank you.
