### ISSUE TITLE
RTMP_ReadPacket, failed to read RTMP packet header

### ISSUE THREAD

**Issue by codercurtis** [fluent-ffmpeg/node-fluent-ffmpeg#520]
This command works if I run it locally:
`ffmpeg -re -i C:\Users\Grant\Desktop\Projects\msi\mml-e2e/testVideos/testVideo.mp4 -ar 11025 -f flv rtmp://MyFMSWorkspace:1935/osc-simple-ingest/cumin/mp4:cumin_%v`

However this code:

```
		private sendStream:(options: http.RequestOptions, data?: any) => Q.IPromise<string> = (options: http.RequestOptions, data?: any): Q.IPromise<string> => {
			var deferred: Q.Deferred<string> = Q.defer<string>();
			this.ffmpegCommand = ffmpeg();
			this.ffmpegCommand.input(__dirname + '/testVideos/testVideo.mp4');
			this.ffmpegCommand.inputOptions('-re');
			this.ffmpegCommand.outputOptions(['-ar 11025', '-f flv']);
			this.ffmpegCommand.output(config.stream);
			
			this.ffmpegCommand.on('start', (command: string): void => {
				console.log('command is ',command);
			});
			
			this.ffmpegCommand.on('error', (err: Error, stdout: string ,stderr : string): void => {
				console.log(err);
				console.log(stdout);
				console.log(stderr);
				
				deferred.reject(err);
			});
			
			this.ffmpegCommand.on('progress', () : void => {
				console.log('stream in progress');
				deferred.resolve('k');
			});
			
			this.ffmpegCommand.run();
			
			return deferred.promise;
		};
```

produces this error:

```
ffmpeg version N-78335-g9ee4c89 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.100 / 55. 17.100
  libavcodec     57. 24.101 / 57. 24.101
  libavformat    57. 24.101 / 57. 24.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 29.100 /  6. 29.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Grant\Desktop\Projects\msi\mml-e2e/testVideos/testVideo.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01 00:00:00
    encoder         : Lavf53.24.2
  Duration: 00:01:02.32, start: 0.000000, bitrate: 1347 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 959 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 383 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : SoundHandler
RTMP_ReadPacket, failed to read RTMP packet header
rtmp://MyFMSWorkspace:1935/osc-simple-ingest/cumin/mp4:cumin_%v: Unknown error occurred

```

**Comment by njoyard** [comment]
What does your 'start' handler output ?

**Comment by codercurtis** [comment]
@njoyard  the start handler outputs

**Comment by codercurtis** [comment]
@njoyard  the start handler outputs 
```ffmpeg -re -i C:\Users\Grant\Desktop\Projects\msi\mml-e2e/testVideos/testVideo.mp4 -ar 11025 -f flv rtmp://MyFMSWorkspace:1935/osc-simple-ingest/cumin/mp4:cumin_%v```

**Comment by njoyard** [comment]
Which is... the same that the one working on command line.
I'm wondering if there isn't an escaping issue. Could you try to generate your input path properly with path.join(...) and see where that leads ?

**Comment by codercurtis** [comment]
Replacing this line: `this.ffmpegCommand.input(__dirname + '/testVideos/testVideo.mp4');`

with this line:  `this.ffmpegCommand.input(path.join(__dirname, '/testVideos/testVideo.mp4'));`

  makes my new command:
`ffmpeg -re -i C:\Users\Grant\Desktop\Projects\msi\mml-e2e\testVideos\testVideo.mp4 -ar 11025 -f flv rtmp://MyFMSWorkspace:1935/osc-simple-ingest/cumin/mp4:cumin_%v`

Which still locally, but still produces the same error

**Comment by codercurtis** [comment]
The problem was with my RTMP server rejecting the stream. Nothing wrong with this. Great work, by the way.

**Comment by njoyard** [comment]
Thanks, and glad you found a solution!

**Comment by ehouse322** [comment]
Just wondering, I am having a similar issue. What was your RTMP server doing that caused it to reject the stream?

**Comment by hanxinle** [comment]
> Just wondering, I am having a similar issue. What was your RTMP server doing that caused it to reject the stream?
I solved it. I guess bacause a : in his url.
rtmp url should follow rtmp://<TcUrl>/stream_name, like rtmp://255.255.255.255/live/livetream is OK.

**Comment by hanxinle** [comment]
> Just wondering, I am having a similar issue. What was your RTMP server doing that caused it to reject the stream?

I solved it. I guess bacause a : in his url.
rtmp url should follow rtmp:///stream_name, like rtmp://255.255.255.255/live/livetream is OK.

**Comment by hanxinle** [comment]
> Just wondering, I am having a similar issue. What was your RTMP server doing that caused it to reject the stream?

I guess bacause a : in his url.
rtmp publish url should be like rtmp://stream_name. So rtmp://255.255.255.255/live/livetream is OK.
rtmp://255.255.255.255/live is the TcUrl. livestream is stream name.
