### ISSUE TITLE
Use newer codec parameter syntax

### ISSUE THREAD

**Issue by domosapien** [fluent-ffmpeg/node-fluent-ffmpeg#521]
Newer versions of FFmpeg supports `vcodec` as an alias for `codec:v` (or simply `c:v`), but the latter are much more powerful as they allow for using stream specifiers (http://ffmpeg.org/ffmpeg-all.html#Stream-specifiers). Please consider updating the codec parameters to use the new format.

**Comment by njoyard** [comment]
Yup, I know of c:a/c:v, but they're useless for now as we have no way of specifying stream-specific output yet. I'll be happy to review a PR, though ;)
