### ISSUE TITLE
libopus not available, and ffprobe nodejs error

### ISSUE THREAD

**Issue by RamyElkest** [fluent-ffmpeg/node-fluent-ffmpeg#522]
Hi,
2 issues, (probably my fault but would appreciate help :+1: )
I'm using avconv and avprobe (on meteor if it makes a difference)

**1:** I get a <code>[Error: Audio codec libopus is not available]</code>
when I
<pre>
 ffmpeg(fileName)
   .format('ogg')
   .audioCodec('libopus')
   .audioQuality(0)
   .on('error', (err) => console.error(err))
   .on('end', () => console.log('Finished!'))
 .save('/tmp/av-out.ogg');
</pre>
although <code>ffmpeg.getAvailableCodecs()</code> shows
<pre>
opus: 
  { type: 'audio',
    description: 'Opus (Opus Interactive Audio Codec) (decoders: libopus ) (encoders: libopus )',
    canDecode: true,
    canEncode: true,
    intraFrameOnly: false,
    isLossy: true,
    isLossless: false },
 libopus: 
  { type: 'audio',
    description: 'Opus (Opus Interactive Audio Codec) (decoders: libopus ) (encoders: libopus )',
    intraFrameOnly: false,
    isLossy: true,
    isLossless: false,
    canEncode: true,
    canDecode: true },
</pre>
also 
<pre>
$ avconv -codecs | grep opus
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
DEA.L. opus                 Opus (Opus Interactive Audio Codec) (decoders: libopus ) (encoders: libopus )
</pre>
tried with opus and libopus, running the command manually works
<pre>avconv -i input.mp3 -acodec libopus -vbr on output.ogg</pre>

**2:**
<pre>
~/node_modules/core-js/modules/$.defined.js:3
  if(it == undefined)throw TypeError("Can't call method on  " + it);
                           ^
TypeError: Can't call method on  undefined
    at TypeError (<anonymous>)
    at module.exports (~/node_modules/core-js/modules/$.defined.js:3:28)
    at module.exports (~/node_modules/core-js/modules/$.to-object.js:4:17)
    at Function.keys (~/node_modules/core-js/modules/es6.object.keys.js:6:18)
    at ~/node_modules/fluent-ffmpeg/lib/ffprobe.js:153:40
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at handleExit (~/node_modules/fluent-ffmpeg/lib/ffprobe.js:152:46)
    at ChildProcess.<anonymous> (~/node_modules/fluent-ffmpeg/lib/ffprobe.js:190:11)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
</pre>
when i try to
<pre>ffmpeg(fileName)
 .ffprobe(function(err, metadata) {
     console.dir(err, metadata);
 });</pre>

logging data at ffprobe.js:153 shows <code>{ streams: [ ] }</code>
again, avprobing from cli is alright.

any help would be appreciated, Thanks

**Comment by njoyard** [comment]
Are you setting ffmpeg/ffprobe paths to point to avconv/avprobe ? This is definitely *not supported* in fluend-ffmpeg. They don't have the same CLI as ffmpeg/ffprobe.

Please use the "real" ffmpeg or the mimics that normally come with avconv, those are mostly working.

**Comment by RamyElkest** [comment]
Ah nice one,  Thanks for the info @njoyard, when I switched to ffmpeg it did indeed solve both issues.
