### ISSUE TITLE
Test case for URL is not for a URL

### ISSUE THREAD

**Issue by scaryguy** [fluent-ffmpeg/node-fluent-ffmpeg#524]
See:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/058d5b19d5e0a5e3667ffcbfbbcb7a781803ebdc/test/processor.test.js#L974

`it` block claims it's testing `input from an URL` condition, however, it's testing a file path case.
```javascript
var testFile = path.join(__dirname, 'assets', 'testURLInput.avi');
```

Am I wrong?

**Comment by njoyard** [comment]
Yep, you're wrong :)
This is the expected output file for the test. The input is specified here: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/058d5b19d5e0a5e3667ffcbfbbcb7a781803ebdc/test/processor.test.js#L978 and the variable used here: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/058d5b19d5e0a5e3667ffcbfbbcb7a781803ebdc/test/processor.test.js#L17

**Comment by scaryguy** [comment]
Oh okay, sorry :)
