### ISSUE TITLE
codecData doesn't fire on piped inputs

### ISSUE THREAD

**Issue by jdp** [fluent-ffmpeg/node-fluent-ffmpeg#526]
The `codecData` event doesn't fire on piped inputs because ffmpeg doesn't emit the "Press [q] to stop, [?] for help" message when the inputs are piped in, and [that's the message being used as a sentinel](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/utils.js#L298). Maybe the sentinel should be the stream mapping section?

**Comment by njoyard** [comment]
Good idea, please submit a PR ;)

**Comment by jdp** [comment]
Done and done https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/527

**Comment by njoyard** [comment]
Oh, my bad !
