### ISSUE TITLE
Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by vatex** [fluent-ffmpeg/node-fluent-ffmpeg#531]
Node.js >> This is my code but when I'm running, it fails... 

var ffmpeg = require('fluent-ffmpeg');

ffmpeg('path/to/file.mp3')
            .audioCodec('libfaac')
            .format('wav')
            .save('path/to/file.wav');

I want to convert MP3 to WAV. this is error >>

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /home/valeri/username/server/node_modules/fluent-ffmpeg/lib/processor.js:119:22
    at /home/valeri/username/server/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /home/valeri/username/server/node_modules/async/lib/async.js:49:16
    at /home/valeri/username/server/node_modules/async/lib/async.js:1165:30
    at /home/valeri/username/server/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/valeri/username/server/node_modules/fluent-ffmpeg/lib/utils.js:227:9
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)

**Comment by vatex** [comment]
Now I install ffmpeg on my ubuntu and now throws other error :D
Error: Audio codec libfaac is not available

**Comment by Buzut** [comment]
How is your script started? Which user? Does it start through a cron?

**Comment by vatex** [comment]
No, it's started manually. I installed ffmpeg on my ubuntu and it works. :)

**Comment by vatex** [comment]
mark it as resolved

**Comment by Buzut** [comment]
If the user you start your node script with has access to ffmpeg. There should be no problem. 
You can try this with typing `ffmpeg` or `whereis ffmpeg`. 

Often, if script is started via cron, $PATH in cleared. So you might manually set it, for instance:
`PATH="/usr/local/bin:/usr/bin:/bin"`
