### ISSUE TITLE
Cannot read property 'on' of undefined in "ffmpegProc.stdout.on"

### ISSUE THREAD

**Issue by Buzut** [fluent-ffmpeg/node-fluent-ffmpeg#533]
Hi!

I often end up with this error while trying to encode audio files:

     /home/encoder/node_modules/fluent-ffmpeg/lib/processor.js:493
                ffmpegProc.stdout.on('data', function (data) {
                                 ^

    TypeError: Cannot read property 'on' of undefined
        at processCB (/home/encoder/node_modules/fluent-ffmpeg/lib/processor.js:493:30)
        at /home/encoder/node_modules/fluent-ffmpeg/lib/processor.js:203:7
        at FfmpegCommand.proto._getFfmpegPath (/home/encoder/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
        at FfmpegCommand.proto._spawnFfmpeg (/home/encoder/node_modules/fluent-ffmpeg/lib/processor.js:116:10)
        at /home/encoder/node_modules/fluent-ffmpeg/lib/processor.js:429:12
        at /home/encoder/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:52:16
        at Immediate._onImmediate (/home/encoder/node_modules/fluent-ffmpeg/node_modules/async/lib/async.js:1206:34)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

As it might help, it's for mp3 encoding. Here's the code:

    function encodeAudio(mediaToEncodePath, mediaEncodedPath) {
        var ffmpegCmd = ffmpeg(mediaToEncodePath);
        var ffmpegOpts = ['-ac 2', '-map 0:a', '-map_metadata -1', '-threads 0'];

        ffmpegCmd
        .audioCodec('libmp3lame')
        .audioQuality(1)
        .outputOptions(ffmpegOpts)
        .on('error', function(err) {
            console.error('FFMPEG audio error ' + err.message);
        })
        .on('end', function() {
            […]
        })
        .save(mediaEncodedPath);
    }

I don't know if it can have an incidence, but it might be relevent to point out that this function is often called several times in parallel.

**Comment by njoyard** [comment]
This is really weird, I'll try to investigate a bit. Can you tell me your nodejs version, and whether the paths you use are actual physical paths ?

**Comment by Buzut** [comment]
I'm sorry I took so long to answer. I was investigating on my side too. It finally appears that I was launching too many instances of the function in parallel and ended reaching my system stack size limit! Thus, ending with undefined variables and errors.

**Comment by LevitatingBusinessMan** [comment]
I am getting the same error in [this](https://github.com/LevitatingBusinessMan/yt_mp3) project of mine. But only on _one_ of my linux machines... @Buzut explained that by launching too many parallel instances he was reaching his system stack limit, can you please elaborate? By default my program opens multiple ffmpeg instances but it can be configured to only open one, but the error stays.
