### ISSUE TITLE
Extract Frames, Apply Filter, Merge Frames

### ISSUE THREAD

**Issue by amolpatel** [fluent-ffmpeg/node-fluent-ffmpeg#534]
What is the best way to approach first splitting a video into frames, applying a certain filter, and then rejoining the frames into a new video? I have been having a lot of trouble approaching this task. Any help would be greatly appreciated.

**Comment by njoyard** [comment]
What is the filter you need to apply on frames ? ffmpeg has a lot of built-in filters, if some of them can achieve what you want then it'll be a simple command :)

**Comment by amolpatel** [comment]
Grayscale and a few other text layovers. However, this needs to run on a server so that’s why I chose fluent-ffmpeg. I am having trouble being able to take in several frames or video, apply some sort of filter, and then recompile the frames and allow the user to download the video.

**Comment by njoyard** [comment]
You can definitely do that with a single command. Try to achieve it on the command line and then if you need help converting it to a fluent-ffmpeg call, come back here :)

Some pointers :
* colorchannelmixer filter, grayscale example : https://ffmpeg.org/ffmpeg-filters.html#Examples-36
* drawtext filter : https://ffmpeg.org/ffmpeg-filters.html#drawtext-1

**Comment by njoyard** [comment]
Oh for grayscale you're probably better off using the eq filter to set saturation to 0.

**Comment by amolpatel** [comment]
I've figured out how to do it on the command line just been having trouble converting it to fluent-ffmpeg

**Comment by njoyard** [comment]
What is your command, your code, and the issues you're having ?

**Comment by amolpatel** [comment]
`ffmpeg -i input.mp4 -vf fps=1 out%d.png`
This line outputs one frame every second.

`ffmpeg -f image2 -framerate 12 -i out%d.jpeg -s WxH newVideo.mp4`
This line merges all of the frames and outputs the video. 

I cannot figure out how to do this within fluent-ffmpeg.

**Comment by njoyard** [comment]
The second one cannot be done currently, I think. You should really use filters with a single command, though :)
