### ISSUE TITLE
Event Emitter for SIGKILL

### ISSUE THREAD

**Issue by crosofg** [fluent-ffmpeg/node-fluent-ffmpeg#537]
I want to receive a callback when the ffmpeg process is killed through command.kill('SIGKILL').

What has to be changed and where so that on('end') get called?

**Comment by njoyard** [comment]
You can use on('error'). The error message will be "ffmpeg was killed with signal 9".

**Comment by crosofg** [comment]
That's the way around to do it. Cant this be implemented in the on('end')

**Comment by njoyard** [comment]
No, on('end') is only called when ffmpeg terminates by itself and without error.

**Comment by crosofg** [comment]
okay

**Comment by Ranjeetvit453** [comment]
## Server Configuration
- **Instance:** `t2.2xlarge`
- **vCPUs:** 8
- **Memory:** 32 GB

If you're deploying an application on EC2 using this instance, ensure that you configure resources and optimize `ffmpeg` usage to leverage the available hardware. Make sure ffmpeg is tuned for multi-threading to fully utilize the 8 vCPUs and ensure that the instance's 32 GB memory is effectively managed during video processing.

For more details on ffmpeg video conversion, refer to the repository below:

### Related GitHub Repository:
[h264-video-conversion-ffmpeg](https://github.com/ranjeetvit2012/h264-video-conversion-ffmpeg/blob/master/README.md)
