### ISSUE TITLE
Windows PATH environment variable format

### ISSUE THREAD

**Issue by ninox92** [fluent-ffmpeg/node-fluent-ffmpeg#540]
Using the following FFMPEG_PATH variable I received a ENOENT error:
C:\ffmpeg\bin\ffmpeg.exe

Escaping the '\' slashed fixed this.
C:\\ffmpeg\\bin\\ffmpeg.exe

**Comment by njoyard** [comment]
Hello,
This is not related to fluent-ffmpeg. You must escape backslashes in JS strings.

**Comment by ninox92** [comment]
Im using the Windows environment variable. Its not common to escape the backslashes in Windows.
I'm suggesting something like the following in lib/capabilities.js proto._getFfmpegPath or an example in the Readme?
`
var os = require('os');
if (os.platform() === 'win32') {
  var path = process.env.FFMPEG_PATH;
  path = path.replace('\', '\\');
}
`

**Comment by njoyard** [comment]
This will not work (you don't have any '\' chars in your variable, you have '\f' and '\b' characters instead).
All paths must have escaped backslashes on windows. Or you can use path.join. This is not fluent-ffmpeg responsibility :)
