### ISSUE TITLE
Question : How to loop an audio till a certain duration

### ISSUE THREAD

**Issue by sbsomya** [fluent-ffmpeg/node-fluent-ffmpeg#544]
How to loop an audio till a certain duration

**Comment by njoyard** [comment]
Hello,
Please read the [ffmpeg documentation](https://ffmpeg.org/documentation.html) and the [fluent-ffmpeg documentation](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#fluent-ffmpeg-api-for-nodejs-).

**Comment by swampthang** [comment]
I updated your awesome library today and now my loop audio setup is breaking in Windows. This is an Electron app. 

I snagged the latest FFMPEG and FFPROBE static binaries from [here](http://evermeet.cx/ffmpeg/). Does work in Mac. It actually broke in Mac until I ran a rebuild. Rebuilding in Windows didn't fix it.

First of all, the way the FFMPEG docs tell you to loop audio is the way I'm doing it below. I tried using...
```
ffmpeg({}).loop(1.22)
          .addInput(filepath)
```
But it errors saying the input is undefined. 

Here's what works and has been working in Mac:
```
function createCompositeAudio(data) {

// variables declared above

  if ( numLoops > 0 ) {
    inputStr = `amovie=${data.filepath}:loop=${data.numLoops}`;
  } else {
    inputStr = data.filepath;
  }

  var proc = new ffmpeg();

  // I do have some other callbacks that log some stuff in progress, etc but removed them here

  proc.addInput(inputStr)
  .on('error', function(error) {
      /// error handling
      console.log('error: ',error);
  })
  .addInputOption('-f lavfi')
  .addOutputOption('-y')
  .output(`${tempFolder}temp.wav`)
  .run();
}
```
In windows, first thing it complains about is the inputStr (var from the script above). Here's the log/error ouput (replaced user name with 'usr'):
```
----- inputStr:  amovie=C:\Users\usr\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav:loop=2
C:\Users\usr\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:131 error:  Error: ffmpeg exited with code 1: amovie=C:\Users\usr\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav:loop=2: No such file or directory
    at ChildProcess.<anonymous> (C:\Users\usr\Documents\kinetic-text-animator\build\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
So, I removed the loop and just put the input file to see what would happen and it complained about the lavfi filter...
```
error:  Error: ffmpeg exited with code 1: C:\Users\usr\AppData\Roaming\kinetictextanimator\audio\fun\BigFunLoop.wav: Invalid argument

    at ChildProcess.<anonymous> (C:\Users\usr\Documents\kinetic-text-animator\build\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
C:\Users\usr\Documents\kinetic-text-animator\build\modules\svg-animate\audio-manager.js:132
Uncaught ReferenceError: stddout is not defined
```
Any help you can give on this is greatly appreciated. Thanks again for this awesome npm wrapper for FFMPEG!

**Comment by swampthang** [comment]
I'm just now thinking you might not see this since it's closed. Will move to a new issue.
