### ISSUE TITLE
Main Options

### ISSUE THREAD

**Issue by oldwisenir** [fluent-ffmpeg/node-fluent-ffmpeg#547]
hey i couldnt find any support of using advanced [options()](https://ffmpeg.org/ffmpeg.html#toc-Advanced-options)
such as <-map> options
does fluent ffmpeg suports this??

**Comment by FallingSnow** [comment]
Use [outputOptions](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputoptionsoption-add-custom-output-options).

**Comment by oldwisenir** [comment]
Thanks it works
