### ISSUE TITLE
Is it possible to tail an input video file ?

### ISSUE THREAD

**Issue by nionis** [fluent-ffmpeg/node-fluent-ffmpeg#551]
--> createTailStream -> transcode -> pipe out
or
--> pipe in -> transcode -> pipe out

**Comment by nionis** [comment]
video is being recorded --> ffmpeg waits for new data from the video --> transcodes new data --> pipe out new data
ffmpeg shouldnt consider the video 'completed' if it is at the end of the video, instead wait for the new data that is being recorded to the video.

basically something like this https://github.com/jasontbradshaw/tailing-stream , I tried to use it with fluent but it doesnt seem to work, so I am wondering if you guys know a way to do it.

**Comment by njoyard** [comment]
I don't know of a way of doing this with files (it may be possible though, maybe have a look through the ffmpeg documentation). However I think it should work with tailing-stream. Can you post your code and the output ?

**Comment by nionis** [comment]
Hey thanks for getting back!

```javascript
new ffmpeg(tailStream.createReadStream(info.convertDir, { timeout : 20000 }))
	.outputOptions([ '-threads 12',
     '-acodec aac',
     '-vcodec libx264',
     '-f mp4',
     '-preset ultrafast',
     '-reset_timestamps 1',
     '-movflags empty_moov+default_base_moof+frag_keyframe' ] )
	.format('mp4')
	.on('progress', (i) => {
		console.log('progress ' + Math.floor(i.percent) + '%');
		}
	})
	.on('end', () => {
		console.log('done processing input stream');
	})
	.on('error', (err) => {
		console.log('an error happened: ' + err.message);
	})
	.pipe(stream, { end: true });
```

==========
Output:
an error happened: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input

=========
Pipe: 0 should be associated with tailStream.createReadStream and not the output pipe, as far as I know

**Comment by njoyard** [comment]
Yeah, the output pipe is pipe:1.

The 'error' event gets two more arguments (stdout and stderr from ffmpeg), could you add them to your handler and paste what their content is please ?

Also beware that using streams both for input and output may deadlock eventually due to nodejs streams implementation.

**Comment by nionis** [comment]
Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input

    at ChildProcess.<anonymous> (/home/tests/bridge/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

ffmpeg version N-80026-g936751b Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 42.100 / 57. 42.100
  libavformat    57. 36.100 / 57. 36.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 45.100 /  6. 45.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
pipe:0: Invalid data found when processing input

**Comment by njoyard** [comment]
Hmmm I wonder if there isn't a simple sync issue. Like a partial frame written to the stream that ffmpeg reads before it is complete. If it is the case, then you don't have an easy solution AFAIK. You'd have to decode the MP4 stream to ensure only complete frames (or whatever data blocks MP4 uses) are passed through the stream... which is not easy :)

Or maybe there's an ffmpeg or MP4 option that says "if you have an incomplete frame don't complain and just wait for more data" ? Maybe have a look at the ffmpeg doc or ask the ffmpeg community about that.

BTW, where does your stream come from ? If that's from a streaming URL or a capture device, you may be better off using it directly as ffmpeg input (in this case it will behave correctly I think/hope...)

**Comment by nionis** [comment]
setup was like this
```javascript
getusermedia -> mediaRecorder -> node write stream -> file -> tailing file -> pipe:0 -> ffmpeg -> pipe:1
```

Spawning ffmpeg process and using command like "-i pipe:0 ... pipe:1", and then feeding it directly with ffmpeg.stdin.write(buffer); does the job (also skips the file part), I am wondering if there is a way to do it in fluent-ffmpeg ?

FYI: I am trying to setup real time communication with mediasource and websockets, and its a pain

**Comment by njoyard** [comment]
I wonder, why are you creating the file in the first place ?
Why not do this directly:
```
getusermedia -> mediaRecorder -> passthrough stream -> pipe:0 -> ffmpeg -> pipe:1
```

**Comment by nionis** [comment]
Writing it to a file could be useful in my scenario, however I can do both by using your method suggested, thanks

**Comment by njoyard** [comment]
I'm closing this, feel free to reopen if you still have issues ;)
