### ISSUE TITLE
Is there a way to forcefully end the ffmpeg operation

### ISSUE THREAD

**Issue by sbsomya** [fluent-ffmpeg/node-fluent-ffmpeg#553]
Want to do a CTRL + C operation on the ffmpeg process
Actually want to do a screen capture and stop when required 
If i do command.kill("SIGSTOP")
It does not saves the video

**Comment by njoyard** [comment]
SIGSTOP doesn't end the process, it stops (suspends) it. You want to use SIGTERM or SIGINT instead. But in any case, if you kill the process before it had time to write files, you won't get any results.

**Comment by sbsomya** [comment]
Thanks SIGTERM works :+1: :+1:
