### ISSUE TITLE
lavfi and anullsrc input

### ISSUE THREAD

**Issue by TomKaltz** [fluent-ffmpeg/node-fluent-ffmpeg#557]
How do I generate the following...

```ffmpeg -i inputfile.mp4 -f lavfi -i anullsrc=cl=1 -shortest -c:v libx264 -c:a aac output.mov```

**Comment by njoyard** [comment]
Please read the [documentation](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#fluent-ffmpeg-api-for-nodejs-) and come back here if there is something you can't find a solution for.

**Comment by mikebell90** [comment]
I read the docs and still can't do

//ffmpeg -f lavfi -i color=black:s=640x480:r=25 -an -t 10.00 empty.mp4

command
			.inputFormat('lavfi')
			.inputOption('color=black:s=640x480:r=25')
			.noAudio()
			.duration(duration)
			.output(outputFile.name);
		
fails with
Error: No input specified
    at FfmpegCommand.proto.withInputFormat.proto.inputFormat.proto.fromFormat (/Users/mike/git/transcoder/node_modules/fluent-ffmpeg/lib/options/inputs.js:77:13)

**Comment by mikebell90** [comment]
.input('color=black:s=640x480:r=25')
			.inputFormat('lavfi')
			
worked

**Comment by laggingreflex** [comment]
I'm still struggling with the same issue as OP (@TomKaltz) - how to specify `anullsrc` as input? I'm trying to add [a null audio source](https://ffmpeg.org/ffmpeg-filters.html#anullsrc) to an audio-less video stream. The docs say that input can only be either a filename, an image pattern, or a readable stream, so I've tried `.input('anullsrc')` but it doesn't generate/attaches a null audio to the output video. 

@mikebell90's issue *seems* different, although if he was able to put `.input('color=black:s=640x480:r=25')` which seems not to be either of the 3 formats specified in the docs then it *should* be able to work with `anullsrc` as well, right? Not sure why it isn't working. It might be I'm not using ffmpeg correctly, but just wanted to be sure whether the fluent-ffmpeg does indeed support this option in the input (i.e. `anullsrc` which is not one of the 3 types mentioned in the docs). Does it?

**Comment by FinnFrotscher** [comment]
how did you solve this? `anullsrc` is not accepted by `.input()`

**Comment by bobbigmac** [comment]
> 

`.input('anullsrc=channel_layout=mono:sample_rate=22050').inputFormat('lavfi').inputOptions(['-t', '3s']);`
