### ISSUE TITLE
Video duration trimming to incorrect time length

### ISSUE THREAD

**Issue by AaronLlanos** [fluent-ffmpeg/node-fluent-ffmpeg#558]
Hello, I have a video setup as the following: 

``` js
ffmpeg(path)
    .format('mp4')
    .size('?x500')
    .duration(10)
    .screenshots({
      timemarks: ['50%'],
      filename: name+'.png',
      folder: 'uploads',
      size: '?x700'
    })
    .on('error', function(err) {
      console.log('error', err.message);
    })
    .on('end', end)
    .save('uploads/'+name+'.mp4');
```

It seems as though if I upload a 10 second mp4 to my server and pass it through this function, I randomly get end up with videos between 5 - 8 seconds. Please let me know if I can give any more information that can help. My setup is: 

```
node: 6.0.0
host: heroku
"fluent-ffmpeg": "^2.1.0"
```

**Comment by njoyard** [comment]
I think the problem comes from ffmpeg. Can you try it from command line (using the command line reported by the 'start' event) and see if it behaves the same ?
