### ISSUE TITLE
merging still frames to a video

### ISSUE THREAD

**Issue by endquote** [fluent-ffmpeg/node-fluent-ffmpeg#561]
I have a bunch of bmp files that I'm trying to convert into a 30 fps video, one image per frame. This is what I'm trying...

```
ffmpeg('000000.bmp')
    .input('000001.bmp')
    .input('000002.bmp')
    .on('error', function(err) {
        console.log('An error occurred: ' + err.message);
    })
    .on('end', function() {
        console.log('Merging finished!');
    })
    .fps(30)
    .videoCodec('libx264')
    .mergeToFile('out.mp4', 'tmp');
```

This completes without error, but I can't play the output file in any players.

I'm on Windows 10, with the latest ffmpeg in my path variable. Thanks for any tips!

**Comment by endquote** [comment]
Also... is this creating a command line to ffmpeg.exe in the end? If so, is it going to fail when I have thousands of frames to process just because the command gets too long?

**Comment by njoyard** [comment]
Yes, this is the goal of fluent-ffmpeg. It will probably fail given Windows has stupildy low limitations on command line lengths. Use the %d notation in this case (see ffmpeg docs).

Also you don't want to use mergeToFile(). This is used to concatenate videos.

**Comment by endquote** [comment]
Thanks for the reply... this seemed to work for something that I could play in VLC.

```
ffmpeg('%06d.bmp')
    .save('out.mp4'));
```
