### ISSUE TITLE
Getting the ffmpeg command

### ISSUE THREAD

**Issue by endquote** [fluent-ffmpeg/node-fluent-ffmpeg#562]
Is there a way to see what command-line was generated and executed?

I see that the `end` event gets all the stdout from ffmpeg, which is helpful, but I'm not sure how to tell what went in.

This would be helpful in debugging.

**Comment by njoyard** [comment]
Yes : https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#start-ffmpeg-process-started

**Comment by endquote** [comment]
Ah, perfect. I was looking at pretty much every event except for that one!

**Comment by endquote** [comment]
FYI... there is no percent property on the progress object here:

```
  .on('progress', function(progress) {
    console.log('Processing: ' + progress.percent + '% done');
  });
```
