### ISSUE TITLE
Error when using on progress handler.

### ISSUE THREAD

**Issue by norbertsongin** [fluent-ffmpeg/node-fluent-ffmpeg#563]
I'm using following code to cut down .mp4 video:

``` javascript
let command = ffmpeg(videoFile)  
.setStartTime(startTime)  
.setDuration(endTime)  
.output(path.resolve(config.RECORDINGS_DIR, `cut-${videoName}`))
```

and it runs without any issues, cutting video and saving it on disk.

However when I add event handler for 'progress' event:

``` javascript
command.on('progress', (progress) => {
  console.log('progress', progress)
})
```

I'm getting following errors:

> Error: ffmpeg exited with code 1: Error opening filters!

and for ffmpeg stderr:

> [aac @ 00000000007299a0] Number of bands (14) exceeds limit (11).
> [aac @ 00000000007299a0] Reserved bit set.
> [aac @ 00000000007299a0] Number of bands (49) exceeds limit (27).
> [aac @ 00000000007299a0] channel element 2.3 is not allocated
> [aac @ 00000000007299a0] channel element 1.5 is not allocated
> [aac @ 00000000007299a0] channel element 3.1 is not allocated
> [aac @ 00000000007299a0] channel element 1.10 is not allocated
> [aac @ 00000000007299a0] channel element 3.11 is not allocated
> [aac @ 00000000007299a0] Number of bands (37) exceeds limit (10).
> [aac @ 00000000007299a0] channel element 2.15 is not allocated
> [aac @ 00000000007299a0] channel element 1.14 is not allocated
> [aac @ 00000000007299a0] channel element 3.2 is not allocated
> [aac @ 00000000007299a0] SBR was found before the first channel element.
> [aac @ 00000000007299a0] channel element 3.4 is not allocated
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Inconsistent channel configuration.
> [aac @ 00000000007299a0] get_buffer() failed
> [aac @ 00000000007299a0] channel element 2.0 is not allocated
> [aac @ 00000000007299a0] channel element 2.10 is not allocated
> [aac @ 00000000007299a0] invalid band type
> [aac @ 00000000007299a0] channel element 1.4 is not allocated
> [aac @ 00000000007299a0] Reserved bit set.
> [aac @ 00000000007299a0] invalid band type
> [aac @ 00000000007299a0] Reserved bit set.
> [aac @ 00000000007299a0] SSR is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
> [aac @ 00000000007299a0] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
> [aac @ 00000000007299a0] channel element 1.6 is not allocated
> [aac @ 00000000007299a0] channel element 3.1 is not allocated
> [aac @ 00000000007299a0] channel element 2.1 is not allocated
> [aac @ 00000000007299a0] Reserved bit set.
>     Last message repeated 1 times
> [aac @ 00000000007299a0] Number of bands (35) exceeds limit (17).
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Inconsistent channel configuration.
> [aac @ 00000000007299a0] get_buffer() failed
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Inconsistent channel configuration.
> [aac @ 00000000007299a0] get_buffer() failed
> [aac @ 00000000007299a0] Number of bands (19) exceeds limit (6).
> [aac @ 00000000007299a0] Dependent coupling is not supported together with LTP
>     Last message repeated 12 times
> [aac @ 00000000007299a0] invalid band type
> [aac @ 00000000007299a0] channel element 2.5 is not allocated
> [aac @ 00000000007299a0] channel element 1.14 is not allocated
>     Last message repeated 1 times
> [aac @ 00000000007299a0] channel element 1.4 is not allocated
> [aac @ 00000000007299a0] Number of bands (45) exceeds limit (27).
> [aac @ 00000000007299a0] Number of bands (12) exceeds limit (9).
> [aac @ 00000000007299a0] channel element 3.1 is not allocated
> [aac @ 00000000007299a0] channel element 3.10 is not allocated
> [aac @ 00000000007299a0] Reserved bit set.
> [aac @ 00000000007299a0] Number of bands (4) exceeds limit (1).
> [aac @ 00000000007299a0] Number of scalefactor bands in group (50) exceeds limit (40).
> [aac @ 00000000007299a0] Reserved bit set.
> [aac @ 00000000007299a0] Number of bands (49) exceeds limit (35).
> [aac @ 00000000007299a0] channel element 3.13 is not allocated
> [aac @ 00000000007299a0] channel element 2.10 is not allocated
> [aac @ 00000000007299a0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
> [aac @ 00000000007299a0] channel element 3.13 is not allocated
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] decode_pce: Input buffer exhausted before END element found
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Inconsistent channel configuration.
> [aac @ 00000000007299a0] get_buffer() failed
> [aac @ 00000000007299a0] channel element 1.0 is not allocated
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Remapped id too large
> [aac @ 00000000007299a0]  is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
> [aac @ 00000000007299a0] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
> [aac @ 00000000007299a0] channel element 2.14 is not allocated
> [aac @ 00000000007299a0] Prediction is not allowed in AAC-LC.
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Inconsistent channel configuration.
> [aac @ 00000000007299a0] get_buffer() failed
> [aac @ 00000000007299a0] Number of bands (7) exceeds limit (6).
> [aac @ 00000000007299a0] channel element 1.13 is not allocated
> [aac @ 00000000007299a0] channel element 2.10 is not allocated
> [aac @ 00000000007299a0] channel element 2.11 is not allocated
> [aac @ 00000000007299a0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
> [aac @ 00000000007299a0] channel element 2.2 is not allocated
> [aac @ 00000000007299a0] Sample rate index in program config element does not match the sample rate index configured by the container.
> [aac @ 00000000007299a0] Inconsistent channel configuration.
> [aac @ 00000000007299a0] get_buffer() failed
> [aac @ 00000000007299a0] channel element 2.12 is not allocated
> [aac @ 00000000007299a0] channel element 3.2 is not allocated
> [aac @ 00000000007299a0] Number of scalefactor bands in group (59) exceeds limit (51).
> [aac @ 00000000006124a0] decoding for stream 0 failed
> [aac @ 00000000006124a0] Could not find codec parameters for stream 0 (Audio: aac (SSR), 4.0, fltp, 343 kb/s): unspecified sample rate
> Consider increasing the value for the 'analyzeduration' and 'probesize' options
> pipe:0: could not seek to position 0.000
> Input #0, aac, from 'pipe:0':
>   Duration: N/A, bitrate: 343 kb/s
>     Stream #0:0: Audio: aac (SSR), 4.0, fltp, 343 kb/s
> [abuffer @ 000000000072bf60] Value inf for parameter 'time_base' out of range [0 - 2.14748e+009]
>     Last message repeated 3 times
> [abuffer @ 000000000072bf60] Error setting option time_base to value 1/0.
> [graph 0 input from stream 0:0 @ 000000000072cb40] Error applying options to the filter.
> Error opening filters!

This is really strange because once again, without 'progress' event handler there are no errors at all (and video is saved correctly).
Any thoughts ?

**Comment by njoyard** [comment]
This is weird indeed. Can you reproduce it with any input video, or only some of them ? If the latter, could you publish an example of failing video ?

**Comment by jleal52** [comment]
I have the same Issue. I've compiled the latest snapshot release from ffmpeg and downloaded latest fluent-ffmpeg (2.1.0)

I run the next code:
```
var url = 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';
http.get(url, (res) =>  {
        var command = ffmpeg(res)
                .audioCodec('libfdk_aac')
                .audioBitrate('128k')
                .videoCodec('libx264')
                .format('hls')
                .outputOptions([
                                     '-preset medium',
                                     '-profile:v baseline',
                                     '-level 3.0',
                                     '-pix_fmt yuv420p',
                                     '-hls_segment_filename big_bunny%05d.ts',
                                     '-hls_list_size 0',
                                     '-start_number 1'
                                ])
                .output('big_bunny.m3u8')
                .on('start',function(cmd) {
                      console.log(`Command Line: ${cmd}`);
                })
                .on('error', (err) => {
                        console.log(`FFMPEG ERROR ${err}`);
                })
                .on('progress', (progress) => {
                        console.log(progress);
                })
                .on('stderr', function(stderrLine) {
                    console.log(`Stderr output: ${stderrLine}`);
                })
                .run();
});
```
`

Then I get in the output:

> 
> Command Line: ffmpeg -i pipe:0 -y -acodec libfdk_aac -b:a 128k -vcodec libx264 -f hls -preset medium -profile:v baseline -level 3.0 -pix_fmt yuv420p -hls_segment_filename big_bunny.mp4%05d.ts -hls_list_size 0 -start_number 1 big_bunny.m3u8
> Stderr output: ffmpeg version N-81295-gbbec14d Copyright (c) 2000-2016 the FFmpeg developers
> Stderr output:   built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
> Stderr output:   configuration: --prefix=/home/usuario/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/usuario/ffmpeg_build/include --extra-ldflags=-L/home/usuario/ffmpeg_build/lib --bindir=/home/usuario/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-nonfree
> Stderr output:   libavutil      55. 28.100 / 55. 28.100
> Stderr output:   libavcodec     57. 51.100 / 57. 51.100
> Stderr output:   libavformat    57. 46.100 / 57. 46.100
> Stderr output:   libavdevice    57.  0.102 / 57.  0.102
> Stderr output:   libavfilter     6. 50.100 /  6. 50.100
> Stderr output:   libswscale      4.  1.100 /  4.  1.100
> Stderr output:   libswresample   2.  1.100 /  2.  1.100
> Stderr output:   libpostproc    54.  0.100 / 54.  0.100
> Stderr output: pipe:0: Invalid data found when processing input
> Stderr output:
> FFMPEG ERROR Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input
> 


I have detected:
- Only fails if I use 'progress' event.
- Previous versions of fluent-ffmpeg doesn't fail.
- Only fails with some videos, not all of them. With [this one](http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi) it also fails but with a different output.

I hope this helps to solve the Issue. 

Thank you.
