### ISSUE TITLE
error while gneration screenshot through ffmpeg-ffluent

### ISSUE THREAD

**Issue by alishagupta20** [fluent-ffmpeg/node-fluent-ffmpeg#564]
ffmpeg(videoUrl)
        .on('filenames', function (filenames) {
            logger.info('Will generate ' + filenames.join(', '));
        })
        .on('end', function () {
            logger.debug('Screenshots taken');
            var url = config.clientPath + '/home/gugulydev/ouut_api/' + thumbsFolder + '/' + archive.id + '_thumbs.png';
            return url;
        })
        .on('error', function (err) {
            logger.info('Error' + err.message);
            return null;
        })
        .screenshots({
            count: 1,
            folder: videoThumbs,
            filename: 123-101-104 + '_thumbs.png'
        });

when videoUrl is static , then it is working fine, but when passing this url dynamically then gives this error 

"Error:ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error\nframe=    1 fps=0.1 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.0031x    \nvideo:383kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown\nConversion failed!\n" 

please resolve issue

**Comment by njoyard** [comment]
This is most likely not a fluent-ffmpeg issue. Please try it on command line with the same parameters (you can use the 'start' event to get the command line that gets executed).

**Comment by alishagupta20** [comment]
I am using amazon cloud bucket.and it is working fine when I am passing static amazon cloud url. but while integrating with project , it always show this error

**Comment by njoyard** [comment]
As stated above, please dump the actual command line executed using the 'start' event and confirm it works on command line. If it does, then it's a fluent-ffmpeg problem ; otherwise it's either a ffmpeg problem or an issue with the parameters you pass to fluent-ffmpeg.

**Comment by alishagupta20** [comment]
hi,
can we use timeout option with takescreenshot function ?? like this:
ffmpeg({ source: videoUrl ,timeout:30})
        .on('filenames', function (filenames) {
            console.log('Will generate ' + filenames.join(', '))
        })
        .on('end', function () {
            console.log('Screenshots taken');
            var url = config.clientPath + '/home/gugulydev/ouut_api/' +
thumbsFolder + '/' + archive.id + '_thumbs.png';
            cb(null, url);
        })
        .on('error', function (err) {
            console.log('Error::' + err.message);
            cb(err, null);
        })
        .screenshots({
            // Will take screens at 20%, 40%, 60% and 80% of the video
            count: 1,
            folder: thumbsFolder,
            filename: archive.id + '_thumbs.png'
        });

**Comment by njoyard** [comment]
Closing as no answer was given to the info request. Please reopen if necessary.

**Comment by ahmed-sharief5** [comment]
s3 bucket signed url is not working its showing 'No such file or directory'
