### ISSUE TITLE
ffprobe exited with code 1 error

### ISSUE THREAD

**Issue by alishagupta20** [fluent-ffmpeg/node-fluent-ffmpeg#565]
Error::ffprobe exited with code 1
HTTP error 404 Not Found
https://s3.amazonaws.com/ouut-videos/45605592/700f9341-d3e7-48a3-8d24-a8019c447cd0/archive.mp4: Server returned 
404 Not Found
{
  "level": "info",
  "message": "error occured while generating thubnailError: ffprobe exited with code 1\nffprobe version N-80958-g92139c1 Copyright (c) 2007-2016 the FFmpeg developers\n  built with gcc 4.9.2 (Debian 4.9.2-10)\n  configuration: --enable-gnutls\n  libavutil      55. 28.100 / 55. 28.100\n  libavcodec     57. 50.100 / 57. 50.100\n  libavformat    57. 41.100 / 57. 41.100\n  libavdevice    57.  0.102 / 57.  0.102\n  libavfilter     6. 47.100 /  6. 47.100\n  libswscale      4.  1.100 /  4.  1.100\n  libswresample   2.  1.100 /  2.  1.100\n[https @ 0x3a4e860] HTTP error 404 Not Found\nhttps://s3.amazonaws.com/ouut-videos/45605592/700f9341-d3e7-48a3-8d24-a8019c447cd0/archive.mp4: Server returned 404 Not Found\n"
}

Can you pl. tell me why it is not able access this video, because as i am hitting url it is opened in browser, but not accessed by ffmpeg.why?

my code is :: 

ffmpeg({ source: videoUrl,timeout: 10 })
        .on('filenames', function (filenames) {
            console.log('Will generate ' + filenames.join(', '))
        })
        .on('end', function () {
            console.log('Screenshots taken');
            var url = config.clientPath + '/home/gugulydev/ouut_api/' + thumbsFolder + '/' + archive.id + '_thumbs.png';
            cb(null, url);
        })
        .on('error', function (err) {
            console.log('Error::' + err.message);
            cb(err, null);
        })
        .screenshots({
            // Will take screens at 20%, 40%, 60% and 80% of the video 
            count: 1,
            folder: thumbsFolder,
            filename: archive.id + '_thumbs.png'
        });

**Comment by njoyard** [comment]
You cannot use `.screenshots()` with a stream or URL input. `.screenshots()` needs to call ffprobe to compute screenshot timestamps and it does not work on streams or URLs. You have to download the file first or design the screenshots command yourself.
