### ISSUE TITLE
Support for mkv?

### ISSUE THREAD

**Issue by amilajack** [fluent-ffmpeg/node-fluent-ffmpeg#566]
Does this api support mkv files?

**Comment by njoyard** [comment]
The API itself does not support any format/codec/device. It's just an interface to call ffmpeg. It all depends on the version of ffmpeg you're using.

**Comment by amilajack** [comment]
I'm new to video codecs in general so please excuse my cluelessness. So if I understood you correctly, does that mean that if my version of fluent does support mkv, I should be able to use it?

**Comment by njoyard** [comment]
Your version of **ffmpeg**. Fluent-ffmpeg is just an interface library. And yes, if your ffmpeg version supports mkv, you should be good to go :)
