### ISSUE TITLE
How convert to an aac or m4a file?

### ISSUE THREAD

**Issue by JemiloII** [fluent-ffmpeg/node-fluent-ffmpeg#572]
So I was reading the api and was trying to convert an mp3 to  an aac/m4a file. I seem to not have any luck. One of the things I tried, I thought worked, but it was just an mp3 with a different extension that was converted.

When I try this:

```js
ffmpeg('./audio/uploaded/developers.mp3')
    .inputFormat('mp3')
    .audioChannels(2)
    .audioBitrate('64k')
    .audioCodec('libfaac')
    .toFormat('m4a')
    .save('./audio/converted/developers.m4a');
```

I get `Output format m4a is not available` and likewise when I change to aac.

How convert to an aac/m4a file?

I can use the cli to convert it~ `ffmpeg -i ./audio/uploaded/developers.mp3 -c:a libfdk_aac -b:a 128k ./audio/converted/developers.m4a` to convert it.

**Comment by JemiloII** [comment]
Figured it out.

```js
ffmpeg(path.join(process.cwd(), '/developers.mp3'))
    .inputFormat('mp3')
    .audioChannels(2)
    .audioBitrate('64k')
    .audioCodec('aac')
    .save(path.join(process.cwd(), '/developers.aac'));
```

**Comment by dev-farmaan** [comment]
You should set the output format as `mp4` and the file extension can be a `m4a`
