### ISSUE TITLE
Unable to resolve some modules: "./lib-cov/fluent-ffmpeg"

### ISSUE THREAD

**Issue by Jaetoh** [fluent-ffmpeg/node-fluent-ffmpeg#573]
Hi ! 

I got this warning while running my Meteor app with the npm package fluent-ffmpeg. I don't really know what's wrong with this issue because my npm package worked well during more than 3 months. After I installed again all npm packages into my app, i got it.

> Unable to resolve some modules:
> 
>   "./lib-cov/fluent-ffmpeg" in /home/.../MyAPP/node_modules/fluent-ffmpeg/index.js (web.browser)
>                                               
>                                               
> Unable to resolve some modules:
> 
>   "./lib-cov/fluent-ffmpeg" in /home/.../MyAPP/node_modules/fluent-ffmpeg/index.js (os.linux.x86_64)

Thank you in advance for any reply

**Comment by njoyard** [comment]
Hey,

This is weird, items in `lib-cov` should only be referenced during CI. Here is the code from index.js:

```js
module.exports = process.env.FLUENTFFMPEG_COV ? require('./lib-cov/fluent-ffmpeg') : require('./lib/fluent-ffmpeg');
```

Do you happen to have the environment variable `FLUENTFFMPEG_COV` set by any chance ? If so, then unsetting it will probably solve the issue.

**Comment by Jaetoh** [comment]
I exactly have the same code for index.js !
I didn’t set by myself the environment variable `FLUENTFFMPEG_COV`. Maybe it has been modified during a process but i don't think.

I am on Ubuntu 14.04 and i work with Meteor ! I tried to remove the npm package and reinstall it but it is same result. I also did `npm rebuild`

**Comment by chervox** [comment]
Hi Jaetoh, I'm having the exact same problem. Are you using webpack by any chance? I think that the issue is because of trying to solve the path statically:

Here is the offending line:
index.js:
module.exports = process.env.FLUENTFFMPEG_COV ? require('./lib-cov/fluent-ffmpeg') : require('./lib/fluent-ffmpeg');

**Comment by Jaetoh** [comment]
I'm not using webpack ! Did you figure out the warning ?

**Comment by njoyard** [comment]
@Jaetoh this is a Meteor bug. It parses source files and tries to include everything that is in a `require()` call, even if it's conditional. Nothing fluent-ffmpeg can do here.

**Comment by agmcleod** [comment]
Given that webpack has issue resolving this, and that ES6 imports are not done conditionally, is this something you can consider fixing?

**Comment by kus** [comment]
I ran into this also when using Webpack as I'm building a desktop app using this library.

The work around (if you are using Webpack):

plugins: [
    new webpack.DefinePlugin({
        'process.env.FLUENTFFMPEG_COV': false
    })
]

If not using Webpack you could just put `FLUENTFFMPEG_COV=0` at the start of your npm script.

**Comment by crakjie** [comment]
I'm running into the same problem with https://github.com/electron-userland/electron-builder

**Comment by Jfeng3** [comment]
I am trying to use kus @kus 's approach 
I saw a 
```
plugins: [
  new webpack.DefinePlugin(env.stringified)
]
```
what should I do with it?

**Comment by kus** [comment]
@Jfeng3 assuming your `env.stringified` is an `Object` which it should be, you should check it by adding `console.log('env', env.stringified)` at the end of your WebPack script and run it to make sure it is. It should equal something like:

```
{
	'process.env.NODE_ENV': 'development'
}
```

The important thing is it being an `Object`. If it is; you can inject the new variable in one of the following ways:

_This depends how you are running Webpack, if you get an error like `SyntaxError: Unexpected token ...` use the next one after._
```
plugins: [
	new webpack.DefinePlugin({
		...obj,
		'process.env.FLUENTFFMPEG_COV': false
	})
]
```

```
plugins: [
	new webpack.DefinePlugin(Object.assign({}, obj, {'process.env.FLUENTFFMPEG_COV': false}))
]
```

**Comment by Yasgur99** [comment]
this is still an issue for me

**Comment by Regretful123** [comment]
Hello all,
Using fluent-ffmpeg, I'm puzzle as to why it would even bother loading lib-cov if it's not included in the npm package anyway. 
I am actively looking for alternative solution to get around this, rather than directly modifying your index.js file to get this plugin to work.
Using Angular/Electron build.

**Comment by muzammal-murtaza** [comment]
> I ran into this also when using Webpack as I'm building a desktop app using this library.
> 
> The work around (if you are using Webpack):
> 
> ```
> plugins: [
>     new webpack.DefinePlugin({
>         'process.env.FLUENTFFMPEG_COV': false
>     })
> ]
> ```
> 
> If not using Webpack you could just put `FLUENTFFMPEG_COV=0` at the start of your npm script.

I am getting same issue in my Vue app, any idea how to solve this.

**Comment by dancixx** [comment]
Does somebody have experience what should to do in a react-app? I tried all offers but nothing works.

**Comment by sharunspi** [comment]
> Does somebody have experience what should to do in a react-app? I tried all offers but nothing works.

If you are using webpack in react then add this configuration to your plugins object in webpack configuration
```
    plugins: [
      new webpack.DefinePlugin({
        'process.env.FLUENTFFMPEG_COV': false
      })
    ]

**Comment by max-programming** [comment]
> I ran into this also when using Webpack as I'm building a desktop app using this library.
> 
> The work around (if you are using Webpack):
> 
> ```
> plugins: [
>     new webpack.DefinePlugin({
>         'process.env.FLUENTFFMPEG_COV': false
>     })
> ]
> ```
> 
> If not using Webpack you could just put `FLUENTFFMPEG_COV=0` at the start of your npm script.

I think this works for many people but I am using Rollup and it's not working for me. I used the Rollup approach to set the environment variable.

I ran this command but I get the same error:
`rollup -c --environment FLUENTFFMPEG_COV:false` and also this `rollup -c --environment FLUENTFFMPEG_COV:0`

**Comment by Losses** [comment]
> I'm running into the same problem with https://github.com/electron-userland/electron-builder

open `.erb/configs/webpack.config.base.js`,

replace the last section with:
```
  plugins: [
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      FLUENTFFMPEG_COV: '',
    }),
  ],
```

**Comment by vishal-c-addweb** [comment]
i am using esbuild for build and running in same issue.

**Comment by vishal-c-addweb** [comment]
i am using esbuild for bundle and running into same problem.
adding 'process.env.FLUENTFFMPEG_COV' = '0' solve my problem.
---->     custom: {
               esbuild: {
                 define: { 'process.env.FLUENTFFMPEG_COV': '0' },
               },
           }   
while using serverless.

**Comment by PAXANDDOS** [comment]
I am facing the same issue now. Working on the Electron application and I really need to use FFmpeg features.
Have a custom script to serve my application, so the `package.json` is:
```JSON
"scripts": {
	"dev": "node scripts/watch.mjs"
```
And right at the beginning of which I have put:
```js
process.env.FLUENTFFMPEG_COV = false
process.env.NODE_ENV = 'development'
. . .
```
Also tried with an empty string and a zero, but the issue still exists...
Any idea, please?

**Comment by lanly-dev** [comment]
This works for me:
```js
new EnvironmentPlugin({
  FLUENTFFMPEG_COV: '',
})
```

**Comment by serg06** [comment]
@max-programming @PAXANDDOS I was able to fix this in Vite/Rollup by adding the following line to my Vite config:

```js
export default defineConfig(() => ({
  resolve: {
    alias: {
      './lib-cov/fluent-ffmpeg': './lib/fluent-ffmpeg'  // This line
    },
  },
}));
```

**Comment by elron** [comment]
If you're using Netlify Functions, you can add this to the **netlify.toml** file:

```
# Production context: all deploys from the Production branch 
# set in your site’s Branches settings in the UI will inherit 
# these settings. You can define environment variables 
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository. 
[context.production]
  environment = { FLUENTFFMPEG_COV = "false" }
```

**Comment by Tikam02** [comment]
> plugins: [
>     new webpack.DefinePlugin({
>         'process.env.FLUENTFFMPEG_COV': false
>     })
> ]

where to add this in React project?

**Comment by vikash265** [comment]
plugins: [
new webpack.DefinePlugin({
'process.env.FLUENTFFMPEG_COV': false
})
]

where to add this in React project?

**Comment by vikash265** [comment]
plugins: [
new webpack.DefinePlugin({
'process.env.FLUENTFFMPEG_COV': false
})
]

where to add this in React project?

**Comment by oakgary** [comment]
My solution when using `serverless-bundle`, which is a framework on top of Webpack, was to exclude `fluent-ffmpeg` from being built with Webpack by using 
```
custom:
  bundle:
    externals:
      - knex
      - sharp
      - fluent-ffmpeg
```

**Comment by leumasme** [comment]
In rollup, this can be solved with the plugin [@rollup/plugin-alias
](https://www.npmjs.com/package/@rollup/plugin-alias)

rollup.config.js
```ts
import alias from "@rollup/plugin-alias";
export default {
  plugins: [
    alias({
      entries: [
        { find: "./lib-cov/fluent-ffmpeg", replacement: "./lib/fluent-ffmpeg" },
      ]
    })
  ]
}
```

**Comment by gersongams** [comment]
> while using serverless.

this worked for me!! thanks!

**Comment by mcorrigan** [comment]
> I ran into this also when using Webpack as I'm building a desktop app using this library.
> 
> The work around (if you are using Webpack):
> 
> ```
> plugins: [
>     new webpack.DefinePlugin({
>         'process.env.FLUENTFFMPEG_COV': false
>     })
> ]
> ```
> 
> If not using Webpack you could just put `FLUENTFFMPEG_COV=0` at the start of your npm script.

This worked for me, just make sure to `const webpack = require('webpack')` as the top

**Comment by subvertallchris** [comment]
If you're using a .env file, be aware that `FLUENTFFMPEG_COV=false` will not treat `false` as a boolean. It will be read as a string. So the evaluation in code:

```
module.exports = process.env.FLUENTFFMPEG_COV ? require('./lib-cov/fluent-ffmpeg') : require('./lib/fluent-ffmpeg');
```

...will be evaluated to the true condition because `'false'` is a truthy value. You can do this:

```
FLUENTFFMPEG_COV=''
```

The empty string is falsy.

**Comment by PDKSophia** [comment]
I also have the same problem. According to everyone's solutions, I have not solved it.

I use `React+Vite+Electron`. I will share some of my knowledge

when i downloaded `fluent-ffmpeg`，i want to import it，but i got error

<img src="https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/assets/29560420/ffde297f-3a52-482e-b259-8bcceb3c76e3" width=450 />

then i went to the `node_modules/fluent-ffmpeg` folder to see its source code，the `process.env.FLUENTFFMPEG_COV ` may be an error value.

```js
module.exports = process.env.FLUENTFFMPEG_COV ? require('./lib-cov/fluent-ffmpeg') : require('./lib/fluent-ffmpeg');
```

in vite docs , we can be configured through the `define` attribute, so i go to configure value

```js
// vite.config.js
export default defineConfig({
  // ...
  define: {
    'process.env.FLUENTFFMPEG_COV': false,
  },
}
```

And added two lines of code to the source code, print `process.env.FLUENTFFMPEG_COV` value

```js
// node_modules/fluent-ffmpeg
console.log('[fluent-ffmpeg]', process.env.FLUENTFFMPEG_COV);
console.log('[fluent-ffmpeg]', typeof process.env.FLUENTFFMPEG_COV);

module.exports = process.env.FLUENTFFMPEG_COV ? require('./lib-cov/fluent-ffmpeg') : require('./lib/fluent-ffmpeg');
```

<img src="https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/assets/29560420/692467cc-98bc-4cb4-b044-47b2870432a2" width=700 />

we expect it to be a `boolean`, but it's actually a `string` !!!

try again, this time we change it to `undefined`, same result !

<img src="https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/assets/29560420/96869834-0611-4ac0-b4a3-10d3c6769d0e" width=700 />

--- 

No matter what value is configured, it is of `string type` and will meet the condition of true, so i try to configure as an `empty string`

<img src="https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/assets/29560420/e78a2eb2-9821-4187-8570-4729fd79956e" width=700 />

Error , I don't know why, so hard ！

The solution is to copy the `fluent-ffmpeg folder`, change the source code, but this is not what I expected !

when i'm depressed, i was surprised to find that the `vite startup electron plugin` I wrote can inject environment variables, below is my code: 

```ts
import { Plugin } from 'vite';
import { buildMain, mainOutPath } from '../scripts/build.main';

export const devMainPlugin = (): Plugin => {
  return {
    name: 'vite-plugin-dev-main',
    configureServer(server) {
      buildMain();
      server.httpServer?.once('listening', () => {
        const { spawn } = require('child_process');
        const electronProcess = spawn(require('electron').toString(), [mainOutPath, '--inspect=9229', '--remote-debugging-port=9222', '--env=dev'], {
          cwd: process.cwd(),
          stdio: 'inherit',
          env: {
            FLUENTFFMPEG_COV: '',
          },
        });
        electronProcess.on('close', () => {
          server.close();
          process.exit();
        });
        server.httpServer?.once('close', () => {
          electronProcess.close();
          process.exit();
        });
      });
    },
  };
};
```
this way solved my problem !

**Comment by Geo25rey** [comment]
For those using `vite-plugin-electron` in their `vite.config.ts`

Note: I assume that you aren't using ffmpeg in your preload script. If you do, just copy over the `vite` property from the main entrypoint section.

```typescript
import { defineConfig } from 'vite';
import electron from 'vite-plugin-electron';

export default defineConfig({
  plugins: [
    electron([
      {
        entry: "src/electron/node/main.ts", // wherever your main entrypoint 
        vite: {
          build: {
            rollupOptions: {
              plugins: [
                alias({
                  entries: [
                    {
                      find: "./lib-cov/fluent-ffmpeg",
                      replacement: "./lib/fluent-ffmpeg",
                    },
                  ],
                }),
              ],
            },
          },
        },
      },
      {
        entry: "src/electron/node/preload.ts", // wherever your preload entrypoint 
        onstart(options) {
          // Notify the Renderer-Process to reload the page when the Preload-Scripts build is complete,
          // instead of restarting the entire Electron App.
          options.reload();
        },
      },
    ]),
  ]
});
```

**Comment by Isaccseven** [comment]
Is there someone, who solved this issue with next js ?

**Comment by pabloVoorvaart** [comment]
> new webpack.DefinePlugin({
>         'process.env.FLUENTFFMPEG_COV': false
>     })

/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.FLUENTFFMPEG_COV': false
    })
    )
 
    return config
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '*',
        port: '',
        pathname: '/**',
      },
    ],
  },
}

module.exports = nextConfig

this config works

**Comment by pabloVoorvaart** [comment]
> Is there someone, who solved this issue with next js ?

this config works

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.FLUENTFFMPEG_COV': false
    })
    )
 
    return config
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '*',
        port: '',
        pathname: '/**',
      },
    ],
  },
}

module.exports = nextConfig

```

**Comment by TharukaDananjaya** [comment]
Is there someone, who solved this issue with laravel mix ?

**Comment by McKean** [comment]
For people stumbling over this, this has been addressed but the changes have not been published since:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/68d5c948b689b3058e52435e0bc3d4af0eee349e/index.js#L1

I suggest using something like https://www.npmjs.com/package/patch-package. yarn and pnpm have this feature built in, this is all mentioned in the readme for patch-package.

**Comment by leumasme** [comment]
> this has been addressed

The code you are referencing does not address the issue, it causes it.  
Since bundlers can not know what the value of the environment variable "FLUENTFFMPEG_COV" is at runtime, they will try to bundle both the import for `./lib/fluent-ffmpeg` as well as `./lib-cov/fluent-ffmpeg`. Since `lib-cov` does not exist, this fails.  
The solution is to tell your bundler to treat `process.env.FLUENTFFMPEG_COV` as some given constant value at bundle time.  
Various ways to do this for various bundlers have been mentioned in this thread, but the issue persists without explicit user configuration to address it.

**Comment by subvertallchris** [comment]
A simple patch using [patch-package](https://github.com/ds300/patch-package) fixes this easily. Follow the instructions in the repo to install that and patch `node_modules/fluent-ffmpeg/index.js` so it only requires `lib/fluent-ffmpeg`.

```
diff --git a/node_modules/fluent-ffmpeg/index.js b/node_modules/fluent-ffmpeg/index.js
index 04e594c..68a1522 100644
--- a/node_modules/fluent-ffmpeg/index.js
+++ b/node_modules/fluent-ffmpeg/index.js
@@ -1 +1 @@
-module.exports = process.env.FLUENTFFMPEG_COV ? require('./lib-cov/fluent-ffmpeg') : require('./lib/fluent-ffmpeg');
+module.exports = require('./lib/fluent-ffmpeg');
```

**Comment by fabianwohlfart** [comment]
Also stumbled upon this in a complete different setup (nuxt + layers + vite/rollup)

**Comment by pirmax** [comment]
@pabloVoorvaart Thanks, I use this config since I discover your response, but I've this error when I build the project :

```./node_modules/fluent-ffmpeg/lib/options/misc.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/fluent-ffmpeg/lib/options/misc.js
./node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js
./node_modules/fluent-ffmpeg/index.js
./lib/ffmpeg.ts
./actions/index.ts
./app/(app)/(home)/page.tsx```

**Comment by neoean** [comment]
Update the version to 2.1.3, its ok:
module.exports = require('./lib/fluent-ffmpeg');
