### ISSUE TITLE
Not work  wrapped in webworker-threads

### ISSUE THREAD

**Issue by songbaoqiang** [fluent-ffmpeg/node-fluent-ffmpeg#576]
var Worker = require('webworker-threads').Worker;
// var w = new Worker('worker.js'); // Standard API

// You may also pass in a function:
var worker = new Worker(function(){
                        
                        postMessage("I'm working before postMessage('ali').");
                        
                        this.onmessage = function(event) {
                        
                        postMessage("I'm working after postMessage('ali').");

                        var ffmpeg = require('fluent-ffmpeg');
                        var proc = ffmpeg('/Users/vincentsung/Downloads/test/test.mp4')
                        // Base url
                        .addOption('-hls_base_url', 'http://www.ffmlive.com/')
                        // include all the segments in the list
                        .addOption('-hls_list_size',0)
                        .addOption('-hls_segment_filename','out%04d.ts')
                        // setup event handlers
                        .on('progress', function(progress) {
                            
                            var processing_str = 'Processing:' + progress.percent + '% done';
                            console.log(processing_str);
                            })
                        .on('end', function() {
                            console.log('file has been ffmpeg succesfully');
                            })
                        .on('error', function(err) {
                            console.log('an error happened:' + err.message);
                            })
                        // save to file
                        .save('/Users/vincentsung/Downloads/test/out.m3u8');
                        
                        
                        
                            postMessage('Hi ' + event.data);
                            self.close();
                        };
});
worker.onmessage = function(event) {
    console.log("Worker said : " + event.data);
};
worker.postMessage('ali');

**Comment by songbaoqiang** [comment]
node-fluent-ffmpeg is native module and it is not supported by webworker-threads now.

**Comment by njoyard** [comment]
Hi,
Can you be a bit more explicit please ? What are you trying to achieve, what errors are reported ?

**Comment by songbaoqiang** [comment]
Note: If you would like to require() native modules in a worker, please consider using the process-based tiny-worker instead. It does not use threads, but the WebWorker API is compatible.

https://github.com/audreyt/node-webworker-threads
