### ISSUE TITLE
Error: spawn EACCES when attempting to merge videos from AWS S3

### ISSUE THREAD

**Issue by mmichael0413** [fluent-ffmpeg/node-fluent-ffmpeg#577]
Here's my function:

```
function concat(clips) {
  var mergedVideo = ffmpeg();

  return new Promise(function(resolve, reject) {

    clips.forEach(function(fileName){
      mergedVideo = mergedVideo.addInput(fileName);
    });

    mergedVideo.mergeToFile('./mergedVideo.mp4', './tmp/')
      .on('error', function(err) {
        reject({ status: 500, msg: err.message });
      })
      .on('end', function(result) {
        resolve({ status: 201, result: result });
      });

  });
}
```

`clips` is an array of absolute file paths from Amazon S3 (e.g. https://s3.amazonaws.com/bucket-name/test1.mp4). I also tried with local files but ran into the same error(s).

I'm setting my local ffmpeg and ffprobe paths in a `.env` file:

```
FFMPEG_PATH=./node_modules/ffmpeg
FFPROBE_PATH=./node_modules/ffprobe
```

And I'm getting the following error:

```
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at /Users/username/app_name/node_modules/fluent-ffmpeg/lib/ffprobe.js:155:21
    at /Users/username/app_name/node_modules/fluent-ffmpeg/lib/capabilities.js:194:9
    at /Users/username/app_name/node_modules/async/dist/async.js:486:20
    at nextTask (/Users/username/app_name/node_modules/async/dist/async.js:5008:33)
    at /Users/username/app_name/node_modules/async/dist/async.js:5015:17
    at /Users/username/app_name/node_modules/async/dist/async.js:339:31
    at /Users/username/app_name/node_modules/async/dist/async.js:847:20
```

I also tried setting the paths explicitly (instead of in `.env`):

```
ffmpeg.setFfmpegPath('./node_modules/ffmpeg');
ffmpeg.setFfprobePath('./node_modules/ffprobe');
```

But that raised `{ [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }`

Any suggestions? Thank you!

**Comment by bhushankumarl** [comment]
@mmichael0413 
Did you found the solution, I am facing the same?

**Comment by mmichael0413** [comment]
@bhushankumarl I honestly don't remember at this point. This was for a personal side project but I'm pretty sure I ended up going with another package instead of `node-fluent-ffmpeg`.

**Comment by ArgeKumandan** [comment]
> @bhushankumarl I honestly don't remember at this point. This was for a personal side project but I'm pretty sure I ended up going with another package instead of `node-fluent-ffmpeg`.

which package did u move on?

**Comment by ArgeKumandan** [comment]
> @bhushankumarl I honestly don't remember at this point. This was for a personal side project but I'm pretty sure I ended up going with another package instead of `node-fluent-ffmpeg`.

which package did u move on?
