### ISSUE TITLE
Generate video from images with each image of variable duration

### ISSUE THREAD

**Issue by fcb2** [fluent-ffmpeg/node-fluent-ffmpeg#581]
How can i generate video from a series of images with varying image duration?
I have used image2video.js example. I'd also like to be able to specify a duration for each image. 
One way i found was using zoompan filter(ffmpeg command line) . How can i achieve the same using fluent-ffmpeg? 
Thanks.

**Comment by njoyard** [comment]
Have you found a command line that works ? What part of it do you have trouble rewriting with fluent-ffmpeg ?

**Comment by fcb2** [comment]
Hi Nicolas. I referred to ffmpeg's documentation. There it said it is possible using zoompan filter like:
`ffmpeg -i image-%3d.jpg -vf "zoompan=d=25+'50*eq(in,3)'+'100*eq(in,5)'" test.mp4`
Here ,each picture is shown 1 second (25 frames), except the 3rd picture is shown 3 seconds (25+50 frames) and the 5th picture is shown 5 seconds (25+100 frames).
I have just started using fluent-ffmpeg, and am not sure how can we use the zoompan filter as used in command line in fluent-ffmpeg.
Thanks.

**Comment by njoyard** [comment]
You can use the documentation for video filters here:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#videofiltersfilter-add-custom-video-filters

**Comment by SyntheticTV** [comment]
.videoFilters([`zoompan=z='min(zoom+0.0015,1.5)':d=700:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'`])

**Comment by ademmeral** [comment]
> @fcb2
> 
> To convert image to video:
> 
> ```
> ffmpeg('image1.png')
> .loop(10)
> .output('tmp/ouput.mp4')
> .on('error', (error) => {...})
> .on('end', () => {...}).run();
> ```
> 
> then you can merge videos.

good job
