### ISSUE TITLE
setsar with zoompan filter

### ISSUE THREAD

**Issue by ugurgungezerler** [fluent-ffmpeg/node-fluent-ffmpeg#587]
Hi,
How can i use together this filters

 .videoFilter(["setsar=1"])
 .videoFilter('zoompan=z=\'if(lte(zoom,1.0),4,max(1.001,zoom-0.0900))\':d=49:x=\'iw/2-(iw/zoom/2)\':y=\'ih/2-(ih/zoom/2)\':d=49');

When i use zoompan setsar is not effective.

**Comment by njoyard** [comment]
Have you tried on command line ? Does it work ? Looks to me like this is an issue with ffmpeg, not fluent-ffmpeg.

**Comment by njoyard** [comment]
Closing because no feedback, please reopen if necessary.
