### ISSUE TITLE
Setting mp3 metadata

### ISSUE THREAD

**Issue by aeryx** [fluent-ffmpeg/node-fluent-ffmpeg#589]
I'm trying to set id3 tags (or whatever, let´s just say metadata) in an output mp3 file. I am using
```

ffMpegProc.addOutputOption('-metadata title="Stairway to heaven"');
ffMpegProc.addOutputOption('-metadata artist="Led Zeppelin"');
```

but on run it fails:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: metadata artist="Led Zeppelin": Invalid argument

What am I doing wrong? Thanks!

**Comment by njoyard** [comment]
Use the separate flag/arg form: `addOutputOption('-metadata',  'title="Stairway to Heaven"')`. Automatic splitting of arguments by fluent-ffmpeg only happens when there is only one space.

**Comment by njoyard** [comment]
(and now I have stairway to heaven stuck in my head :guitar: )

**Comment by aeryx** [comment]
You should consider putting a sign http://ukeuniversity.net/wp-content/uploads/2014/11/IMG_0359.jpg

PS: Thanks for the answer!

**Comment by moshfeu** [comment]
A similar very strange problem:

When I have **only** 1 space it failing but if there are 0 or more than one, it doesn't fail:

**Fail**

```javascript
            var outputOptions = [
              "-id3v2_version", "4",
              "-metadata", "title=Summertime a",
              "-metadata", "artist=Seasick Steve"
            ];

            new ffmpeg({
                source: stream.pipe(str)
            })
           .outputOptions(outputOptions)
```

**Doesn't fail**

```javascript
            var outputOptions = [
              "-id3v2_version", "4",
              "-metadata", "title=Summertime a b",
              "-metadata", "artist=Seasick Steve"
            ];

            new ffmpeg({
                source: stream.pipe(str)
            })
           .outputOptions(outputOptions)
```
