### ISSUE TITLE
Upon bad patterns, no error is emitted

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#590]
When I ran some ffmpeg commands with your lib, I saw that the end result wasn't what I expected. So I copied the command and ran it directly in the console:

```
$ ffmpeg -f image2 -thread_queue_size 64 -framerate 15.5 -i /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-7174-bfd1c6c0-8ec7-8d223fc2b668/frames/%d.webp -y -an -vcodec libvpx -filter:v drawtext=fontfile=/home/michael-heuberger/binarykitchen/code/videomail.io/src/assets/fonts/Varela-Regular.ttf:text=www.videomail.io:fontsize=80:fontcolor=white:x=(main_w/2-text_w/2):y=50:shadowcolor=black:shadowx=2:shadowy=2 -vf scale=trunc(iw/2)*2:trunc(ih/2)*2 -crf 12 -deadline realtime -cpu-used 4 -pix_fmt yuv420p -loglevel warning -movflags +faststart /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-7174-bfd1c6c0-8ec7-8d223fc2b668/videomail_preview.webm
zsh: bad pattern: drawtext=fontfile=/home/michael-heuberger/binarykitchen/code/videomail.io/src/assets/fonts/Varela-Regular.ttf:text=www.videomail.io:fontsize=80:fontcolor=white:x=(main_w/2-text_w/2):y=50:shadowcolor=black:shadowx=2:shadowy=2
```

Oh, I can see "zsh: bad pattern"! Why wasn't this error emitted in the error event?

PS the filter I applied was

```js
    command.videoFilters({
        filter: 'drawtext',
        options: {
            fontfile:       path.join(settings.server.paths.fonts, 'Varela-Regular.ttf'),
            text:           'www.videomail.io',
            fontsize:       80,
            fontcolor:      'white',
            x:              '(main_w/2-text_w/2)',
            y:              50,
            shadowcolor:    'black',
            shadowx:        2,
            shadowy:        2
        }
    })
```

**Comment by njoyard** [comment]
Because this error doesn't happen when running the command. Your error comes from zsh, ie. your command line shell, which is not used when running processes from nodejs.

**Comment by binarykitchen** [comment]
@njoyard i am sorry, i dont understand. i have copied the command fluent-ffmpeg has generated to the command line. and i expect it to work there. that's why i wonder if fluent-ffmpeg has generated a wrong command?

when i remove the above `videoFilters`, copy-paste the produced command, then it works fine in the command line.

**Comment by njoyard** [comment]
The command line generated from the `start` event is just an indication of what fluent-ffmpeg is running. It is formed by joining all command-line arguments with a space between them. It is not guaranteed to be a valid shell command line (though it may be valid in some simple cases).

If you want to run this command from your shell, you have to ensure that each argument is properly escaped, ie. that there are no characters that have a special meaning for your shell that are left unescaped. The most common example is the space character (used to separate arguments by most shells), but there are other characters (eg. parentheses in bash) that may need escaping.

Fluent-ffmpeg does not do this by itself for the following reasons:

1. this is just an indicator of what we are running
2. fluent-ffmpeg does not *need* escaping arguments as they are passed as separate strings to child_process.spawn
3. there are as many escaping rules for command line arguments as there are shells; fluent-ffmpeg does not know which shell you will be using and its specific escaping rules

**Comment by binarykitchen** [comment]
@njoyard ah, i see now - this explains very well. maybe worth to document the start event in README.md a bit more in regards to this space encoding stuff?

and do you know a trick (off-topic) how one could convert the command line generated from the `start` event into a fully valid, executable command for bash / zsh?

**Comment by njoyard** [comment]
I don't know zsh at all, but I think adding double-quotes around your filter line would help.

Feel free to submit a pull request for README changes ;)

**Comment by binarykitchen** [comment]
yes, double quoting that worked

but now i see no watermark - weird. am i forgetting a parameter or are ttf fonts not supported?

**Comment by binarykitchen** [comment]
i think further down in the code i have this line `.outputOptions('-vf', 'scale=trunc(iw/2)*2:trunc(ih/2)*2')`

will this override any video filters i have declared before this line? @njoyard

**Comment by njoyard** [comment]
It shouldn't, ffmpeg supports multiple -vf arguments.
(you should use `.videoFilter('scale=trunc(iw/2)*2:trunc(ih/2)*2')` instead)

**Comment by binarykitchen** [comment]
thanks, all good now - learned my lesson. having `command.videoFilters({ ... }, { ... })` did the trick

**Comment by binarykitchen** [comment]
thanks, all good now - learned my lesson. having `command.videoFilters({ ... }, { ... })` did the trick
