### ISSUE TITLE
Stream video file to RTMP

### ISSUE THREAD

**Issue by al922001** [fluent-ffmpeg/node-fluent-ffmpeg#592]
Hi, I would like to know how to stream an input file to an RTMP url.

I can do it directly with ffmpeg but I don't know how to do with this library.

Thanks

**Comment by njoyard** [comment]
Just use `.save("your rtmp url")` as if you were saving to a file (just like on command line).

**Comment by al922001** [comment]
Thank you

**Comment by azarus** [comment]
Error: ENOENT: no such file or directory, open 'D:\nodejs\ffmpeg\streamurl' at Error (native)

**Comment by uniquegodwin** [comment]
Does streaming work?
