### ISSUE TITLE
Wrong duration when input is a stream image 

### ISSUE THREAD

**Issue by cat2608** [fluent-ffmpeg/node-fluent-ffmpeg#593]
Hi, 

```js
var stream = fs.createReadStream('image.png');
  ffmpeg()
    .input(stream)
    .withVideoCodec('libx264')
    .loop(30)
    .output('file.mp4')
    .run();
```
The output is always just 1 frame, so it's 0 seconds.

While, if I'm running the same command in the console: 
```
 cat image.png | ffmpeg -loop 1 -i pipe:0 -vcodec libx264 -t 30 file.mp4
```
the output is correct, I'm getting a 30 seconds of video.  Am I doing something wrong?
Thanks

**Comment by njoyard** [comment]
Those are not the same command: in the first case you're doing `-loop 30` and in the second `-loop 1 -t 30`. If your command line in the bottom works, use `.loop(1).duration(30)` to do the same with fluent-ffmpeg.

**Comment by cat2608** [comment]
With the command that I described, inspecting `FfmpegCommand()` `options`, it receives:
```
[ '-loop',
  '1',
  '-i',
  'pipe:0',
  '-y',
  '-vcodec',
  'libx264',
  '-t',
  30,
  '/[PATH]/file.mp4' ]
```
`.loop(30)` is setting `-loop 1` and `-t 30`. And when I run `.loop(1).duration(30)` I get:

```
  [ '-loop',
  '1',
  '-i',
  'pipe:0',
  '-y',
  '-vcodec',
  'libx264',
  '-t',
  1,
  '-t',
  30,
  '/[PATH]/file.mp4' ]
```
So the `-t` is defined twice and I still have the same problem, when the input is a stream I can't set the duration.

**Comment by njoyard** [comment]
Oh, I think you misunderstood the `loop()` method:
* `loop()` sets `-loop 1`
* `loop(1234)` sets `-loop 1 -t 1234`

So you just have to use `loop(30)`. No `duration()` call.

**Comment by cat2608** [comment]
Yes, you are right and because of that, the command I'm using is what I post in the first comment:
```
var stream = fs.createReadStream('image.png');
  ffmpeg()
    .input(stream)
    .withVideoCodec('libx264')
    .loop(30)
    .output('file.mp4')
    .run();
```
The bug still persists thought: the duration isn't set when the input is a stream. It outputs a video with a single frame.

**Comment by fozzle** [comment]
Hey @cat2608 were you able to fix this issue? I'm running into the same thing. When I source from a file it makes the video with the correct duration but if I don't it creates a single frame video. Pretty much the same command as you're using.

I've been able to achieve a longer video by lowering the inputFps, but that makes the code harder to read so I'm not a fan.

**Comment by cat2608** [comment]
Hi @fozzle, have you tried what you need running it in the command line? In my case, with this command:

```
cat image.png | ffmpeg -loop 1 -i pipe:0 -vcodec libx264 -t 30 file.mp4
```

I get what I need. What is not working for me is the translation using this `node-fluent-ffmpeg`...
