### ISSUE TITLE
How set the video's duration when streaming over http

### ISSUE THREAD

**Issue by gpapin** [fluent-ffmpeg/node-fluent-ffmpeg#600]
Sorry if the question is a little bit too broad.
The story
--------
What I'm trying to do is a "on the fly" http transcoder. So basically on my web server I have a hi-res clip and I want to be able to stream it to different clients depending on their requirements, (mobile, tablet, desktop, etc...).
So here is my sample code for itI've kept it simple on purpose.

```
var express = require('express');
var ffmpeg  = require('fluent-ffmpeg');

var app = express();


var pathToMovie = "sample.mkv";


app.get('/', function(req, res) {
	res.contentType('mp4');
	var proc = ffmpeg(pathToMovie)
		.format("mp4")
		.size("?x480")
		.addOptions([
			"-movflags frag_keyframe+faststart"
		])

		// setup event handlers
		.on('end', function() {
			console.log('file has been converted succesfully');
		})
		.on('error', function(err) {
			console.log('an error happened: ' + err.message);
		})

		// save to stream
		.pipe(res, {end:true});
});

app.listen(8888);
```

Now if I point google chrome to http://localhost:8888 it woks but I have two issue.

First problem:
---
First the time is wrong, chrome always thinks the video is 10 sec long regardless of the clip used. and when the playback eventually goes beyond those 10 sec it just keeps playing the the control are a bit odd, cf screenshot: 
![capture d ecran 2016-09-29 16 59 59](https://cloud.githubusercontent.com/assets/3064311/18961828/45edf20a-8666-11e6-80be-0125fe613574.png)

Second issue:
---
If I want to jump somewhere in that video it just doesn't work, it will just continue streaming from where it is...

I've already tried to set the video's duration in the header response using ```content-duration``` I also used ```content-size``` both doesn't work...

Any help will be appreciated,
thanks

**Comment by njoyard** [comment]
Sorry, but that's just not going to work. HTML video playback has not be designed to handle live-transcoded streams with seeking, only 1. "real" live streams and 2. video files served from static sources (eg. video hosting platforms that transcode streams in advance and then serve them statically). The main problem is that data exchange is done on a byte-offset basis, not on a time-offset basis, which screws you completely unless you use **striclty constant** bitrate.

There are several closed issues on this repository that address the problem and propose solutions (I'll add links to them here when I get some time, or you can search by yourself).

**Comment by njoyard** [comment]
See #418 #137 for example

**Comment by gpapin** [comment]
Thanks for the quick feedback.
It's a shame I can't do it but at least I can stop trying now 😄

**Comment by njoyard** [comment]
Well if you read the linked issues, I found a solution that's quite working, but tedious to implement... The idea is to override the html seeking controls with a custom one and pass the time offset in the query when the user clicks. It's a bit clunky but it worked quite well.

**Comment by gpapin** [comment]
That would sort the second issue I have (moving the playback in the video) but even when I let the video play from naturally, Chrome keeps thinking it's 10 seconds long. Also, I noticed that clicking somewhere else on the control bar's timeline doesn't trigger another request, so I'm not sure how I would update the stream server's side.

In my scenario I have a lot of cpu free but not so much disk space so pre-encoding and store the video isn't really a solution. (I was working on this to be able to re-encode everything in the memory efficient x265 and then transcode it back on the fly)
