### ISSUE TITLE
ffprobe not working with stream input

### ISSUE THREAD

**Issue by ADaborn** [fluent-ffmpeg/node-fluent-ffmpeg#601]
I need to use ffprobe with a stream input, but it only seems to work with a filename. 

``` javascript
const ffmpeg = require('fluent-ffmpeg');
const fs = require('fs');

// Attempt to read metadata from a file using a stream (doesn't work)
const command = ffmpeg(fs.createReadStream('test.mp3'));
command.ffprobe(function (err, data) {
    if (err)
        console.error('\nERROR[1]: ' + err);
    else
        console.log('\nMETADATA[1]: ' + JSON.stringify(data));
});

// Attempt to read metadata from the same file using a filename (this works)
const fileCommand = ffmpeg('test.mp3');
fileCommand.ffprobe(function (err, data) {
    if (err)
        console.error('\nERROR[2]: ' + err);
    else
        console.log('\nMETADATA[2]: ' + JSON.stringify(data));
});
```

The output is here:

```
ERROR[1]: Error: write EOF

METADATA[2]: {"streams":[{"index":0,"codec_name":"mp3","codec_long_name":"MP3 (MPEG audio layer 3)","profile":"unknown","codec_type":"audio","codec_time_base":"1/44100","codec_tag_string":"[0][0][0][0]","codec_tag":"0x0000","sample_fmt":"s16p","sample_rate":44100,"channels":1,"channel_layout":"mono","bits_per_sample":0,"id":"N/A","r_frame_rate":"0/0","avg_frame_rate":"0/0","time_base":"1/14112000","start_pts":0,"start_time":0,"duration_ts":2489282712,"duration":176.39475,"bit_rate":64000,"max_bit_rate":"N/A","bits_per_raw_sample":"N/A","nb_frames":"N/A","nb_read_frames":"N/A","nb_read_packets":"N/A","disposition":{"default":0,"dub":0,"original":0,"comment":0,"lyrics":0,"karaoke":0,"forced":0,"hearing_impaired":0,"visual_impaired":0,"clean_effects":0,"attached_pic":0}}],"format":{"filename":"test.mp3","nb_streams":1,"nb_programs":0,"format_name":"mp3","format_long_name":"MP2/3 (MPEG audio layer 2/3)","start_time":0,"duration":176.39475,"size":1411158,"bit_rate":64000,"probe_score":51,"tags":{"title":"20140913_wesat_can_a_cow_even_","artist":"NPR","genre":"Blues"}},"chapters":[]}
```

This is running on Windows10, with node 5.7.0, fluent-ffmpeg 2.1.0

Looking at the code in ffprobe.js, ffprobe.exe is being called correctly, but stdin is throwing the error after only a couple of chunks have been read from the input stream. The ffprobe output has been correctly streamed to stdout and parsed, but because we received an error and made the callback, the code will NOT make callback a second time and return the result.

ie, because of the error picked up here:

``` javascript
// Skip errors on stdin. These get thrown when ffprobe is complete and
// there seems to be no way hook in and close stdin before it throws.
ffprobe.stdin.on('error', function (err) {
    if (['ECONNRESET', 'EPIPE'].indexOf(err.code) >= 0) {
        return;
    }
    handleCallback(err);                    
});
```

...the second call to handleCallback() at the end of processing won't pass anything back, so we get nothing.

``` javascript
function handleExit(err) {
...populate data with contents from stdout...
handleCallback(null, data);
```

I cannot see how it can EVER work...but it obviously does for some people. I can't figure out why. Maybe because I'm running on Windows?

**Comment by njoyard** [comment]
Maybe @timdp or @chazmo03 have an idea ?

**Comment by timdp** [comment]
Definitely used to work on Windows for me. I don't think I was using it with a file stream though (we used it with S3), although I might have done in experiments. Aren't there tests? I can't remember.

**Comment by njoyard** [comment]
I can't remember either unfortunately :/

**Comment by chazmo03** [comment]
I also used this with S3, not on the file system. I just ran your sample code and I don't get either the ERROR[1] or METADATA[1] callbacks. I'm running v0.10 on OSX. I'm running off a different [branch](https://github.com/chazmo03/node-fluent-ffmpeg#side-data). I just ran your sample against it and it calls both METADATA callbacks.

**Comment by leeroybrun** [comment]
I was getting the same error on Windows with an input stream (from WebTorrent).

I added `EOF` to the array of ignored errors for ffprobe (https://github.com/leeroybrun/node-fluent-ffmpeg/commit/d090e83209b0ef463f68f5aa3d23a5dccad659f9)

Now it works and I can get the metadata of the stream.

I don't know what this error really means and if it should be ignored like `ECONNRESET` and `EPIPE`, but seems to works this way.

**Comment by llcat** [comment]
> I was getting the same error on Windows with an input stream (from WebTorrent).
> 
> I added `EOF` to the array of ignored errors for ffprobe ([leeroybrun@d090e83](https://github.com/leeroybrun/node-fluent-ffmpeg/commit/d090e83209b0ef463f68f5aa3d23a5dccad659f9))
> 
> Now it works and I can get the metadata of the stream.
> 
> I don't know what this error really means and if it should be ignored like `ECONNRESET` and `EPIPE`, but seems to works this way.

Thanks, this methods solve my problem, I work on azure function app with blob, met the same error!
