### ISSUE TITLE
video recorded by iPhone (quicktime format) causes "Error opening filters!" only if uses stream input

### ISSUE THREAD

**Issue by waterstar** [fluent-ffmpeg/node-fluent-ffmpeg#603]
Following code will cause "ffmpeg exited with code 1: Error opening filters!" while the one (commented out) with file input will not. Interestingly this happen only with the video recorded with iPhone but not the one created from iMovie. Is there a way to support streaming video recorded by iphone? Thanks.

```
   var fs = require('fs');
    var ffmpeg = require('fluent-ffmpeg');
    ffmpeg()
      .input(fs.createReadStream("../ffmpeg/ffmpeg_test.mov"))
      //.input('../ffmpeg/ffmpeg_test.mov') <-- this will work
      .output('./output.divx')
      .preset('divx')
      .on('end', function() {
        console.log('file has been converted succesfully');
        res.ok();
      })
      .on('error', function(err) {
        console.log('error: ' + err.message);
      })
      .run();

```

**Comment by njoyard** [comment]
Can you paste the full stderr output, please?

**Comment by waterstar** [comment]
"ffmpeg exited with code 1: Error opening filters!" is all I get. I am not sure how to get more details debug output.

**Comment by waterstar** [comment]
Some additional info after look into ffmpeg logging flag:

```
cat ../ffmpeg/ffmpeg_test.mov | ffmpeg -pix_fmt yuv420p -analyzeduration 4G -probesize 4G -i pipe: ./output2.mp4
ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --disable-lzma --enable-vda
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Option pixel_format not found.
```

**Comment by wisecolt** [comment]
Hello there. I also could not find a way to run quicktime files with fluent-ffmpeg. Sample..


`
var fs = require('fs');
var ffmpeg = require('fluent-ffmpeg');
ffmpeg()
.input(fs.createReadStream("video.mov"))
//.input('../ffmpeg/ffmpeg_test.mov') <-- this will work
.output('output.flv')
.on('end', function() {
  console.log('file has been converted succesfully');
})
.on('error', function(err) {
  console.log('error: ' + err.message);
})
.run();
`

**Comment by njoyard** [comment]
@wisecolt please open a separate issue (I think you already did but just in case...)

@waterstar i'm closing this issue as it is getting very old. If you still have a problem feel free to reopen.
