### ISSUE TITLE
command.kill is not a function [issue]

### ISSUE THREAD

**Issue by ibrahimsaqr** [fluent-ffmpeg/node-fluent-ffmpeg#604]
hi, all :)

the fluent-FFmpeg plugin works gr8 but when trying to kill the process I have this error "comman.kill is not a function"

so here is my code

```js
var command = ffmpeg('http://ip:8008')
            .format('mpeg1video')
            .size('640x480')
            .videoBitrate('800k')
            .fps(25)
            .on('error', function(err) {
                console.log('An error occurred: ' + err.message);
            })
            .pipe()
            .on('data', function(chunk) {
                  // emit to spacific user
            });
setTimeout(function(){
      command.kill('SIGKILL');
}, 10000);
```

and when console.dir(command) I can't find anything related to kill() or process ID.

so what I need is to kill the process or grab the PID to kill it manually.

thanks for your help 👍

**Comment by njoyard** [comment]
You're setting command to `ffmpeg()....pipe().on('data', ...)`.
`pipe()` returns the output stream, and the 'on' method on streams returns nothing. So there you have it :)
