### ISSUE TITLE
Can't use ffprobe show_frames arguments

### ISSUE THREAD

**Issue by pierreprevoteau** [fluent-ffmpeg/node-fluent-ffmpeg#608]
I was trying to read the 120 firsts frames of a video with ffprobe by passing the -show_frames arg and a read interval with something like this : https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/383
But data always return undefined.
Did I missed something ? 

Thanks !

**fluent-ffmpeg : v2.1.0**
**ffmpeg : v3.1.3**
**macOS**

```
ffmpeg(input.mov).ffprobe(['-read_intervals 00:00%+#120', '-show_frames'], function(err, data) {
console.log(data);
});
```

also tried

```
ffmpeg(input.mov).ffprobe(['-read_intervals 00:00%+#120 -show_frames'], function(err, data) {
console.log(data);
});
```

**Comment by njoyard** [comment]
The ffprobe method in fluent-ffmpeg. does not allow arbitrary ffprobe calls. You should use node-ffprobe for more specific needs.
