### ISSUE TITLE
pipe:1 for aiff leaving file corrupt

### ISSUE THREAD

**Issue by jmahmud** [fluent-ffmpeg/node-fluent-ffmpeg#613]
Hi

I am trying to convert a wav to an aiff and via memory streams (using npm package: memorystream).  This works for converting wav to mp3, but when I do it for aiff, the file is corrupted.  If I instead write to file, it only works if I add a second output of 'tmp.mp3' and the aiff is not corrupted anymore.

Then command that gets generated when I use the memory stream is:
`
ffmpeg -i ./inputwav -y -f aiff -id3v2_version 3 -write_id3v2 1 -metadata "title=My Track Title" pipe:1
`

Any ideas why aiff may be corrupted?

Thanks
Josh

**Comment by njoyard** [comment]
Looks like an issue with ffmpeg, not fluent-ffmpeg. Please try the same thing in command line first.

**Comment by jmahmud** [comment]
Hi 

Yes, it seems that ffmpeg pipe to the stdout when piped to a file does not write out the header properly (particularly for wavs and aiffs) - tried doing this directly with ffmpeg and piped to the file and the same issue occured.

Thanks for the reply.

Josh

**Comment by njoyard** [comment]
Maybe there's an option to force writing the header? Have a look at the ffmpeg doc.
