### ISSUE TITLE
Unable to convert m4a to mp3 through streams but works with file path

### ISSUE THREAD

**Issue by anurag-gethullo** [fluent-ffmpeg/node-fluent-ffmpeg#615]
When I run fluent-ffmpeg with file path, it gives me an proper output, but while running the same script with file stream reader it generates an mp3 which only contains ffprob `ID3 TXXX major_brandM4A TXXX minor_version512TXXX compatible_brandsisomiso2TSSE Lavf57.41.100`
My code is:
var fileReader = fs.createReadStream(__dirname + "/audio.m4a");
        var tp = ffmpeg(fileReader)
            .withNoVideo()
            .inputFormat('m4a')
            .audioCodec('libmp3lame')
            .audioBitrate(128)
            .format('mp3')
            .on('error', (err) => console.error(err))
            .on('end', () => console.log('Finished!'))
            .save(fs.createWriteStream("audio.mp3"));

The wired thing for me is why the same audio.m4a is working great with file path, but not working with streams? FYI i am working on my local machine.

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
