### ISSUE TITLE
Can't live stream with FacebookAPI

### ISSUE THREAD

**Issue by lufivuahaitac** [fluent-ffmpeg/node-fluent-ffmpeg#618]
Does anyone have solutions to stream video file (eg: mp4) to Object Video Facebook API?
`	var publish = res.stream_url;

	// make sure you set the correct path to your video file
	var proc = ffmpeg(infs)
	  .format('mp4')
	  .size('320x?')
	  .videoBitrate('512k')
	  .videoCodec('libx264')
	  .fps(24)
	  .audioBitrate('96k')
	  .audioCodec('aac')
	  .audioFrequency(22050)
	  .audioChannels(2)
	  // setup event handlers
	  .on('end', function() {
		console.log('file has been converted succesfully');
	  })
	  .on('error', function(err) {
		console.log('an error happened: ' + err);
		})
	  // save to stream
	  .save(publish);`
**an error happened: ffmpeg exited with code 1:**

**Comment by geraldoramos** [comment]
same happening to me...

**Comment by lufivuahaitac** [comment]
`.format('flv')
Change .format('flv') instead .format('mp4')

**Comment by njoyard** [comment]
You can read more about the error by looking at other arguments to the "error" event (see doc). Closing this as it looks like it has been solved.
