### ISSUE TITLE
partial read stream not working

### ISSUE THREAD

**Issue by hasanlsn** [fluent-ffmpeg/node-fluent-ffmpeg#619]
Hi,

i am trying to stream video but no chance so far.

Here is my code
    
   var filePath = null;
   filePath       = config.files.cls.videoBasePath + classVideo;
   var stat       = fs.statSync(filePath);
   var total      = stat.size;
   
    var range          = req.headers.range;
    var parts           = range.replace(/bytes=/, "").split("-");
    var partialstart = parts[0];
    var partialend  = parts[1];

    var start         = parseInt(partialstart, 10);
    var end           = partialend ? parseInt(partialend, 10) : total-1;
    var chunksize = (end-start)+1;

    res.writeHead(206,
     {
      'Content-Range'  : 'bytes ' + start + '-' + end + '/' + total,
      'Accept-Ranges'  : 'bytes',
      'Content-Length' : chunksize,
      'Content-Type'     : 'video/mp4'
     }
    );

    var file = fs.createReadStream(filePath);

    ffmpeg(file)
    .videoFilters({
     filter: 'drawtext',
     options: {
      fontsize:20,
      fontfile: 'public/fonts/Roboto-Black.ttf',
      text: req.cookies.IEUSERNAMESURNAME,
      x:10,
      y:10,
      fontcolor:'red'
     }})
     .format('mp4')
     .outputOptions(['-frag_duration 100','-movflags +faststart','-pix_fmt yuv420p'])
     .videoCodec('libx264')
     .audioCodec('copy')
     .size('640x?')
     .aspect('4:3')
     .on('error', function(err, stdout, stderr) {
      console.log('Cannot process video: ' + err.message + stderr);
     })
     .output(res).run();

When i run this code, gives me this error

Cannot process video: ffmpeg exited with code 1: Error opening filters!
ffmpeg version git-2016-10-06-0919151 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-17)
  configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --extra-libs=-ldl --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libfreetype --enable-libspeex --enable-libtheora
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 60.101 / 57. 60.101
  libavformat    57. 51.102 / 57. 51.102
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 63.100 /  6. 63.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xbf363a0] stream 1, offset 0x30: partial file
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xbf363a0] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 640x480, 966 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:0':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf53.24.2
  Duration: 00:00:31.00, bitrate: N/A
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), none, 640x480, 966 kb/s, 25 fps, 25 tbr, 12800 tbn, 25600 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 383 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
[buffer @ 0xbf5c040] Unable to parse option value "-1" as pixel format
    Last message repeated 1 times
[buffer @ 0xbf5c040] Error setting option pix_fmt to value -1.
[graph 0 input from stream 0:0 @ 0xbf767c0] Error applying options to the filter.
Error opening filters!

So, what am i doing wrong? Is there any other way to draw text into video? 
Thanks for your help.

**Comment by njoyard** [comment]
It looks like ffmpeg fails to parse the input pixel format. Have you tried using a file input instead of a stream input ? If your input file has "headers" at the end, it would explain why ffmpeg fails to decode it when passed as a stream.

**Comment by njoyard** [comment]
Closing as no further information was provided. Please reopen if needed.
