### ISSUE TITLE
System reboots during ffmpeg tool installation

### ISSUE THREAD

**Issue by rajasuba** [fluent-ffmpeg/node-fluent-ffmpeg#620]
I have enabled QSV with reference of the streambuilder's enabling-iqsv docs.

**Reference** : http://streambuilder.pro/docs/requirements/enabling-iqsv/

**MACHINE DETAILS**

**Server** : Intel(R) Xeon(R) CPU E3-1285 v4 3.50GHz w/ Supermicro X10SLH-F

**Kernel** : Linux 3.10.0-229.1.2.44985.MSSr7.el7.centos.x86_64 #1 SMP Wed Nov 9 16:26:25 PST 2016 x86_64 x86_64 x86_64 GNU/Linux

I have installed ffmpeg with --enable-nonfree --enable-libmfx configurations, configuration command was successfully done.Then, I invoke make and our server gets hanged in few seconds and it will gets rebooted automatically.

I feel it might be compilation issue with make script.
```

./configure --prefix="/usr/ffmpeg" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/bin" --pkg-config-flags="--static" --enable-nonfree --enable-libmfx
make 
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2068, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn()                          = 2068
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
stat("libavcodec/intrax8dsp.o", {st_mode=S_IFREG|0644, st_size=82840, ...}) = 0
stat("libavcodec/ituh263dec.o", 0x7ffff86affb0) = -1 ENOENT (No such file or directory)
stat("libavcodec/ituh263dec.c", {st_mode=S_IFREG|0644, st_size=38617, ...}) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
vfork()                                 = 2072
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, CC libavcodec/ituh263dec.o

```
I have attached [config.log](https://drive.google.com/open?id=0B1N73zJVTNRnNG1Md2daZ0EzNU0) and [FFMPEG-MAKE-TRACE.log](https://drive.google.com/open?id=0B1N73zJVTNRnWTVMcW5jN0VNVDA) file.

**Comment by njoyard** [comment]
Hello,
This is a ffmpeg bug, please report it to the ffmpeg community.
