### ISSUE TITLE
Bug: end event called twice

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#623]
Seeing this error log from my app (thanks to the async lib it threw that error):

```
/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/async/internal/onlyOnce.js:9:32
    at (removed)
    at (removed)
    at emitTwo (events.js:106:13)
    at FfmpegCommand.emit (events.js:191:7)
    at emitEnd (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/fluent-ffmpeg/lib/processor.js:421:16)
    at endCB (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/fluent-ffmpeg/lib/processor.js:584:15)
    at handleExit (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/fluent-ffmpeg/lib/processor.js:165:11)
    at ChildProcess.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/fluent-ffmpeg/lib/processor.js:179:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
ffmpeg comand was a simple mux of two inputs:

$ ffmpeg -i /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-ab00-9f44ba50-ba4a-ad713badb2d0/videomail_preview.webm -i /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-ab00-9f44ba50-ba4a-ad713badb2d0/videomail_preview_for_webm_stretched.wav -y -c copy -shortest /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-ab00-9f44ba50-ba4a-ad713badb2d0/videomail_preview.webm

Probably a bug?

**Comment by binarykitchen** [comment]
looks like the `captureStdout` option is messing here calling handleExit() upon stream close

**Comment by njoyard** [comment]
Can you please show the code used to trigger this behaviour ?

**Comment by binarykitchen** [comment]
@njoyard hard to reduce this here into a simple case - using the code in a complex server side application :(

**Comment by binarykitchen** [comment]
i could give you access to this private repo but that's probably too cumbersome - let me know

**Comment by njoyard** [comment]
There's no way I can analyze, let alone fix, a case without reproducing code. If your code is so complex that you cannot derive a simple test case, the probability the problem actually comes from your code is quite high.

I'm closing this, feel free to reopen if you have a reproductible test case.

**Comment by binarykitchen** [comment]
Fair enough - totally understand

**Comment by friddle** [comment]
function recongize(audioPath,callback)
{
    var format="wav";
    var m4a_path=audioPath.replace("file://","").replace("mp3",format)
  console.log("set parse:audioPath:\t"+audioPath+":\t output_path"+m4a_path)
   var writeStream=fs.createWriteStream(m4a_path);
   writeStream.close()
   ffmpeg(audioPath).inputFormat('mp3')
    .audioChannels(1).audioBitrate("64k")
    .audioFrequency("16k")
    .toFormat(format)
    .save(m4a_path)
     .on('end', ()=>{recongize_callback(m4a_path,format,callback)})
     .execute()
}

async function recongize_callback(m4a_path,format,callback)
{
  var stats = fs.statSync(m4a_path)
  var fileSize = stats["size"]
  var content=fs.readFileSync(m4a_path, {encoding: 'base64'})
  let info=await speechApi.speechReg(content,fileSize,format)
  callback(info)
}

recongize_callback open twice
![Uploading image.png…]()
