### ISSUE TITLE
ffprobe emits empty error

### ISSUE THREAD

**Issue by rufengch** [fluent-ffmpeg/node-fluent-ffmpeg#624]
I was trying to use ffprobe to retrieve metadata. Here's my code.

```javascript
        ffmpeg.ffprobe(mediaSrc, (err, metadata) => {
          if (err) {
            logError('ffprobe failed', err);
          } else {
            logger.info('Metadata:');
            logger.info(metadata);
          }
        });
```

The result is `ffprobe failed`, but `err` is an empty object.

What does this empty `err` mean?

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
