### ISSUE TITLE
How to achieve multiple video concatenation with blank video in between as per the required duration?

### ISSUE THREAD

**Issue by HemanthAnakapalle** [fluent-ffmpeg/node-fluent-ffmpeg#626]
Hi,

Scenario:
======
Consider like, while recording a video, we have multiple network disconnections in between ... which results in generating multiple files (mkv format) , which are all related to a single video.

Requirement:
========
How to concatenate all these separate files into a single video, along with a empty video with a note saying "network disconnect" in between.

And also note that "empty video duration" in between the files, will vary as per the network disconnect time.

We are thinking to generate a "single empty file with the maximum network disconnection time" and use it in rest all places by specifying the duration of the video to be considered. Is this the right approach ? ... If not ... what are the suggestions ?

Also note that, we should not alter any of the parameters of the actual video like resolution, aspect ratio etc.

Can we have a sample JavaScript code to meet this requirement ?

Thanks,
Hemanth

**Comment by njoyard** [comment]
Hi,

I think ffmpeg is capable of generating blank video segments and rendering text on them. You should look in the [ffmpeg documentation](http://ffmpeg.org/ffmpeg-all.html) and try to achieve your goal with command line ffmpeg first. When you have a working solution, try to convert it to the fluent-ffmpeg API and feel free to (re)open issues here for help.
