### ISSUE TITLE
Get 'would be' command line before running the command

### ISSUE THREAD

**Issue by kschiffer** [fluent-ffmpeg/node-fluent-ffmpeg#627]
I am trying to get the ffmpeg command line that fluent-ffmpeg would compose if I used the run() command. Is there any way to achieve this?

**Comment by njoyard** [comment]
Yes, but that's not part of the API and may break at any time:
```js
command._prepare(function(err, args) { /* "args" contain your comand line */ } , false);
```
Otherwise use the `start` event and kill the command immediately.

**Comment by kschiffer** [comment]
Oh that's nice. Thank you! I will go with this and switch to the workaround in case it should break. However, I think a function like this might come in handy for others as well.

**Comment by njoyard** [comment]
Feel free to propose a PR :)
