### ISSUE TITLE
Screenshot name : using %s creates variable length numeric values

### ISSUE THREAD

**Issue by manquer** [fluent-ffmpeg/node-fluent-ffmpeg#628]
creating screenshots by using count option ( i.e. automatically evenly distributing across the file) 
and using the %s parameter generates inconsistent length, long integer names like
```
basename_11.806666599999998.png
base_23.613333199999996.png
base_35.4199998.png
base_47.22666639999999.png
```
The number of decimal points should be controllable , or more ideally it should take the nearest second or at least named so.

**Comment by njoyard** [comment]
That's an ffmpeg issue. Please look for a solution in the [ffmpeg documentation](http://ffmpeg.org/ffmpeg-all.html) or ask the question to the ffmpeg community :)
