### ISSUE TITLE
Exit node script after save.

### ISSUE THREAD

**Issue by swordsreversed** [fluent-ffmpeg/node-fluent-ffmpeg#629]
Hi, I have a simple problem but i cant figure out the right way to solve it. I want to exit my script after saving:

```
var RecordStream = new Ffmpeg({ source: stream })
      .setDuration(duration)
      .withAudioCodec('libfdk_aac') // TODO make these nconf vars?
      .withAudioBitrate('64k')
      .outputOptions('-movflags +faststart')
      .on('end', function () {
        console.log('ended recording at ' + moment().format());
      })
      .save(file);
      process.exit(0);
```

however the process.exit closes the script immediately and i can't run a callback within save. Anyone know what I should do here?

**Comment by njoyard** [comment]
Just put your exit call inside the 'end' handler
