### ISSUE TITLE
Layering 2 Audio Files

### ISSUE THREAD

**Issue by vegnabeast** [fluent-ffmpeg/node-fluent-ffmpeg#631]
I am not sure whether I am just missing something but there doesnt seen to be any method of layering Two audio files into one.

For example I have:

Audio File 1: Music for a song
Audio File 2: Vocals for a song

And want them combined into one audio file containing both.

My first thought was to MergeToFile() and set the start of the second input to 0 but I dont see it working.

**Comment by njoyard** [comment]
That's an ffmpeg issue. Please find a way to do that with ffmpeg first and then try to convert it to fluent-ffmpeg :)

You will probably need the [amix filter](http://ffmpeg.org/ffmpeg-all.html#amix)
