### ISSUE TITLE
Concat webm video files server-side

### ISSUE THREAD

**Issue by SalvatoreAD** [fluent-ffmpeg/node-fluent-ffmpeg#632]
Hi, I am creating a video conferencing system with the recording. Each time interval (30 seconds) send the server a .webm files (audio + video) for each participant and would like concaterare the previous, already saved on the server, with that coming.
E 'can concatenate webm files without re-encoding ?.
I am using this code:

`fileBuffer = new Buffer(file.contents, "base64"); 
var logStream = fs.createWriteStream(filePathTMP, { 'flags': 'w' }); 
logStream.write(fileBuffer); 
var finalStream = fs.createWriteStream(filePath, {'flags': 'a' }); 
var proc = new ffmpeg()
.mergeAdd(filePathTMP)
.mergeToFile(filePath, function(){
console.log('files has been merged succesfully');
});`
I tried this code, but it does not work:

`var merge = ffmpeg();
    merge.input(filePathTMP)
        .inputOptions(['-f concat', '-safe 0'])
        .outputOptions('-c copy')
        .save(filePath);`

Can you help me? Thanks

**Comment by njoyard** [comment]
A few points to check:
* Are you sure all webm files have the exact same codecs ? WebM is just a format and supports various codecs.
* The 'concat' format that you use requires the input file to be a *text file* with a list of file paths to concatenate, one per line. I'm not sure you can use the 'copy' codec in this case, you may want to specify full codec and format options.

Also, I don't know your exact needs but it seems to me that concatenating 30s segments each time a new one comes in is not optimal. You will end up re-reading the whole recording each time. Maybe a better option would be to wait until the conference is finished and concatenate all segments at once then.

**Comment by SalvatoreAD** [comment]
webm file is created with mediastreamrecorder

**Comment by bohdanbirdie** [comment]
@SalvatoreAD  that's how i get all webm files from folder that created with `mediastreamrecorder`
` fs.readdir(`${tempPath}${folderName}`, (err, items) => { // returns the array of items in alphabetical order
    console.log(items)
    for (var i in items) {
      command.input(`${tempPath}${folderName}/${items[i]}`)
    }
    concat()
  })`

And concat function here
`command.mergeToFile(`${tempPath}${folderName}/out.mp4`)`

**Comment by SalvatoreAD** [comment]
I am using the mergetofile command, but it is very slow for large files. I wanted to find a faster method. Would you recommend any?

**Comment by bohdanbirdie** [comment]
@SalvatoreAD I'm not sure about that, but probably it's doesn't matter which command you using, FFmpeg take a lot of resources
I'm merging couple of files with 1 sec length each, render time sometimes depends on amount of free resources on you computer

**Comment by livey0u** [comment]
@SalvatoreAD, how did you solved it? Experiencing similar problem. mergetofile is very slow.

**Comment by SalvatoreAD** [comment]
I tried many solutions but in the end I changed technology, using a media server.-------- Messaggio originale --------Oggetto: Re: [fluent-ffmpeg/node-fluent-ffmpeg] Concat webm video files server-side (#632)Da: livey0u A: fluent-ffmpeg/node-fluent-ffmpeg CC: SalvatoreAD ,Mention @SalvatoreAD, how did you solved it? Experiencing similar problem. mergetofile is very slow.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fluent-ffmpeg/node-fluent-ffmpeg","title":"fluent-ffmpeg/node-fluent-ffmpeg","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fluent-ffmpeg/node-fluent-ffmpeg"}},"updates":{"snippets":[{"icon":"PERSON","message":"@livey0u in #632: @SalvatoreAD, how did you solved it? Experiencing similar problem. mergetofile is very slow. "}],"action":{"name":"View Issue","url":"https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/632#issuecomment-311018656"}}}

**Comment by livey0u** [comment]
@SalvatoreAD, media server meaning? If you dont mind, could you share more about that?

**Comment by njoyard** [comment]
I'm closing this issue as the problem seems no longer relevant. Feel free to continue discussing, though.
