### ISSUE TITLE
Scaling videos dont work properly 

### ISSUE THREAD

**Issue by daslicht** [fluent-ffmpeg/node-fluent-ffmpeg#633]
Hi, 
I have the following setup:

```
        let ratio = '4:3'
        let width = '150x?'
        let video_data = {
                ogv_path: output_path + output_filename + '.ogv',
                mp4_path: output_path + output_filename + '.mp4',
                webm_path: output_path + output_filename + '.webm'
            }
            
            ffmpeg()
                .input( tmp_path ) //that points to a mp4 file
                .size( width )
                .aspect( ratio )
                .output( video_data.ogv_path )
                .output( video_data.mp4_path )
                .output( video_data.webm_path ) 
                .on('end', () => {
                    resolve( video_data );
                })
                .on('error', (err, stdout, stderr)=> {
                    reject( err.message );
                })
                .run();
```

If I start that process i get 3 new files generated, but they are have different sizes :)
The ```mp4``` file is ```176 px``` wide which is the same as the original, followed by the ```webm``` which is smaller than the mp4. The ```ogv``` is the smallest.

Whats wrong here ?

Cheers Marc

**Comment by njoyard** [comment]
As stated in the documentation, [output-related options only apply to one output at a time](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputtarget-options-add-an-output-to-the-command), which is either:
* the last output that was added if any or,
* the first output when no output has been specified yet (for backwards compatibility reasons).

So your code will do what you expect by doing that instead:
```js
                .size( width )
                .aspect( ratio )
                .output( video_data.ogv_path )
                .output( video_data.mp4_path )
                .size( width )
                .aspect( ratio )
                .output( video_data.webm_path ) 
                .size( width )
                .aspect( ratio )
```
Or perhaps more readably, without using the backwards compatibility trick:
```js
                .output( video_data.ogv_path )
                .size( width )
                .aspect( ratio )
                .output( video_data.mp4_path )
                .size( width )
                .aspect( ratio )
                .output( video_data.webm_path ) 
                .size( width )
                .aspect( ratio )
```

You can do that in a loop if you don't like repeating yourself :)

**Comment by daslicht** [comment]
ahh ok , I need separate ```.size( width )```  ```.aspect( ratio )``` for each output?
