### ISSUE TITLE
progress event never fired

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#634]
With my very long ffmpeg command to encode a video based on image frames with a given fps, node-fluent-ffmpeg doesn't fire the progress event at all. Even when encoding can take minutes.

Any reasons why? Or is this by nature when using images? Happy to add more information, whatever it takes to find this out.

Thanks heaps :)

**Comment by binarykitchen** [comment]
Ah, it turns out that the progress event depends on the log level you have set. If it's set to `warning`, then you won't see any progress events. I think this should be documented.

And better, I think this should be isolated. The progress event should be fired, processed internally, regardless of the log level. Probably more work but more elegant I think ...

**Comment by njoyard** [comment]
No, I don't think the progress event depends on the log level at all. One thing that I can see is that the progress event handler must be registered before calling `save()` or `pipe()` or `run()` ; if you register the handler afterwards, progress events will not be emitted.

Closing this, if you have an example of code where progress events are emitted when **only** changing the log level, please paste it here :)

**Comment by binarykitchen** [comment]
hmmm, nope, that's not the case here. calling the run fn at the end. so must be something else ...

... i tested all over again and it seems the progress event isn't always fired. but more often fired when encoding larger files. for smaller videos, the event doesn't seem to get fired much often. is this a known issue?
