### ISSUE TITLE
Feature: forEach frames

### ISSUE THREAD

**Issue by AmitMY** [fluent-ffmpeg/node-fluent-ffmpeg#635]
I was looking at the doc, and could not find a method that returns all frames, or a single frame by index.
I probably missed it, as it seems like an obvious method, but after looking several times I can't find it.

I need to take every frame of a video, plus the audio chunk played in that frame.

**Comment by njoyard** [comment]
This library is an API to call the ffmpeg command line executable, not a video API. This feature will never happen unfortunately.

You can work around by first using ffmpeg to convert video to single images files, then loop over the images.
