### ISSUE TITLE
Map multiple audio tracks

### ISSUE THREAD

**Issue by Tweetgo** [fluent-ffmpeg/node-fluent-ffmpeg#637]
how to do it?

```
ffmpeg -i input.mkv \
    -map 0:0 -map 0:1 -map 0:1 -map 0:3 \
    -c:v copy \
    -c:a:0 libmp3lame -b:a:0 128k \
    -c:a:1 libfaac -b:a:1 96k \
    -c:s copy \
    output.mkv
```

**Comment by njoyard** [comment]
Not supported currently unless using filters. Use [`outputOptions`](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputoptionsoption-add-custom-output-options) in the mean time.
