### ISSUE TITLE
Automatic Rotation taking ScreenShot

### ISSUE THREAD

**Issue by fromcouch** [fluent-ffmpeg/node-fluent-ffmpeg#641]
Hi, I have a simple web page that upload videos and take screenshot of first frame. It's really a simple code:
```
                var ffmpeg = require('fluent-ffmpeg');
                ffmpeg('./' + req.file.path)
                    .on('filenames', function(filenames) {
                        console.log('Will generate ' + filenames.join(', '))
                    })
                    .on('end', function() {
                        console.log('Screenshots taken');
                    })
                    .screenshots({
                        count: 1,
                        folder: './images/posters',
                        filename: 'poster-%f.png',
                        size: "640x?"
                    });
```

The problem is when I upload videos from mobile devices screenshot is automatically rotated 90 degrees and I don't know why. I read Issue #322 but i can't figure how to add filter to my code without doing complex coding.

Any help? Thanks,

**Comment by njoyard** [comment]
That's a ffmpeg issue, you should try to do the same on command line and find a way in the ffmpeg documentation to cancel the auto rotate.

Maybe this is a good start: http://stackoverflow.com/questions/9408542/video-captured-from-iphone-gets-rotated-when-converted-to-mp4-using-ffmpeg

**Comment by fromcouch** [comment]
Hi @njoyard ,

thanks, not helping link. I'm using docker with a node:latest image and a really complex Dockerfile. I'm trying to simplify all process as possible and installation of ffmpeg is with apt-get. 

Aptitude are installing 2.6.9 version and the only purpose of ffmpeg is taking screenshot of first frame of video using your library. No more actions with ffmpeg. If you know how to install in other way with only one line to avoid video rotation I will appreciate. 

I'm very confused with this library and ffmpeg. To much options.

Regards,

**Comment by njoyard** [comment]
Well, this is just a JS API interface to ffmpeg, so you really have to understand ffmpeg before using fluent-ffmpeg :)

**Comment by fromcouch** [comment]
I see, solved, thanks.
