### ISSUE TITLE
Add stdout parameter to the error event

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#642]
Currently the error event has the `err` parameter. But for internal error handling would be also good to have the `stdout` parameter. Because I often need to see the whole ffmpeg output to find out what caused the error.

**Comment by njoyard** [comment]
See https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#error-transcoding-error

**Comment by binarykitchen** [comment]
ah, thanks
