### ISSUE TITLE
Some flags don't have equivalent function

### ISSUE THREAD

**Issue by rightaway** [fluent-ffmpeg/node-fluent-ffmpeg#643]
Some ffmpeg command-line flags, like `-xerror`, and `-abort_on empty_output` and `-y` (to overwrite files without asking), don't seem to have any equivalent function in node-fluent-ffmpeg. Is it still possible to use these flags from node?

**Comment by njoyard** [comment]
Use [`outputOptions()`](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputoptionsoption-add-custom-output-options). And read the documentation, please :)
