### ISSUE TITLE
Video To Frames

### ISSUE THREAD

**Issue by fcb2** [fluent-ffmpeg/node-fluent-ffmpeg#646]
Is there any way to convert a video to images using fluent ffmpeg? Example am having a video with total duration 60 seconds. I want images between different set of duration like between 2-6 seconds, then between 15-24 seconds and so on. Is that possible using ffmpeg?

**Comment by njoyard** [comment]
That's an ffmpeg usage question. Please refer to the ffmpeg docs and community.
