### ISSUE TITLE
Help with Drawbox filter

### ISSUE THREAD

**Issue by leozino** [fluent-ffmpeg/node-fluent-ffmpeg#652]
Alo,
Could use any help using the drawbox filter. 
I'm able to use drawtext as a videoFilters and also as a complexFilter
However, I want to add a box around the text and I'm unable to.

The ffmpeg command that works is:

`-vf \
	"format=yuv444p, \
	 drawbox=y=ih/PHI:color=black@0.4:width=iw:height=48:t=max, \
	  drawtext=fontfile=OpenSans-Regular.ttf:text=$2'Title of this Video':fontcolor=white:fontsize=24:x=(w-tw)/2:y=(h/PHI)+th, \
	   format=yuv420p" \
`

what I have tried in node is 
`.complexFilter([
{
  filter: 'drawtext',
  options: {
    fontfile:'/usr/share/fonts/TTF/UbuntuCondensed-Regular.ttf',
    text: 'THIS IS TEXT',
    fontsize: 30,
    fontcolor: 'white',
    x: '(main_w/2-text_w/2)',
    y: 'main_h-(text_h*2)',
    shadowcolor: 'black',
    shadowx: 2,
    shadowy: 2
  }
},
{
filter: 'drawbox',
options:{
    x: '(main_w/2-text_w/2)',
    y: 'main_h-(text_h*2)',
color:'black@0.4', 
width:'main_w/2',
height:48,
t:'max',
}

}])`

The error I get back is
`An error occurred: ffmpeg exited with code 1: Cannot find a matching stream for unlabeled input pad 0 on filter Parsed_drawbox_1`

Any help would be greatly appreciated,
thanks in advanced.

**Comment by yisalk** [comment]
The options you are using are not valid for the drawbox. You should use the following options
`const ffmpeg = require('fluent-ffmpeg');
 ffmpeg(filePath).videoFilter({ //here filepath the variable containing file path
        filter: 'drawbox',
        options: {
          w: 640, //width
          h: 480,// height
          x: 0, //x-axis position
          y: 40, //y-axis position
          color: 'violet' //color of the box
        }
      })`

Hopefully, it will work for you. Thanks
