### ISSUE TITLE
error: ffmpeg exited with code 1

### ISSUE THREAD

**Issue by jessicaleyland8** [fluent-ffmpeg/node-fluent-ffmpeg#654]
Im running the below code: 

var source = "input/video.mp4";
var name = req.user.facebook.name;
var profileImage = req.user.facebook.photo;

var time = Date.now();
var rand = Math.floor((Math.random() * 100) + 1);
var filename = 'outputfile'+time+''+rand+'.mp4';

ffmpeg(source)
			.on('error', function(err, stdout, stderr) {
					console.log('error: ' + err.message);
					console.log('stdout: ' + stdout);
					console.log('stderr: ' + stderr);
			})
			.input(profileImage)
			.complexFilter([
				{
				 filter: 'overlay',
				 options: {
					 enable: 'between(t,8,10)',
					 x: 'W-w-10',
					 y: 'H-h-10'
				 },
				 outputs: 'watermark'
			 },
			 {
				 filter: 'drawtext',
				 options: {
					 enable: 'between(t,8,10)',
					 fontfile: 'assets/fonts/FuturaStd-Bold.otf',
					 text: name,
					 fontsize: 20,
					 fontcolor: 'white',
					 x: '(main_w/2-text_w/2)',
					 y: '340-(text_h/2)',
					 shadowcolor: 'black@0.5',
					 shadowx: 2,
					 shadowy: 2
				 },
				 inputs: 'watermark'
			 }
			])
			.output('exports/'+filename+'')
			.on('end', function() {
					// video has finished processing
					console.log('Finished processing');
					// redirect to end/complete page
					res.redirect('/complete?videosrc=' + filename);
			}).run();

it works fine locally but on my Apache server I get: 

error: ffmpeg exited with code 1
stdout: undefined
stderr: undefined

**Comment by njoyard** [comment]
Have you tried doing the same on command line ? Does it give different results ?

**Comment by njoyard** [comment]
No further info provided, closing.
