### ISSUE TITLE
error using ffprobe ( "Error: { [Error: spawn /usr/local/bin/ffprobe ENOENT]")

### ISSUE THREAD

**Issue by ndonnipa** [fluent-ffmpeg/node-fluent-ffmpeg#659]
has anyone had success dealing with the following error message:

 "Error: { [Error: spawn /usr/local/bin/ffprobe ENOENT]"

My code: 

  ffmpeg.setFfprobePath("/usr/local/bin/ffprobe");
  ffmpeg.ffprobe('path', function(err, metadata) {
    console.log('Error:', err);
    console.log('Metadata', metadata);
  });

when I comment out the probePath, I get the following error then:

"Error: [Error: Cannot find ffprobe]". 

I have done "which ffmpeg" and "which ffprobe" commands to get my paths. I have also tried doing a setFfmpegPath and I keep getting this error. I am using a mac if that helps. 

Any help would be appreciated

**Comment by njoyard** [comment]
Are you sure /usr/local/bin/ffprobe exists and is executable ?

**Comment by jasan-s** [comment]
Im having the same issue on win 10 x64

**Comment by njoyard** [comment]
No further info, closing. @jasan-s this is not the same platform, please open a separate issue.
