### ISSUE TITLE
var FfmpegCommand = require('fluent-ffmpeg'); is giving error Usage: npm <command> Error

### ISSUE THREAD

**Issue by Nikmike** [fluent-ffmpeg/node-fluent-ffmpeg#660]
I have installed FFmpeg and also installed " npm install fluent-ffmpeg" .  when i run above code using JS it gives me FOllowing Error:

**ERROR**
C:\Users\GORDEN\Desktop>npm FFmpeg.js

Usage: npm <<'command'>>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\GORDEN\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 C:\Program Files\nodejs\node_modules\npm

**How can you produce it** :
1> Create one Js file on desktop "ffmpeg.js"
2> add below lines of code in it 👍 

var FfmpegCommand = require('fluent-ffmpeg');
var command = new FfmpegCommand();
console.log("Program Ended");

3>run this js using following command
C:\Users\GORDEN\Desktop>npm FFmpeg.js

4> please attached JS as well

[New Text Document.txt](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/files/756825/New.Text.Document.txt)

**Comment by njoyard** [comment]
Hi, you're not using npm correctly. Please read its documentation first.
