### ISSUE TITLE
Need a nice stop. SIGSTOP not working

### ISSUE THREAD

**Issue by rd4k1** [fluent-ffmpeg/node-fluent-ffmpeg#662]
I figured out how to get gdigrab to hls, but now I need a nice way to stop the process so ffmpeg finishes where it currently is and adds "#EXT-X-ENDLIST" to the m3u8

The code I'm testing with:
```javascript
var stream = ffmpeg({source: './lookatthosetits.png', timeout: 432000});
stream
	.inputOptions([
		'-f gdigrab',
		'-i desktop'
	])
	.videoBitrate(1500)
	.videoCodec('libx264')
	.addOption('-hls_time', 1)
	.addOption('-hls_list_size', 6)
	.addOption('-hls_flags', 'split_by_time')
	.on('end', function(){
		console.log('converted');
	})
	.on('error', function(err){
		console.error(err);
	}).
	output('./http/live/stream.m3u8');

function start(){
	stream.run();
}
function stop(){
	stream.kill('SIGSTOP'); //Error: Unknown signal: STOP
}

start();
setTimeout(stop, 5000);

```
SIGSTOP doesn't work. Am I doing that wrong and/or is there another way to quit ffmpeg like 'q' or 'ctrl+c'?

**Comment by rd4k1** [comment]
I just found one way to do this, but is this the best way?
```javascript
function stop(){
	stream.ffmpegProc.stdin.write('q');
}
```

**Comment by synweap15** [comment]
Hey, this approach looks interesting and seems to work. The problem I see here is that the 'end' event will be emitted instead of 'error', which would be expected as the process was interrupted.

**Comment by njoyard** [comment]
Well the process actually terminated itself normally following a user request.
I'd even consider that solution as a new feature for fluent-ffmpeg (but I really don't have much free time these days). If anyone wants to make a PR ;)

(oh btw that won't work when working with a stream input, stdin is used for the input in that case)

**Comment by rd4k1** [comment]
It did work actually. It stopped the stream and made a playlist end tag as expected if you hit q or ctrl+c in ffmpeg directly.

I'm on to doing webrtc streaming now though. I'll probably use fluent-ffmpeg for streaming to rtmp for other platforms
