### ISSUE TITLE
Fluent-ffmpeg on windows

### ISSUE THREAD

**Issue by thalescast** [fluent-ffmpeg/node-fluent-ffmpeg#663]
Firstly, I'd like to thank the module and say that it has been very useful for an application developed in my linux. However now I'd like to move to windows and have given a bug that I have not been able to identify. The error is NaN and is in the following code snippet:

`    var ffmpeg = require('fluent-ffmpeg');

    ffmpeg({ source: arquivo_original })

        .setStartTime(inicio)
        .setDuration(duracao_final)
        .output('inicio_cortado.webm')
    
        .on('end', function(err) {
            if (!err) {
                console.log('conversion Done');
                document.getElementById("wait").style.display = "none";
                vex.dialog.alert("Conversão realizada com sucesso")

                //var video = document.getElementById('video').setAttribute('src', '../inicio_cortado.webm')
                /* Quando se faz o deploy a pasta corrente fica dois níveis acima da app */
                var video = document.getElementById('video').setAttribute('src', '../../../inicio_cortado.webm')

                // SETO VALOR COMO TRUE PARA PODER INFORMAR QUE A PRIMEIRA PARTE FOI CORTADA
                video_parte_1_cortado = true // Sera usado na segunda parte 
            
            }

        })
        .on('error', function(err, stdout, stderr) {
            console.log('error: ', + err.message);
            console.log('error: ', + stdout);
            console.log('error: ', + stderr);
            document.getElementById("wait").style.display = "none";
            vex.dialog.alert("Erro: verifique os tempos. É necessário informar o tempo de duração correto")
            

        }).run();  `

**Comment by njoyard** [comment]
What does "the error is NaN" mean ?
What is the output from ffmpeg (stdout/stderr) ?

**Comment by njoyard** [comment]
Closing, no further info given.
