### ISSUE TITLE
does ffprobe have a on("end")?

### ISSUE THREAD

**Issue by ndonnipa** [fluent-ffmpeg/node-fluent-ffmpeg#664]
I am using the "ffmpeg.ffprobe(input, function(err, metadata) {" to get the duration of a video input and within this I am doing the ffmpeg(input).on stuff. My question is does ffprobe also have a .on("end") funnctionality. I think I am running into an issue where ffmpeg terminates but not ffprobe. any help?

**Comment by njoyard** [comment]
The callback function is called when ffprobe ends. There is no event facility on ffprobe calls.
