### ISSUE TITLE
Unable to create video from images with different duration

### ISSUE THREAD

**Issue by vivek-jain** [fluent-ffmpeg/node-fluent-ffmpeg#665]
I am trying to create video from set of images and a single audio as per code below:

var ffmpeg = require('fluent-ffmpeg');
var command = ffmpeg()
        .input('/tmp/out_1.png').duration(153)
        .input('/tmp/out_2.png').duration(711)
        .input('/tmp/out_3.png').duration(153)
        .input('/tmp/out_4.png').duration(711)
        .withFps(25)
        .input('/tmp/audio.mp3')
        .videoCodec('libx264')
        .size('640x?')
        .on('start', function(commandLine) {
                console.log('Spawned Ffmpeg with command: ' + commandLine);
        })
        .on('error', function(err) {
                console.log('An error occurred: ' + err.message);
        })
        .on('end', function() {
                console.log('Processing finished !');
        })
        .save('outputffffff.mp4');;

The output video doesn't contain video, also the audio length is truncated. Is fluent api meant to handle inputs with various durations?

**Comment by swampthang** [comment]
Hi, vivek-jain. 
I was able to create a video from static images using a text file. I'm creating the text file dynamically but it ends up looking like this:
```
file '/myTempFilePath/temp0.jpg'
duration 1.11
file '/myTempFilePath/temp1.jpg'
duration 1.14
file '/myTempFilePath/temp1.jpg'
```
Of course, your filepaths will be different (my temp file path is a long one, so I replaced it with `myTempFilePath` in the example above for brevity). One thing to note though, if you use absolute paths, you'll probably have to set an inputOption of `-safe 0`. Here's the code I'm using:
```
function createBgVideo(){

  var proc = new ffmpeg(),
      filelist = `${tempFolder}bglist.txt`, // the dynamically created text file noted above
      tempFile = `${tempFolder}tempbg.mp4`, // output file name
      FPS = parseInt($('#frames-per-second').val()); // frames-per-second - I have a setting for this in my html

  proc.addInput(filelist)
  .inputOptions(['-safe 0','-f concat'])
  .on('start', function(ffmpegCommand) {
      console.log(`started creating bg video`);
  })
  .on('progress', function(data) {
      console.log('progressing');
  })
  .on('end', function() {
      console.log(`ended creating bg video`);
  })
  .on('error', function(err, stdout, stderr) {
      /// error handling
      console.log('error: ' + err.message);
      console.log('stderr:' + stderr);
      console.log('stdout:' + stdout);
  })
  .outputOptions([`-vf fps=${FPS}`,'-pix_fmt yuv420p'])
  .output(tempFile)
  .run();
}
```

**Comment by vivek-jain** [comment]
Hi, swampthang.

This works like a charm. Thanks for helping me out. I haven't explored crossfading so far, if you have some video examples, could you please pass them on. 
I will get back if I find some ways to crossfade images.

Thanks again!

**Comment by njoyard** [comment]
Closing as the issue seems solved :)
