### ISSUE TITLE
output movie will revert parts that have been cut

### ISSUE THREAD

**Issue by EasonWang01** [fluent-ffmpeg/node-fluent-ffmpeg#667]
I want to convert 60fps movie to  29.7 FPS movie.It converted successful but some parts of the movie that have already been cut using quicktime will come back to the movie.

How to convert FPS and not modify the origin movie? thanks.

```


var ffmpeg = require('fluent-ffmpeg');
/**
 *    input - string, path of input file
 *    output - string, path of output file
 *    callback - function, node-style callback fn (error, result)        
 */
function convert(input, output, callback) {
    ffmpeg(input)
        .output(output)
        .inputFPS(29.7)
        .on('end', function() {                    
            console.log('conversion ended');
            callback(null);
        }).on('error', function(err){
            console.log(err);
            callback(err);
        }).run();
}

convert('./test01.mov', './output.mov', function(err){
   if(!err) {
       console.log('conversion complete');
       //...

   }
});


```

**Comment by njoyard** [comment]
Have you tried the same with command line ffmpeg ? If the problem also happens there, this is an ffmpeg issue and it's the wrong place to report it :)

**Comment by EasonWang01** [comment]
Thanks,I have try command below,although not happen thing like above,but it not convert FPS.
`ffmpeg -i input.mov  -r 29.7 -y output.mov`

**Comment by njoyard** [comment]
That's not the same. What you wrote in JS executes `ffmpeg -r 29.7 -i input.mov -y output.mov`

**Comment by EasonWang01** [comment]
yes,same things happen,do you know why it will cause this?

**Comment by njoyard** [comment]
No idea. You should probably ask the ffmpeg community.

**Comment by EasonWang01** [comment]
and put this to windows will cause drop frame.

**Comment by EasonWang01** [comment]
thanks.
