### ISSUE TITLE
Error: av_interleaved_write_frame(): Broken pipe

### ISSUE THREAD

**Issue by aakashgupta96** [fluent-ffmpeg/node-fluent-ffmpeg#668]
This is the FFmpeg command that I'm using to stream to facebook and updating the image file given as input to ffmpeg process using a rails app.

`$HOME/bin/ffmpeg -loop 1 -re -y -f image2 -i 'public/uploads/post/25/frame1.png' -acodec copy -bsf:a aac_adtstoasc -pix_fmt yuv420p -profile:v high -s 1280x720 -vb 400k -maxrate 400k -minrate 400k -bufsize 600k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -t 14400 -strict -2 -f flv "rtmp_link" 2> "logfile"`

Logs of this FFmpeg process: [http://pastebin.com/vC1vLDEg](url)

Sometimes, it suddenly stops and throws the error
`av_interleaved_write_frame: Broken Pipe`
 and then conversion fails and streaming stops.
And in some cases, it runs perfectly fine.

I'm not able to figure out the reason of this error.

**Comment by njoyard** [comment]
This is not an ffmpeg repository, please direct your question to the ffmpeg community instead :)
