### ISSUE TITLE
HLS from stream not playing in iOS

### ISSUE THREAD

**Issue by swordsreversed** [fluent-ffmpeg/node-fluent-ffmpeg#669]
This may be an ffmpeg issue but i'm hoping someone can help me. I're recording a radio stream and creating a m3u8/ts:

```
Ffmpeg({ source: 'http://xx.x.x.x:8000/listen' })
  .setDuration(3600)
  .inputFormat('mp3') 
  .audioCodec('aac')
  .audioBitrate('64k')
  .addOption('-hls_time', 10)
  .addOption('-hls_list_size', 0)
  .addOption('-hls_flags', 'single_file')
  .on('end', function () {
    console.log('ended recording');
    process.exit(0);
  })
  .on('error', function (err) {
    console.log('an error happened: ' + err.message);
  })
  .save('coolshow.m3u8');
```

This works on desktop fine using hls.js library, but won't play on iOS devices. Has anyone seen anything similar, or can tell me if there is something obvious i'm doing wrong here?

TIA

**Comment by njoyard** [comment]
Have you tried the same on command line ? Does it have the same behaviour ? If it does then that's not the right place to ask :)a

**Comment by swordsreversed** [comment]
Yeah it does, sorry :)

**Comment by vhmth** [comment]
@swordsreversed did you ever figure this out? Does it persist? What version of FFMPEG were you using? I'm about to do a dive in HLS stuff right now. Completely understand if the fluent-ffmpeg peeps don't want this convo to happen here. If you see this @swordsreversed, please email me at vinay@useloom.com if you find the time!
