### ISSUE TITLE
express-stream.js example need for 'index.html' send?

### ISSUE THREAD

**Issue by jdmb77** [fluent-ffmpeg/node-fluent-ffmpeg#670]
Not so much an issue as confusion on my part I'm sure. In the express-stream.js example there is an app.get(), which sends the text, 'index.html'. I am not sure what this is for as if I comment this section out my video still streams, except it is using the index.html file located in the flowplayer directory. This occurs regardless if it is commented or not. Thanks in advance!

**Environment:**

- Windows 7 Enterprise
- Node.js v7.7.1
- FFMPEG v3.2.4
- fluent-ffmpeg v2.1.0

```
const express = require('express')
const ffmpeg = require('fluent-ffmpeg')
const opn = require('opn')
const app = express()

app.use(express.static(`${__dirname}/flowplayer`))

// Still runs with this commented ???
/*app.get('/', (req, res) => {
  res.send('index.html')
})*/

app.get('/video/:filename', (req, res) => {
  res.contentType('mp4')

  let pathToMovie = `./video/Wildlife.wmv`
  let proc = ffmpeg(pathToMovie)
    .preset('flashvideo')
      .format('mp4')
      .size('320x?')
      .addOptions([
        '-movflags frag_keyframe+faststart'
    ])
    .on('end', () => {
      console.log('File has been converted.')
    })
    .on('error', err => {
      console.log(`An error occurred ${err.message}`)      
    })
    .pipe(res, {end: true})
})

app.listen(4000)
opn('127.0.0.1:4000', { app: 'chrome' })
```

**Comment by njoyard** [comment]
`express.static('${__dirname}/flowplayer')` will serve static files and automatically serve indexes therein
