### ISSUE TITLE
ffmpeg profile query

### ISSUE THREAD

**Issue by tapankumar** [fluent-ffmpeg/node-fluent-ffmpeg#671]
I want to know, how to pass below parameter to ffmpeg via fluent-ffmpeg.

 -profile:a aac_he
or 
-profile:a aac_he_v2

**Comment by njoyard** [comment]
Use [`outputOptions()`](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputoptionsoption-add-custom-output-options). And read the documentation, please.

**Comment by tapankumar** [comment]
Sorry and Thankyou
