### ISSUE TITLE
Pipe input from SDP string

### ISSUE THREAD

**Issue by aydinkn** [fluent-ffmpeg/node-fluent-ffmpeg#679]
### Version information

* fluent-ffmpeg version: 2.1.0
* ffmpeg version: 3.2.4
* OS: Ubuntu Linux

### Code to reproduce

```js
const stringToStream = require('string-to-stream');
const ffmpeg = require('fluent-ffmpeg');

// Create a readable stream from an SDP string (v=0\no=......)
let sdp = stringToStream(sdpString);

ffmpeg(sdp)
        .inputOptions(['-protocol_whitelist "pipe,udp,rtp"', '-f sdp'])
        .outputOptions(['-c copy', '-map 0']).format('flv').save('test.flv');
```

### Expected results

FFMpeg get UDP stream from SDP (without SDP file) and save it to file (or publish to RTMP server).
This logic is working but I need to implement it with Fluent-FFMpeg:

```
cat test.sdp | ffmpeg -protocol_whitelist "pipe,udp,rtp" -f sdp -i - -c copy -map 0 \
-f flv "test.flv"
```

### Observed results

I've got this Error: ffmpeg exited with code 1: pipe:0: Invalid argument

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by aydinkn** [comment]
I solved the problem. Input / output options (including keys and values) must have array item like this:
``` javascript
ffmpeg(sdp)
        .inputOptions(['-protocol_whitelist', 'pipe,udp,rtp', '-f', 'sdp'])
        .outputOptions(['-c', 'copy', '-map', '0']).format('flv').save('test.flv');
```

**Comment by suresh-borad** [comment]
@aydinkn I'm facing this error : `Output file #0 does not contain any stream`

**Comment by aydinkn** [comment]
@suresh-borad my input stream compatible for flv, so i basically copy all the channels in the input stream to output file.
If your input stream incompatible for flv, you need to re encode your input stream to output file.

https://trac.ffmpeg.org/wiki/Map#Example9
