### ISSUE TITLE
Error: ffmpeg exited with code 1: At least one output file must be specified

### ISSUE THREAD

**Issue by ethernetweb** [fluent-ffmpeg/node-fluent-ffmpeg#680]
node.js version: v6.6.0
ffmpeg version 3.0.2-4~bpo8+1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)

sserver@server1:~/test/fluent-ffmpeg$ ls
err_ffmpeg.js  test.mp4

sserver@server1:~/test/fluent-ffmpeg$ cat err_ffmpeg.js 
var iArr = ["-threads 8"];
var oArr = ["-b:v 500k","-r 26","-g 52","-force_key_frames 'expr:gte(t,n_forced*2)'","-vf scale=640:480","-async 1","-c:a aac","-b:a 128k","-c:v libx264 -x264opts 'threads=2'"];

var inFile = "test.mp4", outFile = "out.mp4";

var ffmpeg = require("fluent-ffmpeg");
var proc = ffmpeg({source:inFile,nicencess:19});
proc.inputOptions(iArr);
proc.outputOptions(oArr);
proc.output(outFile);

proc.run();

proc.on("start",function(data) { console.log(data); });

proc.on("end",function() { });

proc.on("error",function(err) {
  console.log(" *** FFMPEG ERR: "+err); console.log(err.stack);
});

sserver@server1:~/test/fluent-ffmpeg$ node err_ffmpeg.js 
ffmpeg -threads 8 -i test.mp4 -y -b:v 500k -r 26 -g 52 -force_key_frames 'expr:gte(t,n_forced*2)' -vf scale=640:480 -async 1 -c:a aac -b:a 128k -c:v libx264 -x264opts 'threads=2' out.mp4
 *** FFMPEG ERR: Error: ffmpeg exited with code 1: At least one output file must be specified

Error: ffmpeg exited with code 1: At least one output file must be specified

    at ChildProcess.<anonymous> (/home/sserver/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

sserver@server1:~/test/fluent-ffmpeg$ ffmpeg -threads 8 -i test.mp4 -y -b:v 500k -r 26 -g 52 -force_key_frames 'expr:gte(t,n_forced*2)' -vf scale=640:480 -async 1 -c:a aac -b:a 128k -c:v libx264 -x264opts 'threads=2' out.mp4
ffmpeg version 3.0.2-4~bpo8+1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr --extra-version='4~bpo8+1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2017-01-01 10:18:08
    encoder         : x264
  Duration: 00:00:31.80, start: 0.000000, bitrate: 240 kb/s
    Stream #0:0(eng): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 930x568 [SAR 1:1 DAR 465:284], 239 kb/s, 15 fps, 15 tbr, 1500 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2017-01-01 10:18:08
      handler_name    : VideoHandler
No pixel format specified, yuv444p for H.264 encoding chosen.
Use -pix_fmt yuv420p for compatibility with outdated media players.
[libx264 @ 0x1d4c7a0] using SAR=1395/1136
[libx264 @ 0x1d4c7a0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x1d4c7a0] profile High 4:4:4 Predictive, level 3.0, 4:4:4 8-bit
[libx264 @ 0x1d4c7a0] 264 - core 142 r2431 a5831aa - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=52 keyint_min=5 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'out.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    encoder         : Lavf57.25.100
    Stream #0:0(eng): Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv444p, 640x480 [SAR 1395:1136 DAR 465:284], q=-1--1, 500 kb/s, 26 fps, 13312 tbn, 26 tbc (default)
    Metadata:
      creation_time   : 2017-01-01 10:18:08
      handler_name    : VideoHandler
      encoder         : Lavc57.24.102 libx264
    Side data:
      unknown side data type 10 (24 bytes)
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
frame=  259 fps=127 q=16.0 size=     521kB time=00:00:08.11 bitrate= 525.5kbits/s dup=109 drop=0 speed=3.97x   frame=  327 fps=128 q=14.0 size=     649kB time=00:00:10.73 bitrate= 495.2kbits/s dup=138 drop=0 speed=4.21x   frame=  400 fps=131 q=12.0 size=     773kB time=00:00:13.53 bitrate= 467.9kbits/s dup=169 drop=0 speed=4.43x   frame=  469 fps=132 q=10.0 size=     922kB time=00:00:16.19 bitrate= 466.7kbits/s dup=198 drop=0 speed=4.55x   frame=  826 fps=133 q=-1.0 Lsize=    1341kB time=00:00:31.69 bitrate= 346.6kbits/s dup=349 drop=0 speed=5.09x    
video:1330kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.785466%
[libx264 @ 0x1d4c7a0] frame I:18    Avg QP: 4.14  size: 54076
[libx264 @ 0x1d4c7a0] frame P:235   Avg QP: 7.31  size:  1479
[libx264 @ 0x1d4c7a0] frame B:573   Avg QP:14.62  size:    71
[libx264 @ 0x1d4c7a0] consecutive B-frames:  6.7%  0.7%  5.4% 87.2%
[libx264 @ 0x1d4c7a0] mb I  I16..4: 71.7%  6.1% 22.2%
[libx264 @ 0x1d4c7a0] mb P  I16..4:  2.7%  0.5%  0.5%  P16..4:  1.6%  0.2%  0.1%  0.0%  0.0%    skip:94.3%
[libx264 @ 0x1d4c7a0] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.8%  0.0%  0.0%  direct: 0.0%  skip:99.2%  L0:44.5% L1:55.0% BI: 0.5%
[libx264 @ 0x1d4c7a0] final ratefactor: 2.29
[libx264 @ 0x1d4c7a0] 8x8 transform intra:8.5% inter:44.9%
[libx264 @ 0x1d4c7a0] coded y,u,v intra: 15.7% 14.2% 14.0% inter: 0.2% 0.1% 0.1%
[libx264 @ 0x1d4c7a0] i16 v,h,dc,p: 47% 53%  0%  0%
[libx264 @ 0x1d4c7a0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39% 24% 36%  0%  0%  0%  0%  0%  0%
[libx264 @ 0x1d4c7a0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 41% 10%  2%  3%  4%  3%  3%  3%
[libx264 @ 0x1d4c7a0] Weighted P-Frames: Y:0.4% UV:0.4%
[libx264 @ 0x1d4c7a0] ref P L0: 75.2%  5.4% 13.3%  6.1%
[libx264 @ 0x1d4c7a0] ref B L0: 68.7% 30.2%  1.1%
[libx264 @ 0x1d4c7a0] ref B L1: 95.4%  4.6%
[libx264 @ 0x1d4c7a0] kb/s:342.86

**Comment by njoyard** [comment]
Closing as this is too old, sorry for the inactivity.

If you intend to pass a raw list of arguments to ffmpeg, you should rather use spawn than fluent-ffmpeg anyway.
