### ISSUE TITLE
DrawText with fadein / fadeout

### ISSUE THREAD

**Issue by elinadenfina** [fluent-ffmpeg/node-fluent-ffmpeg#685]
Hi!
Is it possible to add a DrawText filter that fades in when it's shown and out when it's being removed? 

Preferably it should look something like this: 

```
.videoFilters({
  filter: 'drawtext',
  options: {
    fontfile:'Arial.ttf',
    text: 'hello hello',
    fontsize: 20,
    fontcolor: 'white',
    x: '(main_w/2-text_w/2)',
    y: 50,
    shadowcolor: 'black',
    shadowx: 2,
    shadowy: 2,
    fadeIn: 0.3, <---
    fadeOut: 0.4 <---
  }
})
```

Thanks!

**Comment by njoyard** [comment]
This is an ffmpeg question. Please look in the ffmpeg docs.

**Comment by Dhruv-Shetty** [comment]
> Hi! Is it possible to add a DrawText filter that fades in when it's shown and out when it's being removed?
> 
> Preferably it should look something like this:
> 
> ```
> .videoFilters({
>   filter: 'drawtext',
>   options: {
>     fontfile:'Arial.ttf',
>     text: 'hello hello',
>     fontsize: 20,
>     fontcolor: 'white',
>     x: '(main_w/2-text_w/2)',
>     y: 50,
>     shadowcolor: 'black',
>     shadowx: 2,
>     shadowy: 2,
>     fadeIn: 0.3, <---
>     fadeOut: 0.4 <---
>   }
> })
> ```
> 
> Thanks!

Hey did fadeIn and fadeOut worked 
we used alpha value to set fade in and fade out but it was too complex in node js
If you found any solution can you share it?
