### ISSUE TITLE
an error happened: ffmpeg exited with code 1

### ISSUE THREAD

**Issue by jonahzheng** [fluent-ffmpeg/node-fluent-ffmpeg#687]
debian 7.5

ffmpeg 0.8.17-6:0.8.17-2
libavutil    51. 22. 3 / 51. 22. 3
libavcodec   53. 35. 0 / 53. 35. 0
libavformat  53. 21. 1 / 53. 21. 1
libavdevice  53.  2. 0 / 53.  2. 0
libavfilter   2. 15. 0 /  2. 15. 0
libswscale    2.  1. 0 /  2.  1. 0
libpostproc  52.  0. 0 / 52.  0.100
root@iZ23h4x1pxcZ:/opt/rt_center# node a.js 
an error happened: ffmpeg exited with code 1

a.js
`var ffmpeg = require('fluent-ffmpeg');
var fs = require('fs');

// open input stream
var infs = fs.createReadStream('/opt/rt_center/doc/test.flv');

infs.on('error', function(err) {
  console.log(err);
});

// create new ffmpeg processor instance using input stream
// instead of file path (can be any ReadableStream)
var proc = ffmpeg(infs)
  .preset('flashvideo')
  // setup event handlers
  .on('end', function() {
    console.log('done processing input stream');
  })
  .on('error', function(err) {
    console.log('an error happened: ' + err.message);
  })
  // save to file
.save('/opt/rt_center/doc/your_target.flv');
`

**Comment by jonahzheng** [comment]
Upgrade system to 'Debian GNU/Linux 8.7 (jessie)'
is ok.

**Comment by njoyard** [comment]
Please read and abide to the issue template when creating one.
