### ISSUE TITLE
Error: Cannot find ffprobe

### ISSUE THREAD

**Issue by gibbok** [fluent-ffmpeg/node-fluent-ffmpeg#691]
### Version information

* fluent-ffmpeg version: 2.1.0 
* ffmpeg version: 3.2.4
* OS: Win 8.1

### Code to reproduce

```js
        ffmpeg(videoUrl)
            .ffprobe(0, function (err, data) {
                if (err) {
                    return reject(err)
                }
                resove(data);
            });

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
Data should be populated with meta information.

### Observed results

> Error: Cannot find ffprobe

Issue happens even after adding PATH (correctly) to Windows for ffmpeg bin folder (as show in this [tutorial](http://www.wikihow.com/Install-FFmpeg-on-Windows)).

As workaround I am currently specifying the path from node using :

```
    ffmpeg.setFfmpegPath(path.join(__dirname, '../ffmpeg/bin/ffmpeg.exe'));
    ffmpeg.setFfprobePath(path.join(__dirname, '../ffmpeg/bin/ffprobe.exe'));
```

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [X] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by arjndr** [comment]
Why the "`..`" in `'../ffmpeg/bin/ffmpeg.exe'`?
Try 
```
ffmpeg.setFfmpegPath(path.join(__dirname, '/ffmpeg/bin/ffmpeg.exe'));
ffmpeg.setFfprobePath(path.join(__dirname, '/ffmpeg/bin/ffprobe.exe'));
```

**Comment by gibbok** [comment]
Thanks, it can work also on that way.

**Comment by njoyard** [comment]
I don't have a windows installation so I cannot debug that further. But this looks like the right way to specify ffmpeg location anyway.
