### ISSUE TITLE
localtime is invalid

### ISSUE THREAD

**Issue by jonahzheng** [fluent-ffmpeg/node-fluent-ffmpeg#692]
### Version information

* fluent-ffmpeg version:
* ffmpeg version:ffmpeg version git-2017-04-04-1229007 Copyright (c) 2000-2017 the FFmpeg developers
* OS: debain 8.7.1

### Code to reproduce

```js
        {
            filter: 'drawtext',
            options: {
                fontfile:'/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
                fontsize:20,
                fontcolor:'red@0.8',
                x:165,
                y:302,
                text:"AAA %{localtime:%T}"
            },
            inputs: '[0:v]',
            outputs: 'txt'
        },

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
localtime is invalid

### Checklist

* [ ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Please abide by the checklist when submitting issues.
This is a ffmpeg problem, please direct the question to ffmpeg support community.

**Comment by notedit** [comment]
@jonahzheng   Have you made it work?  I came to the same issue.
