### ISSUE TITLE
Any way to convert multiple files with fluent-ffmpeg?

### ISSUE THREAD

**Issue by arjndr** [fluent-ffmpeg/node-fluent-ffmpeg#693]
Hello, I am looking for a way to convert an array of input files, but I want the output to be a set of files based on the input file for e.g:

an array of files `['123.mp3', '456.mp3']`
123.mp3 should convert to 123.ogg and 456.mp3 to 456.ogg etc.

Any resources? tricks to do this? please let me know. Thanks ^_^

**Comment by njoyard** [comment]
There is no built-in feature for handling multiple conversions at the same time. You'll have to write usual JS code to do this (launch all commands in a loop and call a callback when all are finished, or launch the first command and have its end event launch the next one until there are no more)

**Comment by arjndr** [comment]
Ah dang! Anyways thanks for the library, really handy!
