### ISSUE TITLE
send progress to the client side

### ISSUE THREAD

**Issue by flenoir** [fluent-ffmpeg/node-fluent-ffmpeg#694]
### Version information

* fluent-ffmpeg version: 2.0.1
* ffmpeg version: n-82966-g699bbc
* OS: Windows 7

Hi, i can use fluent-ffmpeg with Meteor. 

From the client side, i use a Meteor Call to send the file i want to code to the server. The server encode the file.

 I can output the percent value in the server console. As i want to have a progress bar on the client side, i am wondering how this can be achieved. 

 Can you tell me if this is possible ? 

 thanks a lot

  Best regards

 FLenoir

**Comment by njoyard** [comment]
This is a Meteor question, not a fluent-ffmpeg question. From fluent-ffmpegs side you look like you already know how to get notified with progress events.
