### ISSUE TITLE
Seekable stream of a file with express

### ISSUE THREAD

**Issue by jersobh** [fluent-ffmpeg/node-fluent-ffmpeg#701]
Hi there, 

I'm close, as I can see, to get this seekable streaming working. This is my code 

`var app = express();
  app.use(cors());
  app.get('/audio/:filename', function(req, res) {
    res.contentType('mp3');

    var path = './' + req.params.filename
      , stat = fs.statSync(path)
      , total = stat.size

      if (req.headers['range']) {
        var range = req.headers.range
          , parts = range.replace(/bytes=/, "").split("-")
          , partialstart = parts[0]
          , partialend = parts[1]
          , start = parseInt(partialstart, 10)
          , end = partialend ? parseInt(partialend, 10) : total-1
          , chunksize = (end-start)+1

        console.log('RANGE: ' + start + ' - ' + end + ' = ' + chunksize)

        var file = fs.createReadStream(path, {start: start, end: end})

        res.writeHead(206
                     , { 'Content-Range': 'bytes ' + start + '-' + end + '/' + total
                       , 'Accept-Ranges': 'bytes', 'Content-Length': chunksize
                       , 'Content-Type': 'audio/mpeg'
                       })
        file.pipe(res)
      }
      else {
        console.log('ALL: ' + total)
        res.writeHead(200
                     , { 'Content-Length': total
                       , 'Content-Type': 'audio/mpeg'
                       })
        fs.createReadStream(path).pipe(res)
      }

var proc = new ffmpeg(file)
    .toFormat('mp3')
    .audioCodec('libmp3lame')
    .on('error', function(err,stdout,stderr) {
        console.log('an error happened: ' + err.message);
        console.log('ffmpeg stdout: ' + stdout);
        console.log('ffmpeg stderr: ' + stderr);
    })
    .on('end', function() {
        console.log('Processing finished !');
    })
    .on('progress', function(progress) {
        console.log('Processing: ' + progress.percent + '% done');
    })
    .pipe(res, { end: true });
  });

app.listen(4000);`

Then I get: Output #0, mp3, to 'pipe:1':
Output file #0 does not contain any stream

I know that the ffmpeg part was meant to be related with the if/else part, but I couldn't figure out how to do this.

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
