### ISSUE TITLE
run ffmpeg remotely (wrap ffmpeg command)

### ISSUE THREAD

**Issue by legomind** [fluent-ffmpeg/node-fluent-ffmpeg#702]
First of all thanks so much for this module.

Second, I am working on a project that requires multiple ffmpeg instances be distributed over several servers.

My first instinct was to create a shell file to distribute the commands via ssh.

```bash
#!/bin/bash
ssh ${REMOTE_SERVER}.local ffmpeg "$@"
```

```js
ffmpeg.setFfmpegPath(join(__dirname, "ffmpeg"))
```

This works, for basic commands, but when the ffmpeg command contain quotes or stars, the command fails.

Would you be open to a pull request that allows the modification of the ffmpeg command before it is executed? Something like:

```js
 ffmpeg('input.mp4')
        .withCommandFactory(cmd => `ssh ${remoteServer} "${cmd}"`

```

**Comment by njoyard** [comment]
You most likely just need to escape special shell characters in your script. That's not really (IMO) fluent-ffmpegs responsibility.

Can you give a failing example, please?

**Comment by njoyard** [comment]
Closing, no further info given
