### ISSUE TITLE
Failed to inject frame into filter network: Invalid argument

### ISSUE THREAD

**Issue by jonahzheng** [fluent-ffmpeg/node-fluent-ffmpeg#715]
### Version information

* fluent-ffmpeg version:"2.1.2
* ffmpeg version: 3.1
* OS:debian 8.7

### Code to reproduce

```js
ffmpeg('/home/test/my.mp4').withNativeFramerate()
.videoFilters('drawtext=\"text=\'%{localtime\\:%Y %m %d %H %M %S}\':fontsize=40:fontcolor=white:box=1:x=10:y=10:boxcolor=black@0.5\"')
.on('start', function(commandLine) {
        console.log('Ffmpeg with command: ' + commandLine);
})
.on('progress', function(progress) {
    frames = progress.frames;
    timemark = progress.timemark;
    console.log('currentFps:' + progress.currentFps + ' Processing: ' + progress.frames + ' timemark: ' + progress.timemark);
})
.on('error', function(err) {
    console.log('An error occurred: ' + err.message);
})
.on('end', function() {
    console.log('Processing finished !');
    //aa();
})
.format('flv')
.output("rtmp://192.168.0.23/live/sss", {end: true}) .run(); 

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Observed results

```
root@debian:/home/test/client# node video.js 
Ffmpeg with command: ffmpeg -re -i /home/test/my.mp4 -filter:v drawtext="text='%{localtime\:%Y %m %d %H %M %S}':fontsize=40:fontcolor=white:box=1:x=10:y=10:boxcolor=black@0.5" -f flv rtmp://192.168.0.23/live/sss
An error occurred: ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!
====================================
ffmpeg -re -i /home/test/my.mp4 -filter:v drawtext="text='%{localtime\:%Y %m %d %H %M %S}':fontsize=40:fontcolor=white:box=1:x=10:y=10:boxcolor=black@0.5" -f flv rtmp://192.168.0.23/live/sss
```

The command line can run correctly

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Could you please include stderr as received from the 3rd argument from the 'error' event ?

**Comment by jonathanleang** [comment]
@jonahzheng maybe you are missing filter: 'subtitles'

**Comment by jonahzheng** [comment]
use drawtext=expansion=strftime:text='%Y.%m.%d'
is ok.

**Comment by jonahzheng** [comment]
@nevyn the 3rd argument from the 'error' event, is no any information.

**Comment by maztan** [comment]
"drawtext='text=%{localtime\\:%Y %m %d %H %M %S}:fontsize=40:fontcolor=white:box=1:x=10:y=10:boxcolor=black@0.5\'")
