### ISSUE TITLE
Documentation addition?

### ISSUE THREAD

**Issue by heart4hackers** [fluent-ffmpeg/node-fluent-ffmpeg#717]
Just to let you know, i found a way to handle the problem you describe below.
I think the answer is very simple and maybe someone else is faced with that.

What you wrote: 

> Warning: ffprobe may be called with an input stream, but in this case it will consume data from the stream, and this data will no longer be available for ffmpeg. Using both ffprobe and a transcoding command on the same input stream will most likely fail unless the stream is a live stream. Only do this if you know what you're doing.

what i did to solve the problem:
```javascript
const stream = require('stream');
const pass = new stream.PassThrough();
const pass2 = new stream.PassThrough();
ffmpeg(pass).
.ffprobe(function(err, data) {
         ffmpeg(pass2)
                    .size('320x200')
                    .output('outputfile.mp4')
                    .save('outputfile.mp4');
})
```

node.js does copy the stream into two. That's it...

Best

**Comment by njoyard** [comment]
Submit a PR ;)
