### ISSUE TITLE
stream with multi rtp output

### ISSUE THREAD

**Issue by notedit** [fluent-ffmpeg/node-fluent-ffmpeg#718]
### Version information

* fluent-ffmpeg version: 2.1.12
* ffmpeg version: 3.3
* OS: macos 

### Code to reproduce

```js
ffmpeg('guigu.mp4').native()
    .outputOptions([
        '-vcodec copy',
        '-an',
        '-f rtp'
        ])
    .output('rtp://127.0.0.1:20000')
    .outputOptions([
        '-acodec copy',
        '-vn',
        '-f rtp'
    ])
    .output('rtp://12.0.0.1:30000')
    .on('start', function(command) {
         console.log('Spawned Ffmpeg with command: ' + command);
    })
    .on('error', function(err){
        console.log('An error occurred: ' + err);
    })
    .on('end',function(){
        console.log('Processing finished !');
    })
    .run();

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

ffmpeg -re -i guigu.mp4 -vcodec copy  -f rtp rtp://127.0.0.1:20000  -acodec copy -f rtp rtp://12.0.0.1:30000

### Observed results

ffmpeg -re -i guigu.mp4 -vcodec copy -an -f rtp -acodec copy -vn -f rtp rtp://127.0.0.1:20000 rtp://12.0.0.1:30000
An error occurred: Error: ffmpeg exited with code 1: Output #0, rtp, to 'rtp://127.0.0.1:20000':
Output file #0 does not contain any stream

### Checklist

* [ *] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ *] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by notedit** [comment]
got

**Comment by Kostanos** [comment]
I have the same issue but even without using multi output.
I have 3 cameras, 2 of them works well, but the third one never connects and exit with this error.
each of 3 cameras are different brand, and all of them streaming well (tested using VLC player)

Any Idea?

My code is:

```
      self.camera = FFMpeg(cameraUrl, {timeout: 30});
      self.camera
        .inputOptions('-loglevel error')
        .noAudio()
        .format('singlejpeg')
        .output(self.stream, {end: true});
```

This is my log:
```
2017-09-27T04:23:18.064Z ip:error:Camera Ffmpeg stderr [rtsp @ 0x7fe523ad8220] method PAUSE failed: 455 Method Not Valid in This State
2017-09-27T04:23:18.064Z ip:error:Camera Ffmpeg stderr Output file #0 does not contain any stream
2017-09-27T04:23:18.066Z ip:error:Camera Video stream closed error(ffmpeg exited with code 1: Output file #0 does not contain any stream
) stderr([rtsp @ 0x7fe523ad8220] method PAUSE failed: 455 Method Not Valid in This State
```

Let me know if you prefer me to open new issue for this.

thank you for the help

**Comment by lookapanda** [comment]
@notedit How did you do it?

**Comment by Kostanos** [comment]
I didn't found the fix yet for that..

**Comment by lookapanda** [comment]
I did it like this now and it works:
```
            .output('rtp://127.0.0.1:8004')
            .outputOptions(['-f rtp'])
            .videoCodec('libx264')
            .videoBitrate(2048, true)
            .addOption('-preset', 'ultrafast')
            .addOption('-deadline', 'realtime')
            .addOption('-qmin', 0)
            .addOption('-qmax', 50)
            .addOption('-crf', 10)
            .fps(30)
            .size('1280x720')
            .withNoAudio()

            .output('rtp://127.0.0.1:8002')
            .outputOptions(['-f rtp'])
            .audioCodec('opus')
            .audioBitrate('196k')
            .withNoVideo();
```

Apparently, it's important to **first** declare the output, then the options for it.

**Comment by njoyard** [comment]
@lookapanda indeed, quoting [the docs](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#outputtarget-options-add-an-output-to-the-command)

> Adding an output switches the "current output" of the command, so that any fluent-ffmpeg method that applies to an output is indeed applied to the last output added. For backwards compatibility reasons, you may as well call those methods before adding the first output (in which case they will apply to the first output when it is added).
