### ISSUE TITLE
Throws error when no output is present instead of emitting an error event

### ISSUE THREAD

**Issue by zya** [fluent-ffmpeg/node-fluent-ffmpeg#720]
* fluent-ffmpeg version: 2.1.0
* ffmpeg version: 3.2.4-static
* OS: Centos

This is not really a bug related to ffmpeg commands. It is the way the library handles the case where no output is preset. When no output is present, we throw an error in the line below: 
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/dcc052ab578bced58ce56e52edf58284688f6e60/lib/processor.js#L403-L405

To handle this case, the user will need to try and catch the error. I was expecting the get the error through the error listener similar to other errors.

Is there a specific reason that this error is handled differently?

**Comment by njoyard** [comment]
There is a reason : the 'error' event is for processing errors during execution, and synchronous exceptions are thrown when processing itself cannot be launched.
