### ISSUE TITLE
MacOS, pipe issue, please help

### ISSUE THREAD

**Issue by xianbinlin** [fluent-ffmpeg/node-fluent-ffmpeg#725]
### Version information

* fluent-ffmpeg version:2017.06.22
* ffmpeg version: 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.31)
* OS:MacOS serria

### Code to reproduce

```js
var command = ffmpeg(videoPaths[0])
    .videoCodec('libx264')
    .noAudio()
    .size('1920x1080')
    .on('start', function(cmdline) {
      console.log('Command line: ' + cmdline);
    })
    .on('error', function(err, stdout, stderr) {
      console.log('An error occurred: ' + err.message);
      console.log('Error: ' + err.message);
      console.log('ffmpeg output:\n' + stdout);
      console.log('ffmpeg stderr:\n' + stderr);
    })
    .on('end', function() {
      console.log('Processing finished !');
    });

    console.log("ffmpeg cmd:",command);

  var ffstream = command.pipe();
  ffstream.on('data', function(chunk) {
    console.log('ffmpeg just wrote ' + chunk.length + ' bytes');
  });

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Observed results

Command line: ffmpeg -i /Users/Graz/Desktop/kizoa/sources/anim/650_256.mp4 -an -vcodec libx264 -filter:v scale=w=1920:h=1080 pipe:1
An error occurred: ffmpeg exited with code 1: pipe:1: Invalid argument

Error: ffmpeg exited with code 1: pipe:1: Invalid argument

ffmpeg output:

ffmpeg stderr:
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.31)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --disable-lzma --enable-vda
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/Graz/Desktop/kizoa/sources/anim/650_256.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.18.101
  Duration: 00:00:06.02, start: 0.000000, bitrate: 254 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 256x512 [SAR 1:1 DAR 1:2], 247 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[NULL @ 0x7f83de80ae00] Unable to find a suitable output format for 'pipe:1'
pipe:1: Invalid argument

### Checklist

* [ ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Looks like the "pipe:" protocol is not supported on osx and/or wih your ffmpeg version. Please try to upgrade or direct your question to the ffmpeg community.

**Comment by maximedupre** [comment]
I think this ticket was closed without really being considered.

In isssue #802, @konnextv said:

> When using pipes, you need to tell ffmpeg which format you are using.
Just add .format('wav') and you should be good to go.

This made it for me.
