### ISSUE TITLE
No Longer receiving playlist msg 

### ISSUE THREAD

**Issue by otaku06hxh** [fluent-ffmpeg/node-fluent-ffmpeg#728]
while downloading a video through ffmpeg im getting this msg
![capturezz](https://user-images.githubusercontent.com/29062787/27766815-b9260172-5efb-11e7-905b-712ae46253a4.PNG)

Why does the "no longer receiving playlist" msg come.....also the bitrate drops???

Is there a way to avoid it???

One more thing the max bitrate for this stream is 6130 kbps but the max i get is only around 3000 kbps WHY???

**Comment by njoyard** [comment]
The bitrate is the conversion bitrate, not the video bitrate.
As for the error messages, this is not a fluent-ffmpeg but a ffmpeg issue, please see the ffmpeg docs/community.
