### ISSUE TITLE
Execute raw commands with this addon? (Not an issue)

### ISSUE THREAD

**Issue by klodoma** [fluent-ffmpeg/node-fluent-ffmpeg#730]
Not an issue, just a question. 

Can you execute raw ffmpeg commands?
For example, I have several ffmpeg commands like:

`ffmpeg -i ./capture/screen%05d.jpeg -framerate 60 -c:v libx264 -preset slow -tune animation -crf 10 -vf 'format=yuv420p,pad,crop=1920:1080:0:39' -y videoEncoded.mp4 -y /home/admin/docker-capture-frames/output.mp4`

and I would like to run this as it is with the script and get the progress of ffmpeg. 

Thanks.

**Comment by dipernaa** [comment]
Bump. Also really interested in this.

**Comment by njoyard** [comment]
No.

You can convert your command to a fluent-ffmpeg call and watch progress from here.

Or you can directly spawn your command line using the `child_process` node module and process the output from ffmpeg to read progress yourself. Feel free to reuse code from fluent-ffmpeg if you do this, that's what open source is for.
