### ISSUE TITLE
Question. Cut video in time range

### ISSUE THREAD

**Issue by atherdon** [fluent-ffmpeg/node-fluent-ffmpeg#736]
Hello and thank you for this awesome package!

Can you share an example, of how I can download a part of a video, by specifying Start and End points?
I know that how to do this on windows, by using a CLI:

`C:/ffmpeg/bin/ffmpeg.exe -i C:/ffmpeg/bin/movie.mp4 -ss 00:00:10 -t 00:01:00 -async 1 new.mp4`

Thanks in advance!

**Comment by njoyard** [comment]
Closing, this can be solved easily by reading the docs.
