### ISSUE TITLE
How do I convert webm to mp3 then add it to an mp4?

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [fluent-ffmpeg/node-fluent-ffmpeg#739]
These are the commands I would use on CLI:
webm to mp3:
`ffmpeg -i in.webm  -vn -ab 128k -ar 44100 -y out.mp3` 
add mp3 to mp4:
`ffmpeg -i in.mp4 -i in.mp3 -c copy -map 0:v:0 -map 1:a:0 out.mp4`

The commands above work, now I just need to do this in the API. I tried the following:
webm to mp3:
`new ffmpeg(audio_path)
    .noAudio()
    .audioCodec('libmp3lame')
    .save(audio_path+".mp3")
    .on('error', function(err){
      console.log("An Error occured: " + err);
    });`

add mp3 to mp4:
`new ffmpeg()
    .input(vid_path)
    .input(audio_path)
    .save("new"+vid_path)
    .on('error', function(err) {
      console.log('An error occurred: ' + err);
    })
    .on('end', function() {
      console.log('Final video created!');
      //remove the old files
    });`

I have also tried a few other things, and every time I got the same error:
`Invalid data found when processing input`

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
