### ISSUE TITLE
kill is not a function

### ISSUE THREAD

**Issue by tommyknows** [fluent-ffmpeg/node-fluent-ffmpeg#741]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: -
* OS: Debian

### Code to reproduce

```js
      var proc = ffmpeg(file)
        .format('matroska')
        .audioCodec('libmp3lame')
        .on('error', function(err,stdout,stderr){
	  if (err.message === "Output stream closed") {
	    proc.kill();
	  } else {
          console.log('an error happened: ' + err.message);
          console.log('ffmpeg stdout: ' + stdout);
          console.log('ffmpeg stderr: ' + stderr);
	  }
        })
        .on('end', function(){
          console.log("finished transcode");
        })
        .pipe(res, { end: true});
```

The above code results in the following error when the output stream gets closed:

server.js:44
		          proc.kill('SIGSTOP');
		               ^
TypeError: proc.kill is not a function

What am I doing wrong? 

Thanks for the help

**Comment by SaulGarza** [comment]
I also have this issue. bumping in hopes of solution.

- fluent-ffmpeg version: 2.1.2
- ffmpeg version: 3.4
- OS: MacOS Sierra

I am piping the stream into the speaker module (https://www.npmjs.com/package/speaker) which makes the close event close that stream. without ffmpeg.kill() there currently doesn't seem to be a viable solution other than closing my terminal window or running `killall ffmpeg` as a child process, which stops my script after 3 attempts.

**Comment by liweilup** [comment]
I also encountered the same problem, how do you solve. Thank you

**Comment by tommyknows** [comment]
I didn't, I just commented out the `proc.kill();` line...

**Comment by liweilup** [comment]
Thank you for your answer

**Comment by njoyard** [comment]
Do not call `kill()` in the `error` handler. The process is already dead here.
