### ISSUE TITLE
How to convert mp4 to ts format

### ISSUE THREAD

**Issue by kenjimelody** [fluent-ffmpeg/node-fluent-ffmpeg#742]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.3.2
* OS: Linux

### Code to reproduce

```js


```

(note: if the problem only happens with some inputs, include a link to such an input file)
i can not convert mp4 to ts. 

**Error message** 

> "error: Cannot process video: Output format ts is not available"

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Closing, incomplete bug report
