### ISSUE TITLE
Output of Static AAC Audio File Is Not Reflecting Input Options.

### ISSUE THREAD

**Issue by pdushkin** [fluent-ffmpeg/node-fluent-ffmpeg#744]
Hi, I am able to successfully get the results I am looking for locally, but not when the below code is run in firebase. As stated, output file isn't reflecting input parameters. 

### Version information

* macSierra: 10.12.4
* node v8.1.0
* ffmpeg v3.2.2
* fluent-ffmpeg v2.1.2

### Code to reproduce

```
 var ffmpegPath = require('ffmpeg-binaries').ffmpegPath();
    var ffprobePath = require('ffmpeg-binaries').ffprobePath();
          console.log('ffprobePath: ', ffprobePath);
    // Generate a croped file using ffmpeg.
    var command = new ffmpeg({ source: tempFilePath, timeout: 0 })
          .setFfmpegPath(ffmpegPath)
          .setFfprobePath(ffprobePath)
          .inputOption('-t', '10')
          .inputOption('-ss', '10')
          //.outputOption('-acodec', 'copy')
          .audioCodec('aac')
          .on('start', function(commandLine) {
                console.log('Spawned Ffmpeg with command: ', commandLine);
           })
          .on('end', function() {
              console.log('Preview file cropping done successfully');
           })
          .on('error', function(err, stdout, stderr) {
              var build = err;
              if (!stdout === '') { build = build + '\n' + stdout; }
              build = build + '\n' + stderr;
              
              console.log(build);
           }).save(tempFilePath);
    }).then(() => {
    console.log('Preview file created at', tempFilePath);
    // We add a 'preview_' prefix to the audio file name. that's how it will appear in firebase.
    const previewFileName = PREVIEW_PREFIX + fileName;
    console.log('previewFileName is', previewFileName)
    //const previewFilePath = path.join(path.dirname(filePath), previewFileName);
    const previewFilePath = path.join('previewFiles', previewFileName);
    console.log('previewFilePath is', previewFilePath);
    // Uploading the preview file to firebase.
    return bucket.upload(tempFilePath, {destination: previewFilePath});
  // Once the file has been uploaded delete the local file to free up disk space.
  }).then(() => fs.unlinkSync(tempFilePath));
```

### Expected results

When a user records an audio file and uploads to firebase storage, run a trigger that crops a clip of that file and saves it to a "preview" directory. Cropped file should start and stop per the defined mpeg input options. 

### Observed results

When the file arrives on the server, it is just dead air before the start time (10 seconds) and then doesn't stop after the duration of 10 seconds is exceeded.  It also appears on firebase as audio/x-aac, not audio/aac but I don't know if that matters?

There is no "error" for this issue. It just isn't cropping the file correctly. However, I was initially getting the error _Output file #0 does not contain any stream_ but that seems to have gone away by setting the codec explicitly. I have posted that issue, with the stderr, on SO in case that helps. 

https://stackoverflow.com/questions/45715640/ffmpeg-fluent-ffmpeg-output-file-0-does-not-contain-any-stream

### Command Exectued on Firebase

> Spawned Ffmpeg with command:  ffmpeg -t 10 -ss 10 -i /tmp/2EB100B0-6C1E-4D51-9087-764CA653AFC720170711232034.aac -y -acodec aac  /tmp/2EB100B0-6C1E-4D51-9087-764CA653AFC720170711232034.aac

### Above Command Run Locally - Console Output

> $ ffmpeg -t 10 -ss 10 -i 2EB100B0-6C1E-4D51-9087-764CA653AFC720170711232034.aac -y -acodec aac output_file.aac
> 
> ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers built with llvm-gcc 4.2.1 (LLVM build 2336.11.00) configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect libavutil 55. 34.100 / 55. 34.100 libavcodec 57. 64.101 / 57. 64.101 libavformat 57. 56.100 / 57. 56.100 libavdevice 57. 1.100 / 57. 1.100 libavfilter 6. 65.100 / 6. 65.100 libswscale 4. 2.100 / 4. 2.100 libswresample 2. 3.100 / 2. 3.100 libpostproc 54. 1.100 / 54. 1.100 [aac @ 0x7fac6c800a00] Estimating duration from bitrate, this may be inaccurate Input #0, aac, from '2EB100B0-6C1E-4D51-9087-764CA653AFC720170711232034.aac': Duration: 00:01:07.71, bitrate: 223 kb/s Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 277 kb/s Output #0, adts, to 'output_file.aac': Metadata: encoder : Lavf57.56.100 Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 128 kb/s Metadata: encoder : Lavc57.64.101 aac Stream mapping: Stream #0:0 -> #0:0 (aac (native) -> aac (native)) Press [q] to stop, [?] for help size= 159kB time=00:00:10.00 bitrate= 130.5kbits/s speed=12.7x video:0kB audio:156kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.887004% [aac @ 0x7fac6d004600] Qavg: 383.548

Thanks for any help.

**Comment by njoyard** [comment]
I'm closing because it's too old. Sorry for the inactivity, but please reopen this issue if you still have the same problem.
