### ISSUE TITLE
Events override

### ISSUE THREAD

**Issue by SerCarciofini** [fluent-ffmpeg/node-fluent-ffmpeg#746]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.2.4-1build2
* OS: Ubuntu 17.04

### Code to reproduce

```js
var command = new FfmpegCommand();
// here i put start event, but i mean every event
command.on("start", () => console.log("event 1"));
command.on("start", () => console.log("event 2"));
// [some ffmpeg options...]
command.run();
```
### Observed results
```
event 1
event 2
```

As illustrated, when putting two callbacks to the same event, at event time, both callback functions are called. There's no override.
Is there a way to delete registered callbacks?

**Comment by juiyout** [comment]
Run into the same predicament.
Maybe there could be a `clear(event)` function?

**Comment by njoyard** [comment]
https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener
