### ISSUE TITLE
Can't get ffprobe to work

### ISSUE THREAD

**Issue by marceloclp** [fluent-ffmpeg/node-fluent-ffmpeg#749]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: N-87095-gef0c6d9
* OS: Windows 10 x64
* OBS: I am working with Electron.

### Code to reproduce

OBS: `path` is a valid windows path being retrieved directly from an HTML input tag. The file (obviously) exists.
```js
ffmpeg.ffprobe(path, (err, metadata) => {
    console.log(metadata);
});
```

### Expected results
It should return an object with the file's metadata.

### Observed results
Metadata is undefined and this is the returned error:
```
{ Error: spawn D:\Program Files\FFMPEG\bin ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn D:\\Program Files\\FFMPEG\\bin',
  path: 'D:\\Program Files\\FFMPEG\\bin',
  spawnargs:
   [ '-show_streams',
     '-show_format',
     'D:\\Users\\Marcelo\\Videos\\Courses\\Electron for Desktop Apps - The Complete Developer\'s Guide\\01 - Basics of Electron\\01 - How to Get Help.mp4' ] }
```

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [X] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by jasan-s** [comment]
@marceloclp  where you able to solve it? My windows env path is set but ffprobe cant be read a a command ffmpeg does work.  I copied the entire ffmpeg folder into the project directory but now ne error shows `Error Error: spawn /../ffmpeg/bin/ffprobe.exe ENOENT`

**Comment by marceloclp** [comment]
Hi, yes, I managed to solve it. I was linking my env variable to the /bin as explained on the setup guide, rather than the .exe itself. After I fixed it, it worked fine.
