### ISSUE TITLE
Can't open camera in MacOS

### ISSUE THREAD

**Issue by ahwhfei** [fluent-ffmpeg/node-fluent-ffmpeg#751]
The following command can work in Mac OS.
```text
ffmpeg -f avfoundation -r 30 -i "0" -t 10 "output.mpg" 
```

But The following command cannot work well in Mac OS. (Move `-r 30` after `-i "0"`)
```text
ffmpeg -f avfoundation -i "0"  -r 30 -t 10 "output.mpg" 
```

I tried open camera via fluent-ffmpeg in Mac OS. fluent-ffmpeg always generate args list as the second command, `-i "0"` before `-r 30`.

I don't know whether is it a bug of fluent-ffmpeg or ffmpeg.

The following code is my testing code:
```javascript
(function () {

    const ffmpeg = require('fluent-ffmpeg');

    ffmpeg()
        .fps(30)
        .input('0')
        .inputFormat('avfoundation')
        .duration(10)    
        .save(`./${new Date().toLocaleString().split('-').join('').split(':').join('')}.mpg`)
})();
```

**Comment by njoyard** [comment]
Use `inputFps(30)` instead 🙂
