### ISSUE TITLE
how to detect if video file is corrupted(question) 

### ISSUE THREAD

**Issue by jasan-s** [fluent-ffmpeg/node-fluent-ffmpeg#752]
I am currently trying to run some ffmpeg filter on some files , but I have noticed if the file is corrupt the process just hangs forever. How can I detect if the video file is corrupt free in order to run the filters.

**Comment by njoyard** [comment]
Did you try doing it on command line? Does it hang as well?

**Comment by njoyard** [comment]
Closing, no further info given
