### ISSUE TITLE
could not find function "shell" for ffmpeg in R on Mac Sierra 

### ISSUE THREAD

**Issue by ClumsyPro** [fluent-ffmpeg/node-fluent-ffmpeg#753]
Hi
I am very new to Mac. when I was running my R program on windows, ffmpeg worked perfectly. one month ago, I bought Mac and my same program is not working on Mac. I mean this following bit:

call FFMPEG and make the video

shell("open ./ffmpeg -report -i g%d.tif -b:v 2048k NO11_lineR.mpg",mustWork=FALSE)

I kept having this message:
Error in shell("open ./ffmpeg -report -i g%d.tif -b:v 2048k NO11_lineR.mpg", :
could not find function "shell"

before in windows I had this
"C:/Users/Clumsy/Downloads/ffmpeg/bin/ffmpeg.exe" instead of "open ./ffmpeg" and it was just fine.

I tried the following:
"/usr/local/Cellar/ffmpeg/3.3.3"
and "/usr/local/Cellar/ffmpeg"
and" ./ffmpeg"
instead of "open ./ffmpeg" and none of them have worked. still have the same previous shell error message.
I install ffmpeg with homebrew. would you please advice me how to modify the path of ffmpeg in R code so it will work and how to change it on terminal and please consider I am new to all these things: terminal, homebrew, and Mac.

thanks in advance

**Comment by njoyard** [comment]
Hello, sorry but this is not the ffmpeg repository. This is a repository for node-fluent-ffmpeg, an interface module for ffmpeg in nodejs. You should direct your question to the ffmpeg community.
