### ISSUE TITLE
complexFilter apply overlay and get screenshot

### ISSUE THREAD

**Issue by IvanMMM** [fluent-ffmpeg/node-fluent-ffmpeg#754]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: N-85604-g207e6de
* OS: Win10 x64

### Code to reproduce

```js
    return ffmpeg()
        .input(path.join(__dirname,'/videos/SampleVideo_360x240_2mb.mp4'))
        .input(path.join(__dirname,'/test/mark.png'))
        .complexFilter([
            {
                filter:'overlay',
                options:"x=(main_w-overlay_w)/2:y=(main_h-overlay_h)/2"
            }
        ])
        .on('start', function(commandLine) {
            console.log('watermarkvideo Spawned FFmpeg with command: ' + commandLine);
        })
        .on('error', function(err) {
            console.log('watermarkvideo Cannot process video: ' + err.message);
        })
        .on('end', function(filenames) {
            console.log('watermarkvideo Processing finished successfully '+filenames[0]);
        })
        .on('stderr', function(stderrLine) {
            console.log(stderrLine);
        })
        .output(path.join(__dirname,'/videos/watermarked.mp4'))
        .output(path.join(__dirname,'/videos/watermarked.jpg'))
        .run();

```

### Expected results
Two outputs, overlayed videofile and screenshot of this video. If I use only one output, it works fine. But using two gives bad results.

### Observed results
Corrupted videofile with sound and very few first frames and screenshot without overlay on it.

I also saw ComplexFilter called 'select' and tried to use it like 'select=1', but I didn't understand how can I save named outputs, one from overlay and one from screenshot. Looks like it's [possible](https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs) using map, but still can't get it even using map. Can you please give me direction, how can I apply overlay, get screenshot of overlayed video and then save them separate? Thank you :)

**Comment by njoyard** [comment]
I'm not sure what you're trying to achieve here. Did you try doing that on command line ?

**Comment by njoyard** [comment]
Closing, no further info given
