### ISSUE TITLE
Stream to RTMP

### ISSUE THREAD

**Issue by invasioncredible** [fluent-ffmpeg/node-fluent-ffmpeg#756]
Not an issue actually, but need some help. 
Could you please provide a little example how to stream a webm file to RTMP server using this library?

**Comment by astroza** [comment]
Right now, Can you do that with FFmpeg command line?, fluent-ffmpeg is a wrapper for FFmpeg program. There is a synthetic way to translate it to fluent if you already have the command line

**Comment by eskawl** [comment]
There is command line method stated [here](https://wiki.archlinux.org/index.php/Streaming_to_twitch.tv). How should I get started with the synthetic way.

**Comment by njoyard** [comment]
Just pass the RTMP server URL to the `save()` method as if it were a file. There is [a (kinda minimal) example in the tests](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/test/processor.test.js#L1181).
