### ISSUE TITLE
Error: spawn UNKNOWN - WINDOWS 10

### ISSUE THREAD

**Issue by Blitzlord** [fluent-ffmpeg/node-fluent-ffmpeg#759]
This script only doenst work on Windows. No Problems on OSX

### Version information

* fluent-ffmpeg version:  2.1.2
* ffmpeg version: oct. 2017
* OS: Windows 10
* Node Version: v6.11.4

### Code to reproduce

```js
var ffmpeg = require('fluent-ffmpeg');
var command = ffmpeg('test.mp4')
	.save('./test-2.mp4');

```
Code was executed with **admin rights**.

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

A new outputfile.

### Observed results

internal/child_process.js:328
    throw errnoException(err, 'spawn');
    ^

> Error: spawn UNKNOWN
>     at exports._errnoException (util.js:1020:11)
>     at ChildProcess.spawn (internal/child_process.js:328:11)
>     at exports.spawn (child_process.js:369:9)
>     at \node_modules\fluent-ffmpeg\lib\processor.js:152:24
>     at \node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
>     at \node_modules\async\dist\async.js:421:16
>     at \node_modules\async\dist\async.js:5302:29)
>     at \node_modules\async\dist\async.js:906:16
>     at \node_modules\fluent-ffmpeg\lib\capabilities.js:116:11
>     at \node_modules\fluent-ffmpeg\lib\utils.js:225:7

**Comment by njoyard** [comment]
Hey,

This looks like an error when trying to launch the actual ffmpeg executable.
Could you try the following and paste the results:

1. [Set the path to the ffmpeg executable explicitly](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#setting-binary-paths-manually) and retry your code
2. Call `ffmpeg._getFfmpegPath(function(err, command) { console.log(err); console.log(command); })`

**Comment by njoyard** [comment]
Closing, no further info given

**Comment by oumad** [comment]
I got the same issue
```
internal/child_process.js:408
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:553:9)
    at C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\fluent-ffmpeg\lib\processor.js:152:24
    at C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
    at wrapper (C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\async\dist\async.js:268:20)
    at next (C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\async\dist\async.js:4582:24)
    at Object.<anonymous> (C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\ffmpeg.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```



> Hey,
> 
> This looks like an error when trying to launch the actual ffmpeg executable.
> Could you try the following and paste the results:
> 
> 1. [Set the path to the ffmpeg executable explicitly](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#setting-binary-paths-manually) and retry your code
> 2. Call `ffmpeg._getFfmpegPath(function(err, command) { console.log(err); console.log(command); })`

Following These steps gives me `TypeError: ffmpeg._getFfmpegPath is not a function`

This is my code

```js
const ffmpeg = require("fluent-ffmpeg");
const fs = require("fs");

ffmpeg.setFfmpegPath("C:/ffmpeg/bin/ffmpeg.exe");
ffmpeg.setFfprobePath("C:/ffmpeg/bin/ffprobe.exe");

// test ffmpeg path
ffmpeg._getFfmpegPath(function (err, command) {
  console.log(err);
  console.log(command);
});

const videoFile = "path/to/video.mkv";
const videoDir = "path/to/directory";

const command = ffmpeg();
command.input(videoFile);
command.output(`${videoDir}/${videoFile.replace(/\.[^/.]+$/, ".%04d.png")}`);
command.on("start", () => {
  fs.mkdirSync(videoDir, { recursive: true });
});
command.on("end", () => {
  console.log("done");
});
command.on("error", (err) => {
  console.log("error", err);
});
command.run();

```

**Comment by mohsenfaraj** [comment]
if any one has this problem and found this place don't name your node module file ffmpeg.js! this will cause system to think that it should run the ffmpeg.js file instead of ffmpeg and as a result it will break your code!
hope it helps :)

**Comment by Samciu** [comment]
> I got the same issue
> 
> ```
> internal/child_process.js:408
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn UNKNOWN
>     at ChildProcess.spawn (internal/child_process.js:408:11)
>     at spawn (child_process.js:553:9)
>     at C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\fluent-ffmpeg\lib\processor.js:152:24
>     at C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
>     at wrapper (C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\async\dist\async.js:268:20)
>     at next (C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\node_modules\async\dist\async.js:4582:24)
>     at Object.<anonymous> (C:\Users\Mohamed\Desktop\WIP\GEAR_WORKS\DEV\TESTING\image-convert\ffmpeg.js:5:8)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>     at internal/main/run_main_module.js:17:47
> ```
> 
> > Hey,
> > This looks like an error when trying to launch the actual ffmpeg executable.
> > Could you try the following and paste the results:
> > 
> > 1. [Set the path to the ffmpeg executable explicitly](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#setting-binary-paths-manually) and retry your code
> > 2. Call `ffmpeg._getFfmpegPath(function(err, command) { console.log(err); console.log(command); })`
> 
> Following These steps gives me `TypeError: ffmpeg._getFfmpegPath is not a function`
> 
> This is my code
> 
> ```js
> const ffmpeg = require("fluent-ffmpeg");
> const fs = require("fs");
> 
> ffmpeg.setFfmpegPath("C:/ffmpeg/bin/ffmpeg.exe");
> ffmpeg.setFfprobePath("C:/ffmpeg/bin/ffprobe.exe");
> 
> // test ffmpeg path
> ffmpeg._getFfmpegPath(function (err, command) {
>   console.log(err);
>   console.log(command);
> });
> 
> const videoFile = "path/to/video.mkv";
> const videoDir = "path/to/directory";
> 
> const command = ffmpeg();
> command.input(videoFile);
> command.output(`${videoDir}/${videoFile.replace(/\.[^/.]+$/, ".%04d.png")}`);
> command.on("start", () => {
>   fs.mkdirSync(videoDir, { recursive: true });
> });
> command.on("end", () => {
>   console.log("done");
> });
> command.on("error", (err) => {
>   console.log("error", err);
> });
> command.run();
> ```

I got the same issue
