### ISSUE TITLE
Travis CI Build is failing: missing flvtool2

### ISSUE THREAD

**Issue by nfiles** [fluent-ffmpeg/node-fluent-ffmpeg#761]
The Travis CI build is failing (https://travis-ci.org/fluent-ffmpeg/node-fluent-ffmpeg)

```text
apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install wget tar bzip2 flvtool2" failed and exited with 100 during .
```

It looks like the package `flvtool2` is no longer available from the standard PPAs, but it is available from this third-party PPA: https://launchpad.net/~sauce/+archive/ubuntu/ppa

It is possible to [add a third-party PPA](https://docs-staging.travis-ci.com/user/installing-dependencies/#Installing-Packages-from-a-custom-APT-repository) and install `flvtool2`, but I think that requires removing `sudo: false` from the Travis configuration. Are there any security concerns associated with that?

**Comment by njoyard** [comment]
Should we not remove flvtool/flvmeta support altogether ? I mean, who still makes flv videos anyway...

**Comment by nfiles** [comment]
Hmm, I didn't look that far. There can't be many people out there making flv videos, but I'll leave that decision to you. :)
