### ISSUE TITLE
Provide less verbose messages in the message attribute of the error being thrown

### ISSUE THREAD

**Issue by robertmain** [fluent-ffmpeg/node-fluent-ffmpeg#763]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 
* OS: Windows 10

### Code to reproduce

```js
return new Promise((resolve, reject) => ffmpeg('C:\songs\doesntexist.mp3').ffprobe( (err, stream_metadata) => {
    if (err) {
        reject(err)
    } else {
        resolve(stream_metadata);
    }
}))
```

### Expected results
An error object thrown with a short message explaining the nature of the problem (i.e: unable to locate file on disk)

### Observed results
An error object is thrown with `message` and `stack` set to the following:

```
"ffprobe exited with code 1
ffprobe version 3.3.3 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
C:\songs\doesntexist.mp3: No such file or directory
```

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Hey,

This is a good idea, but it would require parsing ffmpeg output and knowing every possible error message. It would also be a nightmare to maintain as every ffmpeg version potentially changes how error are printed out. Plus, some users of fluent-ffmpeg probably already do some kind of parsing of errors in their code, so such a change would break their scripts.

I'm closing this issue, but if you ever come to a solution that seems to *not* cause those issues, feel free to submit a PR :)

**Comment by robertmain** [comment]
>This is a good idea, but it would require parsing ffmpeg output and knowing every possible error message. 


Would it though? From what I've seen it looks like ffmpeg always puts it's error messages in the same place. In fact - you already seem to be somehow detecting that because the actual errror message (for example `C:\songs\doesntexist.mp3: No such file or directory` shows up red whilst the rest of the text shows up white...
