### ISSUE TITLE
Can't remove -filter_complex from the arguments

### ISSUE THREAD

**Issue by numerobis2** [fluent-ffmpeg/node-fluent-ffmpeg#764]
So everytime I use fluent-ffmpeg I end up with "-filter_complex split=1[screen0]"... in the arguments.
It's not a problem with most of the files I deal with but on a few, it causes the screenshot not to be generated.
Also I can't use size() because of it. So my real issue is how to I remove the -filter_complex from the command?
I tried calling **complexFilter** with an empty array, no success, -filter_complex still appears.

### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.3.1
* OS: Windows10

### Code to reproduce

```js
    ffmpeg(videoPath)
    .on("start", (commandLine) => {
        console.log('Spawned ffmpeg with command: ' + commandLine);
    })
    .on("end", (a, b) => {
    })
    .on("error", (err, stdout, stderr) => {
        console.log('--- err')
        console.error(err)
        console.log('--- stdout')
        console.error(stdout)
        console.log('--- stderr')
        console.error(stderr)
    })
    .size('100x100')
    .screenshots({
        count: 1,
        timemarks: ['00:00:25'],
        filename: 'screenshot.jpg',
        folder: 'A:/THUMBS_TEST'
    })
    .complexFilter([])
```
I usually put the size in the object that is passed to **screenshots()** args, but this way the problem happens with every videos.

### Expected results
The screenshot should be created.

### Observed results
Spawned ffmpeg with command: ffmpeg -ss 25 -i A:/video.mp4 -y -filter_complex split=1[screen0] -vframes 1 -filter:v scale=w=100:h=100 -map [screen0] A:\THUMBS_TEST\screenshot.jpg
**--- err**
Error: ffmpeg exited with code 1: Filtergraph 'scale=w=100:h=100' was specified through the -vf/-af/-filter option for output stream 0:0, which is fed from a complex filtergraph.
-vf/-af/-filter and -filter_complex cannot be used together for the same stream.
    at ChildProcess.<anonymous> (D:\PROG\Electron\graffiti\sources\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
**--- stdout**

**--- stderr**
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'A:/video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Part 23: Enabling your app to Record Video
    album           : Part 23: Enabling your app to Record Video
    encoder         : Lavf54.6.101
    comment         : C#, Windows 8, Windows Store App
    copyright       : 2012 Microsoft Corporation
  Duration: 00:04:10.71, start: 0.000000, bitrate: 1704 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1024x576 [SAR 1:1 DAR 16:9], 1575 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 123 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Filtergraph 'scale=w=100:h=100' was specified through the -vf/-af/-filter option for output stream 0:0, which is fed from a complex filtergraph.
-vf/-af/-filter and -filter_complex cannot be used together for the same stream.

**Comment by njoyard** [comment]
The `screenshots()` helper uses `-filter_complex` to generate screenshots. If you want to take screenshots without it, you'll have to do it manually.

As stated in the documentation, you cannot use `size()` with `screenshots()`.
