### ISSUE TITLE
Only one Audio stream included in converted file?

### ISSUE THREAD

**Issue by JustMeDaFaq** [fluent-ffmpeg/node-fluent-ffmpeg#765]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.3.1
* OS: Windows10

### Code to reproduce

```js
app.get('/video/:filename', function(req, res) {
  res.contentType('flv');

  var pathToMovie = 'C:/temp/' + req.params.filename;
  var proc = ffmpeg(pathToMovie)
    .format('matroska')
    .videoCodec('copy')
    .audioChannels(2)
    .audioBitrate('128k')
    .audioCodec('libmp3lame')
    .on('end', function() {
      console.log('file has been converted succesfully');
    })
    .on('error', function(err) {
      console.log('an error happened: ' + err.message);
    })
    .pipe(res, {end:true});
});

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
Both Audio streams, not just the first, should be included in generated file

### Observed results
Only first audio stream exists in generated file.

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Hi,

Which audio streams are you talking about ? From your code it seems you're including 2 audio channels (which means 1 stereo channel).

**Comment by JustMeDaFaq** [comment]
Sorry, i was just too tired. Got it working as intended the other day.
Now just need to get seeking working. As i read, theres no easy way on supporting seeking, or?
Probably just going to use seekInput() and handling stuff like time by myself?

**Comment by njoyard** [comment]
Yeah seeking has to be done manually when you do dynamic transcoding.

The way I implemented it on a project was to use a custom-made client side seek bar, and whenever the user seeked, it just switched the video src to like `/path/to/video/:id/:seektime`, which triggered a new ffmpeg call with a seekInput each time.

**Comment by njoyard** [comment]
Closing, problem was solved
