### ISSUE TITLE
Stream to RTMP

### ISSUE THREAD

**Issue by tjmcclure0501** [fluent-ffmpeg/node-fluent-ffmpeg#768]
### Version information

* fluent-ffmpeg version: 1.21
* ffmpeg version: 3.3.2
* OS: Debian stretch

### Code to reproduce
ffmpeg -re -i /usr/src/../uploads/videos/41ce6dafe8ed8c7c6119298abf89ad33 -y -map 0:0 -pix_fmt yuv420p -vcodec libx264 -r 25 -vf scale=1024:576 -threads 0 -b:v: 2048k -bufsize 2244k -maxrate 2560k -preset veryfast -profile:v baseline -tune zerolatency -g 100 -x264opts no-scenecut -f flv "rtmp://wowza_user:BUvaN2vapruprat@develop-wowza.strax.co:1935/live/eei-1292.stream flashver=FMLE/3.0(compatible;FMSc/1.0) live=true" -map 0:1 -codec copy -f mpegts udp://localhost:1282

The following command works from the command line but does not work through the fluent-ffmpeg.  I get the following error:

FFMPEG stopped ffmpeg exited with code 1: "rtmp://wowza_user:BUvaN2vapruprat@develop-wowza.strax.co:1935/live/eei-1292.stream flashver=FMLE/3.0?(compatible;?FMSc/1.0) live=true": No such file or directory

It seems it does not recognize then rtmp url and all of it's parameters.  There was a similiar issue closed 3 days ago - I did not know how to reopen it.  I look at the unit tests and they were not doing the same as me.

The code:

 if(config.video.path) {
    inputOptions.push('-re');
    console.log('APP_ROOT', process.env.APP_ROOT);
    url = `${process.env.APP_ROOT}/${config.video.path}`;

    var outputOptionsVideo = [];

    outputOptionsVideo.push('-map');
    outputOptionsVideo.push('0:0');

    config.options.forEach(function (entry) {
      outputOptionsVideo.push(entry)
    })

    outputOptionsVideo.push('-f');
    outputOptionsVideo.push('flv');

    console.log("config=" + JSON.stringify(config));
    var outputUrl = '"rtmp://'  + config.userName + ':' + config.password + '@' + process.env.WOWZA_SERVER + '/' + process.env.WOWZA_APPLICATION + '/' + config.feedName + '.stream flashver=FMLE/3.0\20(compatible;\20FMSc/1.0) live=true"';
    var klvUrl = config.klvUrl;

    this.command = ffmpeg(url).inputOptions(inputOptions).output(outputUrl).outputOptions(outputOptionsVideo)
      .on('start', function (commandLine) {
        self.count++;
        self.logger.debug("loop count=" + self.count);
        self.commandLine = commandLine;
        self.logger.debug("command line=" + self.commandLine);
      })
      .on('error', function (err) {
        if ((err.message.includes('ffmpeg was killed with signal SIGKILL')) === false) {
          self.logger.error("command line =" + self.commandLine);
          self.logger.error('FFMPEG stopped ' + err.message);
        }
      })
      .on('end', () => {
        logger.info(`${this.config.video.name} finished playing.`);

        const payload = {
          _id: this.config._id,
          capture: 'false'
        };
        this.mediaService.updateVideoFeed(this.config._id, payload).then(function () {
            logger.info('Feed successfully updated after simulation run.');
          })
          .catch(function (err) {
            logger.error('Error updating feed after simulation run.', err.error);
          });
      });

      var outputOptionsKLV = [];
      outputOptionsKLV.push('-map');
      outputOptionsKLV.push('0:1');
      outputOptionsKLV.push('-codec');
      outputOptionsKLV.push('copy');
      outputOptionsKLV.push('-f');
      outputOptionsKLV.push('mpegts');
      this.command.output(klvUrl).outputOptions(outputOptionsKLV);

    this.command.run();
    this.running = true;

**Comment by tjmcclure0501** [comment]
I installed flvmake it that did not help.

**Comment by tjmcclure0501** [comment]
Sorry I meant I install flvmeta and it did not help.

**Comment by njoyard** [comment]
Remove the double quotes from the output. Double quotes are only useful when using a shell, you're not using a shell here.
