### ISSUE TITLE
How can I stream to multiple rtmp outputs?

### ISSUE THREAD

**Issue by rabashani** [fluent-ffmpeg/node-fluent-ffmpeg#775]
### Code to reproduce

```js
var command = ffmpeg('video.mp4')
      .videoCodec('libx264')
      .audioCodec('copy')
      .outputOptions(['-map 0', '-flags', '+global_header', '-c:v libx264', '-c:a aac'])
      .outputOptions(['-f', 'tee'])
      .output(destinationsArray[0])
      .format('flv')
      .output(destinationsArray[1])
      .format('flv')
      .run();

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
actually i am trying to generate this command -- 

-map 0 -flags +global_header -c:v libx264 -c:a aac -f tee "[f=flv:onfail=ignore]$rtmp1 | [f=flv:onfail=ignore]$rtmp2"

**Comment by njoyard** [comment]
What is the problem ?

**Comment by njoyard** [comment]
Closing, no further info given
