### ISSUE TITLE
Keep aspect ratio while generating screenshots

### ISSUE THREAD

**Issue by nlfiedler** [fluent-ffmpeg/node-fluent-ffmpeg#776]
Is there a means of invoking the same basic operation as the following command line invocation?

```
$ ffmpeg -i infile -vframes 1 -an -filter:v scale=w=240:h=240:force_original_aspect_ratio=decrease outfile
```

That is, I want to take the first frame of the video, resize to 240x240 pixels, while maintaining the aspect ratio. I cannot see how to do this with the existing fluent-ffmpeg API.

**Comment by nlfiedler** [comment]
I should clarify that I am speaking of the `screenshots()` function, but I don't see how to keep the aspect ratio when using that function.

**Comment by njoyard** [comment]
For something that specific you should not use the screenshots function I think. It's far easier just to write the command. Look at the docs, it should be pretty straightforward.

**Comment by mulhoon** [comment]
I used the video metadata to set the screenshot size using the display_aspect_ratio. This fixed issues where the videos weren't the correct ratio. 
```js
ffmpeg.ffprobe('movie.mp4', function(err, metadata) {

	let meta = metadata.streams[0]
	let ratio = meta.display_aspect_ratio.split(':')
	ratio = ratio[0] / ratio[1]
	let width = Math.round(meta.height * ratio)
	let height = meta.height

	ffmpeg(filename)
		.screenshots({
			timestamps: ['0.10'],
			filename: 'poster.png',
			folder: '/dist',
			size: width + 'x' + height,
		})
})
```
I know this is an old question, but it was useful for me. You can replace both `meta.height` to `240` to limit the height to 240 while maintaining aspect ratio. With a little fiddling you can make it fit 240 width or height
