### ISSUE TITLE
mergeToFile not working

### ISSUE THREAD

**Issue by yamiryu** [fluent-ffmpeg/node-fluent-ffmpeg#779]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.4.1 (installed using ``@ffmpeg-installer/ffmpeg``)
* OS: OSX 10.12.6

### Code to reproduce

```js
let deferred = promise.defer(); // Selenium webdriver promise, can be replaced with making a native Promise
let imgList = getFiles(inDir); // Sync get list of image names from a directory
// ... Already done check exist and empty directory, imgList is verified to have correct list of files

let fCommand = ffmpeg();
Promise.resolve(fCommand)
.then((fCmd) => {
    return imgList.reduce((result, img) => {
        result.input(path.join(inDir, img));
        return result;
    }, fCmd);
})
.then((fCmd) => {
    // console.log(fCmd._inputs) // verified to contain all of the inputs
    fCmd.outputFPS(fps)
        .outputFormat('mp4')
        .videoBitrate('1024k')
        .videoCodec('libx264')
        .outputOptions('-pix_fmt yuv420p')
        .on('start', () => {
            console.log('    Creating video...');
        })
        .on('error', (err, stdout, stderr) => {
            console.log('        Error: ' + err.message);
            console.log('        ffmpeg output:\n' + stdout);
            console.log('        ffmpeg stderr:\n' + stderr);
            deferred.reject(err);
        })
        .on('end', () => {
            console.log('        Video created.');
            deferred.resolve('Video created.');
        })
        .mergeToFile(path.join(outDir, 'movie.mp4'), path.join(outDir, 'tmp/'));
});

return deferred.promise;

```

### Expected results
A video containing all images that are in ``imgList``

### Observed results
Only create 0 to 1 second video, show up to the second image, eliminating the rest of the list. Terminal output looks fine, no error.
It works ok if I change file names to use for example ``%03d.png`` and ``output()``. But my file name also contains varied short description, and I can't use ``*`` like ``ffmpeg``. Probably should use something to mark any-string?
Is there a way to just pass the inputDir and file filter like .png?

**Comment by njoyard** [comment]
There is no way to pass a directory or a file glob for now, but that could be a feature if someone wants to make a PR.

Could you try to get that command to do what you want from command line, by specifying each output explicitly (no file globs) and see if something is missing ?

**Comment by njoyard** [comment]
Closing, no further info given
