### ISSUE TITLE
could I create video from array rather than files?

### ISSUE THREAD

**Issue by PinkGabriel** [fluent-ffmpeg/node-fluent-ffmpeg#782]
In my node program, I get jpeg files from aws S3 and convert them into videos, but I only found the file input.
Could I use array in the memory as input to form a video?

thanks very much!

**Comment by njoyard** [comment]
You can pass readable streams as inputs, see https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#specifying-inputs
