### ISSUE TITLE
setFfmpegPath doesnt work

### ISSUE THREAD

**Issue by haojia321** [fluent-ffmpeg/node-fluent-ffmpeg#786]
Hi,
For some reason I cannot install ffmpeg on my cloud server. So I have to use a ffmpeg static binary here. This is the static lib im using https://www.npmjs.com/package/ffmpeg-static

My when I try to manually set the path by calling setFfmpegPath. It gives below errors: 
I20171225-19:26:53.321(-5)? Exception in callback of async function: Error: Cannot find module './lib/fluent-ffmpeg'
I20171225-19:26:53.322(-5)?     at makeMissingError (packages/modules-runtime.js:221:12)
I20171225-19:26:53.322(-5)?     at require (packages/modules-runtime.js:231:19)
I20171225-19:26:53.323(-5)?     at meteorInstall.node_modules.fluent-ffmpeg.index.js (packages/modules.js:481:86)
I20171225-19:26:53.323(-5)?     at fileEvaluate (packages/modules-runtime.js:333:9)
I20171225-19:26:53.323(-5)?     at require (packages/modules-runtime.js:228:16)
I20171225-19:26:53.324(-5)?     at imports/server/AttachmentFile.js:59:30
I20171225-19:26:53.324(-5)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20171225-19:26:53.325(-5)?     at FilesCollection.onAfterUpload (imports/server/AttachmentFile.js:51:15)
I20171225-19:26:53.325(-5)?     at packages/ostrio_files.js:927:50
I20171225-19:26:53.326(-5)?     at packages/mongo/collection.js:652:5

**Comment by haojia321** [comment]
This is the code how I call ffmpeg

var ffmpegStatic = require('ffmpeg-static');
                var ffprobeStatic = require('ffprobe-static');
                console.log(ffmpegStatic);
                var ffmpeg = require("fluent-ffmpeg");
                ffmpeg.setFfmpegPath(ffmpegStatic.path);
                ffmpeg.setFfprobePath(ffprobeStatic.path);

**Comment by njoyard** [comment]
Can you please relate the error stack trace to your code ? I don't see where it fails.

**Comment by AdityaAnand1** [comment]
I'm facing the same error, I need to hook up ffmpeg-static binaries with fluent ffmpeg. Although ffmpeg static gives me back the "correct" path (\bin\win\x64\ffmpeg.exe), upon running the application it does not seem to find it.

I'm not sure where the root is supposed to be. @haojia321 How did you solve this?

**Comment by haojia321** [comment]
I had to install ffmpeg in local server and explicitly called the cmd command to use it.

However there is another post might help. Please let me know if it works for you.

https://github.com/damianociarla/node-ffmpeg/issues/45#issuecomment-378416108
