### ISSUE TITLE
saveToFile xxx.pcm file error

### ISSUE THREAD

**Issue by eadio** [fluent-ffmpeg/node-fluent-ffmpeg#788]
i use express to write some code like this:
`var express=require('express');
var router=express.Router();
var fs=require('fs');
var Multiparty =require('multiparty');
var ffmpeg=require('fluent-ffmpeg');//创建一个ffmpeg命令
var command=ffmpeg();

router.post('/recognition', function(req, res, next){
...
    command.addInput('./public/audio/recognition.mp3')
      //.withAudioCodec('pcm_s16le')
      // .withAudioBitrate('48k')
      //.withAudioChannels(1)
      //.saveToFile('./public/audio/222.wav')//it works
      .saveToFile('./public/audio/16k-2.pcm')//it error
      .on('error', function(err){
        console.log('mp3 to pcm error');
        console.log(err)
      })
      .on('end', function(){
        console.log('processiong finish');
//do something
      })
......
});

module.exports=router;`

if i save to xxx.wav that works. but i try to save to xxx.pcm. that make mistakes like this:

Error: ffmpeg exited with code 1: ./public/audio/16k-2.pcm: Invalid argument

    at ChildProcess.<anonymous> (e:\MeijuWork\chuquyou_xcx_server\node_modules\f
luent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)

**Comment by njoyard** [comment]
Please try to do the same with command line ffmpeg first.
Please look at ffmpeg stderr, it will tell you what is wrong.
In this case it's most likely that the pcm format you're trying to write is missing some parameters.

**Comment by itcastWsy** [comment]
i had this problem too .
