### ISSUE TITLE
Pause/Resume Ffmpeg transcoding process on Windows?

### ISSUE THREAD

**Issue by ericmai624** [fluent-ffmpeg/node-fluent-ffmpeg#789]
Hello everyone, is there a way to pause/resume the ffmpeg process systematically on Windows?

command.kill() works on Mac but I don't think Windows supports signal which maybe the reason it failed. 

Any suggestions on workaround? 

Thanks!

### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.4.1
* OS: Windows 10

### Code to reproduce

```js
command.kill('SIGSTOP')

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
ffmpegProc should pause. 

### Observed results
[0] internal/util.js:186
[0]   throw new errors.TypeError('ERR_UNKNOWN_SIGNAL', signal);
[0]   ^
[0]
[0] TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: SIGCONT

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by liweilup** [comment]
I also encountered such a problem, do you have not resolved. please help me. Thank you

**Comment by njoyard** [comment]
Not that I know of unfortunately. You should look more generally at how to suspend/resume processes in windows from node, not sure there is a way.

**Comment by laggingreflex** [comment]
I was looking for the same thing, found an answer on [video.stackexchange][1]: 

>A simple method is to suspend it with <kbd>ctrl</kbd><kbd>z</kbd>. Or you could get the PID with `pgrep ffmpeg` then use `kill -s SIGSTOP <PID>` to suspend.
>
>Then resume with `fg` command or `kill -s SIGCONT <PID>`

I think it might be easier if this were implemented in fluent-ffmpeg itself, it could these signals to the ffmpeg child process.

[1]: https://video.stackexchange.com/questions/17061/is-there-a-way-to-pause-and-resume-ffmpeg-encoding

**Comment by jimlynnjulian** [comment]
Click F12 (Pause) and when ready, resume by giving the console window focus and clicking the "Eneter" key. This will not let you close the console window or reboot the computer.

**Comment by dixiak** [comment]
In Windows 10, run ffmpeg from a PowerShell window.
Now while transcoding, if you select a block of text the process will be paused.
Press enter to unselect the text and the process will resume.

**Comment by FedericoCarboni** [comment]
I'm writing this just for reference, for anyone who might still be looking for a way to pause FFmpeg, or any other process type from Node.js.
Suspending a process in Windows is a non-trivial topic, there is no way (as of today) to do it from JavaScript in Node.js, the only way to do it is to write a native addon and suspend the process by its id from C++.
