### ISSUE TITLE
Simulating a command

### ISSUE THREAD

**Issue by Anmolk22** [fluent-ffmpeg/node-fluent-ffmpeg#790]
I am trying to Dynamic adaptive streaming using http. So, I am following this tutorial as per this tutorial it uses the FFmpeg software I was looking for a nodejs lib and found 

Tutorial Link https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/

I am trying to use ffmpeg into a nodejs project. Can I simulate the command mention below:

ffmpeg -y -i inputfile -c:a libfdk_aac -ac 2 -ab 128k -c:v libx264 -x264opts 'keyint=24:min-keyint=24:no-scenecut' -b:v 800k -maxrate 800k -bufsize 500k -vf "scale=-1:540" outputfile540.mp4

**Comment by njoyard** [comment]
Most likely, yes.
Please read the documentation and try to do it, and open an issue here if you have problems.
