### ISSUE TITLE
How to reduce size of a video using ffpmeg ?

### ISSUE THREAD

**Issue by chanakaDe** [fluent-ffmpeg/node-fluent-ffmpeg#792]
Guys,
I'm new to ffpmeg. But I have use Node JS a lot. I need to use this for some video controlling application about drones. What I'm doing is uploading some drone footage and using GPS, drawing paths and manipulate some stuff. Those video size is so high. The format can be .mp4 or .avi. I think format of the video doesn't matter.
Is there any way to reduce size of the video using ffmpeg ? Please guys this question is not according to your issue reporting format. Pardon on that. Can anyone help me. Imagine the original size is 500 MB and need to reduce the size. At least to 400MB or better than that.

**Comment by njoyard** [comment]
This is an issue about ffmpeg, not fluent-ffmpeg. Please direct your question to the ffmpeg community !

**Comment by chanakaDe** [comment]
someone told me this task can be done by node-fluent-ffmpeg
Can't this ?

**Comment by chanakaDe** [comment]
@njoyard  Please advice

**Comment by njoyard** [comment]
@chanakaDe fluent-ffmpeg is a wrapper to ffmpeg. You have to find out what you want to do with ffmpeg first.
