### ISSUE TITLE
using showwavespic in filter, help needed

### ISSUE THREAD

**Issue by Lutando** [fluent-ffmpeg/node-fluent-ffmpeg#795]
For the life of me I cannot figure out to translate:

`-i foo.mp3 -filter_complex aformat=channel_layouts=mono,showwavespic=s=4000x1000 -frames:v 1 foo.png`

Into a fluent-ffmpeg command. Can anyone help me out?

I have tried with the most basic command:

```
var inputStream = fs.createReadStream('C:/Somewhere/foo.mp3')
var outputStream = fs.createWriteStream('C:/Somehere/foo.png')

var proc = ffmpeg()
     .input(inputStream)
     .complexFilter([
         'showwavespic'
     ])
     .on('error', function(err) {
          console.log('an error happened: ' + err.message);
     })
     .save(outputStream);
```

I get the error thrown from the handler:` an error happened: ffmpeg exited with code 1: Cannot find a matching stream for unlabeled input pad 0 on filter Parsed_showwavespic_1`

I have also tried using .AudioFilters() but that doesnt work too.

**Comment by njoyard** [comment]
First, why are you creating streams for your files? This is useless here, ffmpeg can open the files itself directly, just pass the filenames to `input()` and `save()` (you can even bypass `input()` altogether and pass the input filename to the constructor).

Second, you should pass complete filters to `complexFilters()` (see [the docs](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#complexfilterfilters-map-set-complex-filtergraph)), for example

```js
     .complexFilter([
         'aformat=channel_layouts=mono',
         'showwavespic=s=4000x1000'
     ])
```

or you can split the options for a more js-y syntax:

```js
     .complexFilter([
         { filter: 'aformat', options: { channel_layouts: 'mono' } },
         { filter: 'showwavespic', options: { s: '4000x1000' } }
     ])
```

**Comment by Lutando** [comment]
I am reading the files from a cloud bucket in my real use case. It works fine for transcoding pretty well, just need to produce that png waveform for it too which is where it is not working too well (even locally as described in my code snippet)

Have you tried your complexFilter suggestions? They do not work for me as I get the same error as explained above, using latest npm package and all.

```
var proc = ffmpeg('C:/Somewhere/something.mp3')
  .complexFilter([
    'aformat=channel_layouts=mono',
    'showwavespic=s=4000x1000'
  ])
  .on('error', function(err) {
    console.log('an error happened: ' + err.message);
  })
  .save('C:/Somewhere/something.png');
```

`Ffmpeg.getAvailableFilters` shows that I indeed have the filters required to do this operation. Thanks for your response, I know you are no longer in active support for this project right now.

**Comment by njoyard** [comment]
Hmm... I had not tried the conversion myself, but indeed it fails. Ffmpeg seems to not like it when filter chains are joined with semicolons (which it used to like), only with commas now.

You can use `.complexFilter("aformat=foo,showwavespic=bar")` directly to work around that until a fix is available.

**Comment by njoyard** [comment]
> Ffmpeg seems to not like it when filter chains are joined with semicolons (which it used to like), only with commas now.

Erratum: it seems I understood (filtergraph syntax)[https://ffmpeg.org/ffmpeg-all.html#Filtergraph-syntax-1] wrongly, especially the distinction between filterchains and filtergraphs.

For now, if you want to specify filterchains with several filters, you have to pass them as comma-sepearated strings.

**Comment by Lutando** [comment]
Fantastic :) thanks
