### ISSUE TITLE
Cannot find module './lib-cov/fluent-ffmpeg' while using with BrowserifyRails

### ISSUE THREAD

**Issue by dharin** [fluent-ffmpeg/node-fluent-ffmpeg#796]
I am getting `Cannot find module './lib-cov/fluent-ffmpeg'` error. I am using 'youtube.com' node_module which is using this node_module as dependency. I am not using angular-cli.

I am getting BrowserifyRails::BrowserifyError - Cannot find module './lib-cov/fluent-ffmpeg'

How I can set process.env.FLUENTFFMPEG_COV = false with BrowserifyRails?

**Comment by njoyard** [comment]
Please [search](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues?utf8=%E2%9C%93&q=is%3Aissue+lib-cov) before opening issues

**Comment by Olfeix** [comment]
Oh man, this issue still exists.
This issue is not solved.
