### ISSUE TITLE
Stream RTSP URL and get Frames in JPG or PNG format

### ISSUE THREAD

**Issue by komalpharate** [fluent-ffmpeg/node-fluent-ffmpeg#798]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 2.8.11-0ubuntu0.16.04.1
* OS:linux

### Code to reproduce

```js


```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
I have the rtsp url. format-   rtsp://<ip_address>:<port>/onvif1
Video streams with 25fps
I need 1fps so need grab frame after a second.
Can I get the code to do that?

ffmpeg -loglevel debug -rtsp_transport tcp -i "rtsp://<ip_address>:<port>/onvif1" -c copy -map 0 foo.mp4

I'm able to get video from this command

**Comment by njoyard** [comment]
Please read the docs
