### ISSUE TITLE
PassThrough stream not working

### ISSUE THREAD

**Issue by SkeLLLa** [fluent-ffmpeg/node-fluent-ffmpeg#804]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: ```ffmpeg version N-87327-g18821e3ba1-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-5) 20170906
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 75.100 / 55. 75.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100```
* OS: linux
* Node.js: 9.4.0

### Code to reproduce

Just as in example:

```js
var command = ffmpeg('/path/to/file.avi')
  .videoCodec('libx264')
  .audioCodec('libmp3lame')
  .size('320x240')
  .on('error', function(err) {
    console.log('An error occurred: ' + err.message);
  })
  .on('end', function() {
    console.log('Processing finished !');
  });
 
var ffstream = command.pipe();
ffstream.on('data', function(chunk) {
  console.log('ffmpeg just wrote ' + chunk.length + ' bytes');
});
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

Messages like `ffmpeg just wrote` are shown in console

### Observed results

Ffmpeg exits with code 1: `Error: FFmpeg exited with code 1: pipe:1: Invalid argument`
Stdout/err: `[NULL @ 0x5269640] Unable to find a suitable output format for 'pipe:1'`

**Comment by njoyard** [comment]
You have to specify an output format, ffmpeg cannot guess which output format you want when writing to a stream.

**Comment by SkeLLLa** [comment]
First of all, that's an example from the documentation. If it's not working there are two cases:
- the example is wrong
- the example was correct, but the bug appeared later because this case wasn't properly tested.

The second thing is, FFmpeg could guess file format from the file extension. But there's no option to pass it through pipe methods of this module.

**Comment by njoyard** [comment]
@SkeLLLa there is no file name when using pipe outputs. It's a stream, not a file.

Examples are mostly outdated. Feel free to write a PR to fix them.
