### ISSUE TITLE
How to apply a low- and highpass?

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#806]
I'd like to reduce background noise by applying a low and high audio filter. For example like that

```
$ ffmpeg -i INPUT -af lowpass=3000,highpass=200 OUTPUT
```

(inspired by https://manerosss.wordpress.com/2017/07/24/ffmpeg-%C2%B7-apply-a-filter-to-enhance-voice-by-removing-low-and-high-frequency-noises/)

In your examples, can't find any hints how to achieve this best. Using latest version here.

Thanks for adding documentation how to do this.

**Comment by gvsro** [comment]
```javascript
var ffmpeg = require('fluent-ffmpeg');
var proc = ffmpeg()
    .input('test.mp3', {'af':"lowpass=3000,highpass=200"})

    .on('end', function() {
        console.log('File has been converted succesfully');
    })

    .on('error', function(err) {
        console.log('Error ' + err.message);
   })

    .save('test_filtered.mp3');
```

**Comment by binarykitchen** [comment]
thanks - can't i set it via `inputOptions()`?

**Comment by binarykitchen** [comment]
never mind, sorted it out and works well. thanks

**Comment by BryanOliverosD** [comment]
@binarykitchen how to solve that problem ? with inputOptions or with audioFilters?

**Comment by binarykitchen** [comment]
it's like `addInput(file, { af: 'lowpass=3000,highpass=200' })`

**Comment by shikharpatel5** [comment]
@binarykitchen how do I apply afftdn to it ? 
CLI code ->   -af "afftdn=nf=-25"

**Comment by sergeevabc** [comment]
I'd like to turn off **everything** below 16000 Hz and listen to what's left.
Trying lowpass and highpass with no luck. Any help would be appreciated.
