### ISSUE TITLE
Unrecognized option 'headers'  using http path as input and custom headers for OptionsInput.

### ISSUE THREAD

**Issue by fcheong3b** [fluent-ffmpeg/node-fluent-ffmpeg#808]
### Version information

* fluent-ffmpeg version: ^2.1.2
* ffmpeg version:3.4.2
* OS: macOS High Sierra 10.13.3

### Code to reproduce

```js


```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Observed results

ffmpeg exited with code 1: Unrecognized option 'headers 'access-key: my-privtae-key'. Error splitting the argument list: Option not found

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Please include code, stderr and stdout in bug reports.

**Comment by charles001636** [comment]
"headers" option must be before "-i" even in the command line
So we need to use "addInputOption" instead.
the syntax should be
`proc.addInputOption('-headers','Referer: http://www.example.com')`

hope this help

**Comment by hkcharleschan** [comment]
"headers" option must be before "-i" even in the command line
So we need to use "addInputOption" instead.
the syntax should be
`proc.addInputOption('-headers','Referer: http://www.example.com')`

hope this help
