### ISSUE TITLE
[Close files mp4] fluent-ffmpeg don't close file after parse mp4 file

### ISSUE THREAD

**Issue by duyanhstar** [fluent-ffmpeg/node-fluent-ffmpeg#810]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.3.4-2
* OS: Ubutu 16, ubutu 17

### Code to reproduce

```
ffmpeg(path_MP4)
            .addOption('-hls_playlist_type', 'vod')
            .on('end', function(stdout, stderr) {
                 if(fs.existsSync(path_MP4))
                            fs.unlink(path_MP4);
                return true;

            }).save(path_M3u8);


```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results

I want to deleled  path_MP4 after video is finished.
but i don't see any release space! when i check : sudo lsof | egrep '^COMMAND|deleted'

i see ( look my pic): 

![29354600_1489422337832800_4846314963563160753_o](https://user-images.githubusercontent.com/14048444/37898088-16b3d88a-3112-11e8-9207-9a21cbe6da1f.jpg)

So i think  problem from fluent-ffmpeg which don't close file mp4 after proccessing

### Checklist

* [x ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ x] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
Fluent-ffmpeg does not open files. It passes the filenames to ffmpeg, which is the one actually opening files.

Did you actually try on command line to see if something similar happens?

Please also include stderr and stdout from ffmpeg.

**Comment by duyanhstar** [comment]
i i check, i don't see anything...but when i use htop, i see this duple process
