### ISSUE TITLE
How to mux audio at a delay of 0.25sec?

### ISSUE THREAD

**Issue by binarykitchen** [fluent-ffmpeg/node-fluent-ffmpeg#815]
I have a situation where the audio is ahead of the video of my final video.

Based on https://superuser.com/questions/982342/in-ffmpeg-how-to-delay-only-the-audio-of-a-mp4-video-without-converting-the-au it seems to be possible to pull back audio with a small offset.

But I do not see how this is doable with node-fluent-ffmpeg. Tried to get smart with the documentation. Probably I missed something?

**Comment by njoyard** [comment]
What did you try ?

**Comment by binarykitchen** [comment]
honestly nothing. not getting smart when reading documentation. there is the `itsoffset` argument but how to use it, to apply it to the correct stream?

**Comment by gvsro** [comment]
```
var ffmpeg = require('fluent-ffmpeg');
var conv = new ffmpeg({ source: 'E:\\test\\Big_Buck_Bunny_1080p_surround\\test.avi'}, { logger: "debug"});
conv
.addOptions(['-itsoffset 3', '-i E:\\test\\Big_Buck_Bunny_1080p_surround\\test.avi', '-map 0:v', '-map 1:a', '-c copy'])
.on('start', function(commandLine) {
	cmd=commandLine;
	console.log(commandLine);
	console.log('Start ...');
})
.on('progress', function(progress) {
	console.log(Math.round(+progress.percent));
})
.on('error', function(err, stdout, stderr) {
	dty='\n\Command : \n'+cmd+'\n\Message: \n'+err.message+'\n\nStderr : \n'+stderr+'\n\nStdout : \n'+stdout;
	console.log('Convert Err : '+dty);
})
.on('end', function(filenames) {
	console.log("\n\nFinish.\n\n");
})
.saveToFile('delayed-3s-test.mp4')
```
The key part is ``` -itsoffset 3 ``` and specifying the input file again right after.
For more info check your own stackoverflow [link.](https://superuser.com/questions/982342/in-ffmpeg-how-to-delay-only-the-audio-of-a-mp4-video-without-converting-the-au)

**Don't forget to close the issue if this answer suffices your needs.**

**Comment by gvsro** [comment]
Can we double check and close this? @njoyard or @binarykitchen

**Comment by gvsro** [comment]
@binarykitchen If you have any problems, feel free to reopen the issue.

**Comment by binarykitchen** [comment]
sure, so busy right now but will check out your code sooner or later
