### ISSUE TITLE
Progress only getting called at the first download

### ISSUE THREAD

**Issue by escept** [fluent-ffmpeg/node-fluent-ffmpeg#817]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 3.4.2
* OS: Windows 10

### Code to reproduce

```js
    let stream = ytdl(link, { quality: "highestaudio" });       
    ffmpeg(stream)
      .audioBitrate(128)
      .save(`${socket.id}.mp3`)
      .on("progress", p => {
        socket.emit(
          "progress",
          Math.floor(toSec(p.timemark) / socket["seconds"] * 100)
        );
      })
      .on("end", () => {
        exclusions.push("/" + socket.id + ".mp3");
        socket.emit("finished", socket.id + ".mp3");
      });
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
A progress bar to show up on each download

### Observed results
The progress bar works fine on the first file, then will never get called until the script is restarted.
(No output was given in the console.)

**Comment by njoyard** [comment]
Set the event handlers before calling `save()`.
