### ISSUE TITLE
How to get total bytes in a stream?

### ISSUE THREAD

**Issue by owen-mills** [fluent-ffmpeg/node-fluent-ffmpeg#821]
How do I get the total byte size of a stream in ffmpeg? I am converting an mp4 `readStream` to just audio by using `noVideo()` on it. How do I get the resulting total bytesize of the new file before it is converted?

**Comment by njoyard** [comment]
You can't, unless you use a CBR encoding and do the bitrate*duration computation yourself.

**Comment by owen-mills** [comment]
That's what I'm doing. Thank you.
