### ISSUE TITLE
merge multiple videos to a single .mp4 files

### ISSUE THREAD

**Issue by krisalay** [fluent-ffmpeg/node-fluent-ffmpeg#831]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version:4
* OS:linux mint

### Code to reproduce

```js
var fluent_ffmpeg = require("fluent-ffmpeg");

var mergedVideo = fluent_ffmpeg();

mergedVideo
  .mergeAdd('./Video1.mp4')
  .mergeAdd('./Video2.mp4')
  // .inputOptions(['-loglevel error','-hwaccel vdpau'])
  // .outputOptions('-c:v h264_nvenc')
  .on('error', function(err) {
      console.log('Error ' + err.message);
  })
  .on('end', function() {
      console.log('Finished!');
  })
  .mergeToFile('./mergedVideo8.mp4', '/tmp');

```
When I run this code, then I get `conversion failed` error.

### Observed results

```
Error ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #3:0
Conversion failed!
```

I have tried the same conversion using the command line:
`ffmpeg -f concat -i textfile -c copy -fflags +genpts merged8.mp4`
Where `textfile` has the following content-
```
file 'Video1.mp4'
file 'Video2.mp4'
```
And I was able to concatenate the video file. But I want to get the same result using this package.

**Comment by acuntex** [comment]
I'm using the following snippet:

```
async function mergeFilesAsync(files, folder, filename)
{
	return new Promise((resolve, reject) => {
	
		var cmd = ffmpeg({priority: 20}).videoCodec('h264').fps(29.7)
		.on('error', function(err) {
			console.log('An error occurred: ' + err.message);
			resolve()
		})
		.on('end', function() {
			console.log(filename + ': Processing finished !');
			resolve()
		});

		for (var i = 0; i < files.length; i++)
		{
			cmd.input(files[i]);
		}
	
		cmd.mergeToFile(folder + "/" + filename, folder);
	});
}
```

**Comment by tupizz** [comment]
> I'm using the following snippet:
> 
> ```
> async function mergeFilesAsync(files, folder, filename)
> {
> 	return new Promise((resolve, reject) => {
> 	
> 		var cmd = ffmpeg({priority: 20}).videoCodec('h264').fps(29.7)
> 		.on('error', function(err) {
> 			console.log('An error occurred: ' + err.message);
> 			resolve()
> 		})
> 		.on('end', function() {
> 			console.log(filename + ': Processing finished !');
> 			resolve()
> 		});
> 
> 		for (var i = 0; i < files.length; i++)
> 		{
> 			cmd.input(files[i]);
> 		}
> 	
> 		cmd.mergeToFile(folder + "/" + filename, folder);
> 	});
> }
> ```

It's working?

**Comment by jatingajera31** [comment]
i am trying this way but not merge file it gives error 
error: ffmpeg exited with code 1: Cannot find a matching stream for unlabeled input pad 3 on filter Parsed_concat_0

my code:
 
ffmpeg('videos/test.webm')
    .input('videos/test2.webm')
    .on('error', function(err) {
      console.log('An error occurred: ' , err);
    })
    .on('end', function() {
      console.log('Merging finished !');
    })
    .mergeToFile('../videos/merged.avi', '../new');

**Comment by codingMASTER398** [comment]
did anyone get a solution?

**Comment by dannycortesv** [comment]
@codingMASTER398 i could make it work by using videos of the same dimensions, but still takes a looot of time...

**Comment by ZinovNikita** [comment]
ffmpeg('list.txt')
    .inputOptions(['-f concat','-safe 0']).outputOptions(['-c copy'])
    .on('end', () => console.log('DONE'))
    .save('video.mp4')

**Comment by klesun** [comment]
Hm, I'm getting "Input format concat is not available" error when I try the solution provided by ZinovNikita.
