### ISSUE TITLE
Why does outputOptions set doSplit to false when passing strings?

### ISSUE THREAD

**Issue by waynebloss** [fluent-ffmpeg/node-fluent-ffmpeg#833]
Hello, just looking through [the code](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/lib/options/custom.js#L105) in master and I see that when I pass an array to `outputOptions`, each option is split by space. However, when passing each option as a param they are not.

What is the reason for this difference?

I think the following doesn't even work:

`.outputOptions('-hide_banner', '-loglevel panic')`

However, this does work:

`.outputOptions(['-hide_banner', '-loglevel panic'])`

Thanks!

**Comment by njoyard** [comment]
This is kind of history. In earlier fluent-ffmpeg versions, you could either pass command line tokens to the method (`outputOptions('-loglevel', 'panic', '-hide_banner')`) or an array of "options with parameters" (`outputOptions(['-hide_banner', '-loglevel panic'])`). This has been kept for compatibility purposes, even if we can agree it is kind of not so pretty ;)

**Comment by waynebloss** [comment]
Thank you.
