### ISSUE TITLE
how to define bit depth of wav files

### ISSUE THREAD

**Issue by Fchen48** [fluent-ffmpeg/node-fluent-ffmpeg#834]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: N-91462-g97d766ff52
* OS: Win 10 x64

### Question
Hi, I want to convert an audio/video file to mp3 and wav files, if I convert the file to mp3 I can set bitrate with `.audioBitrate(320)`, but how can I set the bit depth of a wave file (e.g. 24 bit, 32 bit, ...)?

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
There is no builtin method for that. Use outputOption to pass the corresponding ffmpeg option manually
