### ISSUE TITLE
Cannot read the file (mp4 from telegram).

### ISSUE THREAD

**Issue by folt** [fluent-ffmpeg/node-fluent-ffmpeg#853]
### Version information

* fluent-ffmpeg version:
 fluent-ffmpeg@2.1.2
* ffmpeg version:
4.0.2
* OS:
MacOs 10.13.6

### Code to reproduce

```js
helper.js
const mediaInfo = (path) =>
    new Promise((res, rej) => {
        ffmpeg({source: path})
            .ffprobe(function (err, data) {
                    if (err) rej(err);
                    else res(data)
                }
            );
    });

index.js
let media_info = await helper.mediaInfo(doc.local_path);

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
Error: ffprobe exited with code 1
ffprobe version 4.0.2 Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.10.44.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libass --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --enable-openssl --disable-lzma --enable-nonfree
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[aac @ 0x7fa9d8003400] Audio object type 0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa9d8808400] Failed to open codec in avformat_find_stream_info
[aac @ 0x7fa9d8003400] Audio object type 0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'public/5eb91652-5608-4528-aa19-26fc333e1334/video/mp4/2018/9/10/c4498bc7-6381-415c-aacc-4e9d92619fc0.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: isom3gp4
    creation_time   : 2018-10-08T10:42:21.000000Z
  Duration: 00:00:03.29, start: 0.000000, bitrate: 478 kb/s
    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 360x640, 368 kb/s, 20.08 fps, 19.98 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2018-10-08T10:42:18.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 2 channels, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-10-08T10:42:21.000000Z
      handler_name    : VideoHandle
[aac @ 0x7fa9d9009200] Audio object type 0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
Could not open codec for input stream 1

    at ChildProcess.<anonymous> (/Users/folt/Documents/Working/funtome-storage/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)

### Checklist

* [+ ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [-] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [-] I have included full stderr/stdout output from ffmpeg

[video.mp4.zip](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/files/2465173/video.mp4.zip)

**Comment by gvsro** [comment]
This is ffmpeg related not fluent related.
Update your ffmpeg and try to convert it with the command line. If it works there and not with fluent then feel free to reopen.

> [aac @ 0x7fa9d8003400] Audio object type 0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa9d8808400] Failed to open codec in avformat_find_stream_info
[aac @ 0x7fa9d8003400] Audio object type 0 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
