### ISSUE TITLE
Reversing videos

### ISSUE THREAD

**Issue by arherzf8er** [fluent-ffmpeg/node-fluent-ffmpeg#854]
### Version information

* fluent-ffmpeg version: latest
* ffmpeg version: latest
* OS: Ubuntu 18.04

### Code to reproduce

```js
ffmpeg
  .input(video)
  .input(audio)
  .outputOptions([
    '-c copy',
    '-reverse',
    '-shortest'
  ])
  .save();

```

### Observed results
```
An error occurred: ffmpeg exited with code 1: Unrecognized option 'reverse'.
Error splitting the argument list: Option not found
```

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by gvsro** [comment]
`-reverse` is not an option. The error message tells you clearly. The documentations of ffmpeg states that reverse is a Video Filter so you would have to use `-vf reverse`
