### ISSUE TITLE
ffmpeg exited with code 1: pipe:1: Invalid argument | stream h264, express

### ISSUE THREAD

**Issue by mStirner** [fluent-ffmpeg/node-fluent-ffmpeg#858]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 2.8.15
* OS: Ubuntu X64 16.04

### Code to reproduce

Modified example:

```js

  app.get('/video', function (req, res) {
    
    const head = {
      //'Content-Length': fileSize,
      'Content-Type': 'video/mp4'
    };

    res.writeHead(200, head);
    
    
var proc = ffmpeg("./video.webm")
    // use the 'flashvideo' preset (located in /lib/presets/flashvideo.js)
    //.preset('flashvideo')
    .videoCodec("libx264")
    // setup event handlers
    .on('end', function() {
      console.log('file has been converted succesfully');
    })
    .on('error', function(err) {
      console.log('an error happened: ' + err.message);
    })
    // save to stream
.pipe(res, {end:true});



});

```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
Stream to HTTP client (h264/mp4)

### Observed results
ffmpeg exit with code 1, "invalid argument" -> "pipe:1"

### Checklist

* [X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [X] I have included full stderr/stdout output from ffmpeg

[STDERR.txt](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/files/2539102/STDERR.txt)

**Comment by Jgaleas7** [comment]
same problem.

**Comment by mStirner** [comment]
I would make a fork and fix the bug.
But i dont want to waste my time.

It looks like the maintainer is active on github, but not in this repositroy.
When he would comment that he merge the fix, i would debug & fix the problem.

**Comment by PranayShah** [comment]
> add `.format`

Link [here](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/802#issuecomment-366469595)
