### ISSUE TITLE
X11grab option 

### ISSUE THREAD

**Issue by buisine** [fluent-ffmpeg/node-fluent-ffmpeg#859]
### Version information

* fluent-ffmpeg version: latest
* ffmpeg version: ffmpeg version 3.4.4-0ubuntu0.18.04.1
* OS: Unbuntu server 18.04

### Code to reproduce

  videoCommand.addInput(':99.0+0,150')
  .withSize('720x480')
  .withFpsInput(60)
  .withFpsOutput(60)
  .addOption('-y', '-f x11grab')
  .outputOptions(['-c:v libx264', '-crf 18' , '-preset veryfast' , '-t 00:00:05'])
  .output(base_path+'/video.mp4')
  .run();

------

use X11grab to get screen 99.0
haven't seen in the documentation 

### Observed results

Works great with ffmpeg command line, but with fluent i get 

Error: ffmpeg exited with code 1: Unrecognized option 'f x11grab'.
Error splitting the argument list: Option not found

**Comment by mranosa** [comment]
up!

**Comment by buisine** [comment]
'-y', '-f' , 'x11grab' is the correct way to specify options
