### ISSUE TITLE
Taking too long to generate a ScreenShot in ffmpeg

### ISSUE THREAD

**Issue by Vishnupriya112** [fluent-ffmpeg/node-fluent-ffmpeg#860]
### Version information
    "fluent-ffmpeg": "^2.1.2",
    "ffmpeg": "0.0.4",
```
ffmpeg(main_folder_path)
  .on('filenames', function(filenames) {
    console.log('Will generate ' + filenames.join(', '))
  })
  .on('end', function() {
    console.log('Screenshots taken');
  })
  .screenshots({
pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/'
timestamps: [30.5, '20%', '01:10.123'],
filename: 'thumbnail-at-%s-seconds.png',
folder: pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/',
size: '320x240'
  });
```

Am getting screenshots. But its taking more than 2 to 3 minutes to generate.

**Comment by gvsro** [comment]
Try using a more recent version of ffmpeg and include a system info with the issue and maybe a example file. I tested this on a i7 with 16gb of ram and it took something like 2 seconds.
Mileage may vary depending on pc, os, ffmpeg version, pc load. 
Closing this as it's not clear if it's an fluent api problem or other.
