### ISSUE TITLE
How to create a crop filter on one stream

### ISSUE THREAD

**Issue by upekshapriya** [fluent-ffmpeg/node-fluent-ffmpeg#863]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.0.2-tessus
* OS: MacOS 10.13.6

### Code to reproduce

I want 

```js
videoFilters('crop=960:720:160:0');

```
to only work on stream 0
### Expected results

To give ffmpeg code as

```
-filter:v:0 crop=960:720:160:0
```

Not 
### Observed results

```
-filter:v crop=960:720:160:0
```

Is there a way of doing this with fluent-ffmpeg?

**Comment by gvsro** [comment]
Take a look [here](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#inputoptionsoption-add-custom-input-options)
`.inputOptions('-filter:v:0 crop=960:720:160:0')`
