### ISSUE TITLE
Take buffer as input

### ISSUE THREAD

**Issue by James2516** [fluent-ffmpeg/node-fluent-ffmpeg#874]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.1
* OS: MacOS

### Code to reproduce

```js
const express = require('express');
const multer = require('multer');
const ffmpeg = require('fluent-ffmpeg');

const router = express.Router();

router.post('/', multer().single('file'), (req, res, next) => {
  ffmpeg(req.file.buffer)
    .format('wav')
    .save('./a.wav');
});
```

### Expected results

Should get a wav file output

### Observed results

>   Error: ffmpeg exited with code 1: Output #0, wav, to './a.wav':
>   Output file #0 does not contain any stream
>     at ChildProcess.<anonymous> (.../node_modules/fluent-ffmpeg/lib/processor.js:182:22)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

### Checklist

* [x] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [x] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [x] I have included full stderr/stdout output from ffmpeg

**Comment by llcat** [comment]
Hi, I have met this problem in azure function app too.
but `fluent-ffmpeg` supports receive a readable stream, so you can convert the buffer to a stream.
there are a simple tool you could try: [into-stream](https://github.com/sindresorhus/into-stream), hope my answer will help you!

**Comment by James2516** [comment]
@llcat Thanks! I have another problem: how do I convert the output to buffer? I'm using [wav-decoder](https://www.npmjs.com/package/wav-decoder) which only accepts buffer as input.

I tried to pipe the output to a writable stream so that I can use [stream-to-buffer](https://www.npmjs.com/package/stream-to-buffer) to convert it to buffer:
```
const ws = new Writable();
ws._write = ws.write;

ffmpeg(fileStream)
  .format('wav')
  .pipe(ws)
  .on('end', () => {
    console.log('ended');
  });
```

But the `'end'` event is never triggered.

**Comment by tong3jie** [comment]
@James2516 has your problem been solved？

**Comment by gvsro** [comment]
@James2516 This is an example: 
```
stream = Buffer.alloc(0)
let mediaURL = '../../../Downloads/bbb_sunflower_1080p_60fps_normal.mp4'
ffmpeg(mediaURL)
  .outputOptions('-f wav')
  .outputOptions('-ac 1')
  .outputOptions('-ar 11025')
  .pipe(stream, { end: true })
  .on('data', function(chunk) {
    console.log('I got a Chunk')
   stream = Buffer.concat([stream, chunk])
  })
  .on('end', () => {
    console.log(stream.length)
  });
```

**Comment by AScripnic** [comment]
@tong3jie Hello, have you fixed your issue, as I've encountered it as well? Thank you
