### ISSUE TITLE
Bump beginners away

### ISSUE THREAD

**Issue by SamHobbsOrg** [fluent-ffmpeg/node-fluent-ffmpeg#878]
Yes, I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ) but all the other items in the checklist are irrelevant.

This is a documentation issue, specifically about the readme for [fluent-ffmpeg/node-fluent-ffmpeg: A fluent API to FFMPEG](http://www.ffmpeg.org). May I assume that if I don't know what fluent and/or node.js are that I should stop and just ignore everything else? If so then it would help to say that explicitly. It could at least be clear that it is only for writing programs, if that is true.

For me, I am a programmer. I am not sure if Fluent ffmpeg-API for node.js has any relevance but since I don't know what node.js is I assume it cannot help me. However if I wanted to write a GUI interface for ffmpeg then Fluent ffmpeg-API for node.js might help. It might but it will take time for me to study it and that time might be wasted if it is not useful at all. I am not suggesting that the readme file help with that.

I am suggesting that if Fluent ffmpeg-API for node.js is useless for non-programmers then the readme could say that explicitly.

**Comment by ajfarkas** [comment]
I think there's a fair assumption that if you're on Github, you're doing some programming.
There has to be some line to draw in documentation, ie you can't start every doc with "silicon is an element, an important one for creating computers." I'm being hyperbolic, but Github is _a programming tool_.

That said, we also need to make assumptions that people understand there are different programming languages, and if you don't recognize the name of the language, you don't know how to code in it (yet). There' a tool at the top of the main `Code` section of every Github repository that shows what languages the repo uses.

I'm not trying to be flippant: there's a real tradeoff between maintaining code and creating detailed documentation. This project has more docs than most, and what you're asking for is generally considered outside the scope of a Github `README.md`

**Comment by SamHobbsOrg** [comment]
AJ Farkas wrote on 1/17/2019 11:47 AM:
> There' a tool at the top of the main |Code| section of every Github 
> repository that shows what languages the repo uses.
The language something is written in does not determine how it can be used.

**Comment by njoyard** [comment]
Everything you need is in the main header title of the README

> Fluent ffmpeg-API for node.js

* "API", it's for programmers
* "node.js", it's for node.js programmers
* "ffmpeg", it is used to work with ffmpeg

Not sure we really want to spend time handling users that cannot read a title.
