### ISSUE TITLE
File size after transcoding

### ISSUE THREAD

**Issue by ithustle** [fluent-ffmpeg/node-fluent-ffmpeg#879]
Is there a way to get file size after transcoding?

**Comment by njoyard** [comment]
If you're using a constant bitrate, yes: multiply duration and bitrate.
Otherwise, no.

**Comment by ithustle** [comment]
@njoyard maybe I wasn't clear. I want to get a resume of the file size before transcoding has to be made. Something like that:

Actual size: 500000
Size after transcode: 3000.

I'm using 96 bitrate and `.audioQuality()` method, but seem that when I use `.audioQuality()` the bitrate doesn't any effect.

Any help?

**Comment by gvsro** [comment]
@ithustle Can you upload an example file? Because if you have a 96k audiotrack and you convert it to 96k again there will be no change in the file size.

**Comment by ithustle** [comment]
@njoyard , I'm sorry if I explain wrong ... Please, see my code below:

                       ```
                         ffmpeg(assetUrl)
			.inputFormat("mp3")
			.outputFormat("mp3")
			.audioQuality(6)
			.withNoVideo()
			.audioBitrate(96)
			.audioChannels(2)
			.audioFrequency(44100)
			.audioFilters([
				{
					filter: 'volume',
					options: ['0.4']
				},
				{
					filter: 'silencedetect',
					options: { n: '-50dB', d: 5 }
				}
			])
			.output(pathFileMusicaId)
			.on('end', function(err) {
				console.log('done!', err)
				ms.pipe(req, res, pathFileMusicaId);
			})
			.on('error', function(err) {
				console.log('an error: ' + err);
			}).run();
```

My audio file has 192k and I want transcode to 96k and then stream it to mobile devices. I'm doing this to reduce my users data consume usage. What is happen? 

My original file has a 739590 size and when I use code above (but with `.pipe()` instead `.run()`) to stream, I can't get the file size after transcoding to put it on headers "Content-Length". If I put the original size, the streaming fail. That's the reason that I want to get a some kind resume the file size will be after transcode.

**Comment by ithustle** [comment]
@njoyard any help?

@gvsro any help?

**Comment by gvsro** [comment]
You need a `middleware` function with `express` that uses `ffprobe` to grab the metadata, specifically the `duration` inside the metadata. Then you multiply it by what bitrate you want to use and set the `Content-Length` header.

BTW, the way you do it (if it's not a corner case) is very wasteful with resources. Each client will run the ffmpeg command with each request. You need to either pre-transcode the files and then send them when the user asks them at least. Or the better approach, check if the file exists (the transcoded one), and if there is one send it, if not, transcode it on the fly but save a copy locally for the next client. Imagine a situation when 20 users need a transcoded files. 20 ffmpeg processes. You will run out of resources very fast. They can even ddos your service with this. 100 request will be sufficient to clogg any small to medium vps that you may use and maybe 1000-10000 will kill any large vps with no autoscale. Remember, 10000 request is easily doable, I just have to tell your express that i'm interested in that file then I drop the connection. This will not kill the ffmpeg process

**Comment by ithustle** [comment]
@gvsro , thanks for advise. Actually, my code already do that  

> Or the better approach, check if the file exists (the transcoded one), and if there is one send it, if not, transcode it on the fly but save a copy locally for the next client.

Many thanks.
Do have an example to do that with `ffprobe`? Its my first time that I'm working with that.

**Comment by gvsro** [comment]
ffmpeg.ffprobe('/path/to/file.avi', function(err, metadata) {
    console.dir(metadata);
});

**Comment by ithustle** [comment]
@gvsro , I've been tried before to come back because the callback return to me metadata as `undefined`. Any suggest? Maybe I'm doing something wrong ...

**Comment by ithustle** [comment]
And another question, how can I speed up this process (transcode and save)?
