### ISSUE TITLE
help maintaining

### ISSUE THREAD

**Issue by gWOLF3** [fluent-ffmpeg/node-fluent-ffmpeg#886]
Hey @njoyard , 

I will be using this library with my current project and do not mind helping maintaining as well. 

Could not find any other means of contacting you so I hope you don't mind that I just created an issue. 

I've frequently use ffmpeg and contribute to other ffmpeg library for android. Am just starting with now running from node server but expect to be able to at least contribute some time to help. Appreciate your work on this library. 

Thanks,
Glenn

**Comment by njoyard** [comment]
Thanks for the offer. Feel free to contribute!
