### ISSUE TITLE
Project Maintainer Dead?

### ISSUE THREAD

**Issue by FullstackJack** [fluent-ffmpeg/node-fluent-ffmpeg#889]
Last commit in master was over a year ago and PRs are piling up, could we please get someone to take over ownership or add another owner?

I'm joking, of course about being dead, but how likely will it be for me to get a PR merged that adds headers for HTTP inputs on secure buckets? I just completed the work and going to submit a PR tonight.

**Comment by FullstackJack** [comment]
If you don't have time or lost interest, could you please a few maintainers?

**Comment by njoyard** [comment]
See https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/755.
