### ISSUE TITLE
why does the 'start' event be triggered only once?

### ISSUE THREAD

**Issue by evilArsh** [fluent-ffmpeg/node-fluent-ffmpeg#908]
### Version information

* fluent-ffmpeg version:newest version
* ffmpeg version:newest version
* OS:windows10

I have two camera and want to transport the rtsp to rtmp stream and put the decoded video to the electron client.But why does the **start** event only be triggered once?Is there any other way to let the start event be triggered every time when i initialize a ffmpeg instance?

```js
    ffmpeg('rtsp://admin:123456abc@169.254.35.12:554/11')
            .outputOptions([
                "-vcodec",
                "copy",
                "-r",
                "25",
                "-an"
            ])
            .inputFPS(50)
            .noAudio()
            .aspect("4:3")
            .format("flv")
            .save('rtmp://localhost:9090/live/123')
            .on("start", function (e) {
                _this.notify("[ffmpeg start]" + e);
            })
```

**Comment by xedsvg** [comment]
Are you using the same ` .save('rtmp://localhost:9090/live/123')` on both cameras?

**Comment by evilArsh** [comment]
change .save() to .output() will be ok.

**Comment by totzcc** [comment]
You should register event handlers before calling save(), because the processing methods check for registered event handlers at the beginning. That would probably explain unpredictible results when registering events after having called save().

#674
