### ISSUE TITLE
What's the reason behind rounding to multiples of two

### ISSUE THREAD

**Issue by RyanAfrish7** [fluent-ffmpeg/node-fluent-ffmpeg#910]
I have been facing size issues with the screenshots generated. Most times I find it offset by 1 pixel. Just now going thru the code pointed me out this. Please add this to the documentation if this is unavoidable.

https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/22db625717068e39d0d43aa935df275f70ba1eb0/lib/options/videosize.js#L95

**Comment by njoyard** [comment]
Because many codecs require multiples of two (eg. x264)

**Comment by kj800x** [comment]
Is this documented anywhere?

Related: RyanAfrish7/thumbsupply#6
