### ISSUE TITLE
Create a video from Buffer

### ISSUE THREAD

**Issue by ilicmarko** [fluent-ffmpeg/node-fluent-ffmpeg#912]
I have a list of base64 images that I want to convert to a video.

```
image = Buffer.from(snapshot, 'base64');
```

I am wondering if it is even possible to add multiple buffers (images) and generate a video?

Currently, what I can do is save the images to some folder and then use them as an input.

```js
    fs.writeFileSync(path.resolve(output, `${i}.${ext}`), imageStream)
    ffmpeg()
        .addInput(path.join(output, '%d.jpg'))
        .inputFPS(1)
        .noAudio()
        .output(path.join(output, '../test.mp4'))
        .outputFPS(30)
        .run();
```

This is not an ideal solution because I would have to temporarily save the images and then delete them after the video conversion is done.

I think this issue/question is maybe related to #546.

**Comment by njoyard** [comment]
You can do this with one image by turning the buffer into a readable stream (with eg. streamifier).

There's no way to do this with multiple buffers though. There is only one standard input to the ffmpeg process that we can pipe data into.

Maybe an alternative solution would be to find a multiple-image container format that is supported by ffmpeg (eg. animated gif or png), generate a single buffer from your multiple images in nodejs, then pipe that buffer into ffmpeg. That sounds way more complicated than storing files though.

Plus, there's nothing wrong with storing temp files in the first place :wink:

**Comment by ilicmarko** [comment]
I ended up using [tmp](https://www.npmjs.com/package/tmp) and creating a dir with images. Then use that as the source. Turned out great.
