### ISSUE TITLE
Process doesn't exit once ffmpeg is done processing

### ISSUE THREAD

**Issue by c24w** [fluent-ffmpeg/node-fluent-ffmpeg#913]
### Version information
* fluent-ffmpeg version: 2.1.2
* ffmpeg version: N/A
* OS: N/A

### Code to reproduce
```js
console.time('node process duration');
process.on('exit', () => console.timeEnd('node process duration'));

console.time('ffmpeg duration');
ffmpeg('https://ia802508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3', { timeout: 10 })
  .addOption('-t', 1)
  .addOption('-f', 'null')
  .on('end', () => console.timeEnd('ffmpeg duration'))
  .saveToFile('/dev/null');
```

### Expected results
Node.js process exits once ffmpeg is done processing.

### Observed results
```shell
ffmpeg duration: 2970.030ms
node process duration: 10090.792ms
```

This is due to [`processTimer`](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/9cc9c4998d8f48414fbba19696f7f1afe6912dd9/lib/processor.js#L469) not being cleared when ffmpeg operations have completed.  The following changes in `processor.js` produce the expected behaviour:

```js
self.processTimer = setTimeout(function() { /*...*/ });

function endCB(err, stdoutRing, stderrRing) {
  clearTimeout(self.processTimer);
  // ...
}
```

**Comment by njoyard** [comment]
:+1: can you submit a PR ?
