### ISSUE TITLE
rtsp url  Invalid argument

### ISSUE THREAD

**Issue by evilArsh** [fluent-ffmpeg/node-fluent-ffmpeg#917]
![image](https://user-images.githubusercontent.com/20971355/60649567-d0eb7e80-9e74-11e9-9546-e7bff5d39d8d.png)

**Comment by evilArsh** [comment]
I put the comandline to cmd.it worked well.
`ffmpeg -rtsp_transport tcp -r 29 -i  rtsp://admin:123456abc@169.254.35.11:554/11 -an -vcodec copy -rtbufsize 0 -preset ultrafast -tune zerolatency -f flv rtmp://localhost:10002/live/1562225863882`

**Comment by evilArsh** [comment]
sorry get that url with space
url.trim()

**Comment by hammooooody** [comment]
Could you please share your code?
