### ISSUE TITLE
index.d.ts typings for typescript users

### ISSUE THREAD

**Issue by jcapinc** [fluent-ffmpeg/node-fluent-ffmpeg#948]
If I submitted a PR with an `index.d.ts` addition that would add typings so that typescript users could use this library more easily, would it be accepted?

**Comment by noamalffasy** [comment]
You can always submit a PR to DefinitelyTyped/DefinitelyTyped

**Comment by jcapinc** [comment]
I did actually, that was my first accepted PR on any project. I was just offering it here too.
