### ISSUE TITLE
how use itsoffset in fluent ffmpeg

### ISSUE THREAD

**Issue by mohsen158** [fluent-ffmpeg/node-fluent-ffmpeg#952]
hi 
i want to run this command with fluent FFmpeg in node :

`    ffmpeg -ss 9.920500 -itsoffset  9.920500   -i t_video.mp4  -t 19.880500   -vf  "format=yuv444p, drawtext=text='Title of this Video':fontcolor=white:fontsize=24:x=(w-tw)/2:y=(h/PHI)+th, format=yuv420p"  -acodec copy  -c:v h264  -segment_format mpegts strea2m1.ts
`

how can I use this ??
 I test this code but doesn't work : 
        `   
    
    var tt=ffmpeg('/home/gheidar/Desktop/ffmpeg_test/testWater/public/video13/t_video.mp4').addOptions(['-ss 9.920500','-itsoffset 9.920500', ' -t 19.880500 ', '-acodec copy',' -c:v h264','-segment_format mpegts'])
   
           .videoFilters({
              filter: 'drawtext',
              options: {
                text: 'VERY LONG TEXT VERY VERY VERY VERY LOL!!!',
                fontsize: 36,
                fontcolor: 'white',
                x: '(main_w/2-text_w/2)',
                y: '(text_h/2)+15',
                shadowcolor: 'black',
                shadowx: 2,
                shadowy: 2
              }
            })
    
    .on('start', function(commandLine) {
      cmd=commandLine;
      console.log(commandLine);
      console.log('Start ...');
    })
    .on('progress', function(progress) {
      console.log(Math.round(+progress.percent));
    })
    .on('error', function(err, stdout, stderr) {
      dty='\n\Command : \n'+cmd+'\n\Message: \n'+err.message+'\n\nStderr : \n'+stderr+'\n\nStdout : \n'+stdout;
      console.log('Convert Err : '+dty);
    })
    .on('end', function(filenames) {
      console.log("\n\nFinish.\n\n");
    })
    .pipe(res)
`
 

actually i want to use start time and itsoffset and end time + vf filter.

**Comment by njoyard** [comment]
Any option that would go before `-i` on command line must be added using `inputOptions`.
