### ISSUE TITLE
How to setup -user agant header in ffmpeg before -i input source?

### ISSUE THREAD

**Issue by user-1984** [fluent-ffmpeg/node-fluent-ffmpeg#953]
I im using lastest version of node-fluent-ffmpeg 2.1.2 and all is working perfectly except i can't send header to my ffmpeg when connecting to source...as i read ffmpeg manual i see that i must put

 `-user-agent "MyCustomAgentName"`

before -i tag in ffmpeg command...fluent-ffmpeg adds this AFTER -i url source so -user-agent is ignored...my question is:

How can i add -user-agent BEFORE -i url source using fluent-ffmpeg function?

I im currenty using this:

`var ffmpeg('http://blabla.yy')
       .outputOptions('-nostdin', '-user-agent', 'MyCustomAgentName')
       .once('codecData', function(data) {}).on('end', function() {}).on('error', function(err, stdout, stderr) {}).save('/tmp/'+id+'.xx');`

And using htop i see this command is running:

`ffmpeg -i http://blabla.ts -nostdin -user-agent 'MyCustomAgentName'`

And needs to be:

`ffmpeg -nostdin -user-agent 'MyCustomAgentName' -i http://blabla.yy`

How to fix this?

Thanks

**Comment by njoyard** [comment]
Use `inputOptions` :)
