### ISSUE TITLE
how to transport ts files to aws S3 by streaming, without local storage.

### ISSUE THREAD

**Issue by lincanrong586** [fluent-ffmpeg/node-fluent-ffmpeg#957]
### Version information

* fluent-ffmpeg version:
* ffmpeg version:
* OS:

### Code to reproduce

```js


```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Checklist

* [ ] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ ] I tried the same with command line ffmpeg and it works correctly (hint: if the problem also happens this way, this is an ffmpeg problem and you're not reporting it to the right place)
* [ ] I have included full stderr/stdout output from ffmpeg

**Comment by njoyard** [comment]
fluent-ffmpeg allows outputting to files or writable streams, see the docs.
The rest is in S3 scope, so not applicable to this repository.
