### ISSUE TITLE
Cannot cut videos into separated chunks

### ISSUE THREAD

**Issue by alexmoruz** [fluent-ffmpeg/node-fluent-ffmpeg#962]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 4.2.1
* OS: macOS 10.15

### Code to reproduce

```js
ffmpeg('./source.mp4')
    .seekInput(50)
    .duration(10)
    .output('../output/res-1.mp4')
    .seekOutput(70)
    .duration(10)
    .output('../output/res-2.mp4')
    .on('end', function() {
        console.log('Merging finished !');
    })
    .run();
```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
I was expecting it to generate two videos cut out of the `source.mp4` into `res-1.mp4` and `res-2.mp4` baed on the timings

### Observed results
Though it generates completely different videos with do not match the script. Would be great if you could've suggest a better way to split video into smaller chunks.

**Comment by njoyard** [comment]
As stated in the docs you should add output options **after** specifying the output. Output options apply to the last output added before calling them (with the exception that output options specified before any output is added will apply to the first output).

So this should do what you wanted:
```js
ffmpeg('./source.mp4')
    .seekInput(50)
    .output('../output/res-1.mp4')
    .duration(10)
    .output('../output/res-2.mp4')
    .seekOutput(70)
    .duration(10)
    .on('end', function() {
        console.log('Merging finished !');
    })
    .run();
```
