### ISSUE TITLE
Problem with heroku buildpacks

### ISSUE THREAD

**Issue by TechnoTew** [fluent-ffmpeg/node-fluent-ffmpeg#977]
### Version information

* fluent-ffmpeg version: 2.1.2
* ffmpeg version: 0.0.4
* OS: not sure, code hosted on heroku

### Code to reproduce

```
async save(message, downloadQueue, options){
            let start = Date.now()
            let stream = ytdl(downloadQueue.songs[0].url, options)
            const newMessage = await message.send("Progress: ");
            ffmpeg(stream)
            .audioBitrate(128)
            .save(`${__dirname}/../../MusicFiles/${downloadQueue.songs[0].title}.mp3`)
            .on('progress', (p) => {
                newMessage.edit(`Progress: ${p.targetSize}kb downloaded`);
                console.log(`Progress ${p.targetSize}kb downloaded`)
              })
            .on('end', () => {
                const attachment = new MessageAttachment(`${__dirname}/../../MusicFiles/${downloadQueue.songs[0].title}.mp3`);
                const channelID = fs.readFileSync(`${__dirname}/attachmentChannel.txt`, 'utf8', (err, data) => {
                    if (err) throw err;
                    return data;
                })
                newMessage.edit('Completed');
                const attachmentChannel = this.client.channels.get(channelID);
                attachmentChannel.send(`Here you go <@${message.author.id}>.\nDownload took - ${(Date.now() - start) / 1000}s`, attachment);
                downloadQueue.songs.shift();
                if (!downloadQueue.songs[0]) {
                    return newMessage.send('Finished downloading all the songs in the queue.');
                } else {
                    this.save(message, downloadQueue, options);
                }
                
                
            });


```

(note: if the problem only happens with some inputs, include a link to such an input file)

### Expected results
download normally

### Observed results
App not compatible with buildpack: git://github.com/schaermu/node-fluent-ffmpeg.git
       bash: /app/tmp/buildpacks/3d5d28fe28b1af26934b3219d359057b9b2405c365bf77e8d8ce84228aea24b1fc6c16a838303d9b7f2d3ebd206cf3f59cdd723debd73ef3f7332c4947ba7ae0/bin/detect: No such file or directory
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by Lucasdsk** [comment]
hey @TechnoTew how did you manage to fix this issue? I'm facing the same.

**Comment by TechnoTew** [comment]
> hey @TechnoTew how did you manage to fix this issue? I'm facing the same.

I'm not sure if I ever solved the problem, but I do remember switching a library/ a hosting provider.

Sorry I can't be of much help
